### ISSUE TITLE
Refinements to Activity Submission page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#102]
- [x] Add 'Licensing Agreement' checkbox and textbox with License to the submission page
- [x] Move Language drop down to "Required" section and autofill with English
- [x] Type and Grade Level checkboxes<br>
~~Sim field -- gray shadow of screenshot with plus sign to add a sim~~
      - [x] choose from a list of sim names with checkboxes in a scrolling dialogue
      - [x] allow to select multiple sims
- [x] Left align PhET Design Guidelines
      - [x] Add icon of dog-eared page with gold star

**Comment by arouinfar** [comment]
After meeting with @amanda-phet and @ariel-phet, there are some further refinements to make:
- [ ] All sections will be required, re-organize the sections to be grouped more logically
   - [ ] Try grouping Type, Grade Level, Subject side-by-side
   - [ ] File selection should be directly after sim selection
   - [ ] Organization should match what is planned for updated activity pages
- [ ] Make PhET Design Guidelines more visible on the page
- [ ] Show screenshots of sims once they have been selected (4/row)
- [ ] Further refine file selection section
   - [ ] Use colored FontAwesome logos for file icons (Red for .pdf, Blue for .docx, etc.)
   - [ ] Create an icon for text files with a T
   - [ ] Decide on what file types should be supported (Are .esp and .cck necessary?)
- [ ] Compare radio buttons and a drop down for Duration (N/A preselected) 
- [ ] Remove Standards Alignment (this is a bigger issue to revisit later)

**Comment by oliver-phet** [comment]
@arouinfar .esp and .cck are Energy Skate Park and Circuit Construction Kit save files. I would think we would want to continue to support users uploading those.

**Comment by patricialoeblein** [comment]
Yes, please continue to support the sim saved files.

Trish

**Comment by arouinfar** [comment]
Thanks for your input @oliver-phet and @patricialoeblein. I was not aware that these were sim save files (nor were some others on the team). I had found some obscure chemistry software that uses the .esp extension and a clip art format for the .cck extension, so it was not clear to us why would support these file types. Given that they are sim save files, we will continue to support them.

**Comment by arouinfar** [comment]
Further refinements suggested during the website design meeting with @oliver-phet, @amanda-phet, and @ariel-phet 

- [ ] Make button padding match the buttons on the main site
- [ ] Decide on the number of sims to display in the scrolling window
- [ ] Change "Submit" to "Submit Activity"
- [ ] Refine text beneath Answers Included checkbox 
- [ ] Mock up what happens when a user tries to submit an activity with missing fields
- [ ] Add tool tip to gold star icon

**Comment by aaronsamuel137** [comment]
I have some bandwidth to start on this if need be, but I want to check if the mockups in the sim pages doc are generally good to work from or if I should wait until things are more finalized. Thoughts @ariel-phet and @arouinfar?

**Comment by arouinfar** [comment]
We have generally settled on the look for the activity submission page, but it's a bit different from what's currently in the design doc. The only outstanding issues are the remaining unchecked items in my previous comment. I will go ahead and update the screenshots in the doc and email a higher res version to @aaronsamuel13.

**Comment by aaronsamuel137** [comment]
@arouinfar, are we going to stop keeping track of the standards? I don't see these on the new mockup.

![screen shot 2015-04-15 at 11 59 28 am](https://cloud.githubusercontent.com/assets/3193912/7165769/f1574d66-e366-11e4-8656-fafaf0a36b80.png)

**Comment by arouinfar** [comment]
@aaronsamuel137, we will be removing these particular standards, as they are now outdated. We will be addressing NGSS and CCSS-M standards alignment in the future, but that will be a more complicated project.

**Comment by oliver-phet** [comment]
At a design meeting on 4/21 these outstanding issues were identified that need to be completed:
- [ ] Add 'Want a Gold Star' panel with tooltip, and remove "Please check the PhET Design Guidelines (PDF)"
- [ ] If coming from a sim page, check that sim by default
- [ ] Language is pulling from locale the website is being viewed in
- [ ] Add period to the sentence "Please be aware that all users can see the answers if included"

New things:
- [ ] It looks like the old screenshots are being used when a sim is checked? We want to use the new shots.
- [ ] Add an "X" to the upper right-hand corner of the screenshot to remove a sim (and uncheck from list)
- [ ] Add the shadow used for screenshots on the 'new sim' page to these screenshot
- [ ] Reduce column width of 'Subject/Grade level/Type 
- [ ] Change "Undergraduate - Intro" to "Undergrad - Intro", same with "Advanced"
- [ ] Remove  the 'Approved' field from database/existing activities - or could "hide" it (up to you Aaron)
- [ ] From PhET/Gold Star - this list should be vertical and check boxes should be on the left. Look is identical to Subject(s) list.
See this screenshot:

- [ ] Add a field to the 'Duration' drop down "Choose One". Have this selected by default.

**Comment by aaronsamuel137** [comment]
What should the gold star panel tool tip say?

**Comment by aaronsamuel137** [comment]
> It looks like the old screenshots are being used when a sim is checked? We want to use the new shots.

It uses the new screenshot if it exists. There are still some sims that don't have new screenshots, most notably many of the legacy versions of sims that have HTML5 versions.

We could also look into scaling these thumbnails in the browser if we don't want to worry about new screenshots.

**Comment by arouinfar** [comment]
@aaronsamuel137 the gold star panel tool tip text should match the current gold star tool tip, but that language will be updated (see #131)

**Comment by aaronsamuel137** [comment]
Just to confirm - we are no longer wanting any approval process from contributions? This means that any user can submit a contribution and it will immediately appear on the website.

Also, I am assuming the fromPhet and goldStar checkboxes should only appear if you are a phet team member, as is happening now.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - that is correct. Currently, all submissions are approved anyhow, so it is a historical control that is now unnecessary. 

And yes, fromPhet and goldStar should only appear if you have admin privileges

**Comment by arouinfar** [comment]
@aaronsamuel137, we do not manually approve activities -- they are all approved by default. I created a dummy account to see if the box appears on non-admin accounts, and it doesn't. 

The PhET and Gold Star checkboxes should only appear on admin accounts, as they do now.

**Comment by arouinfar** [comment]
@aaronsamuel137, we have updated the gold star tool tip text to read:

A gold star indicates high quality, inquiry-based activities that follow the PhET design guidelines.

**Comment by amanda-phet** [comment]
I request that we use a hyphen in "high quality" (so that it would be "high-quality" instead) since we are using the phrase as an adjective.

**Comment by arouinfar** [comment]
Great point, @amanda-phet. Please use the hyphen as @amanda-phet has requested, @aaronsamuel137.

**Comment by aaronsamuel137** [comment]
Assigning to @arouinfar for review. Let me know if you think it is ready for testing.

**Comment by arouinfar** [comment]
It's looking good, @aaronsamuel137! There are a few changes need to be made before it's ready for testing.

- [ ] The PhET Design Guidelines link in the blue box appears to be broken. The link should take the user to https://phet.colorado.edu/en/for-teachers/activity-guide. Instead, it redirects to a page with this error:

![image](https://cloud.githubusercontent.com/assets/8419308/7458554/83f65fd2-f252-11e4-97bb-523b5cd55130.png)
- [ ] The author name field is pre-filling with the first name only. It should fill with FirstName LastName.
- [ ] The Grade Level and Type columns are too close. Try moving the Grade Level column about a checkbox's width to the left.
- [ ] When trying to submit an activity with missing fields, this error occurs:
![image](https://cloud.githubusercontent.com/assets/8419308/7458642/36707a58-f253-11e4-850d-46513f1da5d3.png)

**Comment by aaronsamuel137** [comment]
I've added the inner stroke. It is subtle, but there. On dropdown elements only the outer stroke will appear because over-riding the border on these elements has weird side-effects.

The other issues are addressed too. Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Thanks for adding the inner stroke, @aaronsamuel137! I think it's fine to leave it off of the dropdown elements, especially if it causes complication.

Just a few more changes:

- [ ] The Duration dropdown menu should have a N/A option added.
 
- [ ] The text in the Keywords and Description fields is formatted differently when in Firefox. This issue does not exist in Chrome or Safari. Is this something that can be addressed reasonably quickly? If not, don't worry about it. 
![image](https://cloud.githubusercontent.com/assets/8419308/7478518/9b9c711e-f318-11e4-9cae-c38586980a8d.png)
![image](https://cloud.githubusercontent.com/assets/8419308/7478601/1e3e0da8-f319-11e4-895a-0935891242e5.png)

- [ ] The spacing between the Grade Level and Type columns still looks a bit too narrow. 

Current spacing:
![image](https://cloud.githubusercontent.com/assets/8419308/7478779/373faed2-f31a-11e4-8746-7e646bc5504a.png)

Desired spacing (Grade Level moved 10px to the left):
![image](https://cloud.githubusercontent.com/assets/8419308/7478761/063def10-f31a-11e4-8ba4-05d324ab85ee.png)

**Comment by aaronsamuel137** [comment]
I've made these changes - assigning to @arouinfar to verify

**Comment by arouinfar** [comment]
Looks great, @aaronsamuel137! One last thing -- the "Choose One" option appears twice in the Duration dropdown.

**Comment by aaronsamuel137** [comment]
Good catch! I've fixed this. I'm going to close the issue since it seems like the last thing, but feel free to reopen if you notice anything else.
