### ISSUE TITLE
Update software requirements for HTML5 sims to read Internet Explorer 10+

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#104]
@aaronsamuel137, please update the wording in the windows category to say Internet Explorer 10+ (instead of 9+). Should be a quick change, and we will want to do it before we publish Molecule Shapes.

![capture](https://cloud.githubusercontent.com/assets/4051174/6765920/cf6db3c8-cfb8-11e4-84a5-43379ab36533.PNG)

**Comment by aaronsamuel137** [comment]
I've updated this on the html5 sim pages - though right now that is just area builder and ph-scale-basics. I've also updated the requirements section on the FAQ page. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good! Closing
