### ISSUE TITLE
New verbiage for message on "New Sims" page when viewing in a locale

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#105]
Currently on phet-dev going to "new sims" brings you to our HTML5 sims as we have discussed. If you are viewing the site in a non-english locale you get a message as shown below. We should adjust this message to give an easy link to translated sims or such:

![capture](https://cloud.githubusercontent.com/assets/4051174/6829819/8af3a542-d2db-11e4-8471-f3d52c422731.PNG)

**Comment by amanda-phet** [comment]
I agree. Can we direct them to the translations section of the legacy page? I notice this URL (http://phet-dev.colorado.edu/en/simulation/legacy/acid-base-solutions#translations) takes me to that section but does not expand it. (Probably because we asked Aaron to change the behavior of these).

**Comment by aaronsamuel137** [comment]
Directing to that link should expand the text. (It does for me currently). Try refreshing the page and then try the link again.

**Comment by amanda-phet** [comment]
Thanks, it works for me now. 

I just realized that link wouldn't make sense in this message because it is sim-specific. I'll keep thinking of a solution.

**Comment by amanda-phet** [comment]
This issue is addressed in #108.
