### ISSUE TITLE
Links to simulations on an activity page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#107]
Background: If an activity can be applied to both the HTML5 version and the legacy version of the sim, both sims will be listed on the activity page. 

Issue: At the moment, both sims are named the same and link to the HTML5 page. 
- We should identify the HTML5 sim to distinguish the two (eg., Graphing Lines (HTML5), Graphing Lines). 
- We also need to change all links to non HTML5 sim pages to go to the legacy page (eg., Graphing Lines (HTML5) goes to the html5 page, Graphing Lines goes to the java page).

**Comment by aaronsamuel137** [comment]
I think this is fixed now, but I am not sure which activity to test on that has both and html5 and legacy sim listed. Assigning to @amanda-phet for review

**Comment by amanda-phet** [comment]
The activities for Graphing Lines are where I came across this issue. It seems to be fixed! I also checked and the links to the sims go to the correct pages. 
![screen shot 2015-04-02 at 1 22 25 pm](https://cloud.githubusercontent.com/assets/7852916/6971675/593da078-d93b-11e4-847a-4662c2318bc0.png)
