### ISSUE TITLE
More tweaks

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#108]
- [x] Remove green arrow decoration from table on home page
- [x] Remove green arrow decoration from principal sponsors banner 
- [x] try white outlines for focus elements in banner 
- [x] modify search button to connect to entry box, similar to google maps
![screen shot 2015-03-26 at 2 03 08 pm](https://cloud.githubusercontent.com/assets/7852916/6855862/782550dc-d3c1-11e4-8d40-4c649d7e2d9f.png)
- [x] all buttons should not change appearance when clicked (for now) so remove inconsistent behavior 
- [x] reduce size of CU logo a bit
- [x] change size of badges on list of sims to 28px square, change top to -15px
- [x] when clicking on an HTML5 screenshot in a different locale, the html5 sim page should open (with the message about translation at the top) 
- [ ] Change the message on New Sims page (when in a different locale) to read "All of our newest sims are written in HTML5 and run in a browser, but are currently only available in English. Enabling translations is one of our next steps. In the meantime, browse all of our translated sims here." 
- [x] When viewing the site in a different locale, clicking on Play With Sims actually brings users to All Sims rather than New Sims
- [x] Change the navigation link to legacy page to have all caps, remove >>, vertically center in rectangle, font 1.1667em and line-height 1.333em. 
- [x] make sure the space above and below the download/embed buttons is 12px 
- [x] make the margin below the sim title 5 px
- [x] modify screenshot shadow to be 5px, 5px, 20px
- [x] Make the width of the text on sim pages to be the same width (400px) and align primer video with text

**Comment by aaronsamuel137** [comment]
I've addressed these changes. Feel free to uncheck those that you want to tweak some more. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
The search bar looks a little funky in Firefox, but fine in Chrome. Also, the white focus for the search bar doesn't work, but I think we also talked about trying the standard light blue so I'll want to compare different colors for that.

I unchecked two items because I'm not sure if we should revisit them here or not. 
* The message for different locales didn't seem updated for all locales- is this a testing issue? In French, it seemed like it was the old message, but in Dutch it seemed to be updated. 
* The vimeo video doesn't seem to be lining up with the text as we planned. 

Everything else looks really good to me!

**Comment by aaronsamuel137** [comment]
The reason the message is different in different locales is that I have used the same key for the new message. This way, it will default to the old message translated instead of the new message in English untranslated. If you'd like, we can just delete the key and start over, so all translations will be English until they are retranslated.

Also, I am hesitant to try the native blue focus for the search bar since @emily-phet already asked me to change this once. Do you have other ideas? Perhaps we should discuss with her? How does the white focus look to you on the gray buttons?

And I'm sure you noticed I added the new tables. Any thoughts? There isn't an issue for that currently, so we could start one or discuss here.

**Comment by amanda-phet** [comment]
Since people like the orange focus indicator we can stick with that. I just wanted to try white. 

I was planning to make a new issue for the tables so I'll do that now!

**Comment by arouinfar** [comment]
I've noticed that the tables don't seem to be properly sorting by the Gold Star or PhET columns. For example, if I click on the PhET logo once to bring the PhET-contributed activities to the top, the table will be sorted like:
![image](https://cloud.githubusercontent.com/assets/8419308/6975823/ac11d648-d95e-11e4-8cbf-89b1e007f829.png)

**Comment by aaronsamuel137** [comment]
@amanda-phet, a few questions about the unchecked items:

1. Should we delete all translations and start from scratch for the new message on the html5 sim page, or default to the old translation until somebody makes a new translation?

2. Regarding the video alignment, I am not sure what you are wanting. It looks fairly aligned to me. Maybe we should discuss in person to adjust it more?

**Comment by amanda-phet** [comment]
1. Defer to @ariel-phet because I'm not sure what the best way to go is. I didn't realize until your comment that it was intentional. 
2. I thought the width of the video would match the width of the text. They are definitely left-aligned just right, but the right alignment is off. Is there a good solution for this? 
![screen shot 2015-04-06 at 2 00 31 pm](https://cloud.githubusercontent.com/assets/7852916/7011351/8f24c16c-dc65-11e4-83ad-f7317ed56dbf.png)

**Comment by aaronsamuel137** [comment]
OK the video is right aligned with the text now. It's hard to tell for sure, since the text doesn't always end up exactly at the edge of it's container, but it's the best I can do.

**Comment by amanda-phet** [comment]
It seems fine on the Area Builder page but I couldn’t find another page with a video to compare. I’d say it looks good to me!

---
Amanda McGarry
PhET Interactive Simulations
http://phet.colorado.edu

On Apr 6, 2015, at 7:29 PM, Aaron Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


OK the video is right aligned with the text now. It's hard to tell for sure, since the text doesn't always end up exactly at the edge of it's container, but it's the best I can do.

**Comment by amanda-phet** [comment]
As for the translation issue, I think your solutions makes sense. Closing.
