### ISSUE TITLE
Mac/PC Differences in File Selection on Activity Submission Page

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#109]
When uploading an activity file on a Mac, the filename includes a fake path (see below). When uploading a file on a PC, the activity submission page simply lists the file name without the path. Is there a reason the fake path exists for Mac users?

![image](https://cloud.githubusercontent.com/assets/8419308/6929172/0022fd0c-d7b6-11e4-8d1b-3c69948c57fa.png)

**Comment by amanda-phet** [comment]
This appears to be fixed on phet-dev right now.
