### ISSUE TITLE
Questions for Trish

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#110]
Hey Trish, We have a number of questions that have come up when looking at activities. Would you mind answering them here so we can keep track of your responses? 

1. The "approved" checkbox. Do you manually approve all activities before they are posted to the site? Do you remember the reasoning behind having this checkbox? 
2. "Answers included" checkbox. Can you tell us about this checkbox and how you think teachers interpret the information? 
3. When nominating an activity for a gold star, there is a box for a comment that does not get posted. Why have this box? It seems like we'd want to encourage users to publicly comment (praising an activity!) rather than have it just be sent to us (where you then copy and paste it as a comment for the user). Would it make sense to have something along the lines of a button that says "nominate" with no text-entry box?

**Comment by patricialoeblein** [comment]
Amanda,
See below

Trish Loeblein
Patricia.Loeblein@colorado.edu<mailto:Patricia.Loeblein@colorado.edu>
PhET K12 Specialist http://phet.colorado.edu/
Conifer HS Chemistry teacher conifer-hs.jeffco.k12.co.us/conifer/html/science/ploeblei/
UNC Mines Co-STEM Liaison Specialist   www.unco.edu/nhs/science/MinesUNC_home.html<http://www.unco.edu/nhs/science/MinesUNC_home.html>

**Comment by amanda-phet** [comment]
Thank you! After discussing in person it was decided to 
1. Remove the "approved" checkbox from activity submission page. If we see an activity that should not be posted, we will delete it. 
2. Keep the "answers included" checkbox since some activities do include them. 
3. Remove the "nominate for a gold star" option since it doesn't operate well as it is.
