### ISSUE TITLE
Update tables of activities and translations

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#111]
Tweaks in #108 included a change to the tables for activities and translations. We updated the appearance and the default sorting for activities. It will be similar to the original with one slight change:
1. Locale
2. Gold Star
3. Date *updated* rather than date *submitted*

**Comment by amanda-phet** [comment]
My thoughts on the first pass: 
* The tables look really good with the new row height standard! 
* An HTML5 sim page with no activities should show this message above the submit button: Check out **activities for the original sim** for ideas.
* The top (purple) row of the activities table has clickable titles to sort- they are working really well and I love it. The only tweak is that the titles should be in all caps and left-aligned with the column. 
* The alignment in the translations table seems funny when the sim title goes on to a second line. 
* There is probably more padding around the download and run buttons than is necessary.
![screen shot 2015-04-02 at 3 47 22 pm](https://cloud.githubusercontent.com/assets/7852916/6974409/c2320d58-d94f-11e4-9248-29a7dcb69af8.png)

**Comment by patricialoeblein** [comment]
I like your solution to the “no activities” – “Check out activities for the original sim for ideas”. I wonder if you might be able to encourage contributions of activities also? Something like “Want to be one of the first to add an activity? Click here” then the click would go to the submission page. Just an idea..

Trish

**Comment by arouinfar** [comment]
I've noticed that the activity table doesn't seem to be properly sorting by the Gold Star or PhET columns. For example, if I click on the PhET logo once to bring the PhET-contributed activities to the top, the table will be sorted like:
![image](https://cloud.githubusercontent.com/assets/8419308/6975823/ac11d648-d95e-11e4-8cbf-89b1e007f829.png)

**Comment by aaronsamuel137** [comment]
@amanda-phet, where do you want the "Check out activities for the original sim for ideas" link to go to?

**Comment by amanda-phet** [comment]
If it was ESPB, the link would go to http://phet-dev.colorado.edu/en/simulation/legacy/energy-skate-park-basics#for-teachers-header. The link would be unique to each sim. 

If this is difficult, maybe we can wait until we've looked at the activities for each sim. Many of the HTML5 sims will have at least one activity so this might be irrelevant. However, in interviews (yes- I've conducted some!), users did not know how to access the activities (whether they were a new or experienced user). So, actually, we may want this link on every HTML5 activities section...

**Comment by aaronsamuel137** [comment]
Sounds good, that's what I figured it should be. It's not difficult. Let me know if you want the link on every HTML5 page for sure.

**Comment by aaronsamuel137** [comment]
I've made the changes and fixes. HTML sims that have activities will have a link to "browse more activities". Assigning to @amanda-phet for review.

@arouinfar, I think I fixed the bug you mentioned, but let me know if it is working for you.

**Comment by arouinfar** [comment]
The sorting issue appears to have been fixed. Thanks, @aaronsamuel137!

**Comment by amanda-phet** [comment]
Everything here looks good so I'm closing this issue.
