### ISSUE TITLE
Update activity info pages

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#112]
Here is an example of an activity page: https://phet.colorado.edu/en/contributions/view/4015 

We would like to take the existing information and rearrange it slightly, while also adding a few design elements to organize the information. I will email you mockups and artwork files. 

We are also removing the "nominate for a gold star" section based on conversations in #110.

**Comment by BrianNewsom** [comment]
@aaronsamuel137 Included a pull request #138 with some styling updates to this page.

A few things:
* The table is more spaced out.  I used the phet table class.  I can override this and make it more compact, but I didn't want to make it inconsistent styling wise. Let me know and I can fix that pretty quickly.
* I'm not sure if I have to style the breadcrumbs, if they are already updated on phet-dev.  Let me know.

Thanks!

**Comment by ariel-phet** [comment]
@amanda-phet - when we review this page I was realizing that if you get here from the sim page it is the breadcrumbs are nonobvious (on the original page they take you to "Teaching Resources" which seems a bit disorienting), Not sure if we changed this behavior in the new mockups or not.

**Comment by amanda-phet** [comment]
@ariel-phet I did not touch the breadcrumb behavior... it has always appeared odd to me, but I bet most users would click "back" to navigate back to the previous page anyway.

**Comment by ariel-phet** [comment]
OK, can you make a note of this somewhere for our larger (future) activity project

**Comment by amanda-phet** [comment]
Yes. Done.

**Comment by aaronsamuel137** [comment]
@BrianNewsom, see my comments in the pull request.

**Comment by BrianNewsom** [comment]
@aaronsamuel137 thanks, will fix those issues when I get a chance - hopefully tonight!

**Comment by amanda-phet** [comment]
What is the status of the activity pages?

**Comment by aaronsamuel137** [comment]
@BrianNewsom, I may end up taking this over. Have you made any progress since the last pull request? I can either take over from where you are now or from the last pull request, or if you expect to be done in the next few days you can just finish it.

**Comment by BrianNewsom** [comment]
@aaronsamuel137 Sorry, with finals I just had no time and then I managed to get pretty sick the last few days.  I should be able to wrap this up today or tomorrow - my biggest problem spot is making the bullet icons clickable. The other stylistic changes aren't bad, but I think to do that I'll have to redo the way I handled the icons.

**Comment by aaronsamuel137** [comment]
@amanda-phet or @arouinfar - do you think it is important that the icons for each file are also clickable to download the file, or is it okay to have just the text link clickable? I've told @BrianNewsom to make the icon clickable too, but maybe it is not worth the extra work?

**Comment by amanda-phet** [comment]
I thought it would be nice, but I'm not sure if it's necessary. I'll probably know once we do an interview and after playing with it myself. 

If it's complete otherwise, I'd say we can leave that feature out.

**Comment by BrianNewsom** [comment]
@aaronsamuel137 I believe I fixed everything you suggested - let me know if anything doesn't look right still.  If you'd like me to make the icons clickable let me know and I can put some time in and do it!

**Comment by aaronsamuel137** [comment]
Looks great! Thanks @BrianNewsom.

I have deployed these changes to phet-dev. Assigning to @amanda-phet for review. Feel free to assign to me for any remaining tweaks you might want.

**Comment by amanda-phet** [comment]
Just two tweaks, if possible. 
1. I'd like to use our new gold-star everywhere there is a gold star on the website. For example: 
![screen shot 2015-05-11 at 11 46 45 am](https://cloud.githubusercontent.com/assets/7852916/7571300/f954bf68-f7d3-11e4-9680-89ac217194ca.png)
2. Can the text here be left-aligned rather than right-aligned? Also, I didn't think about the resizing of the comment box, so I think we should move the Comment button all the way to the left of the text box.  
![screen shot 2015-05-11 at 11 46 52 am](https://cloud.githubusercontent.com/assets/7852916/7571312/08fa3fe2-f7d4-11e4-9cd1-6a7bb7286bfc.png)

Should be:  
![screen shot 2015-05-11 at 11 52 04 am](https://cloud.githubusercontent.com/assets/7852916/7571341/31c218d2-f7d4-11e4-9597-0aaa0cb54c82.png)

It's looking great! And I don't think the icons not being links is a problem at all.

**Comment by aaronsamuel137** [comment]
I've made these changes. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great!
