### ISSUE TITLE
Navigation links are too close to links on new sim pages

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#113]
The navigation link click area should be smaller so it doesn't interfere with links on the main content of the page. This is especially noticeable on the new sim pages with the "ABOUT" expandable text.

**Comment by aaronsamuel137** [comment]
I've put some padding between the navigation links and the page content. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looking good... there is definitely not interference with the sidebar navigation now.

I would make one small tweak which is to extend the active area for the expandable heading a little on the left (I think 20-30 or pixels or so would do it), just so you don't have to be super precise if you are clicking on the arrows (for some reason my instinct is to click near the left edge of the grey arrows on each heading).

**Comment by aaronsamuel137** [comment]
OK I've extended the clickable area to the left a little bit (20px). Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks great! Closing
