### ISSUE TITLE
Handling empty fields on the activity submission page

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#117]
We have talked about redesigning the way the activity submission page warns users about empty fields. Ideally, the empty fields would be highlighted to make it more immediately noticeable what information is missing. 

There would be a new warning at the top of the page accompanied by the text already generated by the website:
![image](https://cloud.githubusercontent.com/assets/8419308/7036480/b886cd78-dd52-11e4-80c1-37fb41bec579.png)

The empty fields would also be highlighted.
![image](https://cloud.githubusercontent.com/assets/8419308/7036479/a9c8ae5a-dd52-11e4-8559-5327ce2a0705.png)

While this would be a nice touch, this functionality is not strictly necessary to roll out new sim pages. @aaronsamuel137 do you think something like this can be done feasibly without delaying the launch?

**Comment by aaronsamuel137** [comment]
I'm working on this now - I think it will be feasible and not delay the launch, but I will let you know if I run into any unexpected difficulties.

**Comment by aaronsamuel137** [comment]
@arouinfar, can you send me the warning icon with the exclamation mark when you get a chance?

**Comment by arouinfar** [comment]
Icon has been sent to @aaronsamuel137 -- sorry for the delay!

**Comment by aaronsamuel137** [comment]
This is being tracked in the main issue for the activity submit page now #102, so closing here.
