### ISSUE TITLE
Embed link layering

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#120]
Clicking on "Embed" underneath each sim screenshot on each sim page opens a menu that is layered behind the text for the drop down menus ( "About", "For Teachers", etc.).

![embed layerz](https://cloud.githubusercontent.com/assets/5863899/7122272/9bab90d8-e1d7-11e4-9ea9-deb6329f80a2.png)

Tested on each Win 8.1 browser.

**Comment by aaronsamuel137** [comment]
Fixed. Closing
