### ISSUE TITLE
Right to left languages layering

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#121]
Languages that read right to left encounter layering issues below sim screenshots:

![r2l layerz](https://cloud.githubusercontent.com/assets/5863899/7124455/359561ca-e1e6-11e4-8efc-aeaffaa06713.png)

Tested on Win 8.1

**Comment by aaronsamuel137** [comment]
This should be fixed. @phet-steele, will you take a look and see if it works for you? (You might need to force refresh).

**Comment by phet-steele** [comment]
Yup :+1:
