### ISSUE TITLE
Right to left languages search bar

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#122]
Languages reading right to left have a magnifying glass that is improperly placed:

![r2l layerz2](https://cloud.githubusercontent.com/assets/5863899/7124576/680895ea-e1e7-11e4-960c-356665b27645.png)

Tested on Win 8.1

**Comment by phet-steele** [comment]
Also, if I understand right to left languages at all, the cursor in the search bar should be moving to the left while typing, not the right.

**Comment by aaronsamuel137** [comment]
I've moved the magnifying glass (you might need to force refresh to see this change take place). The cursor seems to be moving to the left for me.

**Comment by phet-steele** [comment]
Both Chrome and IE11 look fixed, but FF it's still too far to the right. I did make sure to clear the FF cache.

**Comment by aaronsamuel137** [comment]
I think magnifying glass should be fixed in FF now. (You'll probably need to refresh your browser cache).

Assigning to @phet-steele for review.

**Comment by amanda-phet** [comment]
Looked at by @ariel-phet @arouinfar and myself. Looks good.
