### ISSUE TITLE
Large sponsor images on sim pages

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#126]
My judgement on whether the image for a sponsor was too large or not was based on if the image forced the orange line under the screenshot to be shifted downward.
The ones I encountered:
AACT
Royal Society of Chemistry
ECS
Science 4 Us
JCESC
Norton

**Comment by aaronsamuel137** [comment]
Thanks @phet-steele. I've limited the sponsor height so that none of these should extend beyond the line. Assigning to @phet-steele for review.

**Comment by phet-steele** [comment]
The sponsors can still push the line down.

Normal page:
![normal line](https://cloud.githubusercontent.com/assets/5863899/7663275/063a1198-fb25-11e4-9ac1-23c651ad431d.PNG)

Page with large sponsor:
![low line](https://cloud.githubusercontent.com/assets/5863899/7663273/fac0cae6-fb24-11e4-9c01-5c9b3b2dacab.PNG)

**Comment by aaronsamuel137** [comment]
Good catch. I set a max-height of 95px to all of these images, but some of them have padding that cause them to extend farther. This will be fixed on the next deploy.

**Comment by aaronsamuel137** [comment]
Fixed. Closing
