### ISSUE TITLE
The arrangement of the home screen is in the opposite order for 3 translated home pages

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#128]
Tested on 10.9.4, Chrome 41
For the following translated home pages, the home screen is arranged in an opposite order
http://phet-dev.colorado.edu/fa/
http://phet-dev.colorado.edu/ar_SA/
http://phet-dev.colorado.edu/ku/
The 3 translated home pages have the following order:
![screen shot 2015-04-16 at 11 33 11 am](https://cloud.githubusercontent.com/assets/5631059/7187225/5dafcde2-e42c-11e4-82fe-de2e4b777076.png)

On the English and all other home pages:
![screen shot 2015-04-16 at 11 23 21 am](https://cloud.githubusercontent.com/assets/5631059/7187207/438d20b8-e42c-11e4-9b96-d086a7df3b48.png)

**Comment by orejolaphet** [comment]
Ordering of the translated links at the bottom of the screen are also in reversed for the same 3 translated pages.
On the 3 translated pages:
![screen shot 2015-04-16 at 11 36 20 am](https://cloud.githubusercontent.com/assets/5631059/7187326/03eb3a70-e42d-11e4-966a-2cf816ea091c.png)
On the english page and all other pages:
![screen shot 2015-04-16 at 11 36 37 am](https://cloud.githubusercontent.com/assets/5631059/7187331/09d53bb6-e42d-11e4-9e10-5f9c135e878e.png)

**Comment by phet-steele** [comment]
@orejolaphet this is because these languages are written and read from right to left, so this is intentional albeit weird, I know.
