### ISSUE TITLE
On Java sims "Translate This Sim" button should go to translation utility page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#130]
Currently, on phet-dev clicking the "translate this sim" does not work properly

Clicking this button should take you to the PhET Translation Utility page

http://phet-dev.colorado.edu/en/for-translators/translation-utility

**Comment by aaronsamuel137** [comment]
Link updated. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good, closing
