### ISSUE TITLE
Update the gold star tool tip

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#131]
The tool tip for gold stars refers to a PDF, implying it contains a clickable link. The text should be updated to remove this reference.

![image](https://cloud.githubusercontent.com/assets/8419308/7258193/2a8fedda-e818-11e4-9268-aced921d78b2.png)

**Comment by arouinfar** [comment]
Because the gold star logo is not always attached to a specific activity (e.g. the activity submission page) the text should not read as though it is referring to a specific contribution.

@ariel-phet, @amanda-phet, what about this:

A gold star is used to indicate high quality, inquiry-based activities that follow the PhET design guidelines and that teachers have found to be useful.

**Comment by ariel-phet** [comment]
I am all for minimal text.... maybe just go with:

A gold star indicates high quality, inquiry-based activities that follow the PhET design guidelines.

(I feel like the "high quality" implies that teachers have found them to be useful)

**Comment by arouinfar** [comment]
I agree @ariel-phet. I'll go ahead and close this issue and provide @aaronsamuel137 with the updated text.

**Comment by patricialoeblein** [comment]
Actually we give Gold stars before anyone says that the activity is useful. I don’t mind the addition, I just thought I would clarify. There are many activities that other teachers like and find useful, but we don’t think they leverage the sims’ ability for students to drive their own learning.

Trish

**Comment by patricialoeblein** [comment]
Sorry for the last comment. As I read the thread more carefully, I see that no one is suggesting adding the  anything that implies that teachers find this  particular activity useful. I do like the "high quality" .  I would like to remove my previous comment.

**Comment by arouinfar** [comment]
No problem! Thanks for your input, @patricialoeblein.

**Comment by amanda-phet** [comment]
For clarification, the original tooltip reads: 

This activity has received a gold star because it is a high quality inquiry-based activity that follows the PhET design guidelines (PDF) and teachers have found it useful.

**Comment by patricialoeblein** [comment]
Thanks Amanda,
I made the mistake of just reading the email notification instead of going directly to GitHub to read the entire thread. Lesson 1M learned.

Trish
