### ISSUE TITLE
Final pixel polishing

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#133]
- [x] Remove the "find more information for translators" text/link under the translations table
- [x] Remember what sections on a sim page are open if you navigate away and then back (ex: click activity, click back, "For Teachers" should still be expanded) 
- [x] Move "Sample Learning Goals" section up to "About"

**Comment by aaronsamuel137** [comment]
> Remember what sections on a sim page are open if you navigate away and then back (ex: click activity, click back, "For Teachers" should still be expanded)

This issue is a little tricky. I have a solution that works for the most recently expanded area on modern browsers. To do more than this will require a more complicated solution. How important is this?

**Comment by amanda-phet** [comment]
What do you mean by "modern browsers"? 

It is fairly important. I noticed that sometimes it seemed to remember and other times it would return to the same *position* on the page but not have the section expanded, so I would need to scroll up to find the section and click it again (that is pretty undesirable behavior). So it seems to me that the back button should either go back to the expanded section, or go back to a completely refreshed sim page.

**Comment by aaronsamuel137** [comment]
OK I figured out an pretty nice way of doing this. I'll let you know when it's deployed.

**Comment by ariel-phet** [comment]
@aaronsamuel137 one other little tweak:

Can we also change the label "Activities" to "Teacher Submitted Activities"

**Comment by aaronsamuel137** [comment]
These issues should be addressed. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It should be "Teacher-Submitted Activities", with a hyphen.

The only odd behavior I noticed is that once I expand a section, say "About" on the Area Builder sim page, it is always expanded on future sim pages I visit, like Acid-Base Solutions. It's not necessarily a bad thing, because once I expand a section I probably want to view it on other pages, but I think it's worth seeing what other people think about this behavior. @ariel-phet @oliver-phet @arouinfar want to comment?

**Comment by ariel-phet** [comment]
Oh, I think we definitely we it to be a conscious choice to expand a heading each time. My guess is @aaronsamuel137 was working on things so that when you go back to a particular page where you have expanded, that heading stays expanded (ie you go to the activities, click on an activity and then go back) and then this bug crept in.

**Comment by amanda-phet** [comment]
Right, this is referring to the second item in the original list above.

**Comment by arouinfar** [comment]
I agree with @ariel-phet. I think users should expand the sections each time they visit a <i>new</i> sim page (but not when navigating back to a page they just visited).

I've noticed the credits don't seem to be accurate on HTML5 sim pages. pH Scale's credits seem to be the for the Java version of the sim -- Yuen-ying isn't credited on the sim page, though she lead the redesign. Molecules & Light has an empty credit section.

**Comment by amanda-phet** [comment]
The sections should stay expanded when navigating back! That was the whole point. But if you go to the Simulations page, then click the same sim page you visited earlier in the day, it would be refreshed. 

I suspect that the metadata for HTML5 sim pages needs to be manually updated when the pages are published.

**Comment by arouinfar** [comment]
That's what I meant -- if a user expands the "For Teachers" section on a sim page, clicks on an activity, and then navigates back to the <i>same</i> sim page, For Teachers should still be open. However, if the user navigates to a <i>different</i> sim page, the For Teachers section should not be open until they manually expand it.

**Comment by aaronsamuel137** [comment]
Good catch. The code currently treats all sim pages as the same page. I will fix this.

The expected behavior is that the expanded texts will be remembered for every page as long as the tab is open. It won't persist across tabs - but it will remember even after some time if you go back to a page in the same tab.

@arouinfar - as far as the credits are concerned this is something that will need to be updated manually on a per sim basis. I would say don't bother to do it on phet-dev since it will need to be re-done on the main page anyway.

**Comment by aaronsamuel137** [comment]
I think this should be fixed. You may need to force refresh all of the sim pages you are testing with. Assigning to @amanda-phet

**Comment by amanda-phet** [comment]
Looks like it's working well. Closing!
