### ISSUE TITLE
Reciprocal Related Sims

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#134]
It looks like @patricialoeblein had @phet-steele  working on a spreadsheet identifying sims that linked to related sims (but that didn't link back). I suppose this was created so that we could manually add these related sims. 

Ideally, @aaronsamuel137 could come up with a way for this to be automatically done whenever someone adds a related sim for one sim page, that sim gets added to the other sim page in the related sims category. 

For example: When Least-Squares Regression was added, I added Graphing Lines as a related sim. However, Graphing Lines does not list Least-Squares Regression as a related sim, but it would be nice if this was automatically done. 

Here is a spreadsheet with all existing relations, relations that need added, and some suggestions that @phet-steele created: https://docs.google.com/spreadsheets/d/1WfxOP6F3CZza1t_n16UBsqIO6T52-WAOKXYydEYC0QY/edit?usp=sharing

**Comment by patricialoeblein** [comment]
One reason we made a spreadsheet was to enable the metadata review. It would be a good idea to decide how many sims should ideally be linked - at one time there was a discussion of having a maximum. This summer we hope to have a thorough review including keywords, links to NDSL, etc. As part of that plan it would be helpful it the spreadsheet were maintained.

**Comment by aaronsamuel137** [comment]
@amanda-phet, what should be the behavior when a related sim is removed? Should its reciprocal also be removed?

**Comment by amanda-phet** [comment]
That sounds reasonable to me. Perhaps @patricialoeblein can weigh in again.

**Comment by patricialoeblein** [comment]
Sounds reasonable to me too.

**Comment by aaronsamuel137** [comment]
I've made this change. Now, whenever a related sim is added or removed through the sim admin page, the, both the sim and the related sim will add each other or remove each other.

I also fixed a bug where you can't tell which sims are HTML and which are legacy in the admin interface.

Existing asymmetrical related sim relationships will not be changed by this fix.

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
This seems to be working. I added Gas Properties as a related sim to Area Builder and they are reciprocal. When I deleted it as a related sim, they were both deleted. 

And to clarify, adding a related sim to an HTML5 version of a sim does not also add it for the legacy version. I'm not sure I understand the bug you fixed but everything seems to be working fine.

**Comment by aaronsamuel137** [comment]
Yes that's correct. It wasn't really bug I fixed, I just added that (HTML5) suffix so you can distinguish which ones are which. Feel free to close if this looks good to you.

**Comment by amanda-phet** [comment]
Great! Closing.

**Comment by amanda-phet** [comment]
I think we might need to revisit this issue and have an undergrad go through sims and re-add the related sims. It looks like this functionality works moving forward, but does not make any changes to previously added related sims. @ariel-phet what do you think?

**Comment by ariel-phet** [comment]
I know just the man for this task....

@phet-steele - batter up! :baseball:

**Comment by phet-steele** [comment]
@amanda-phet @ariel-phet should I remove any related legacy sims if they have an HTML5 version, then add the HTML5 version? I'm going to assume the answer is yes and will be moving forward with removing.

**Comment by phet-steele** [comment]
Well never mind, for some reason I can't add legacy sims to the Related Sims category. @ariel-phet can I have @mattpen look into this real quick?

**Comment by ariel-phet** [comment]
@phet-steele - if an HTML5 version exists, we should **NOT** add the legacy version to related sims. So for instance, pH Scale (HTML5) should be added, but the legacy version should not be in related sims.

It appears a legacy sim can be added if no HTML5 version exists (such as sugar and salt solutions in the screenshot above). Is that correct

**Comment by phet-steele** [comment]
> It appears a legacy sim can be added if no HTML5 version exists (such as sugar and salt solutions in the screenshot above). Is that correct

@ariel-phet yes, but I just want to make sure we are absolutely clear here. My question is refering to the actual legacy sim page of Acid-Base Solutions (there are two pages for ABS, HTML5 and the older legacy one). They can have separate related simulations, and I was proposing we add legacy versions to legacy pages only, not to the HTML5 page.

**Comment by ariel-phet** [comment]
@phet-steele on legacy pages, we still want to add HTML5 sims when they exist. The reasoning behind this strategy is we want to continue to drive all traffic to the HTML5 versions. So even on the ABS Java page we want to add related java/flash sims only when an HTML5 version does not exist.

**Comment by phet-steele** [comment]
@ariel-phet 10-4

**Comment by phet-steele** [comment]
@amanda-phet @ariel-phet sims should now have correctly related simulations. You can take a pass to make sure everything is correct, but I do not think there is anything left to do here.

Thanks @alynne-phet for doing this.

**Comment by amanda-phet** [comment]
I looked at a number of sim pages and it seems like the related sims section is looking good. Thanks!
