### ISSUE TITLE
Registration page not fully working

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#135]
I was not able to select a country on the registration page and received the following error

![screen shot 2015-04-23 at 9 55 05 am](https://cloud.githubusercontent.com/assets/7717368/7301297/0d664082-e99f-11e4-9061-4f14e4353450.png)

**Comment by aaronsamuel137** [comment]
This page isn't finished yet. I'll let you know when it's ready for testing.

**Comment by aaronsamuel137** [comment]
Closing - this page will need testing, but it will be tracked in another issue.
