### ISSUE TITLE
Should LTR languages display the whole page LTR?

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#136]
I noticed when using a left-to-right reading language that the whole front page was altered to left-to-right

Dutch
![screen shot 2015-04-23 at 9 58 12 am](https://cloud.githubusercontent.com/assets/7717368/7301378/9ad1dcce-e99f-11e4-9fb2-b8eb36cd61db.png)

Arabic
![screen shot 2015-04-23 at 9 58 25 am](https://cloud.githubusercontent.com/assets/7717368/7301383/a2df794e-e99f-11e4-862c-b0d8cd235058.png)

I assume this is intentional but I just wanted to check

**Comment by aaronsamuel137** [comment]
I'm inclined to not do anything about this. Assigning to @ariel-phet to comment or close.

**Comment by ariel-phet** [comment]
This is the correct behavior (since in a RTL language, viewers will tend to see the play with sims button first in their visual scan)
