### ISSUE TITLE
Flash and HTML5 icons not positioned correctly on Windows 7

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#137]
When opening the sim page in Arabic on Windows 7 IE 11 I observed the following

![screenshot1](https://cloud.githubusercontent.com/assets/7717368/7302441/afba8120-e9a6-11e4-9590-1233370a14de.png)

**Comment by aaronsamuel137** [comment]
Good catch. This issue is on the live site too: http://phet.colorado.edu/ar_SA/simulations/category/html

**Comment by aaronsamuel137** [comment]
This should be fixed now. Assigning to @bryo5363 for review (you may need to refresh your browser cache to see the fix)

**Comment by ariel-phet** [comment]
This is working now, closing
