### ISSUE TITLE
Resizing issues with the top of the page

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#139]
When the browser is about half the size of the screen, some of the top of the page gets cut off. For instance the words "University of Colorado Boulder" are missing:

![resized banner](https://cloud.githubusercontent.com/assets/5863899/7326024/84bf02a0-ea7f-11e4-99de-bde73d54515e.png)

Tested on FF 37.0.2, IE11, Chrome 42.0.2311.90 m with Win 8.1 as well as OSX 10.10.2 Chrome 42.

**Comment by aaronsamuel137** [comment]
There are numerous issues on the site related to resizing as the site as a whole is not responsive. I have moved over the CU logo so it at least it start getting cut off at the same time as the rest of the page content.

@ariel-phet, is there anything I should do for this issue for now?

**Comment by ariel-phet** [comment]
No...let's close for the moment...this will wrapped into the front page redesign, navigation, and moving towards more responsive design.
