### ISSUE TITLE
Searching returns duplicate sim names

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#140]
For example, if you type "acid" in the search bar "Acid-Base Solutions" will be returned twice in the search results. Both of these link to the same (HTML5) sim.

![acid](https://cloud.githubusercontent.com/assets/4051174/7341756/09886602-ec65-11e4-9a11-5f9c05eea59d.PNG)

**Comment by aaronsamuel137** [comment]
This should be fixed. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good, closing!
