### ISSUE TITLE
Autoscroll to selected simulation on submission page after pressing "share an activity"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#141]
I noticed then when I press "Share an Activity" from a sim page and go to the activity submission page it is pretty clear that I have selected a particular sim by the screenshot, but it would also be nice if the list of sim checkboxes also was autoscrolled to the sim from which I had navigated to the activity submission page.

I think this is would be a nice enhancement but not necessarily for completion of #102 so I thought it best as a separate issue.

**Comment by aaronsamuel137** [comment]
This should work now. Assigning to @ariel-phet

**Comment by amanda-phet** [comment]
This isn't working for me.

**Comment by aaronsamuel137** [comment]
Try it after refreshing and let me know if it still isn't working - seems to work for me.

**Comment by amanda-phet** [comment]
Sorry, you're right I hadn't refreshed. Looks good to me!

**Comment by amanda-phet** [comment]
@ariel-phet hasn't responded but this is working so I'll close the issue.
