### ISSUE TITLE
Deploying Java translations could be better

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#142]
Currently, the website is running into a problem when the 'publish now’ button on the translation screen (https://phet.colorado.edu/admin/deploy-translation?dir=%2Fdata%2Fweb%2Fhtdocs%2Fphetsims%2Fstaging%2Ftranslations%2F4-28-2015_4-44PM) no feedback is given - the button just disappears, and I still don’t know if/when the translations actually get published to the site. If I try refreshing the page, the ‘publish now’ button reappears, giving me the impression the translations weren’t deployed… this requires me contacting JO/AD to confirm that the translations were published. Seems like an unnecessary step that could be avoided (and the site used to function and provide feedback).

Example of current behavior:
![screen shot 2015-04-29 at 10 49 09 am](https://cloud.githubusercontent.com/assets/5090275/7396323/70fa495a-ee5d-11e4-93ef-9d79c628cf14.png)
After pressing button....
![screen shot 2015-04-29 at 10 49 18 am](https://cloud.githubusercontent.com/assets/5090275/7396328/78922d5e-ee5d-11e4-9a93-1f2d43737382.png)

Is there a way to add some sort of feedback to this step so that I can confirm with translators when their translations have been published?
Example (after pressing 'publish now'):
![processing](https://cloud.githubusercontent.com/assets/5090275/7396394/db31e76a-ee5d-11e4-914b-21aef0b8c150.jpg)
![published](https://cloud.githubusercontent.com/assets/5090275/7396397/df6fe46c-ee5d-11e4-895a-2497f1d4ac96.jpg)

**Comment by jonathanolson** [comment]
Noted verbally, but this type of behavior used to work. I'm not sure when the regression happened. @aaronsamuel137, any ideas?

**Comment by aaronsamuel137** [comment]
No ideas off the top of my head. The only code I've changed that I am aware is related to translation deploy is in Project.java. Though I don't see how the changes here could've broken this.

I can look into it at some point if that would be helpful.

**Comment by mattpen** [comment]
@oliver-phet - Is this issue still occurring?  Do you need me to look at it anytime soon?

**Comment by phet-steele** [comment]
@mattpen yea this still occurs; I don't mind it (I'm responsible for translating these days). I have my workaround of just waiting to see when they appear on the site, but it would be a nice enhancement. Personally I do not have a "need" for you to look into it.

**Comment by mattpen** [comment]
This issue appears to be stale, removing assignment.

**Comment by zepumph** [comment]
@phet-steele seems to have a work around in place, so this isn't pressing, I'm going to close this issue and combine this into the phetsims/tasks#672. It seems like it could be a relatively simple addition while they are working on the build tools anyways.
