### ISSUE TITLE
Have returning users update their profile

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#143]
If a user who has not completed the latest registration page comes to the site and signs in, we would like to automatically redirect them to the Edit Profile page so that they can update the new registration fields. Once they have done this, it should not happen again. 

The Edit Profile page will also have a message that reads:
We are working to improve the usability of our site. To support this effort, please update your profile! 
![registration-03](https://cloud.githubusercontent.com/assets/7852916/7401790/0a6ec64e-ee84-11e4-8ef1-59d38f34eb75.png)

**Comment by aaronsamuel137** [comment]
Currently, "name" is one field in the database where users can enter first and last name with a space between, or whatever else they want. Switching to first and last name as separate columns will introduce some complications.

Do we want to totally ignore the name column and force users to enter their first and last name again as separate fields when they first log in?

**Comment by aaronsamuel137** [comment]
Assigning to @amanda-phet for review.

**Comment by ariel-phet** [comment]
Pixel polish: I think we might want the text in the "we are working to improve usability" be Bold

**Comment by amanda-phet** [comment]
This is working. To address the comment about separate first and last names... I noticed that when I was prompted to edit my profile it had already split up my name into respective first and last names. Is this what will happen for other users?

**Comment by aaronsamuel137** [comment]
The first and last name issue has been discussed over email. Regarding the bold text, here is a screen shot of what it looks like:

![screen shot 2015-05-05 at 10 37 36 am](https://cloud.githubusercontent.com/assets/3193912/7477702/ca5b4094-f312-11e4-89c5-c294051f88fa.png)

Feel free to close if it looks good @ariel-phet or @amanda-phet

**Comment by amanda-phet** [comment]
Looks good. Closing.
