### ISSUE TITLE
Activity information on phet-dev

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#145]
We went through all of the activities that we determined should have an HTML5 sim listed and modified the information on phet-dev. When you eventually push all of the phet-dev changes to the live site, will these changes to the activities also transfer? We don't want to overwrite any changes that individual teachers may have made to their activities in the meantime, but if you could "sync" just the sim information for an activity that might work. If this is not possible, we can always redo the work after the changes go live.

**Comment by aaronsamuel137** [comment]
Unfortunately that will not be possible. The two databases have gotten very out of sync since this work has begun and trying to sync some changes but not others wouldn't be easy.

**Comment by amanda-phet** [comment]
Makes sense. We were prepared for the possibility that these changes would be temporary.
