### ISSUE TITLE
Remove 3 old entries from Mac Troubleshooting

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#146]
@BrianNewsom @aaronsamuel137 Can one of you please remove the top 3 entries from the Mac Troubleshooting page: http://phet.colorado.edu/en/troubleshooting/mac
(seeing dialog, run now text file, 3d graphics)

These are old entries that no longer need to be there.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph

**Comment by zepumph** [comment]
Removed the top three entries from mac troubleshooting. assigning to @aaronsamuel137 for inspection.

**Comment by aaronsamuel137** [comment]
Looks good to me. @oliver-phet can you review this on phet-dev and make sure the troubleshooting and FAQ pages look up to date to you?

**Comment by oliver-phet** [comment]
Yep. Looks good.

**Comment by oliver-phet** [comment]
This is done. Closing.
