### ISSUE TITLE
Remove old Windows 2000 issue from Windows Troubleshooting

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#147]
Can you also remove the entry about Windows 2000 - we don't support.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph

**Comment by zepumph** [comment]
Removed the entry

**Comment by zepumph** [comment]
assigning to @aaronsamuel137 for inspection.

**Comment by aaronsamuel137** [comment]
Closing this, but @oliver-phet please review all FAQ/troubleshooting changes when you review #146

**Comment by oliver-phet** [comment]
Looks good to me!
