### ISSUE TITLE
Change "All Sims" page to thumbnail view by default

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#150]
When viewing "all sims", the default is to currently see an indexed list and not thumbnails. 

We made a change to the site when viewing in a different locale... If you view the site in French, and click the big play with sims button, you are directed to the All Sims page instead of New Sims (because HTML5 sims aren't translated yet!). 

However, we are realizing now that this is a little odd, because their interaction with browsing sims is in a list and not thumbnails. Also, the list does not distinguish the translated sims from untranslated. 

Rather than directing users in a different locale to http://phet-dev.colorado.edu/fr/simulations/index, they should be directed to http://phet-dev.colorado.edu/fr/simulations so that the translated sims are first and viewed as thumbnails. To be consistent, **we would just like to change "All Sims" (in all locales) to be the thumbnail view by default and not index view.**

**Comment by aaronsamuel137** [comment]
I've updated this link. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It seems like you updated the link for the Play with sims button and it's working well, but clicking on All Sims (in any locale) still directs me to the index view. Is it possible to change that link to be the thumbnail view as well?

**Comment by aaronsamuel137** [comment]
Sorry, missed that bit. I'll do that now

**Comment by aaronsamuel137** [comment]
OK should be good to go now. Assigning to @amanda-phet

**Comment by amanda-phet** [comment]
Looks great. Closing.
