### ISSUE TITLE
Email me PhET's newsletter - should be checked by default

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#151]
When I am prompted to update my profile, this box should be checked by default. 

I checked it myself, and submitted my update. Then, I clicked on "Edit profile" and the box is unchecked! 

When I made a new profile, it *was* checked by default, but when I clicked on "Edit profile" the box is unchecked again.

**Comment by aaronsamuel137** [comment]
I think this is fixed. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I'm having trouble checking- every time I try to register I get the error page. Not sure why. 

![screen shot 2015-05-07 at 3 21 15 pm](https://cloud.githubusercontent.com/assets/7852916/7526164/bc42dfc4-f4cc-11e4-91a4-ce50a01fb9f9.png)

**Comment by amanda-phet** [comment]
actually, I can't log in at all right now.

**Comment by aaronsamuel137** [comment]
Hmm I am seeing log messages:

```User amanda.mcgarry@colorado.edu has not confirmed their email```

Is this a new email you are using to test, or the email you have been using before?

**Comment by amanda-phet** [comment]
the email I was using before. It works on the live site but not phet-dev.

**Comment by aaronsamuel137** [comment]
yeah looks like there are some backend issues happening with registration, I'll let you know when I have resolved some of them.

**Comment by aaronsamuel137** [comment]
OK I've fixed at least one of the errors that was happening. Now you should be able to register for a new account without getting an internal server error.

I still am not sure why your email got unconfirmed @amanda-phet. For now I have manually reconfirmed you, but we will definitely want to watch out for this happening again, and if possible figure out how to reproduce it. I didn't run into this problem myself. Be sure to make a note to other testers to let me know if credentials that previously worked for them stop working.

**Comment by amanda-phet** [comment]
Is there a verification process for emails that checks to see if a user is already registered? I may have tried to register with an email that was already registered.

**Comment by amanda-phet** [comment]
I'm pretty sure that is what happened... I registered with an email I was already using. My profile is now the new one that you manually confirmed.

**Comment by aaronsamuel137** [comment]
Good point. Looks like this email check broke at some point along the way, though it was working before. I'll work on that next.

**Comment by amanda-phet** [comment]
The original issue posted here is addressed, to be clear. 

I'll leave it open while we address the email verification step.

**Comment by aaronsamuel137** [comment]
Trying to register with an existing email address should validate now. Feel free to close if this looks good to you @amanda-phet

**Comment by amanda-phet** [comment]
Perfect. Closing.
