### ISSUE TITLE
Stay logged in longer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#152]
We made a change to stay logged in while the tab is still open. However, this often times out and I have to log in again! Is there a time limit for staying logged in? I thought it was supposed to stay logged in while the tab was open. Is it a problem if I open the site in another tab?

**Comment by aaronsamuel137** [comment]
Right now sessions are set to timeout after 30 minutes of inactivity. I can change this number if you'd like.  What do you have in mind?

Also - you will only be signed in if you are browsing using https. So if you are logged in on one tab and you open another tab using http, it will appear as though you are not logged in. But if you open another tab using https, you will be logged in on both tabs, as expected.

**Comment by amanda-phet** [comment]
I think the issue for me was the http vs. https, so it seemed like I was logged out each time I clicked a new PhET link. 30 minutes seems fine to me. I'll go ahead and close this issue.
