### ISSUE TITLE
error message when uploading activity

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#156]
When I uploaded two different files, one of which was not allowed, I got an error message. Two issues I see. 
1. The message take up a lot of width and doesn't look good behind the blue panel. 
2. Both of my files are gone! Not just the bad one. Now I have to upload the good one again, and I might not be 100% sure which one that even was, because the error message might be behind the blue panel. Or I might not bother to read it all because I see a red box directing me to the problem area(s). 
![screen shot 2015-05-07 at 4 40 56 pm](https://cloud.githubusercontent.com/assets/7852916/7527497/f19cb9ea-f4d8-11e4-8158-5eb5fd4fe126.png)

@arouinfar What do you think? Should the good files remain uploaded? How would this error be handled in that case?

**Comment by aaronsamuel137** [comment]
Fixing the error message width will be an easy fix, but having the correct files remain uploaded will significantly complicate the implementation. I would recommend against this because it doesn't seem too unreasonable to have them select the files again. It will most likely be only one or two files, and it will be clear what the problem is when the blue panel issue is fixed.

**Comment by aaronsamuel137** [comment]
The first issue has been fixed. Assigning to @amanda-phet for review. Feel free to close if the 2nd issue seems non-essential, or let me know if you think it is really important.

**Comment by arouinfar** [comment]
Given that keeping the correct files uploaded is significantly difficult to implement, I think it's fine to have users reselect all of their activity files. I agree with @aaronsamuel137, authors typically only upload a small number of files, so this should only be a minor inconvenience to them.

**Comment by amanda-phet** [comment]
The error message looks good to me. 

I disagree, though, that authors upload a small number of files- they often have at least 4 files (at least internal authors do!). However, since it is complicated to implement, we can skip it.
