### ISSUE TITLE
error message when using an invalid email

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#157]
When I use an invalid email I get a really long error message... can it just say "enter a valid email address"? 
![screen shot 2015-05-07 at 4 40 56 pm](https://cloud.githubusercontent.com/assets/7852916/7527514/22bd4198-f4d9-11e4-999e-6f673edad24f.png)

**Comment by aaronsamuel137** [comment]
Turns out this is an issue on figaro too. Should be fixed now on phet-dev. Assigning to @amanda-phet

**Comment by amanda-phet** [comment]
Looks good. Closing.
