### ISSUE TITLE
Add ability to sign in to the site by clicking the "lock" on a Teacher Primer Video

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#158]
Currently the teacher primer is locked unless you are signed in (as requested). Can we add the ability to sign in to the site by clicking the lock on a Teacher primer video - rather than scrolling to the top of the page and clicking the "sign in" button?
So the user could either click the lock or the video and get the prompt to sign in (similar how they click the screenshot/play button to launch a sim).

![screen shot 2015-05-08 at 12 02 55 pm](https://cloud.githubusercontent.com/assets/5090275/7542487/56f5cfd8-f57a-11e4-8100-71b0e28aa523.png)
![screen shot 2015-05-08 at 12 03 11 pm](https://cloud.githubusercontent.com/assets/5090275/7542488/56f8e042-f57a-11e4-923a-c4d9ac746024.png)

**Comment by aaronsamuel137** [comment]
I can add this. I already added a feature where you can log in by clicking the "Please sign in to watch the video primer" text for the same reason.

**Comment by aaronsamuel137** [comment]
This was a quick change. Should be working now. Assigning to @oliver-phet for review.

**Comment by phet-steele** [comment]
Working for me on OSX 10.10.1, Chrome 42.

**Comment by aaronsamuel137** [comment]
Seems to be working fine, so I'm closing the issue.
