### ISSUE TITLE
Activity Submission - language selection

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#161]
Right now the language dropdown is working as we hoped- it automatically selects the language based on the locale you are viewing the site in. For example, I am viewing in Danish: 

![screen shot 2015-05-11 at 1 41 02 pm](https://cloud.githubusercontent.com/assets/7852916/7573545/ba45177c-f7e3-11e4-9fe1-119419c2d23e.png)

Would it be possible to view the languages in this dropdown in the language of the locale? For example, if viewing in Danish, the languages would be listed in Danish rather than English:
![screen shot 2015-05-11 at 1 44 06 pm](https://cloud.githubusercontent.com/assets/7852916/7573563/e3d24eca-f7e3-11e4-96cc-feef15e09c42.png)

**Comment by aaronsamuel137** [comment]
This will require totally redoing the current implementation of these dropdowns. It's actually a bit of a project, so I'm not sure we want to have this as part of the the first deployment. What are your thoughts @ariel-phet?

**Comment by amanda-phet** [comment]
I think it's fine the way it is since it automatically selects the locale you're viewing the site in. Just wanted to find out how difficult it might be to change.

**Comment by ariel-phet** [comment]
Seems like this would fall in the "nice touch" category, certainly not priority for the moment

**Comment by ariel-phet** [comment]
Reassigning to @mattpen - this is not at all a high priority, but might make a nice project at some point down the road.

**Comment by mattpen** [comment]
@amanda-phet - I took a stab at this tonight.  This dropdown selector is used in several places across the site (the website translation page for example).  Is it ok to go ahead and implement this behavior across the entire site?  If so this change is pretty trivial.

**Comment by amanda-phet** [comment]
@ariel-phet is it ok to implement across the site? I'm not aware of any other instances of it, so it might be good to know all of them before moving ahead with this.

**Comment by ariel-phet** [comment]
@mattpen @amanda-phet - I think it would be OK to implement across the site. If you are viewing the website in a particular locale, there seems to be no downside to displaying the dropdown with languages in that locale.

**Comment by mattpen** [comment]
@amanda-phet @ariel-phet - I published a fix for this to phet-dev.  Does this look ok to publish to figaro?

**Comment by ariel-phet** [comment]
@mattpen something is a bit messed up with the parentheses in a RTL language. 

Notice correct for the chosen language, but funky for most others.

![dropdown](https://cloud.githubusercontent.com/assets/4051174/13408589/e79afb2a-deeb-11e5-912d-e474589578d2.PNG)

**Comment by mattpen** [comment]
@ariel-phet - I think this problem is occurring site-wide - #394

**Comment by mattpen** [comment]
This has been published on phet-dev and appears to be working.  I'll deploy it to figaro next week.

**Comment by mattpen** [comment]
The temporary fix was deployed to figaro tonight.  Permanent fix will be addressed as part of #394.
