### ISSUE TITLE
Add iPad/Tablet category and Chromebook category by default to new sim publications

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#162]
Can we have the iPad/Tablet category and Chromebook categories assigned by default for all new sim publications? Currently it has to be manually added like the others (Physics, Chemistry, Math... etc)

**Comment by ariel-phet** [comment]
@aaronsamuel137 - it looks like you have added this functionality in a commit. Is it working? If so please feel free to close this issue.

**Comment by aaronsamuel137** [comment]
I'm pretty sure this is working. @oliver-phet if it isn't working for you feel free to re-open.
