### ISSUE TITLE
Build and deployment server

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#163]
Input: a list of repo dependencies and the SHAs that they should be at, and list of locales to build
Probably should include where to publish (dev? production?)

Step 1: Checkout repos with SHAs (if necessary), npm install (if necessary)
Step 2: Build the specified locales
Step 3: Upload the built files to the desired server(s)
Step 4: Notify said servers (websites) that they were deployed

The request for build/deploy should be authenticated somehow (it's a PhET request), and any errors should stop the
entire process (and hopefully return a status result about the build).

It would be nice for it to be able to build without deploying anything (for continuous integration testing), just to
see if there are any build problems introduced by commits.

Then we could have a lightweight chipper script that could fire off the request to the build server.

Additionally, it would be nice to have the default build/deploy first build and copy the files, but not "deploy" as in
overwrite the currently-live version. It would be nice to run and test the HTML files that have been built before that
step happening (like the translation deployment).

**Comment by aaronsamuel137** [comment]
I thought we discussed putting this in chipper (or possibly a new repo). Is there a reason you have created the issue in the website repo?

**Comment by jonathanolson** [comment]
My mistake, see https://github.com/phetsims/chipper/issues/141. Closing here.
