### ISSUE TITLE
K-5 check boxes do not appear

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#165]
When registering for an account and one checks they are in "Elementary" under the Grade(s) section, the options to further choose if you are in K-5 don't immediately appear. They appeared after I entered something wrong and the page was reloaded with error messages, or when after creating my account I went to edit my profile.

Mac OSX 10.10.1, Chrome 42

**Comment by ariel-phet** [comment]
@phet-steele - had you marked your country as "USA"?

The checkboxes will only appear if you are in the USA (since these grade levels do not make sense in most other countries)

**Comment by phet-steele** [comment]
No, I was in Latvia. But even then they DID show up after the profile was made.

**Comment by ariel-phet** [comment]
Yeah, that is a bug

**Comment by phet-steele** [comment]
Same with the "University" option.

**Comment by aaronsamuel137** [comment]
I think this is fixed now. At least the issue of the checkboxes appear when you submit and get an error should be fixed. You'll need to hard refresh to see the fix.

Assigning to @phet-steele for review.

**Comment by phet-steele** [comment]
Both instances of check boxes appearing are fixed.
