### ISSUE TITLE
Error message order

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#166]
I noticed that the error messages aren't listed in the order the page is filled out (screenshot taken with no information entered):
![screen shot 2015-05-12 at 9 21 30 am](https://cloud.githubusercontent.com/assets/5863899/7590987/7319d9f0-f888-11e4-9b99-df27b76af796.png)

Wouldn't it make more sense to have "Please enter a valid email address" come first, etc., since it would be the first required field? 

Mac OSX 10.10.1, Chrome 42

Furthermore, just as a side note, there is an error message saying "Please enter a city" even though the option to enter a city isn't available until a state/province is selected so there isn't a box highlighted red until then. It just seems like it could be slightly confusing for a user as they may be looking frantically at the page for a city option without knowing they have to enter a state/province first, maybe...just an additional thought.

**Comment by ariel-phet** [comment]
Agreed, these error messages should be ordered to match the ordering on the form.

As for the city option - that makes sense - is that easy logic to add @aaronsamuel137?

**Comment by aaronsamuel137** [comment]
It is easy to match the order in the register form. However, due to the way the contribution form is implemented, changing the order will require using different kind of form components in the Java code, which will take a little bit longer. I can do this if it seems important.

As far as the city goes, it will be pretty easy to not have that validate unless there is a state selected. But then it won't be obvious that it is required when it does appear.

**Comment by aaronsamuel137** [comment]
Assigning to @ariel-phet. Please reassign to me if you think the order is really important in the contribution submit page or if you'd like the city behavior to be changed again. Right now the city doesn't validate unless a state is selected.

**Comment by ariel-phet** [comment]
Not a big priority, it seems like a nice touch, but not necessary for the initial deploy

**Comment by aaronsamuel137** [comment]
Feel free to take a look at the @zepumph - though it is low priority.

**Comment by zepumph** [comment]
@aaronsamuel137 want to take a look at this, I think It's ready to close.

**Comment by aaronsamuel137** [comment]
Looks good to me. Tested on phet-dev and appears to be working well. The only changes I have made are formatting and removing commented code.

**Comment by aaronsamuel137** [comment]
Closing
