### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#170]
I tried selecting the "forgot password" option when logging in to see if I could reset my password. I got the email pertaining to the password change but when I clicked the link I received the following message 

![screen shot 2015-05-12 at 10 31 15 am](https://cloud.githubusercontent.com/assets/7717368/7592707/10eec3c6-f892-11e4-9abe-28eceae72e86.png)

Note that I was initially on the dev page and was taken to the actual page.

**Comment by phet-steele** [comment]
Maybe unrelated, but changing your password by means of "Edit Profile" --> "Change Password" at the bottom of the page DOES work.

**Comment by aaronsamuel137** [comment]
This is fixed now. It was just the link that was broken - it should point to phet-dev not phet when on the phet-dev site.

Assigning to @bryo5363 for review.

**Comment by bryo5363** [comment]
@aaronsamuel137 I observed some strange behavior when changing my password. I got the PhET password change email and successfully changed my password; after I changed the password I signed out and was taken to a page requesting me to sign in. Once I entered my information and pressed submit, I was taken to the homepage but I was signed out of my profile

**Comment by aaronsamuel137** [comment]
Good catch! Please verify and close the issue if it's working for you @bryo5363

**Comment by aaronsamuel137** [comment]
This was fixed awhile ago. Closing
