### ISSUE TITLE
RTL log in needs work

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#172]
When using an RTL language, I accessed the log in tab and noticed the display needed some work

![screen shot 2015-05-12 at 10 35 27 am](https://cloud.githubusercontent.com/assets/7717368/7592814/e8555532-f892-11e4-88bb-de918e43c34a.png)

**Comment by ariel-phet** [comment]
Good catch @bryo5363

**Comment by aaronsamuel137** [comment]
I've fixed this. It still looks a little weird because there are english strings in rtl, but it should be good once it is translated.

Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good, closingg

**Comment by bryo5363** [comment]
I noticed the RTL login screen still needs some adjustment

![screen shot 2015-05-28 at 12 18 47 pm](https://cloud.githubusercontent.com/assets/7717368/7867505/bd89d17c-0533-11e5-9755-b21d77936175.png)

**Comment by aaronsamuel137** [comment]
There's not an easy way to fix these issues - basically it just has to do with displaying left to right text inside of a right to left container. So the punctuation placement gets messed up. Once it is translated, these issues will not be here anymore.

Do you see other issues aside from punctuation being on the wrong side?

**Comment by bryo5363** [comment]
Nope, nothing besides that. Everything else looks good

**Comment by aaronsamuel137** [comment]
OK in that case I am closing this. It will have to be addressed by the translator.
