### ISSUE TITLE
Issue clicking arrows for pages with drop down menus (Trouble Shooting & FAQ)

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#173]
On the following pages:
https://phet-dev.colorado.edu/en/faqs
https://phet-dev.colorado.edu/en/troubleshooting
    https://phet-dev.colorado.edu/en/troubleshooting/mac
    https://phet-dev.colorado.edu/en/troubleshooting/windows

If you click to the slight to the left of the arrows, not the arrows themselves, the page scrolls down and changes its URL extension 
For example:
Open FAQ
https://phet-dev.colorado.edu/en/faqs

Click to the left of the first arrow for "What are the System Requirements for running PhET simulations?"
the page will scroll down and you will be directed to:
https://phet-dev.colorado.edu/en/faqs#q2-header

OSX 10.10.2 Chrome 42

**Comment by orejolaphet** [comment]
Note that clicking the left of the arrows does not expand the header.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - this seems similar to the issue you and I worked on for the sim pages themselves. I have marked this issue with the "Soon after sim pages deployed" milestone. Would be nice to take care of, but not a top priority

**Comment by phet-steele** [comment]
Clicking slightly above the title of each menu has the same effect.

**Comment by aaronsamuel137** [comment]
Should be fixed. Assigning to @phet-steele or @orejolaphet for verification. Close if it looks good to you.

**Comment by phet-steele** [comment]
Good to go.
