### ISSUE TITLE
Add a "Your changes will not be saved, would you like to continue?"

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#175]
I was thinking the addition of a "Your changes will not be saved, would you like to continue?" pop-up would be appropriate when leaving the edit pages? Namely, edit profile and edit activity.

**Comment by ariel-phet** [comment]
@amanda-phet - seems like a reasonable suggestion...I don't think it is necessary for the initial deployment, but might be useful. What do you think?

**Comment by amanda-phet** [comment]
I'd like to find out how complicated it is to implement. @aaronsamuel137 what would you say?

**Comment by aaronsamuel137** [comment]
It's pretty simple, at least for a basic implementation. I can put something on phet-dev for you to look at if you'd like

**Comment by zepumph** [comment]
Can this issue be closed @aaronsamuel137?  Or is there something I can do to fix it? Why was your commit reverted?

**Comment by aaronsamuel137** [comment]
I don't remember the exact reason for reverting, but I know I ran into some corner cases and/or complications. Also, I never heard back from @amanda-phet and wasn't sure if we wanted to go ahead with this or not. Feel free to work on this @zepumph if @amanda-phet thinks it is worth implementing.

**Comment by amanda-phet** [comment]
I think it would be a nice user interface feature. Do you need a mockup or do you have an idea already for how it should look?

**Comment by aaronsamuel137** [comment]
It will be easiest to just use the default function designed for this use case. It looks like the following on Chrome:

<img width="472" alt="screen shot 2015-07-13 at 11 23 27 am" src="https://cloud.githubusercontent.com/assets/3193912/8655934/b3884ac2-2951-11e5-90c7-4ace57974619.png">

Though we can adjust the wording if needed.

**Comment by amanda-phet** [comment]
I think that would work perfectly.

**Comment by zepumph** [comment]
Assigning to @amanda-phet to make sure that everything works as expected (it should) on the register and create activity pages.

**Comment by amanda-phet** [comment]
Is this on phet-dev? I'm getting an error any time I click on "browse activities" or "share your activities". Actually, I'm even getting an error if I try to click on "simulations".

**Comment by zepumph** [comment]
I'm not sure what's going on there, I'll look into it, but it's up on figaro, and not giving the error there, if you want to look it there.

**Comment by zepumph** [comment]
I'm not sure what's going on there, I'll look into it, but it's up on
figaro, and not giving the error there, if you want to look it there.

On Mon, Jul 20, 2015 at 11:49 AM, Amanda McGarry <notifications@github.com>
wrote:

> Assigned #175 <https://github.com/phetsims/website/issues/175> to @zepumph
> <https://github.com/zepumph>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phetsims/website/issues/175#event-360270945>.
>



-- 
Michael Kauzmann
PhET Interactive Simulations
michael.phet@gmail.com

**Comment by amanda-phet** [comment]
I see it now on figaro. Looks good to me. @ariel-phet Do you want to give it a final look as well? Then close the issue if it looks good to you.

**Comment by amanda-phet** [comment]
Since this has been deployed and there are no complaints, I'm closing this issue.
