### ISSUE TITLE
Expand Columns in "How to Run Simulations" Page

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#177]
On the "How to Run Simulations" page https://phet-dev.colorado.edu/en/get-phet
The "click here" links for the last two columns are partitioned between lines.
![screen shot 2015-05-12 at 11 23 56 am](https://cloud.githubusercontent.com/assets/5631059/7593723/61ecf3cc-f899-11e4-9258-64bfc3faa654.png)

**Comment by ariel-phet** [comment]
I know the "How to Run simulations" is scheduled for refinements after the sim pages deploy

**Comment by amanda-phet** [comment]
That table can't go wider with the current webpage layout. This is definitely in the queue for improvements soon (#91). For now, we might be able to make the first (heading) column narrower, and evenly distribute the other three columns. Here I made the heading column 15% smaller and evenly distributed the other columns, making them all a bit wider: 
Before:
![screen shot 2015-05-12 at 1 50 59 pm](https://cloud.githubusercontent.com/assets/7852916/7596968/ff0fc012-f8ad-11e4-9899-97a9ae2cc0b9.png)
After:
![screen shot 2015-05-12 at 2 04 28 pm](https://cloud.githubusercontent.com/assets/7852916/7597308/d4ebf42a-f8af-11e4-965f-aa85a275c853.png)

**Comment by amanda-phet** [comment]
@aaronsamuel137 How complicated would this change be? If it's really easy we can do it when you have time. If it is complicated, we can wait until I redesign this entire page.

**Comment by aaronsamuel137** [comment]
It's not too complicated - though I think I'll wait until after the sim page stuff is resolved since it seems unrelated.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph.

**Comment by aaronsamuel137** [comment]
The file to look at here is RunOurSimulationsPanel.html

**Comment by zepumph** [comment]
I made each of the table columns 25%, and the whole table just a bit wider, I don't think it's too close to the social media buttons on the right though. Thoughts before I push?
![getphet_table_screenshot](https://cloud.githubusercontent.com/assets/6856943/7889274/beb726b2-05fb-11e5-859a-1d8cd52d6964.png)

**Comment by aaronsamuel137** [comment]
Feel free to push - just reference #177 in your commit message so the commit shows up here. I will take a look before I actually deploy to the main site.

If you committed already and didn't reference #177 you can always just copy the sha in a comment.

**Comment by amanda-phet** [comment]
The mockup above looks good to me. I don't see it live or on phet-dev, though.

**Comment by amanda-phet** [comment]
Actually, It appears that changing the column widths to be evenly distributed did not fix the problem of making the really long text take up less vertical space. The right three columns should be evenly distributed, but the left column should be even narrower to give the right three more space. Hopefully that solves the problem a bit better.

**Comment by zepumph** [comment]
So I did a few things, perhaps not what we want. I moved the whole div tag over, offset from 'How to Run Simulations' but giving us a bit more space. I also narrowed the left column, allowing a wider body. Perhaps its a bit too cramped, but I think it helps with the verticality of the text. What do you think?
![getphet_table_screenshot](https://cloud.githubusercontent.com/assets/6856943/7894451/06fdce82-0627-11e5-806b-ff4f401f9fa9.png)

**Comment by zepumph** [comment]
I could push the blue heading right if we want them to line up, and keep the table more left also.

**Comment by amanda-phet** [comment]
I think either this option or the previous one is fine. This is a short-term solution so I am fine with either one!

**Comment by aaronsamuel137** [comment]
Assigning to @amanda-phet for review. Changes are on phet-dev - you may need to hard refresh to see them.

**Comment by aaronsamuel137** [comment]
Actually wait a moment before reviewing - there is a more recent change that needs to be deployed.

**Comment by amanda-phet** [comment]
The table looks good to me. Feel free to close this issue after it is deployed. I'd like to revisit some questions from the original issue #91 so I'll keep that one open. Thanks!

**Comment by aaronsamuel137** [comment]
Deployed. Closing
