### ISSUE TITLE
Suggestions about sidebar navigation

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#178]
When opening the page initially, the user does not get to see the sidebar information

![screen shot 2015-05-12 at 11 26 54 am](https://cloud.githubusercontent.com/assets/7717368/7593789/d313c8b4-f899-11e4-87ee-7632192bb4be.png)

Only after accessing anything on the page does the user have the option to truly navigate through the site. I personally think that the sidebar navigation should be present when loading the initial page. By removing the "How to Run", "Teaching Resources", "About" table and having the information accessible on the sidebar, the user will be able to comfortably use the website. Currently the only way to see the sidebar information is to click something on the front page and when the user returns to the front page they no longer have the option of sidebar navigation.

![screen shot 2015-05-12 at 11 30 23 am](https://cloud.githubusercontent.com/assets/7717368/7593870/4d8bbce6-f89a-11e4-9911-3cdf8860024b.png)

**Comment by amanda-phet** [comment]
This is something we plan to address in the next website project!

**Comment by ariel-phet** [comment]
Thoughtful suggestion @bryo5363 - but as @amanda-phet said redoing the navigation sitewide (and having persistent nav on the front page) is the next planned step for the site.
