### ISSUE TITLE
Order of activity info randomized?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#180]
I've noticed that if I go to an activity page at different times (or refresh the page), the order of keywords and sims listed seems to randomly change. It would make more sense to me if these were always listed alphabetically. 
![screen shot 2015-05-12 at 12 31 16 pm](https://cloud.githubusercontent.com/assets/7852916/7595234/01cfc992-f8a3-11e4-90b8-07e29c2004b5.png)
![screen shot 2015-05-12 at 12 31 29 pm](https://cloud.githubusercontent.com/assets/7852916/7595239/04587416-f8a3-11e4-904c-5f2cc8489ed9.png)

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph.

**Comment by zepumph** [comment]
assigning to @aaronsamuel137 for inspection.

**Comment by aaronsamuel137** [comment]
Nice work @zepumph! Code changes look perfect. Assigning to @amanda-phet to review on phet-dev before I deploy.

**Comment by amanda-phet** [comment]
It looks like the sim names are always alphabetical now! However, they alternate showing HTML5 first and second- I'm ok with that, but if it's not too difficult I think we should always list the HTML5 sim first.

**Comment by zepumph** [comment]
@amanda-phet how does that look, HTML5 sims will always be first.

**Comment by amanda-phet** [comment]
Looks great!
