### ISSUE TITLE
Non-optimal activity sorting while browsing activities

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#183]
A couple things here I noticed while going through different sorting options and activities. I feel that as is, the hierarchy of sorting and the functionality of re-sorting can be improved. The re-sorting issue might actually be a bug, so even if the design team has exhaustively discussed the sorting order, still please read through to the second point. Take this search result for example (the top is cut off but it's all simulations and all languages):

![search 1](https://cloud.githubusercontent.com/assets/5863899/7615414/bdfaa97c-f95a-11e4-8a39-d4ce0cf21fb4.png)

I've been told that the current sorting hierarchy is:

locale --> gold star --> date updated, 

which this search does follow. I can guess there has more than likely already been discussions on this order and there are reasons for it, but in this particular search it seems non-optimal. I would propose favoring PhET made activities over those that are not, regardless of date updated, so a new search order of:

locale --> gold star --> *PhET made* --> date updated.

In this way, the activity "Undergrad MRI Workshop Activity" would not be first but instead placed at the end of the gold star sorting. This makes the PhET made activity "Resonance: Upper-division college" first and favored.

Furthermore, I feel there is a problem with re-sorting that's most likely arising from sorting locale first (which is something the user can't sort by might I add!). Another search example to make this issue more dramatic:

![search 2](https://cloud.githubusercontent.com/assets/5863899/7615853/8980ac52-f95d-11e4-8194-9710ba8ca118.png)

This search returns activities that are "pseudo-sorted" by gold star --> PhET made since technically they are first sorted by locale. In other words, if the search results were *actually* sorted by gold star --> PhET made, this is exactly how the search would appear. What this causes is that the FIRST time either the gold star or PhET logo is clicked in the user's hopes of re-sorting, nothing happens. I would assume that this is because behind the scenes the site is un-sorting by locale and re-sorting by whatever was clicked, but on the surface it appears to the user that nothing has happened. I believe it would be more optimal to have that first click sort the gold star or PhET made activities, depending on which is clicked, to the bottom (since they already appear to be sorted to the top).

**Comment by zepumph** [comment]
@ariel-phet I can add the 'phet-made' into the sort by chain, if you think that's best. Thoughts?

**Comment by ariel-phet** [comment]
Let me discuss with @amanda-phet and get back to you. In general it seems like a good idea.

@amanda-phet - did we already decide something like this, or should we bring it up at the next website meeting?

**Comment by amanda-phet** [comment]
Let's discuss it Wednesday.

**Comment by amanda-phet** [comment]
At the 7/15 website meeting we decided to implement @phet-steele 's suggestion to add phet-made into the sorting chain. 

We considered his second suggestion and decided that the current click-sort behavior is pretty standard, so we will not make a change there.

**Comment by zepumph** [comment]
assigning to @amanda-phet for a final look over and to close if good.

**Comment by zepumph** [comment]
changes were made on this commit: 6a1ed7b0ec8f6b8a55d53a889ecbcf1010fff63d

**Comment by aaronsamuel137** [comment]
@zepumph, is this deployed on simian or figaro? It's always good to specify.

**Comment by zepumph** [comment]
This is now one figaro, @amanda-phet  if you want to take a look to make sure you like the ordering.

**Comment by amanda-phet** [comment]
It looks good to me! Closing.
