### ISSUE TITLE
Computer crashes after logging in IE 11 Win7

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#184]
Pretty strange issue, both @bryo5363 and I observed this on two different computers.
We were testing on the computers in Norlin Library and attempted to sign in to https://phet-dev.colorado.edu/ on Windows 7 IE 11.0.9600.17420. After signing in the computers crashes and restarts.
I attempted to sign in again, but this time input the incorrect password, and the program IE froze and I had to use the task manager to end the program.

@phet-steele can you check if this happens on one of the Win 7 with IE 11 computers in the office?

**Comment by orejolaphet** [comment]
I can sign in without any issues on Chrome 42 on the same computer in Norlin.

**Comment by phet-steele** [comment]
Well before I even start to try Win 7, I'm trying Win 8.1 and have noticed two severe things.

On IE11, when signing in (incorrect information was handled fine) then trying to sign out or edit profile the user gets sent to a sign in page. This sign in page is infinite and will continue to ask the user to sign in.

On FF, after signing in and going to edit profile, if I decide to navigate away from the profile editing page via a link other than the update button at the bottom my computer crashes. Actually, more specifically my display driver crashes and the screen reboots, but the computer and other programs remain running.

**Comment by phet-steele** [comment]
Chrome is totally fine.

**Comment by orejolaphet** [comment]
@phet-steele I think those two issues deserve their own tickets, but it seems windows isn't handling phet-dev very well with the exception of Chrome.

**Comment by aaronsamuel137** [comment]
Can you guys test and see if any of these issues are on the phet.colorado.edu too?

**Comment by phet-steele** [comment]
@orejolaphet you're probably right, unless @aaronsamuel137 thinks they are related.

But this has brought something else to my attention. @ariel-phet, looking at the PhET inventory spreadsheet, we do not have a Win 7 IE11 device in the office (hence why Norlin is the place to test). We should discuss taking one of our many Win 7 devices and update one of their IEs.

**Comment by orejolaphet** [comment]
@aaronsamuel137 this may be a hard but to track because after recreating it doesn't seem completely consistent.
@bryo5363 signed into phet.colorado.edu on Win 7 IE 11 with out any issues.
I signed into phet.colorado.edu and my computer crashed, but after my computer restarted I signed in again and there was no issue.

Also now @bryo5363 and I just both signed into phet-dev on Win 7 IE 11 and we encountered no issues.

**Comment by orejolaphet** [comment]
I should also mention that the first time I signed in to phet-dev on Win 7 FF 38 the computer crashed, but the second time I signed in there were no issues.

**Comment by orejolaphet** [comment]
Today I signed onto phet-dev on two different windows 7 computers with IE 11 and encountered no issues. First on a Dell computer, the other a Dual Booted IMac.

**Comment by aaronsamuel137** [comment]
I'm going to close this for now. I have no idea where to start with this, and it may have just been a fluke. Feel free to reopen if issues persist.
