### ISSUE TITLE
Signing in/out and editing profile troubles

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#185]
I saw some issues while testing on Win 8.1, but did not have these issues yesterday (5/12).

**IE11**
Signing in then trying to edit profile I get sent to a sign in page. Occasionally this sign in page was infinite and would continue to ask me to sign in. When it didn't, I was brought to the profile page with entry boxes that are too small along the bottom:

![profile boxes](https://cloud.githubusercontent.com/assets/5863899/7617279/5b41d9f6-f967-11e4-98ac-f814c0d7fc61.png)

When navigating away from this page other than clicking on the update button, I was signed out.

Signing in then trying to sign out I get sent to a sign in page, but at least I'm actually signed out.

**FF**
Signing in and going to edit profile, if I decide to navigate away from the profile editing page via a link other than the update button at the bottom (I clicked the PhET logo) my computer crashes. Actually, more specifically my display driver crashes and the screen reboots, but the computer and other programs remain running.

Signing out worked correctly.

**Chrome**
Not broken.

**Comment by phet-steele** [comment]
Looks like for the FF crashing issue, it can still happen after clicking the update info button

**Comment by aaronsamuel137** [comment]
@ariel-phet, you have Windows 8 right? Can you reproduce any of these issues?

**Comment by aaronsamuel137** [comment]
Seems like the IE11 sign-in issue was due to cookies not being enabled. The layout issue with the input boxes will be fixed in the next deploy.

**Comment by ariel-phet** [comment]
IE11 seems to be working fine on my Win 8, not experiencing any of these sign in issues

**Comment by phet-steele** [comment]
@ariel-phet how about FF? IE11 problems were figured out.

**Comment by ariel-phet** [comment]
FF appears to be working fine for me if I sign in, edit, and navigate away from the edit page.

**Comment by aaronsamuel137** [comment]
The look of the input boxes should be fixed. Does it look good to you now @phet-steele?

**Comment by phet-steele** [comment]
Okay, the words aren't cut off anymore in the input boxes so it looks good. However being as nit-picky as I am, the box for the last name MAY be about one pixel shorter on the bottom than the first name box. It's barely noticeable, but what IS noticeable is the city box is smaller than the menu boxes next to it:

![small jeka](https://cloud.githubusercontent.com/assets/5863899/7644545/6fa46f4c-fa63-11e4-94d1-6a938cb13242.png)

**Comment by aaronsamuel137** [comment]
Should be better now. Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
It is indeed better. I'm going to say all the FF crashes were my computer having a bad day, it hasn't happened since.
