### ISSUE TITLE
Trouble uploading activity w/ iPad

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#186]
I am not sure how serious of an issue this is but when I tried to upload an activity on the iPad I was only given permission to upload photos or videos which is NOT consistent with the allowed "upload-able" files.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - it seems we should investigate this a bit...but perhaps iPad's do not support PDF or basic document editing software (such as word/pages etc)

**Comment by aaronsamuel137** [comment]
I can't get anything to upload with my iPad mini - it just hangs after I press upload. This issue exists on phet-dev and the main site currently.

@bryo5363, what browser are you using on iPad? Did you actually get something to upload? Can you give me a link to the activity? I imagine that whatever issue you are running into here exists on the main site too.

**Comment by aaronsamuel137** [comment]
The server eventually returns a "400 bad request error"

**Comment by aaronsamuel137** [comment]
Also, it looks like iPad only allows you to upload photos and no other type of file, at least in Safari and Chrome. I think this is true in general on iPad. If this is the case, then it it probably not worth investigating this issue further.

**Comment by amanda-phet** [comment]
I don't think file uploading is ever supported on iPads, for most websites like this, and I would not expect it to function.

**Comment by ariel-phet** [comment]
Sounds like we can just close the issue...closing.
