### ISSUE TITLE
iPad keyboard should be formatted to email when logging in

### ISSUE THREAD

**Issue by bryo5363** [phetsims/website#187]
I noticed when logging in on the iPad that the keyboard is not converted to the standard email keyboard "Including @ on the main keyboard, including .com, etc). I think that this should probably be consistent with the standard email template so the user does not get confused between a typical username and an email address

**Comment by aaronsamuel137** [comment]
Good call. I have made these inputs type="email", which should make the email keyboard appear on iPad.

Also fixed a formatting issue on iPad while I was at it - the search bar was bigger than the magnifying glass.

Assigning to @orejolaphet for verification.

**Comment by orejolaphet** [comment]
@aaronsamuel137 Verified fixed on iPad Air 2 iOS 8.3 and iPad 2 iOS 8.3. Closing
