### ISSUE TITLE
Activities with missing fields

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#189]
Any sim page that contains activities with a missing field (ie. States of Matter or Resistance in a Wire there are plenty) breaks when the activities are sorted by the missing fields.

https://drive.google.com/file/d/0B3HJopSo_QqLSEN0UVViWU1aR1E/view?usp=sharing

Tested on Win 8.1 Browsers

**Comment by phet-steele** [comment]
Frankly, there are many activities (30-50?) on the website that have missing fields. Those that are missing the level and type fields break the sim pages as described above, while there are still plenty of activities that are missing a sim in the simulation field (and don't break sorting). Some certain courses of action to take care these activities have been discussed by @arouinfar and @ycarpenterphet and it would be helpful if they were repeated and discussed here.

**Comment by aaronsamuel137** [comment]
I'll fix this so that even if there are missing fields for an activity, those activities will appear in their own "Uncategorized" section.

**Comment by aaronsamuel137** [comment]
The sorting should work now even if there are missing fields. Should this be closed or do we want to go and update all of these activities too?

**Comment by amanda-phet** [comment]
I am surprised these fields are missing at all. If I try to submit an activity on the main site- Title, Type, Author, and Level are all required fields. I'm curious how these activities made it though. The example above was submitted less than a year ago. 

BTW, this breaks the table on the live site as well.

**Comment by arouinfar** [comment]
@phet-steele and I found roughly 30 activities that are not associated with any sim. There were some from PhET authors, and others had a sim title in the name of the activity. The best way that we found to find these activities is from the Browse Activities page by viewing all activit
ies and looking for entries with with an empty cell in the simulation column. These activities seem to disappear when you sort by Simulation.

We also found a few cases of duplicate activities, some of which do not have any associated files. For example:
http://phet.colorado.edu/en/contributions/view/3673
http://phet.colorado.edu/en/contributions/view/3674
http://phet.colorado.edu/en/contributions/view/3678

**Comment by arouinfar** [comment]
Here are a few examples of activities that do not have any sims tagged, though it is fairly obvious which sims these activities were written for.
http://phet.colorado.edu/en/contributions/view/3291
http://phet.colorado.edu/en/contributions/view/3599
http://phet.colorado.edu/en/contributions/view/2832
http://phet.colorado.edu/en/contributions/view/3350

**Comment by phet-steele** [comment]
Btw, the sorting isn't broken anymore :+1:

**Comment by ariel-phet** [comment]
@phet-steele can you deal with these activities...ie delete duplicate activities with no associated files, tag activities that are not associated with a sim (if there is an obvious sim), and fill in missing fields if there is an obvious correct answer?

This work should be done on the main site, so that it changes the main database

**Comment by phet-steele** [comment]
I have assured the quality of activities! I hope the deleting didn't create broken links for teachers.

**Comment by ariel-phet** [comment]
Thanks! Closing
