### ISSUE TITLE
Sorting by level puts the For Teachers drop down menu into limbo

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#190]
On a sim page, click on the For Teachers arrow to display all the activities. Then, sort by "Level" and afterwards click on the For Teachers arrow again to close the menu:

![teacher limbo](https://cloud.githubusercontent.com/assets/5863899/7621445/2c398a24-f984-11e4-871f-aba284415d85.png)

For Teachers can no longer be clicked either. Tested on Win 8.1 browsers.

**Comment by aaronsamuel137** [comment]
This should be fixed. Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
:+1:
