### ISSUE TITLE
Support Phet Page inconsistencies

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#191]
I know this isn't necessarily related to phet-dev, but there are a few (minor) issues I noticed when testing.

1) If you sign into phet & phet-dev then click the "Donate Today" link, you are no longer signed in

2) All links on https://donatenow.networkforgood.org/1437859 link to phet not necessarily phet-dev

3) After Selecting "Log in to edit a recurring donation" there are two log in buttons displayed

4) The CU Emblem is not displayed above "University of Colorado"

5) Pages lists "Over 110 million simulations delivered" as opposed to "200" which is listed on phet-dev

![screen shot 2015-05-14 at 9 38 33 am](https://cloud.githubusercontent.com/assets/5631059/7636014/7043f6bc-fa21-11e4-9920-6321b562ed7f.png)

**Comment by phet-steele** [comment]
I believe I can answer some of these more generally, but this page is not maintained by PhET, nor does it use PhET accounts (hence why you aren't logged in). I think this webpage is owned by a separate group that just made their own site look like ours. @aaronsamuel137 correct me if I'm wrong, just trying to remember something from awhile ago. But in any case, I don't feel it would be a terrible idea to let them know of our updated site once it's deployed.

**Comment by aaronsamuel137** [comment]
This page isn't maintained by phet. I am not sure what the process for updating this page would be. Perhaps @jonathanolson knows.

**Comment by jonathanolson** [comment]
Talking to KP or Kathy Dessau would be the way to get these changed. I believe each session of changes includes a fee?

But yes, these are maintained by Network for Good.

**Comment by ariel-phet** [comment]
We probably leave this page until we have re-skinned the site. It is a pain to make the changes and the current configuration is good enough
