### ISSUE TITLE
Ambiguity of translated sims

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#192]
The translated sims page does not distinguish between HTML5 and legacy versions.

![entrans](https://cloud.githubusercontent.com/assets/5863899/7636022/7f770da4-fa21-11e4-89b7-8d9d0c256278.png)

This causes initial confusion, for example, on the Turkish translation page where Acid-Base Solutions is listed as both translated and untranslated.

![tutrans1](https://cloud.githubusercontent.com/assets/5863899/7636161/9be5072e-fa22-11e4-8fa9-d5352f2ae575.png)
![tutrans2](https://cloud.githubusercontent.com/assets/5863899/7636164/a41b89b8-fa22-11e4-81d9-525f54af45de.png)

**Comment by amanda-phet** [comment]
Good catch @phet-steele . That is confusing. @aaronsamuel137 can we use the same naming convention in other places on the site where the HTML5 version of the sim is named Acid-Base Solutions (HTML5)? 

Also, on a less related note, why does only one of the sims have the hyphen? It seems like it should be consistent.

**Comment by aaronsamuel137** [comment]
Should be good to go. Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
Looks good, however perhaps we should have both columns use this distinction? After your fix only the left column distinguishes between HTML5 and legacy. I don't see why the middle column shouldn't.

**Comment by aaronsamuel137** [comment]
Added (HTML5) suffix to middle column. Closing
