### ISSUE TITLE
Software Requirements Confusion

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#193]
Looking at the software requirements on the new sim pages I became confused:

![soft is required](https://cloud.githubusercontent.com/assets/5863899/7636999/1079d542-fa28-11e4-8356-b755c8160049.png)

I'll admit I first read the plus sign as an "and" which led me to wonder why we were listing Windows 7 and PCs at the same time (quite redundant) and why we were listing Macs and PCs in the second column when we had already listed PC requirements. After a short discussion with another, I realized my mistake that the plus was to say "Windows 7 and higher" and so forth, and that the PC was written there to mean laptops and desktops as opposed to tablets. This is kind of an embarrassing mistake :sweat_smile: , but I'm sure I won't be the only one who commits this fib. And also are we going to add Linux?

As a side note, "Software" Requirements is used on sim pages, but "System" Requirements is used in the FAQs. I know they are mostly synonymous, but I'm a fan of consistency and would choose one to use.

**Comment by ariel-phet** [comment]
@amanda-phet perhaps discuss with @oliver-phet 

I agree consistency would be good. I might also be comfortable with just saying "Windows 7 +" and remove the "PCs" altogether. I mean, I know Windows 8 runs on things like a Surface tablet, but this seems like a fine distinction that probably only matters to a very small percentage (likely negligible) of our users.

**Comment by oliver-phet** [comment]
@arnabp and I discussed this a bit. I think just removing "PCs" from both Windows and Mac would make the requirements clear.

**Comment by amanda-phet** [comment]
I agree that including "PCs" is unnecessary and potentially confusing for all. Let's go ahead and remove it.

**Comment by aaronsamuel137** [comment]
PCs has been removed. Closing.
