### ISSUE TITLE
About PhET team problem

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#194]
The current list of PhET team members on the about page (in phet-dev) has quite a few errors and people missing. Are there plans to correct these in the future? I read in an older, closed issue about this page that these change dynamically from the database. So is this not going to be a problem once we move to figaro, or is the database wrong?

**Comment by bryo5363** [comment]
This is also present in the credits for the simulations. The credits on the webpage for the simulation is not consistent with the credits in the actual simulation

**Comment by aaronsamuel137** [comment]
Yes it is dynamically loaded from the database. So this will match what is on the live site when it is deployed.

The credits will need to be manually updated in the admin interface - I think that the right people are aware that this needs to be taken care of after the redeploy.

**Comment by phet-steele** [comment]
Sounds like there won't be a problem, and there's already a ticket tracking the update of the credits. I'll close this now and open it later if the page has mistakes once this goes live.
