### ISSUE TITLE
Add a top-level troubleshooting entry

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#195]
http://phet.colorado.edu/en/troubleshooting

Can we add the following to the "Common Troubleshooting Issues" (first)
Where do I start if the simulations do not run on my computer?

First, update to the latest version of Java: http://java.com/en/
Run the latest version of the sim directly from phet.colorado.edu by clicking the 'Run Now' button on the sim page. e.g.: http://phet.colorado.edu/sims/energy-forms-and-changes/energy-forms-and-changes_en.jnlp

If you are using a Mac please see here for detailed instructions: 
http://phet.colorado.edu/en/troubleshooting/mac#q5-header

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph. Let me know if you have questions. Once you get your identitkey set up I'll show you how to deploy to phet-dev so your changes can be easily reviewed by others.

**Comment by zepumph** [comment]
assigning to @aaronsamuel137 for inspection.

**Comment by oliver-phet** [comment]
Do I need to do a "hard reset' of Chrome or something? I'm seeing this:
![screen shot 2015-06-03 at 4 34 57 pm](https://cloud.githubusercontent.com/assets/5090275/7973024/8f0d983a-0a0e-11e5-9edc-854ec2a4325f.png)

**Comment by aaronsamuel137** [comment]
@oliver-phet - no a hard refresh won't fix this. The string is not found in the database. I need to go over how the translation and string keys work with @zepumph, so this issue is not yet ready for you to review.

Feel free to review #146 and #147 though.

**Comment by zepumph** [comment]
@oliver-phet how does that look on phet-dev now?

**Comment by oliver-phet** [comment]
@zepumph Can you put returns after the lines? Like the text in the original issue:
(before "Run the latest..." and "If you are using a Mac...") and an extra before "If you are using a mac..."

**Comment by aaronsamuel137** [comment]
@zepumph - you can edit the string without actually deploying. Login and go to the admin interface. Under "Manually enter an English string" you can enter the key for that string and give it the new value with ```<br>``` tags or whatever you want

**Comment by zepumph** [comment]
@oliver-phet how does that look?

**Comment by oliver-phet** [comment]
Perfect. Thanks!
