### ISSUE TITLE
Newsletter subscription email

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#199]
I'm really just curious here about how the email confirming my newsletter subscription gets sent to me. I've been editing my profile back and forth between being subscribed and unsubscribed to the newsletter, waiting hopefully adequate time between switching (5 min?). Not once have I got an email from phethelp when doing this. The only time I ever received one was the first day I registered and had selected to subscribe. *I did not choose to subscribe by default when first registering, but a few minutes later went to update my profile to subscribe then got the email*.  Before doing all the switching I've done today (5/15), I searched back through my emails to find the original phethelp email and clicked the link to unsubscribe in hopes it would help phethelp recognize me trying to set up a new subscription.

**Comment by aaronsamuel137** [comment]
Currently that is the expected behavior. An email is sent only when you first register, and not when you subscribe or unsubscribe.

**Comment by phet-steele** [comment]
Well then what I can say is it seems the check box on the profile page being checked or unchecked is completely independent of whether or not I am actually subscribed, or at the least it can't be trusted. I decided to uncheck the box, then go to the news page under About PhET and put in my email to subscribe to the newsletter. The email was sent and it says I have been confirmed to have a subscription. Going back to the profile page still shows the box as unchecked though.

**Comment by aaronsamuel137** [comment]
This seems like a bug. And when I tried to reproduce it, there was an Internal Server Error. Assigning to myself to investigate.

**Comment by aaronsamuel137** [comment]
I think the correct behavior should be that if you already have a phet account, you shouldn't be able to subscribe to the newsletter from this page. You should have to go through the edit profile page.

I have added a check to make sure the email address is not already in use. For example:

![screen shot 2015-05-18 at 4 38 01 pm](https://cloud.githubusercontent.com/assets/3193912/7691980/49dcebec-fd7c-11e4-8829-bff8e4334a55.png)


Assigning to @ariel-phet. Does this seem like the right move here?

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I think the ideal move is that if you put in an email address already in use, that the database (and your profile) is automatically updated. That would be the most seamless user experience in my opinion

**Comment by ariel-phet** [comment]
If the behavior I suggest will take sometime to implement, for now I would have it say

"That email address is already in use, please edit your profile to subscribe to the newsletter" and perhaps have "edit your profile" be a link in that message to the edit profile page?

**Comment by aaronsamuel137** [comment]
I can do that. What should be the behavior when you click subscribe and you already have a profile?

Right now, the behavior is that you are sent a confirmation email and redirected to a page that tells you to confirm by checking your email and clicking the link. This seems unnecessary if you already have a profile and have confirmed your email address already.

**Comment by ariel-phet** [comment]
I think just a confirmation message on the site that says something like "Your profile preferences have been updated. If you wish to change these preferences in the future, edit your profile"

Or something to that effect.

**Comment by ariel-phet** [comment]
@amanda-phet - have thoughts on the wording?

**Comment by aaronsamuel137** [comment]
Should this be on a new page, or just a message that appears on the same page?

**Comment by amanda-phet** [comment]
I like the message you wrote above: "Your profile preferences have been updated. If you wish to change these preferences in the future, edit your profile." If it can be on the same page that seems like it would be nice and clean, but a new page wouldn't be bad either.

**Comment by aaronsamuel137** [comment]
The other complication here is whether or not the user is logged in. It seems like we shouldn't modify a user's profile unless they are logged in. What do you think we should do in the case where a non-logged in user is trying to subscribe?

**Comment by aaronsamuel137** [comment]
Since I have run into a few complications here, I am going to leave this issue unaddressed until after the new sim pages deploy.

**Comment by phet-steele** [comment]
You cannot enter your email on the Newsletter page anymore. This issue is now largely irrelevant.
