### ISSUE TITLE
Searching by category with html sims

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#20]
Working on adding the Area Builder page, I noticed the following when looking under the "Math" category:

![screen shot 2014-10-08 at 10 34 32 am](https://cloud.githubusercontent.com/assets/3193912/4562966/32348cce-4f09-11e4-934e-50c5098411af.png)

Clearly, the size used for the html thumbnails is quite different from the sizes used in the past.

This brings up other questions around how we want to handle searching for sims, such as what should happen if there is both a Java and HTML version? Should both thumbnails appear next to each other in the search?

**Comment by ariel-phet** [comment]
Will be part of #17
