### ISSUE TITLE
Website changes optimizations and code review

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#200]
It would be good at some point to have someone look over all of the recent website changes with an eye for both speed optimizations and code review of some of the changes to registration and activity submission.

In particular, @kathy-phet noted the double resolution screenshots on the sim pages and was wondering if there would be any performance implications for the pages.

**Comment by aaronsamuel137** [comment]
The files that would be the most useful to review are:

RegisterPanel
ContributionEditPanel
SimulationMainPanel
HTML5Panel (there is a bit a of complicated query for selecting HTML5 sims in here that could be perhaps be optimized)

all changes are on branch html5-sim-pages

**Comment by jonathanolson** [comment]
RegisterPanel includes a lot of code duplication for checkboxes, etc. If this could be collapsed to a list of checkbox string names (with code to iterate over), and a "checkbox name => checkbox" map, it would probably be much easier to modify in the future (removing or adding a single item), and probably a bit more readable.

**Comment by jonathanolson** [comment]
It's fairly minor, but usually StaticImage should have alt-text, e.g. missing on:
```java
new StaticImage( "pdf-icon", WebImage.get( "/images/icons/pdf-icon-40.png", true ), " " )
```

If the image doesn't really have "alt text" like this icon, I'd typically use CSS to display the image (background-image) so that a DOM image element isn't used.

This type of thing usually shows up as a big red flag for accessibility scans of pages.

**Comment by jonathanolson** [comment]
I'd encourage running a tool to check for major accessibility issues and fix the low-hanging fruit.

**Comment by jonathanolson** [comment]
Instead of:
```java
locale.toLanguageTag()
```
(from SimulationMainPanel, line 210)
I'd use:
```java
LocaleUtils.localeToString( locale );
```

unless you specifically want to strip "es_MX" down to "es".

**Comment by jonathanolson** [comment]
Everything else is looking good. One last checklist item would be to ensure that it works well with the installer rip, has that been tested?

**Comment by jonathanolson** [comment]
(Best way is to use a user-agent changer in your browser, and browse with 'httrack-web-offline-en' as your user-agent).

**Comment by aaronsamuel137** [comment]
@jonathanolson, can you look at the add checkBoxMap commit above and confirm that this is the kind of change you were anticipating? I wanted to try it on a subset of the checkboxes and make sure it looks good to you before doing it to all of them.

**Comment by aaronsamuel137** [comment]
Other fixes have been made as well. I used the webaim accessibility tool to address some issues, such as adding alt attributes and the lang attribute.

**Comment by jonathanolson** [comment]
Yes, looks good. Thanks.

**Comment by aaronsamuel137** [comment]
OK all these changes have been made. Probably at some point we'll want to create another issue just about accessibility, but I've gotten some of the low hanging fruit. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good! I didn't see anything else sticking out, looking very good overall. Closing the issue, feel free to proceed with prep for deployment.
