### ISSUE TITLE
tab navigation on new sim pages

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#202]
I noticed that the tab navigation is working really well now as I move through the content on a page. However, the one big issue I am seeing is that I don't see a focus rectangle around these headings:
![screen shot 2015-05-20 at 12 23 26 pm](https://cloud.githubusercontent.com/assets/7852916/7733235/0c64add4-feeb-11e4-96b1-6dd6e6d3822d.png)

If I continue to hit tab, I end up going through the content of these sections without ever expanding them. 

Ideally, the tab navigation should cycle through these headings and force the user to hit enter to expand it, then cycle through the content of that heading.

**Comment by aaronsamuel137** [comment]
I'm not sure how I could force a user to hit enter - but we could just automatically expand the texts when they get tabbed to. Does that sound good?

**Comment by amanda-phet** [comment]
That makes sense. That way the user will be able to see what they are navigating through.

**Comment by aaronsamuel137** [comment]
I've added tab navigation and auto-expanding on the sim pages. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I think that's a lot better. Thanks!
