### ISSUE TITLE
Licensing for interoperable sims

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#204]
@kathy-phet says that she has the approved text for this licensing and will need @aaronsamuel137 to post it on the website.

I will follow up with her to make sure the text available soon.

**Comment by zepumph** [comment]
I have added interoperable licensing to the html5 licensing page that Kathy gave me, see 
http://phet.colorado.edu/en/html-terms-privacy-and-licensing, and http://phet.colorado.edu/licensing/html once the new licensing pages go live.
I think this issue can be closed, assigning to @ariel-phet just to make sure.

**Comment by zepumph** [comment]
I also think that phetsims/together#127 can be closed as well.

**Comment by ariel-phet** [comment]
Agreed, can be closed.
