### ISSUE TITLE
Sim credits limited to 255 characters

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#205]
@phet-steele has reported issues submitting credits for sims in the admin interface. Right now the database type for credits is varchar(255), which means it can only hold 255 characters. Either we'll need to accept this limitation and shorten some of the credits for HTML5 sims, or we'll have to make some changes to the database and code here.

Either way, it might be good to add a check and warning in the admin interface so that it doesn't just cause an Internal Server Error when you try to submit more than 255 characters.

I'm not sure how many sims have credits that are longer than 255 characters. @phet-steele, can you list the sims here?

So far I am aware of just Build an Atom and Friction.

**Comment by phet-steele** [comment]
Build an Atom, Friction,  and Molecules & Light. Here is exactly how I am trying to list the credits for each:

Build an Atom:
Kelly Lancaster (lead)
John Blanco (developer)
Sam Reid (developer)
Jack Barbera
Suzanne Brahmia
Julia Chamberlain
Yuen-ying Carpenter
Patricia Loeblein
Emily B. Moore
Robert Parson
Ariel Paul
Kathy Perkins
Sharon Siman-Tov

Friction:
Noah Podolefsky (lead)
Michael Dubson (lead, developer)
John Blanco (developer)
Jonathan Olson (developer)
Bryce Gruneich
Ariel Paul
Kathy Perkins
Carl Wieman
Wendy Adams (interviewer)
Mindy Gratny (interviewer)
Emily B. Moore (interviewer)

Molecules & Light:
Amy Rouinfar (lead)
Jesse Greenberg (developer)
John Blanco (developer)
Sam Reid (developer)
Aaron Davis (developer)
Kelly Lancaster
Yuen-ying Carpenter
Patricia Loeblein
Emily B. Moore
Robert Parson
Ariel Paul
Kathy Perkins
Alex Klinger (graphic arts)

**Comment by phet-steele** [comment]
If you just copy paste these into a word document, they are all under 255 characters. Characters must be added afterward, maybe from the bullet point formatting?

**Comment by aaronsamuel137** [comment]
Most likely the problem is that line breaks get expanded to 4 character <br> tags or possibly 5 (<br/>).

This should be an easy fix, but I'll want to run the database change commands in the evening when there is less traffic

**Comment by aaronsamuel137** [comment]
I've updated the database and updated the credits for these 3 sims. Closing
