### ISSUE TITLE
Administrator user profiles missing fields

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#206]
I noticed that the People page (https://phet.colorado.edu/en/about/team) has some new issues. Before the recent profile changes, PhET team members had additional profile fields that are now missing, and thus not editable. Also, the split name field is causing a problem with displaying full names. 

Can you fix the names so that they show both first and last, and add a field for users to edit our title? We do NOT need to collect phone numbers (which are currently viewable when logged in as an administrator).

**Comment by aaronsamuel137** [comment]
Team page should display first and last name now. Team members can now edit their job title. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks good!
