### ISSUE TITLE
New page needed for third-party-libraries

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#208]
http://phet.colorado.edu/third-party-libraries should redirect to https://github.com/phetsims/sherpa/blob/master/info.md once https://github.com/phetsims/sherpa/issues/22 is taken care of. For now it should redirect to to google doc:  https://docs.google.com/spreadsheets/d/1XWlHFidztUT6ARb7yHQ1Naepd6L0x9LF94AAoKHGaWg/edit#gid=0

**Comment by aaronsamuel137** [comment]
http://phet.colorado.edu/third-party-libraries now redirects to the google doc. Once the md file is ready on github I will change it to redirect there.

**Comment by aaronsamuel137** [comment]
Looks like @samreid's work on https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md is finished. I have updated the redirect on the website to point there. This will go live on the next deploy.

**Comment by samreid** [comment]
> Looks like @samreid's work on https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md is finished.

Just to clarify, I am still refinish the output.  But the link should be permanent.
