### ISSUE TITLE
Make sure Wordpress (for the blog) is up to date

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#210]
Ideally, our Wordpress should be updated automatically to ensure we don't have vulnerabilities, as older versions can be a common target.

Website had a hiccup tonight (~12:42) when a remote server heavily scanned "http://phet.colorado.edu/blog//xmlrpc.php".

@ariel-phet, can you tag for appropriate priority / asignee?

**Comment by aaronsamuel137** [comment]
It looks like Wordpress is up to date and auto updating already. If you log in as a the blog admin and go to updates it says:

>You have the latest version of WordPress. Future security updates will be applied automatically.

**Comment by ariel-phet** [comment]
@jonathanolson - I am closing this issue as per @aaronsamuel137 comments above. Please reopen if you feel further action is appropriate
