### ISSUE TITLE
Can't remove types from contributions

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#211]
From #159:

AM:
> I see Guided Activity as an option, but when I check it and uncheck Lab, Lab still remains on the activity. 

AD:
> This is a bug. Currently you can't remove any subjects, levels, types in contribution edit. This is leftover from the old implementation before the redesign and never got tested until now.

**Comment by aaronsamuel137** [comment]
This should be fixed now. @amanda-phet can you verify that it is working for you on phet-dev before I deploy to the main site?

**Comment by amanda-phet** [comment]
This is working on phet-dev. I'll reassign this to you to close after it's deployed.

**Comment by aaronsamuel137** [comment]
Deployed on the live site. Closing
