### ISSUE TITLE
Delay when uploading teacher tips

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#212]
This is in reference to an issue I noticed with #160. After uploading teacher tips, I'll see them automatically, but only while signed in. If I sign out, they are no longer visible. Eventually I'll see them, as I did with Amy's ESPB or the ones I uploaded, but there is definitely a delay (I'm not sure how long). Do you know why this is happening, and how long we should expect the delay to last?

**Comment by amanda-phet** [comment]
It looks like the delay was about 30 minutes. If we can rely on it consistently taking about 30 minutes to appear on the site, that's fine with me, but it would be helpful to know why this is happening so it does not feel like something is broken!

**Comment by aaronsamuel137** [comment]
My guess is that the page is just being cached by your browser. Try doing a hard refresh when you see the outdated guide and see if it updates. (Or try in another browser where you haven't loaded that page recently)

If that doesn't work, try going to the page with https instead. It might be that it is cached in varnish or somewhere else and loading it over https will cause the correct page to load.

Let me know if either of these work for you. In any case, I doubt it will ever be much of an issue - it is probably just being cached somewhere and it seems like that cache expires in about half an hour.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I was with @amanda-phet when she was seeing this issue. A hard refresh was not helping the issue, but going to the page via https was working. For instance, I could login and see the teacher tips, but if I was logged out and did a hard refresh nothing was visible. I was assuming this issue had something to do with some varnish weirdness.

**Comment by aaronsamuel137** [comment]
If you are looking at the sim page, it is definitely cached by varnish and other internal caching mechanisms. It's nothing to worry about.

I was testing the case of updating a PDF and still seeing the old version. In that case, I think the old pdf is just cached by the browser, and hard refreshing on the pdf page will refresh it.

**Comment by amanda-phet** [comment]
Thanks for answering. As long as the delay is expected I think it's fine.
