### ISSUE TITLE
RPAL name on website

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#213]
When uploading an activity, I noticed that RPAL was the only sim that listed the (HTML5) version after the original version. Then I noticed that the two sims have different names on the website, which is causing this to happen. The java version is called "Reactants, Products and Leftovers" and the HTML5 version is called "Reactants Products and Leftovers". (I'd like to leave it as a challenge to find the difference, but it is simply that one has a comma). 

What should the official name of the sim be? 

When this is decided, we should ask @aaronsamuel137 to update the website accordingly.

**Comment by ycarpenterphet** [comment]
Hah. I never noticed!

The official name should include a comma and should read 'Reactants, Products and Leftovers.' 

This then matches the sim title as displayed in the actual HTML5 (and Java!) simulation and About dialog text.

@aaronsamuel137 Could you update the sim page title accordingly? Thanks!

**Comment by aaronsamuel137** [comment]
Should be updated now. Assigning to @amanda-phet for review.

**Comment by ariel-phet** [comment]
Fixed, closing
