### ISSUE TITLE
Activity license agreement should stay checked

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#215]
Currently, the activity license agreement checkbox is not stored in the database and must be re-checked every time an activity is updated. We should store this in the database and make sure it stays saved after it is checked for the first time.

I am assuming that existing activities that have never checked this agreement before should still need to check it the first time they go to update the activity.

**Comment by amanda-phet** [comment]
That's correct. All existing activities will have false for the license agreement until they check the "I agree..." checkbox. Moving forward, it will remain true, even with edits.

**Comment by amanda-phet** [comment]
When will this be deployed? I didn't notice it working on phet-dev or the live site.

**Comment by aaronsamuel137** [comment]
@zepumph and I have fixed this, but only deployed it locally. I will let you know when I deploy it the the main site.

@zepumph - in the future it is generally good to leave website issues open until they are fully deployed, just so we are in sync with the rest of the team.

**Comment by aaronsamuel137** [comment]
Should be working now on the live site. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It is working for me!
