### ISSUE TITLE
"for-teachers" URLs are broken; create redirect

### ISSUE THREAD

**Issue by schasteen** [phetsims/website#218]
The links to http://phet.colorado.edu/en/for-teachers no longer work with the renaming of this section.  Please create a redirect so that URLs in for-teachers redirect to teaching-resources.

I know we have several printed resources that have been given at conferences with the for-teachers URL, and we also have the for-teachers link in many of our videos.  

For example, http://phet.colorado.edu/en/for-teachers/activitiesDesign no longer works, and is now http://phet.colorado.edu/en/teaching-resources/activitesDesign

**Comment by ariel-phet** [comment]
@aaronsamuel137 we will want redirects for these links and probably should do this soon

**Comment by aaronsamuel137** [comment]
I will deploy this tonight.

**Comment by aaronsamuel137** [comment]
This should be working now. Let me know if the bookmarked links are working for you now @schasteen. Feel free to close if everything looks good.

**Comment by schasteen** [comment]
There is one problematic redirect that I found

http://phet.colorado.edu/en/for-teachers/activitiesDesign
Redirects to
http://phet.colorado.edu/en/teaching-resources/activitiesDesign (which doesn't exist)
The correct URL to redirect to would be
http://phet.colorado.edu/en/teaching-resources/activitesDesign

"Activities" is misspelled in the correct URL.  I think that just changing the URL to be properly spelled would result in a correct redirect.

I didn't directly check all of these, so I'm not sure if other spelling mistakes could be in here.

Stephanie

**Comment by aaronsamuel137** [comment]
Activities is indeed misspelled. It looks like it has been misspelled all along, must have been a spelling error introduced when Mike was working on the new for-teachers pages. The link http://phet.colorado.edu/en/for-teachers/activitiesDesign never would have worked at any point in the past - so I doubt anyone has it bookmarked.

Would still be good to fix though. I guess we should change it to the correct URL and have the typo redirect.

**Comment by aaronsamuel137** [comment]
I am going to create a new issue for the typo, since the redirect from for-teachers to teaching-resources is working as expected.
