### ISSUE TITLE
Add HTML5 sim translator credits page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#224]
Discussed in 6/4/15 dev meeting.

Each sim will be an expandable text with a list of locale, translator, translator info

This page will be linked to from the about dialog on the sim page.

We'll keep track of userId, locale, simId in a table in the db to know who to list on this page.

**Comment by aaronsamuel137** [comment]
Feel free to start on this @zepumph. This should be higher priority than other website issues.

**Comment by aaronsamuel137** [comment]
I can help with this too, but it would be good for you to get a start while I am finishing up some other things.

**Comment by zepumph** [comment]
What were you thinking for a URL for this page, I think it makes sense to put it in about/translationCredit,  because it's one large file.

**Comment by zepumph** [comment]
Then there would also be a way to access the entire list without going through the individual sim through the about section?

**Comment by zepumph** [comment]
@ariel-phet does that seem like good placement, in about. You can see here that you can get to it from a link in the sim page, and in the about navigation:
![translationcredit through about navigation](https://cloud.githubusercontent.com/assets/6856943/8316618/82b3dd7c-19b5-11e5-9b99-21e30e9b6f5a.png)
![about-sim](https://cloud.githubusercontent.com/assets/6856943/8316621/84ef3f1e-19b5-11e5-89bd-66244613a70d.png)

Is this good logic? The actual translation credit page is under /about/translation-credit currently, tell me whatcha think.

**Comment by ariel-phet** [comment]
Hmm, @zempumph - think there was confusion in the way that this issue was written.

I believe the idea was that in the "about dialog" contained *within* the sim there would be a link to translation credits. We had not discussed a link for translation credit on the "sim page" only within the sim itself. Although we might conisider having such a link on the sim page, the proper place would be in the "translations" subsection of the sim page.

That link (much like the licensing link within a sim) will link to a page on the website, which I think should go under "For Translators" - not under about.

So lets plan to make a subheading under "For Translators" in the left hand nav that says "Translation Credits"

Does that make sense?

**Comment by zepumph** [comment]
assigning to @aaronsamuel137  to see if there is anything to be done before Thursday status meeting.

**Comment by zepumph** [comment]
As discussed at 7/9 status meeting:
One table per sim, adding locale as a column, repeating it for every translator of a specific locale.
Add an about column for unique translator information.
Look At java sims to see the string translation.credits, to be filled out by the translator. Use something similar.

**Comment by aaronsamuel137** [comment]
Looks good so far. I'll add the Rosetta integration, which will get more users added to the database to show up. Reassigning to @zepumph.

**Comment by zepumph** [comment]
There is currently a version of this page on phet-dev, with limited data, but there is now a link in the aboutDialog of sims that point to this page, and will take you to the specific sim header. See joist issue 163. https://github.com/phetsims/joist/issues/163.

**Comment by amanda-phet** [comment]
Minor request: Can you match the style that is used in the Translated Sims table, to be consistent? Basically, not bold (since we reserve bold for links/sorting) and left-aligned. 

![screen shot 2015-07-13 at 12 45 04 pm](https://cloud.githubusercontent.com/assets/7852916/8657830/30f6b024-295d-11e5-8c39-01ede5ea535d.png)

**Comment by zepumph** [comment]
This page is now on figaro, because it is currently empty, it shows a coming soon message, but will populate as more and more translators work on sims.

**Comment by amanda-phet** [comment]
@zepumph were you able to match the style of the Translated Sims table? It doesn't appear updated on phet-dev, but I won't know for sure on figaro until a translator enters information!

**Comment by zepumph** [comment]
It's updated now on phet-dev @amanda-phet. I matched the greying out, and the locale formatting. I'm also not using bold. Would you mind being more specific about the exact changed you would like to see for the tables. Thanks!

**Comment by amanda-phet** [comment]
I was referring to the blue title bar for the header
>not bold (since we reserve bold for links/sorting) and left-aligned.
The center alignment looks funny when we don't see edges.

**Comment by zepumph** [comment]
Any other thoughts about the formatting @amanda-phet? https://phet-dev.colorado.edu/en/for-translators/translation-credit

**Comment by amanda-phet** [comment]
Is it my imagination, or is still bold? You said you weren't using bold but it still seems bold to me. 

Otherwise, the alignment is looking good so I don't think I have any other suggestions!

**Comment by zepumph** [comment]
Turns out the table headers are auto bolded, sorry about that. You have a much better eye than I! All fixed now and on phet dev if you want to glance @amanda-phet. I'll keep this issue open until the tables begin to get populated by translators. Also we haven't yet decided what to do with the about section of the table.

**Comment by amanda-phet** [comment]
Thanks for handling my minor pixel-polishing requests! It looks great. 

The "about" section is optional. If a translator has a website they want to link to, it would go there. I believe it would have the text "More Info" if they choose to include a URL. It might've actually been an "Info" section, and the link was "About", but I'm not sure it matters too much. If we find that no translators even want to include a URL maybe it can get deleted altogether.

**Comment by aaronsamuel137** [comment]
During status meeting on 7/23/15, @kathy-phet recommended we create 2 views for this page, the first one by sim (like it currently is), and another "by-locale" view.

**Comment by zepumph** [comment]
This was a big project, so I'm assigning to @aaronsamuel137 for a bit of a code review.

**Comment by zepumph** [comment]
If you want to see the work in progress and say any feedback @amanda-phet go for it, it's on phet-dev.

**Comment by amanda-phet** [comment]
Looks really nice! I like the options to sort by sim or locale. 

The only funny thing is that the tables vary in width- I imagine the table widths are based on the contents and creates some variation. It's not a huge deal, but if you think they could all be the same width then it might be worth playing around with it. If I'm the only one who finds it funny then don't worry about it!

**Comment by aaronsamuel137** [comment]
Code review comments
1. TODO in on line 89: ```// TODO Eventually needs to be if the 'By Sim' button is pressed (also will probably be default)```. Has this been taken care of or not? I'm not totally clear on what is meant here.
2. Another TODO: ```// TODO make this an some sort of ajax update when the 'By Locale' button is pressed.```. I think you decided not to use the ajax approach, correct?
3. I've made some general formatting changes, but nothing too major.

Other comments:
1. I agree with @amanda-phet, tables should have the same width. I've added css for this since it's a one-liner.
2. It seems to me there should only be one toggle button that shows "by simulation" when you are on the by-locale page and "by locale" when you are on the by sim page. What do you think @amanda-phet?

Other than that, things look great too me. Nice work! I'd say just remove or address the TODOs and change the toggle buttons if @amanda-phet agrees with my suggestion.

**Comment by amanda-phet** [comment]
I think that's a good idea, @aaronsamuel137 . So there is text that reads "by locale" and if you click it, the text changes to "by simulation"? That feels really normal to me!

**Comment by zepumph** [comment]
Sorry both of those TODO's were for me, and I forgot to delete them. @aaronsamuel137 I will change the button as well.

**Comment by zepumph** [comment]
This commit as well. 185aaf252f5262e738c004f457dd0bfcdada8204 changed 'bylocale' to 'By language'

**Comment by aaronsamuel137** [comment]
Looks good to me. The last commit doesn't actually seem to do anything, just deletes some empty space as far as I can tell.

**Comment by zepumph** [comment]
Hmm you're right, I didn't pull your commits before adding some stuff, so there were some merge conflicts that I resolved weirdly I guess. But that feature is changed, and I think that this is good to be deployed.

**Comment by aaronsamuel137** [comment]
For some reason, logs on figaro are getting spammed with errors now:

```
05 Aug 2015 18:30:23,634  WARN        PhetCycleProcessor - error encountered!
org.apache.wicket.markup.MarkupException: Unable to find component with id 'toggle-layout' in [MarkupContainer [Component id = translation-credits-panel]]. This means that you declared wicket:id=toggle-layout in your markup, but that you either did not add the component to your page at all, or that the hierarchy does not match.
[markup = file:/data/tomcat/webapps/ROOT/WEB-INF/classes/edu/colorado/phet/website/content/about/TranslationCreditsPanel.html
```

Must be that we didn't test the case where these is no translator data in the database. Not a big deal, the translation-credits page just shows up as blank instead of having the coming soon message. But we should fix this soon if we can, if nothing else so the logs don't get spammed.

**Comment by zepumph** [comment]
Yeah I'm sorry I forgot to add the new button as an invisible component in the edge case. Master is now good.

**Comment by aaronsamuel137** [comment]
Thanks @zepumph!

The last remaining task here is to add a column for the translators website link. Assigning to myself since @zepumph is leaving today.

**Comment by aaronsamuel137** [comment]
I've added the column for "about" and a new section in edit profile for trusted translators to add a link if they want. See https://phet-dev.colorado.edu/en/for-translators/translation-credits/by-locale and go to the Thai section to see an example of how it might look.

Anything more that needs to be done here? Assigning to @ariel-phet for review. You might want to make yourself a trusted translator and take a look at the edit profile page too to see how the translators will add their links.

**Comment by amanda-phet** [comment]
What would we do if the URL is long? Can we use some general text and make it a link? I think "Info" was thrown around.

**Comment by aaronsamuel137** [comment]
That's easy to do. So it would be empty of there was no link, and the text would be "Info" for every link?

**Comment by amanda-phet** [comment]
Correct. Unless there is another idea? I'm just throwing it out there because not all URLs are the perfect length. They can also have a "..." at the end where they get cut off.

**Comment by aaronsamuel137** [comment]
"Info" sounds good to me. Currently the urls just get cut off like so:

<img width="536" alt="screen shot 2015-08-11 at 9 23 35 am" src="https://cloud.githubusercontent.com/assets/3193912/9201500/afcffe3c-400a-11e5-980a-aa88b151df1f.png">

Thoughts on this @ariel-phet?

**Comment by aaronsamuel137** [comment]
Updated on phet dev. Anything else to do here, or can I close?

**Comment by ariel-phet** [comment]
I would be in favor of displaying a link up to a certain length and then having a "..." at the end. My issue with "info" is that different people are going to put different things in this spot (personal website, institution website, etc).

Would a defined displayed link length work @aaronsamuel137?

**Comment by aaronsamuel137** [comment]
I've added the truncated link text and "..."

**Comment by aaronsamuel137** [comment]
Let me know if it looks good to you @amanda-phet or @ariel-phet

**Comment by ariel-phet** [comment]
Yes, the truncated looks good, but it seems like the "simulation" column width is not fixed. In some places it is going on two lines, and some places it is not. Seems we want a fixed width on that column so the other columns don't get shrunk too much.

![capture](https://cloud.githubusercontent.com/assets/4051174/9229439/54666a56-40da-11e5-988d-35b8d2139fb5.PNG)

**Comment by aaronsamuel137** [comment]
That's correct. Column aren't a fixed width in HTML tables. There is a built an algorithm that adjusts the widths to accommodate all of the columns according to their content. We could override this behavior if you think it is necessary, but I'm not sure it is worth it as it is likely to introduce other complications.

**Comment by ariel-phet** [comment]
ah... @aaronsamuel137 that makes sense. So if we have the truncated web address it will always fit.

In that case, looking good to me. Feel free to close this issue unless there is anything left to do.
