### ISSUE TITLE
Links in FAQ unclickable

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#225]
I am unable to open the links provided in the FAQ. For example, if I click on the link to the Source Code or Licensing pages, the questions will collapse instead of directing me to the linked page. Actually, it looks like clicking anywhere within the response will collapse the question. This problem exists in both Chrome and Firefox. 

![image](https://cloud.githubusercontent.com/assets/8419308/7996623/8b2bfd2a-0adf-11e5-9b32-da72760b8929.png)

**Comment by aaronsamuel137** [comment]
Feel free to work on this if you want @zepumph. I won't have time until Monday at the earliest.

**Comment by zepumph** [comment]
Should be fixed, I just manually changed strings on the main and dev sites. You can click the links now. @arouinfar does that look good to you?

**Comment by arouinfar** [comment]
Looks good! Closing.

**Comment by aaronsamuel137** [comment]
@zepumph, what change did you make to the strings? I am just concerned that translators may or may not realize they need to make similar changes. It might be better to address this at the css level instead if possible.

**Comment by aaronsamuel137** [comment]
After discussing with @zepumph, everything seems to look good. Closing.
