### ISSUE TITLE
Change wording in error message

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#227]
The current error message is "An invalid username and/or password has been entered." We do not have *usernames* on our site, so it should say *email address* instead: "An invalid email address and/or password has been entered." 

![screen shot 2015-06-08 at 9 08 04 am](https://cloud.githubusercontent.com/assets/7852916/8038006/2ed314d2-0dbe-11e5-917c-415b38665d4a.png)

**Comment by aaronsamuel137** [comment]
Wording updated. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks good. Closing.
