### ISSUE TITLE
null pointer exception in edit profile for admins

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#229]
When you try to edit your profile as an admin, you get a server error unless Job Title is filled in. We should fix this, and make job title a required field that validates for admins.

**Comment by zepumph** [comment]
Assigned back to @aaronsamuel137 for review.

**Comment by aaronsamuel137** [comment]
Looks pretty good. However, I get a null pointer exception when I try to update my profile with a non admin account. Even the usual validation won't work.

You can create another account to test this with on the VM. You may have to log into the VPN on your VM to get the confirm emails to work though.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph.

**Comment by aaronsamuel137** [comment]
This should be pretty high priority at this point, because master is broken until this gets resolved.

**Comment by zepumph** [comment]
@aaronsamuel137 for review.

**Comment by aaronsamuel137** [comment]
Looks great! The only change I made was to run in the IntelliJ auto-formatter. It's good to get in the habit of doing this before committing, but not a big deal. Closing
