### ISSUE TITLE
Admin "Users" page internal errors

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#230]
While in the administration page and going to "Users", entering an email into the fields for editing, disabling, or deleting a users account that doesn't actually exist returns an internal error as opposed to just saying "email does not exist".
Also, entering an email that doesn't have an account into the subscribe or unsubscribe fields then clicking their submit buttons just returns you to the same page with no indication as to whether it worked or not (which it shouldn't since the account doesn't exist). In hindsight, shouldn't these two fields not differentiate between emails with or without an account? Say if someone was entering a long list of emails from people who opted in to the newsletter during an exhibition?

**Comment by zepumph** [comment]
#155 Covers these errors, and they are now handled, closing
