### ISSUE TITLE
Require users to be logged in in order to download activity files

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#231]
@aaronsamuel137, the following request has come from @kathy-phet and she would like it implemented as soon as is possible

She would like to require users to be logged in to download activity files on the site, much like the current requirement for sim primers. So the use case would go something like this:

If not signed in to the site and going to a sim page:
1. Go to sim page as normal
2. Click on an activity as normal and be able to view the individual activity page
3. Click on one of the activity files - sign in dialog appears

If not signed in to the site and going to browse activities from teacher resources:
1. Equivalently be able to search activities as normal
2. Be able to go to an activity page as normal
3. Click on on one of the activity files - sign in dialog appears

I mentioned to @kathy-phet that more logged in users could be a potential stability risk. She commented that we are in a "low load" state since it is summer now and web traffic is overall low. However she wondered if you could put in an easy "off switch" so if we are finding that requiring log in for activity downloads is causing a problem, we could easily turn off the requirement.

As noted, please make this task your current top priority, and let me know any questions/issues.

**Comment by aaronsamuel137** [comment]
Sounds good. I'll be working on this today.

What should be the behavior when the user clicks submit on the sign in form? It is difficult to both sign the user in AND download the file the way things are currently done. The easiest thing would be to sign the user in when they submit the sign in form, and then they will need to click the download link again to download the file.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I think that will be fine...since the sign in dialog appears over the webpage, I think it will be natural once you sign in to then have to click the file to complete the action.

**Comment by aaronsamuel137** [comment]
This is implemented on phet-dev. Assigning to @ariel-phet for review.

Technically, you can still download the files directly from apache even if you are not logged in if you know what the old links to them are, but those links are not live on the site anywhere after making this change. If you think this is an issue I can look into writing an .htaccess file that will prevent users from downloading these files from apache.

Also, we'll want to test these changes with every file type to make sure they all still work.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - looks good to me on phet-dev.

I don't think we need to worry about people getting the files off apache...if that are that savy and sort of super inclined to not be logged in, more power to them.

If you feel like some testing should be done on phet-dev first, please make a testing task with a description, and assign it to me.

**Comment by aaronsamuel137** [comment]
Since there are only a few things to test, it will probably be faster for me to just do the testing myself.

**Comment by aaronsamuel137** [comment]
I've finished testing and fixed some bugs. This will be deployed tonight.

**Comment by ariel-phet** [comment]
Excellent, thanks!

**Comment by aaronsamuel137** [comment]
Deployed. Feel free to review or close @ariel-phet.

**Comment by ariel-phet** [comment]
Just did some quick testing, accessing activity pages from several places (sim page and browse activities). All seems to be working well. Nice work!

**Comment by amanda-phet** [comment]
I found a file that gave me an error when trying to download it. @aaronsamuel137 Do you know why the word doc in this activity gave an error? Is something wrong with the file? 

https://phet.colorado.edu/en/contributions/view/3908

**Comment by aaronsamuel137** [comment]
Yeah it's unrelated to sign-in, that's just the page that displays if it doesn't work as expected, which will usually be due to not being signed in.

My best guess is that the encoding and decoding of the plus sign is messing it up somehow, though I am not sure why. Short, term you can look at change the file names (replace "+" with "and" or something) and see if that fixes it.

The correct files are definitely on the server and can be downloaded correctly still via the old links.

**Comment by amanda-phet** [comment]
Thanks @aaronsamuel137. I will email the author and ask if she can update the file names because I'd need to download them first in order to do it myself, and I can't!
