### ISSUE TITLE
WebGL disabled page

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#232]
This page needs some help:
http://phet.colorado.edu/en/webgl-disabled-page

It's missing quite a few things seen elsewhere on the site, and the little arrows are pretty far to the left.

**Comment by oliver-phet** [comment]
@aaronsamuel137 Can you clean this page up? Add the normal side navigation, footer, etc. When we update the troubleshooting/faq pages, we'll migrate this page in. But for now I think you can only access this page from Molecule Shapes.

**Comment by aaronsamuel137** [comment]
Assigning to @zepumph. You can fix the arrows by looking at an example of how the expandable text works on the faq pages.

To make it have the normal side navigation, etc., make WebglDisabledPage extend PhetMenuPage.

**Comment by zepumph** [comment]
@aaronsamuel137 how does that look?

**Comment by aaronsamuel137** [comment]
Looks good to me. Next time I deploy I will assign to @oliver-phet to review.

**Comment by aaronsamuel137** [comment]
@zepumph - one more thing. You'll need to either bump the version number of the main css file or move the css changes to the webgl html file.

**Comment by zepumph** [comment]
Version number is fixed.

**Comment by aaronsamuel137** [comment]
Actually, you'll need to change the version number of phet-v29-min.css, not the individual css file, because this is the only file that actually ends up cached. You can do a search for v29 to find all places where this needs to change.

**Comment by zepumph** [comment]
Other version number fixed.

**Comment by aaronsamuel137** [comment]
Assigning to @oliver-phet for review.

**Comment by oliver-phet** [comment]
Looks great @zepumph and @aaronsamuel137. It is even translatable! Closing.
