### ISSUE TITLE
Broken Link from our supporter 'Panco'

### ISSUE THREAD

**Issue by zepumph** [phetsims/website#233]
I was just clicking around on a sim page and went to the panco website: http://www.pancopty.com/
which you can see is a broken link. Panco is one of our supporters. I don't know what we should do with this, just thought I would bring it to someones attention. 

![screenshot-panco](https://cloud.githubusercontent.com/assets/6856943/8216104/b3d2a8f2-14f1-11e5-8013-25f02a400179.png)

**Comment by aaronsamuel137** [comment]
This link is indeed broken. It looks like there a multiple cases of outdated sponsor links being tracked in https://github.com/phetsims/tasks/issues/347 so I'll close the issue here.
