### ISSUE TITLE
Metadata requests for some simulations fail

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#234]
http://phet.colorado.edu/services/metadata/simulation?simulation=build-an-atom&format=phet-master returns:
```
unknown simulation. please see http://phet.colorado.edu/services/project-sorted-simulations.csv for a list of valid simulation names
```
Possibly since there is an older and newer (HTML5) version, and we're using HIbernate's .uniqueResult()?

If you replace build-an-atom with a sim with just an older version (density/CCK) or just a newer version (area-builder) it works.

**Comment by jonathanolson** [comment]
It's also somewhat likely that this may have broken phet-info requests (PhetInfoServicePage) for older Flash/Java simulations. We'll want to test and make sure that is working for sims that have new and legacy versions.

**Comment by jonathanolson** [comment]
For reference, they send requests to services/phet-info with the following construction for post-data (pulled from the Flash common code):
```as3
		var str = "<?xml version=\"1.0\"?>";
		str += "<phet_info>";
		
		if(checkSim) {
			str += "<sim_version request_version=\"" + SIM_REQUEST_VERSION + "\" project=\"" + common.getSimProject() + "\" sim=\"" + common.getSimName() + "\" />";
		}
		
		if(checkInstallation && common.fromFullInstallation()) {
			str += "<phet_installer_update request_version=\"" + INSTALLER_REQUEST_VERSION + "\" timestamp_seconds=\"" + String(common.getInstallationTimestamp()) + "\" />";
		}
		
		str += "</phet_info>";
```

**Comment by aaronsamuel137** [comment]
It's almost certain the unique result is throwing a NonUniqueResultException here and causing the error. However, I am not sure what the correct behavior should be here. Should we just return the html5 sim? Or should there be another parameter for project, or for isHTML? I am not clear enough about how this metadata is used to know what is best here.

**Comment by jonathanolson** [comment]
We've given those URLs out to be used to make sure repositories that point to our sims are up-to-date and can get information for all of our sims. Presumably, they would expect the Java/Flash versions from those URLs.

It might be preferable for us to show the HTML5 sims for those requests, however, as we want people to move towards that.

@kathy-phet, any opinion on whether metadata requests for things like build-an-atom should return Java or HTML5? It's not too feasible to return information for both.

**Comment by zepumph** [comment]
@kathy-phet says at 7/16 dev meeting: only html5 meta data is good.

**Comment by aaronsamuel137** [comment]
Fixed. Closing
