### ISSUE TITLE
General style of web pages, including licensing 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#235]
The style we came up with for headings on the sim pages seems to be working well as we noticed a similar one is used on the HTML5 licensing page: http://phet.colorado.edu/en/html-terms-privacy-and-licensing

I would just like to point out that the blue headings (2nd level?) should be 00A6D3 to be consistent with the sim pages. Moving forward, we would like to continue to use this theme heading on other pages!

**Comment by aaronsamuel137** [comment]
I've updated the color on phet-dev. Take a look around phet-dev and let me know if you'd like me to deploy this. It effects a lot of pages.

**Comment by amanda-phet** [comment]
You're right, it affects a lot. Oddly, I didn't see the change on the HTML licensing page. 

Also, some PhET pages *weren't* affected, which concerns me a bit that those aren't linked in to the CSS the same way (like [troubleshooting](http://phet-dev.colorado.edu/en/troubleshooting) and [research](http://phet-dev.colorado.edu/en/research)). 

For now, let's not make the change, but instead work on addressing these two issues. It would be helpful for future universal CSS changes.

**Comment by aaronsamuel137** [comment]
Research looks updated to me. But troubleshooting is not. I can do an easy fix for troubleshooting, looks like it is just overridden somewhere else.

Should I go ahead and deploy this to the live site after I fix troubleshooting?

**Comment by amanda-phet** [comment]
I'm not sure I like this new look, so rather than deploying the light blue color change I think we should stick with the navy color that is currently used (but fix the overwriting on the troubleshooting page), and use it in the html5 licensing page for consistency (so, that page will change, but will be consistent with the navy that is elsewhere in the site).

**Comment by aaronsamuel137** [comment]
I'll make these minor changes. Closing
