### ISSUE TITLE
Turn java/flash licensing full software agreement text into webpage

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#236]
@zepumph please turn this page into a webpage with a style that matches the HTML licensing page

http://phet.colorado.edu/about/software-agreement_v7.htm

@aaronsamuel137 will help as needed

At status meeting 06/18/2015 it was decided this page does not need to be translatable.

**Comment by zepumph** [comment]
The licensing software agreement is now in similar format to the html5 licensing page (http://phet.colorado.edu/en/html-terms-privacy-and-licensing), you will see it next deploy. See #80 for any other questions about this page
