### ISSUE TITLE
installer ripper is picking up a big and probably unnecessary file in pendulum-lab

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#239]
There is a file under sim/pendulum-lab named pendulum-lab.swd that is 30M in size and, as far as I can tell, isn't used anywhere.  It's being pulled down as part of the rip.  Can this file be removed?  I discussed with @jonathanolson and he thought it would be safe to remove this.  Assigning to @aaronsamuel137 to verify that it can go and, if so, remove it.

**Comment by aaronsamuel137** [comment]
Removed from simian and figaro. Closing
