### ISSUE TITLE
Add Registered Trademark to Logo on Website

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#240]
We need to add the R with circle to the Logo on the header of the website. Amanda and I were working on this some, and thinking it could be the color of the Blue R. 

Assigning to @amanda-phet  to work with @aaronsamuel137 and @zepumph

**Comment by amanda-phet** [comment]
Here is a mockup of what it could look like using the logo we already worked on together. @kathy-phet if you like the way it looks, I will give the registered .png to @aaronsamuel137 to put on the website. 

![screen shot 2015-06-30 at 3 42 34 pm](https://cloud.githubusercontent.com/assets/7852916/8442852/d52a8f5e-1f3e-11e5-929d-7ac010010f26.png)

**Comment by amanda-phet** [comment]
@aaronsamuel137 I am going to email you the new logo for the main header of our website. Does that file touch any other instances on the website? If it is isolated to the header, I think it's safe to say just put it on the live site.

**Comment by aaronsamuel137** [comment]
I've deployed the new image to phet-dev. Does it look ok to you @amanda-phet? (You may need to hard refresh to see it)

**Comment by amanda-phet** [comment]
It looks great.

**Comment by aaronsamuel137** [comment]
Deployed to figaro. Closing
