### ISSUE TITLE
Investigate database backup using PetaLibrary Service

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#241]
@aaronsamuel137 - making an issue to track progress on this investigation

Looks like some basic info is here:

https://www-test.rc.colorado.edu/resources/storage/petalibrary

Would be good to know what the route would be for transfering the data and such (could we have a chornjob type script that would regularly send the data over)

Seems like a reasonable priority (not super high, but worth getting some investigation done). Feel free to pass on to @zepumph if you think he can do the investigation.

**Comment by aaronsamuel137** [comment]
Sent out an investigatory email on 7/1.

**Comment by aaronsamuel137** [comment]
I've gotten this set up, and figuring out last details over email. Anything else you want to track in this issue @ariel-phet?

**Comment by ariel-phet** [comment]
I don't think so. Thanks for getting this done! Closing.
