### ISSUE TITLE
Asking OIT about what it would take to put in a larger server hard drive

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#242]
@aaronsamuel137 - when you get a chance please email OIT (and cc me) about if they would be able to move onto a new hard drive for us, and what that would entail.

Seems like it would be good to know the answer to this question anyhow in case of a catastrophic failure, as well as knowing what sort of downtime would be involved. 

I know this was discussed at dev meeting, just seems worth having an issue for tracking purposes

**Comment by aaronsamuel137** [comment]
Email sent to OIT on 6/30/15

**Comment by aaronsamuel137** [comment]
Here's the response: 

>Figaro currently has all drive bays populated: 4 x 300GB SAS disks, configured as 2 RAID-1s. Adding disk is non-trivial. The only way to add local disk to it would be buying all new larger drives and restoring the OS/data onto them. This would be fairly expensive in terms of price and downtime, depending on what size disks you might purchase. Figaro would be unavailable during the final syncing and restore. I would estimate about a day of downtime for the syncing, not including any problems that arise.
 
> That said, I don't recommend buying replacement disks because it is not a good long-term investment. Figaro will be 7 years old July 27th, 2016 when its current Dell warranty expires. Dell does not allow warranty renewals after 7 years, so figaro's hardware would be unprotected, even if you had purchased new disks. I would instead start thinking about your next hardware iteration of the PHET service. Are you at a point where the service could be split onto multiple machines, perhaps VMs? If not, what is your budget/desire for replacing figaro altogether?

Probably a good idea to discuss this in conjunction with the next version of the website.

**Comment by ariel-phet** [comment]
Since the next step is discussing options for the next version of the website and server architecture I am closing as those issues are being tracked in #244
