### ISSUE TITLE
Odd redirect to Danish CCK page after signing in

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#243]
I’ve tested on quite a few pages, none prompting a login - just pressing the ’Sign In' button and all get redirected to https://phet.colorado.edu/da/simulation/circuit-construction-kit-dc
For instance, I go to the homepage http://phet.colorado.edu/
Press the ‘Sign In’ button > oliver.nix@colorado.edu
![screen shot 2015-06-25 at 5 01 32 pm](https://cloud.githubusercontent.com/assets/5090275/8437199/c56d48b4-1f1a-11e5-8428-93d89c538d43.png)
![screen shot 2015-06-25 at 5 01 41 pm](https://cloud.githubusercontent.com/assets/5090275/8437204/cc54d4f8-1f1a-11e5-9858-617533bb179d.png)

After signing in, I get taken to https://phet.colorado.edu/da/simulation/circuit-construction-kit-dc

**Comment by zepumph** [comment]
I can't seem to recreate this problem, can you be more specific @oliver-phet. I go to a page, and try to sign in, and it works fine, can you still recreate it? Did you try any other usernames?

**Comment by aaronsamuel137** [comment]
Is this still happening for you @oliver-phet? Can you close if not?

**Comment by oliver-phet** [comment]
Yes, still occurs every time I log in.

**Comment by oliver-phet** [comment]
@mattpen If you have time, could you look into this? I seem to be the only one that gets this behavior, but it would be problematic if this happened to users.

**Comment by mattpen** [comment]
@oliver-phet - does this happen when you logon from any computer, or just your own?  Can you try logging on from a separate computer and let me know if it happens?  I've never seen this behavior and can't recreate it to try to troubleshoot it.

**Comment by oliver-phet** [comment]
Ah I should have tested that earlier. I just logged in without issue on another Mac. Any ideas on what could be happening on my machine?

**Comment by mattpen** [comment]
@oliver-phet - It's hard to tell. I would start with clearing cookies and cache for phet.colorado.edu.  It would probably be easiest to call and share your screen over Skype.

**Comment by oliver-phet** [comment]
After a little investigation, it looks like it has something to do with my password program. Closing this for now and I'll try to figure it out on my own!
