### ISSUE TITLE
Next Generation Server Investigation for Figaro Replacement

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#244]
KP will set up a meeting with OIT, Aaron, Jonathan, and Ariel to discuss and plan for transition from Figaro to next steps.

**Comment by kathy-phet** [comment]
Meeting set up for Aug 17, 2pm. 
@aaronsamuel137 
@jonathanolson 
@ariel-phet 
All coming to this meeting at Orrie's place.

**Comment by ariel-phet** [comment]
This server has been ordered, and will soon be setup (in March 2016). Closing
