### ISSUE TITLE
Incorrect link on Research page

### ISSUE THREAD

**Issue by schasteen** [phetsims/website#245]
On http://phet.colorado.edu/en/research

when you click on the link to this reference:
Creating effective interactive tools for learning: Insights from the PhET Interactive Simulations Project, Perkins, K. K., Podolefsky, N. S., Lancaster, K., & Moore, E., B. Wilson & T. Amiel (Eds.), pp. 436-441, 2012 .

It takes you to the link for the reference above it, which is incorrect.  I don't know the correct link, but @emily-phet or @kathy-phet should know.

**Comment by ariel-phet** [comment]
@emily-phet please provide the correct link and I can then reassign to one of the web devs to fix

**Comment by emily-phet** [comment]
This is the best I could find: http://www.editlib.org/p/40781/

**Comment by zepumph** [comment]
I changed the link to the one that emily found. It will be on phet-dev next deploy. I can change it to something else really easily if needed.

**Comment by ariel-phet** [comment]
@zepumph - thanks for taking care of that. Once this is live on main website, please close the issue.

**Comment by kathy-phet** [comment]
@zepumph - did you mean that it will be on phet-figaro next deploy? or phet-dev then phet-figaro after that?

**Comment by zepumph** [comment]
phet-dev sorry for the miscommunication @kathy-phet. I will post here when it is up on any server, and which one it is.

**Comment by zepumph** [comment]
correct link is now up on the actual phet site:
https://phet.colorado.edu/en/research#sims
closing
