### ISSUE TITLE
remove links to download zipped versions of activities for installer-builder rip

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#246]
The size of the activities-included installers could be reduced by eliminating the links on the activities pages to the zipped version of the activities.  It's redundant to have these links anyways when running from a local mirror, since the activities are already on the local disk.  @aaronsamuel137 and I discussed this already, but I thought I'd log an issue to track.

Screenshot of link as currently shown in local mirror (highlight added):

![website-with-download-link](https://cloud.githubusercontent.com/assets/3082831/8630074/c8a80f30-271e-11e5-950a-4bc8d81b5023.png)

**Comment by jbphet** [comment]
Related Unfuddle issue here: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3697

**Comment by aaronsamuel137** [comment]
Removed. Assigning to @jbphet to test with the installer.

**Comment by aaronsamuel137** [comment]
I've talked to @jbphet and it appears that most recent tests of the installer are working. Closing
