### ISSUE TITLE
Can links to activities use https so that installer doesn't have to log in every time?

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#247]
Currently, if a user installs a non-activities version of the local mirror using one of the installers, and then uses it while internet connectivity is present, and follows an activities link, they have to sign in every time they want to download an activity.  This is admittedly a bit of a weird use case - why run a local version if you've got decent Internet access?  But, if it's not too much hassle, I think it would be worth fixing since it is likely to come up occasionally.  The problem is due to the links to the activities being http when ripped (rather than https), so the saved cookie isn't being transmitted in the http request, and the web site can't tell that the user already logged in.

This isn't worth a ton of effort, so please only implement it if it is <= 1 hour of effort.

Related Unfuddle ticket: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3701

**Comment by aaronsamuel137** [comment]
I've update these links to use https. Assigning to @jbphet to verify they work properly in the installer.

**Comment by jbphet** [comment]
The new links appear to work, thanks @aaronsamuel137.  Closing.
