### ISSUE TITLE
Prompt users to considering donating after finishing the registration (or profile update) process

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#248]
At ISTE, I talked to a social media/nonprofit expert that mentioned it might be good to prompt our users to donate right after finishing registration. She mentioned such a strategy has been effective for things like "adblock" on chrome...right after you install it prompts you for a donation.

I mentioned the idea to @kathy-phet and she really liked it...especially since it will help reiterate to our users that donating is possibility on the site, and helpful to our project.

@amanda-phet - can we discuss some mockups at our next website meeting, thinking about what the flow would be when you finish registering? I am thinking a dialogue window similar to the way the sign in window pops up and dims out the page behind it. Perhaps with a short blurb about how every donation counts.

**Comment by patricialoeblein** [comment]
My 2 cents. I think this is ok and if carefully written will not seem negative to teachers. I have thought about it and I recall other teacher resource websites that require a login having similar messages. My typical response is to ignore the request if I have not used enough resources to know if the site is worthy of a donation. Right now, many users who will be registering will be PhET resource users who haven't had to register before to download materials. Teachers who already value PhET might be inclined to donate. I think we should implement this quickly to get that type of benefit while the new feature of being registered is fresh.

**Comment by kathy-phet** [comment]
I am excited about this, and am also looping @kdessau-PhET to this discussions. 

@ariel-phet , @amanda-phet - I think it would be great if Kathy D could participate in the design thinking process about donor flow and such, as we will have a number of such design needs and generating ideas and messages together would be a good foundation to build.

It will be great to get this going - as Trish says - to leverage all those teachers who will be registering soon.

**Comment by ariel-phet** [comment]
Let's go ahead and close this issue, since this was really to track discussion of the idea and if we all agreed.
