### ISSUE TITLE
Add "parent" field on registration page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#249]
In a 7/15 discussion with Kathy D. we realized there are plenty of parents who might register for the site (particularly home-school parents). 

Can you add a parent field to the "I am a..." section of the registration page?

**Comment by aaronsamuel137** [comment]
I've added this - it will appear on the next deploy. I'll let you know then and assign to you for review.

**Comment by zepumph** [comment]
@amanda-phet,  you can go ahead and take a look at this on figaro.

**Comment by amanda-phet** [comment]
Looks great. Thanks.
