### ISSUE TITLE
Metadata for HTML5 pages for Learning Repositories

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#25]
@jonathanolson lets work together (@ariel-phet) to get in touch with the learning repository people for changes we are going to make related to HTML5 sim pages

**Comment by jonathanolson** [comment]
@ariel-phet, should I review how our metadata is working?

**Comment by ariel-phet** [comment]
@jonathanolson this seems like a question for @kathy-phet, marking for next status meeting. As far as I know everything is smooth for the moment.

**Comment by ariel-phet** [comment]
Office of Ed tech has a central server with LRMI compliant metadata and we need a way to get our resources up to data.

There might be a way for the Learning Registry to pull this data, but we might need to set up some service for this to happen.

Priority after server switch, after PhET-iO website, after LTI compliance...

Goal might be end of summer.

**Comment by ariel-phet** [comment]
This issue seems way stale, and several services has used our metadata. Closing
