### ISSUE TITLE
Embed Mac troubleshooting video in Mac troubleshooting l

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#250]
@zepumph Can you embed this video: https://drive.google.com/file/d/0BxerAx_XXHB2M1ByQ2pVTXJNcnc/view

Into this troubleshooting link (above the answer text) http://phet.colorado.edu/en/troubleshooting/mac#q5-header

**Comment by aaronsamuel137** [comment]
Typically, we host videos on figaro if we want users to be able to download them. If we want to embed the video, then we use youtube. Can this video be posted on youtube in the phet account?

**Comment by aaronsamuel137** [comment]
Assigning to @oliver-phet or somebody else who has access to the phet youtube account. Reassign to @zepumph when you have a youtube link for us.

**Comment by aaronsamuel137** [comment]
Actually, I take that back, we might be able to embed with Google Drive directly. I will look into this first.

**Comment by aaronsamuel137** [comment]
@zepumph, you can embed the video directly from google with something like this:

```html
      <iframe src="https://drive.google.com/file/d/0BxerAx_XXHB2M1ByQ2pVTXJNcnc/preview" width="640" height="480" allowfullscreen></iframe>
```

I would say we don't need to bother hosting it on figaro.

**Comment by zepumph** [comment]
I just deployed this feature to phet-dev, @oliver-phet if you can look at it and give me any feedback this afternoon, then we can push it to master and onto phet tonight. Not that this is pressing or anything.

**Comment by oliver-phet** [comment]
Looks good, but can you align the left side of the video to the left side of the text? (Not the arrow)
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Jul 16, 2015, at 3:45 PM, Michael Kauzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


I just deployed this feature to phet-dev, @oliver-phet<https://github.com/oliver-phet> if you can look at it and give me any feedback this afternoon, then we can push it to master and onto phet tonight. Not that this is pressing or anything.

**Comment by zepumph** [comment]
Alright, I just got the formatting that was already there working, which is offset a bit to look more centered. Do you like this, or would you rather have it flush.

**Comment by oliver-phet** [comment]
That looks best. Ready to push!
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Jul 16, 2015, at 3:58 PM, Michael Kauzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright, I just got the formatting that was already there working, which is offset a bit to look more centered. Do you like this, or would you rather have it flush.

**Comment by zepumph** [comment]
It's up on phet now, I don't know why the style didn't update to the main site, I'll look into it.

**Comment by oliver-phet** [comment]
It looks like the top mac entry (Molecule Shapes) has a left aligned screenshot instead of center also.
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Jul 17, 2015, at 9:40 AM, Michael Kauzmann <notifications@github.com<mailto:notifications@github.com>> wrote:


It's up on phet now, I don't know why the style didn't update to the main site, I'll look into it.

**Comment by zepumph** [comment]
Yeah I changed those to match the video indent. I'm having a problem with varnish I think. It works on phet-dev, as you can see on https://phet-dev.colorado.edu/en/troubleshooting/mac  but the same code is having trouble on phet, I think it is because of varnish. We aren't supposed to restart it, to force of reload of the code that I changed on phet, But I was able to restart varnish on phet-dev, which is why it looks pretty. I'm not really sure what to do here @oliver-phet . I apologize. @jonathanolson do you have any thoughts on what I could do?

**Comment by oliver-phet** [comment]
No rush on getting it fixed - we definitely want images and videos to be centered eventually, but it is more important that the content is up.

**Comment by jonathanolson** [comment]
The JS and CSS is bundled into one JS file and one CSS file, which are versioned and set to be cached permanently (for many performance gains). Whenever JS/CSS changes are made that will change those files, the versions should be updated (so that they will have a new URL). These names will need to be updated everywhere, e.g. "phet-v31-min.css" => "phet-v32-min.css" in all code and other files.

See WebsiteBuildCommand for how it is built and combined, and website-build.properties for where the names are read from in the build process.

**Comment by zepumph** [comment]
Great thanks so much, I was changing the css versions on individual pages,
but not the whole minified one, I'll do that, and it will be up next
deploy. I'll keep you posted @oliver-phet, thanks for the patience.

On Fri, Jul 17, 2015 at 8:05 PM, Jonathan Olson <notifications@github.com>
wrote:

> The JS and CSS is bundled into one JS file and one CSS file, which are
> versioned and set to be cached permanently (for many performance gains).
> Whenever JS/CSS changes are made that will change those files, the versions
> should be updated (so that they will have a new URL). These names will need
> to be updated everywhere, e.g. "phet-v31-min.css" => "phet-v32-min.css" in
> all code and other files.
>
> See WebsiteBuildCommand for how it is built and combined, and
> website-build.properties for where the names are read from in the build
> process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phetsims/website/issues/250#issuecomment-122468828>.
>



-- 
Michael Kauzmann
PhET Interactive Simulations
michael.phet@gmail.com

**Comment by zepumph** [comment]
Changes are  up at https://phet.colorado.edu/en/troubleshooting/mac, closing.
