### ISSUE TITLE
Create a donation splash page after registering for site

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#251]
At the 7/15 website meeting with @ariel-phet @arouinfar @oliver-phet and @kdessau-PhET, we decided on a design for a donation splash page at the request of @kathy-phet . 

We would like a dialog box to pop up that has the same theme as the login dialog- background, fonts, etc. I can send you some temporary artwork but we will need Mariah to fix it up a little. Here is the basic look:
If a user selects that they are a "new user" or "occasional user", they will see this dialog:
![screen shot 2015-07-15 at 4 26 08 pm](https://cloud.githubusercontent.com/assets/7852916/8728867/ce21ae32-2ba4-11e5-8577-31931c1b2387.png)

If a user selects that they are an "experienced user" or "power user", they will see this dialog:
![screen shot 2015-07-15 at 4 26 00 pm](https://cloud.githubusercontent.com/assets/7852916/8728883/f036f068-2ba4-11e5-9c4c-01155aae803f.png)

Assigning to @aaronsamuel137 to work with @zepumph .

**Comment by amanda-phet** [comment]
This is in response to #248. Sorry for the duplication.

**Comment by aaronsamuel137** [comment]
We will also look into getting a count of how many people press "Donate Now", whether using Google Analytics or something custom made.

**Comment by aaronsamuel137** [comment]
Should the user be able to press escape or click outside of the dialog to exit, or do we want to require them to press "Maybe later"?

**Comment by amanda-phet** [comment]
Yes, users should be able to click outside or press escape in addition to clicking "maybe later".

**Comment by patricialoeblein** [comment]
I was on Wikipedia today. They have a funding raising that suggests $3 per user. It might be interesting to check out the phrasing.
![image](https://cloud.githubusercontent.com/assets/5091205/8826600/e8f1784c-3044-11e5-9452-80dae54a0458.png)

**Comment by kathy-phet** [comment]
Here are my word-smithed suggestions for the various parts of the text ... 

For all users -- use this text to describe project: 
PhET is a small nonprofit project with a dedicated team of designers, researchers, educators, and developers. We rely upon our users to keep PhET free for everyone. 

For "new users" or "occasional user", have the following ... 
Text on the sign: ... (original is good)

Ask text in bold (line break is placed purposefully, if it works out OK there) :
Every $10 you donate funds more than 
500 student uses.

For "experienced" or "power user", have the following ... 
Text on the sign (drop "PhET" if needed): 
Help convert PhET sims 
to run on tablets! 

Ask text in bold: 
A $10 donation from every registered user 
would fund 20 HTML5 sim conversations.

**Comment by amanda-phet** [comment]
Thanks @kathy-phet . I emailed an updated mockup to @aaronsamuel137 . As for the line spacing, it might be possible, but we'll have to see it after it is coded.

**Comment by aaronsamuel137** [comment]
I haven't gotten an email, can you try resending?

**Comment by aaronsamuel137** [comment]
I have deployed an incomplete version of this to phet-dev. Please take a look @amanda-phet and @kathy-phet.

For now, ignore the image since I still haven't gotten the final versions from @mariahmaephet. The final images will obvious have a transparent background and the text in the sign.

What should be the behavior when you click donate? Right now, it both opens the donate page in a new tab and submits the form in the current tab.

**Comment by kathy-phet** [comment]
Looking good in my tests. I think the behavior on click donate works well now. 

I like the superhero image for the power user, but there is a different image for the new user - correct? - not the super hero image.

**Comment by oliver-phet** [comment]
In my opinion, the popup should only occur with a successful registration (ie: if there are fields that need completed, it should wait to show the "Please correct the fields marked in red.") Then, once the user corrects everything and presses 'Register', they will see the popup.

For 'Donate' behavior, I would opt for opening the donation page in a new tab.

**Comment by kdessau-PhET** [comment]
I agree with Oliver that the popup should only open on a successful registration. There are two messages for the PhET girl for the two conditions. I didn't see any message in this version though. (I guess that's the incomplete part.)

**Comment by aaronsamuel137** [comment]
> I like the superhero image for the power user, but there is a different image for the new user - correct? - not the super hero image.

Yes this is correct, I just haven't gotten the final images yet.

> In my opinion, the popup should only occur with a successful registration (ie: if there are fields that need completed, it should wait to show the "Please correct the fields marked in red.") Then, once the user corrects everything and presses 'Register', they will see the popup.

I agree that the popup should only occur with successful registration. This will require implementing form validation on the client side too, since previously this was done on the server side with wicket. I will add this.

**Comment by kathy-phet** [comment]
I have been thinking about this feature. We are likely to evolve places we put "asks" and when we do them over the course of this year. 

Could you add a field in the database for the user that keeps track of any asks that they encounter? So it just is a mini-array associated with their entry that has "date-time" and "ask-type". And then give each of these asks a type name ... e.g. "NewRegistration" and "ProfileUpdate"? 

Thanks.

**Comment by aaronsamuel137** [comment]
I will look into a JSON column of "asks" in the database, with a structure like so:

```json
[
  {
    "askType": "NewRegistration",
    "datetime": "2015-07-23T12:34:12"
  },
  {
    "askType": "ProfileUpdated",
   "datetime": ...
  }
...
]
```

**Comment by kathy-phet** [comment]
Aaron, Just a comment about how I think about this column. I am thinking about it as a sorted column by datetime, so there could be multiple entries for askType: "ProfileUpdated", but each would have a unique datetime. And I think about potentially checking users last "datetime" before presenting a ask. 

So I wonder if "datetime" should come first in the JSON format? 

I don't know much about structuring JSON ... just wanted to communicate how I was thinking about the data from an excel sort of perspective.

**Comment by aaronsamuel137** [comment]
I've added an "asks" column to the database. Using Postgres's JSON datatype seemed too complicated, so I used a TEXT datatype that holds a JSON string and do the conversion manually.

Users will have something like this after registering and seeing this donation dialog:

```json
[
  {
    "datetime": "2015-07-24T20:08:56.925Z",
    "askType": "NewRegistration"
  }
]
```

**Comment by aaronsamuel137** [comment]
This is up on phet-dev now. @amanda-phet or @kathy-phet, feel free to review if you want. You may need to force refresh the register page to see the most recent updates. I am planning on deploying this too figaro tonight.

If you want an easy way to see the dialog without filling out the form, you can open the browser console and paste this code in (when on the register page). The correct version of the dialog should show up depending on which radio button you have selected.

```js
var checkedRadioValue = $( 'input[name=phetExperienceContainer:phetExperienceRadios]:checked' ).val();
          var radioValues = [];
          $( 'input[name=phetExperienceContainer:phetExperienceRadios]' ).each( function( i, item ) {
            radioValues.push( item.getAttribute( 'value' ) );
          } );

          // use a different image and ask text if the first or second radio buttons are selected (new or occasional)
          if ( radioValues.indexOf( checkedRadioValue ) < 2 ) {
            $( '#donate-ask' ).html( $( '#new-user-ask' ).html() );
            $( '#superhero' ).hide();
            $( '#labcoat' ).show();
          }
          else {
            $( '#donate-ask' ).html( $( '#power-user-ask' ).html() );
            $( '#superhero' ).show();
            $( '#labcoat' ).hide();
          }

          $( '#donate-dialog' ).lightbox_me( {
            centered: true
          } );
```

**Comment by kdessau-PhET** [comment]
This looks great. I hope that we get a lot of donations!


On Jul 24, 2015, at 2:13 PM, Aaron Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


This is up on phet-dev now. @amanda-phet<https://github.com/amanda-phet> or @kathy-phet<https://github.com/kathy-phet>, feel free to review if you want. You may need to force refresh the register page to see the most recent updates. I am planning on deploying this too figaro tonight.

If you want an easy way to see the dialog without filling out the form, you can open the browser console and paste this code in (when on the register page). The correct version of the dialog should show up depending on which radio button you have selected.

var checkedRadioValue = $( 'input[name=phetExperienceContainer:phetExperienceRadios]:checked' ).val();
          var radioValues = [];
          $( 'input[name=phetExperienceContainer:phetExperienceRadios]' ).each( function( i, item ) {
            radioValues.push( item.getAttribute( 'value' ) );
          } );

          // use a different image and ask text if the first or second radio buttons are selected (new or occasional)
          if ( radioValues.indexOf( checkedRadioValue ) < 2 ) {
            $( '#donate-ask' ).html( $( '#new-user-ask' ).html() );
            $( '#superhero' ).hide();
            $( '#labcoat' ).show();
          }
          else {
            $( '#donate-ask' ).html( $( '#power-user-ask' ).html() );
            $( '#superhero' ).show();
            $( '#labcoat' ).hide();
          }

          $( '#donate-dialog' ).lightbox_me( {
            centered: true
          } );

**Comment by amanda-phet** [comment]
This looks great!

I practiced registering and when I clicked "maybe later" or outside of the dialog, I was still on the registration page. I had to click Register a second time to get the typical "an email was sent to..." page. You can sort of see it in the screenshot below.. the dialog is in front of checkboxes. 

Also, in my email to you I fixed a typo but it looks like you used the text from Kathy's message above. The last word should be "conversions" not "conversations". 
![screen shot 2015-07-24 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/7852916/8884476/2b39b4b4-3214-11e5-94a9-00230cb3cace.png)

**Comment by amanda-phet** [comment]
Also, can you make the font size for the "Thanks for registering" text the same as the "Sign In" text on the sign in dialog? I think it would be nice if they were the same size.

**Comment by kathy-phet** [comment]
When I tried this out, I got 2 images in my dialog box? 

![image](https://cloud.githubusercontent.com/assets/5096804/8885395/3c6f0b50-321c-11e5-8212-eb7d92f1b3cf.png)

**Comment by amanda-phet** [comment]
You should do a hard browser refresh, then try again. I got that at first, too.

**Comment by kathy-phet** [comment]
OK - got it working now. Thanks. 

Still need to fix the last word should be "conversions" not "conversations". 

Otherwise looking good!

**Comment by aaronsamuel137** [comment]
This has been deployed! I believe all issues were addressed. Now, when the user exits the dialog in any way, the form will automatically be submitted.

**Comment by kathy-phet** [comment]
I checked out the deployed version, and it looks like great! 

However, the "ask" isn't appearing in the "Profile Update" mode. It should appear whether its for an profile update or a new registration. It was working that way earlier, so I'm not sure what changed. 

I'll re-open. 

@zepumph can you take a look and see if you can get this working when "Update" is pressed on the edit profile page since @aaronsamuel137 is on vacation.

**Comment by aaronsamuel137** [comment]
Sorry, that was a misunderstanding on my part. I thought it was only supposed to appear on the register page. I can add it back to the edit profile page too.

**Comment by aaronsamuel137** [comment]
This now appears on the edit profile page too.

**Comment by kathy-phet** [comment]
Thanks, Aaron!  

Does this log to the users' "ask history" column with a "NewRegistration" tag or a "ProfileUpdate" tag? 

It would be great if it could be labeled "ProfileUpdate" in the ask history. But no rush, this can wait until you get back. Just logging to make a note of it.

**Comment by aaronsamuel137** [comment]
It doesn't yet use a ProfileUpdate tag. I will add this when I get back.

**Comment by aaronsamuel137** [comment]
Ok I've added the ProfileUpdate tag. @kathy-phet, do you want to show this on every profile update, or not ask again once they've seen it once?

**Comment by aaronsamuel137** [comment]
Discussed in 8/6/15 status meeting. We want to not ask again for an update profile if they have already been asked in the last 3 months. Also, update the header to say "Thanks for Updating" instead of "Thanks for Registering".

**Comment by amanda-phet** [comment]
Can this be closed?

**Comment by aaronsamuel137** [comment]
I haven't finished the last touches on this, but it has been delayed due to higher priority issues.

**Comment by aaronsamuel137** [comment]
Finished the last touches here. Will be updated on next deploy. Closing.
