### ISSUE TITLE
Internal Sever error related to giving an invalid url with query parameters.

### ISSUE THREAD

**Issue by zepumph** [phetsims/website#254]
As found during the 7/23 developers meeting, here is part of the stack trace when going to: http://phet.colorado.edu/translation-credits?simName=example-sim&locale=en

23 Jul 2015 17:06:21,249 ERROR              RequestCycle - Can't instantiate page using constructor public edu.colorado.phet.websi
te.content.NotFoundPage(org.apache.wicket.PageParameters) and argument simName = "[example-sim]" locale = "[en]"
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public edu.colorado.phet.website.content.NotFou
ndPage(org.apache.wicket.PageParameters) and argument simName = "[example-sim]" locale = "[en]"

**Comment by aaronsamuel137** [comment]
Thanks @zepumph. I believe I have fixed this problem when addressing https://github.com/phetsims/joist/issues/163

**Comment by ariel-phet** [comment]
Looks fixed when I try the link above, Closing
