### ISSUE TITLE
Redirect for third-party-credits may need to be redeployed

### ISSUE THREAD

**Issue by samreid** [phetsims/website#255]
Yesterday's meeting notes say:

* KP: The URL text should read “Third-party Credits”
  * KP: Were making a new link: http://phet.colorado.edu/third-party-credits
    * AD: redirect added to website

However, when I navigate to http://phet.colorado.edu/third-party-credits I see **The requested page could not be found.** and when I navigate to http://phet.colorado.edu/third-party-credits?simName=acid-base-solutions&locale=en I see **Internal error occurred**

Perhaps the website just needs to be redeployed?  I'm not sure so I decided to create an issue for it.  This is probably related to https://github.com/phetsims/website/issues/254

**Comment by aaronsamuel137** [comment]
This hasn't been deployed yet, but the changes have been made to the website code and tested locally.
See commit 958e465d53666a17aa24107c12ed21971549b5bb (also referenced in https://github.com/phetsims/joist/issues/163)

**Comment by aaronsamuel137** [comment]
Deployed and tested. Closing.
