### ISSUE TITLE
New "Team" Page for PhET

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#256]
I'd like to work on improving the team page on PhET website to be more modern and polished. 

I like the titles "Our Team" or "The Team", as opposed to staff. 

Some models to check out are here: 
https://openstaxcollege.org/about (scroll down to team section)
http://concord.org/about/staff
https://www.khanacademy.org/about/the-team
https://www.desmos.com/team
http://strategyplusdesign.com/
http://www.edutopia.org/about/team
https://www.moore.org/about/our-people/staff
http://www.gatesfoundation.org/Who-We-Are/General-Information/Leadership/Executive-Leadership-Team

I'm sure there are other good models out there. 

Goal for this would be to communicate the roles, expertise, and depth of our great staff. 

I'd like the "always visible" version to include Name, Project Title, and an areas of work/expertise list but in somewhat smaller font (e.g. sim design, curriculum, teacher pd, science, math, research, communications, strategy, fundraising, software, corporate partnerships, accounting, etc.)

We could have some a more detailed blurb and background that is larger with a "before joining PhET" piece - or not.

**Comment by ariel-phet** [comment]
@amanda-phet - we should discuss this project at website meeting at some point soon.

**Comment by amanda-phet** [comment]
Discussion at 7/29 meeting: 
* We think it is important that the pictures have some consistency. Either all shot at the same time, or a standard for resolution, framing, lighting, etc. 
* Large name, bullets for title, education
* optional blurb for longer bio that can be expanded 
* organized with Carl and Kathy at the top, then the team members, collaborators?, undergrads w/o bios, affiliates? 

Questions for Kathy:
* Do you want to include collaborators who are on grants and work on sims? 
* Should there be an affiliate section to include people who work with PhET but aren't really team members? 
* How do you want the team organized?

**Comment by kathy-phet** [comment]
Just a quick update - more next week. There is a grant proposal due Sept 4 that will be reviewed quickly, and this team page would be quite valuable to have up for it.

**Comment by ariel-phet** [comment]
@amanda-phet - it seems given that sort of time constraint, we should probably up the priority of this project.

**Comment by amanda-phet** [comment]
@ariel-phet Of course. It would be good to get some answers to our questions, but we can start working on a mockup.

**Comment by amanda-phet** [comment]
Question for @aaronsamuel137: Is it possible to create an interface for someone to edit information about their profile, either on their PhET edit profile page or for one team member to access and edit everyone's? Will discuss at Status 8/6.

**Comment by aaronsamuel137** [comment]
I'm not sure I understand your question, but it is already possible to edit another users profile via the admin interface under users.

It wouldn't be possible to edit everybody's in one go, but I could probably write a SQL query to do that directly in the database.

We can discuss more tomorrow.

**Comment by aaronsamuel137** [comment]
Discussed at dev meeting on 8/6. I will make it so team members can add their own info through the edit profile page.

**Comment by aaronsamuel137** [comment]
Noted in 8/13 status meeting: we want an admin interface for adding collaborators. Depending on how this interface goes, it may be easier to use this interface for all team members too, instead of modifying the team member profiles to have new fields.

**Comment by aaronsamuel137** [comment]
New team page is ready to review. You'll need to upload the new photos to make them look right because I have changed the aspect ration to 10x8. Also probably a good idea to add some more team members to see how it looks with more people.

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It looks really great. Just a few tweaks! 

- [ ] Can we make the team and undergrad photos a little larger? 
- [ ] Kathy's MORE is really large. Can you make it the same font size as her bio, just like we did with the team members?
- [ ] Consultant and Collaborators should not have bold titles/roles. Just plain text is good. Mockup below.
- [ ] We need to add one more section at the bottom for University of Colorado Boulder Offices. Each entry includes a name and a role (no location). A mockup is below. 

![screen shot 2015-08-26 at 2 58 53 pm](https://cloud.githubusercontent.com/assets/7852916/9506071/02e9eb1a-4c03-11e5-8727-5373a8fc57a8.png)

**Comment by aaronsamuel137** [comment]
New adjustments are deployed to phet-dev. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I'm really happy with it. Everything looks good to me!

**Comment by aaronsamuel137** [comment]
Great! I guess the last step is to coordinate a time to deploy when @phet-steele or whoever will be uploading all the info is available shortly after.

**Comment by ariel-phet** [comment]
Looking good!

**Comment by ariel-phet** [comment]
Project complete, closing
