### ISSUE TITLE
Website translations broken!

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#257]
It looks like the website translations are completely broken right now. I click on any of the language links at the bottom of the website page, and it remains as English at all times. This is also true on phet-dev. 

This is a high priority to fix. 
@zepumph @ariel-phet @jonathanolson @aaronsamuel137 - thoughts? 

I'm assigning to Michael since Aaron just left for vacation, but if anyone else is around and sees the fix - feel free to jump in!

**Comment by aaronsamuel137** [comment]
I have a little time to work on this this morning before I leave. I have an idea of what change might have caused this.

**Comment by aaronsamuel137** [comment]
Translations are working again! Closing.

Feel free to reopen if something still looks off to you @kathy-phet.

**Comment by kathy-phet** [comment]
Awesome! Thanks for the quick fix!!

**Comment by kathy-phet** [comment]
Aaron, Do you know why when I click on the translation, I get a seemingly random query parameter in my URL? 
http://phet.colorado.edu/nb/?sim=BatteryResistor_Circuit 
(and this just keeps shifting to wierd names after the ?)

**Comment by aaronsamuel137** [comment]
I have no idea... I'll create an issue for that. I probably won't have to look into it until after I get back though.

**Comment by aaronsamuel137** [comment]
Tracked here: https://github.com/phetsims/website/issues/258
