### ISSUE TITLE
translation links give seemingly random query parameter in my URL

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#258]
Example: clicking on the "nb" link might go to: ```http://phet.colorado.edu/nb/?sim=BatteryResistor_Circuit```

Feel free to take a look at this if you want @zepumph. I won't be able to until I get back.

**Comment by kathy-phet** [comment]
A bit more information. The random added text is only there when I am *not* logged in. If I am logged in, it seems to work correctly.

**Comment by kathy-phet** [comment]
I am now thinking that this was possibly fixed when Aaron fixed #257 . I had seen it when the website translations were broken. It seems to be improving now, and I am wondering if was a varnish history thing that is slowly fixing itself as some hits go back to tomcat and retreive the correct link info or something.

I will check again in a bit. and close if it seems fully fixed.

**Comment by kathy-phet** [comment]
Nevermind - still broken. 

It looks like if you are at https:// you get the right behavior, if you are at http:// you get the random query parameters. 

http://phet.colorado.edu/in/?levels=all&types=all&sims=98
But should just be http://phet.colorado.edu/in

These look to be related to some sort of search that I did not perform.

**Comment by kathy-phet** [comment]
But on the plus side, the translations all still work, and once you get past the home page all seems well -- no query parameters. 

I think I had seen these random query parameters on all sorts of pages before Aaron's #257 fix -- so there may be some relation. Not completely sure here.

**Comment by aaronsamuel137** [comment]
I think this problem existed before #257 and is probably unrelated. I'll look at it when I get back.

**Comment by aaronsamuel137** [comment]
I've addressed this locally. Should be fixed now. Will test on phet-dev and deploy.

**Comment by aaronsamuel137** [comment]
Fixed on the lives site. Closing.
