### ISSUE TITLE
Troubleshooting item or page for enabling WebGL

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#26]
At least, enabling WebGL if possible. We need to link to instructions from Molecule Shapes if we have to fall back to Canvas (see https://github.com/phetsims/molecule-shapes/issues/4).

**Comment by aaronsamuel137** [comment]
The webGL page has been created at http://phet.colorado.edu/webgl-disabled-page

As of now, it is not translatable but can be made so if it needs to be. Assigning to @ariel-phet for review.

**Comment by jonathanolson** [comment]
Additionally, if it is made translatable in the future, I would imagine it would turn into a redirection to the best locale?

Now sims are loading the URL with a query parameter for their locale, e.g. ?simLocale=en

**Comment by aaronsamuel137** [comment]
@ariel-phet mentioned that this page should be translatable during status meeting on 2/5/15. I'll work on adding that functionality.

**Comment by aaronsamuel137** [comment]
OK I've made this page translatable and redirect to the locale given in the simLocale query parameter. @jonathanolson, let me know if this is what you were expecting.

http://phet.colorado.edu/webgl-disabled-page?simLocale=ar_SA
http://phet.colorado.edu/webgl-disabled-page

**Comment by jonathanolson** [comment]
Yes, looks good to me!

**Comment by aaronsamuel137** [comment]
One more change is needed: add category headers for Windows, Mac, Mobile.

**Comment by aaronsamuel137** [comment]
I've added the category headers. Since no other suggestions were given during status meeting I am closing this issue.
