### ISSUE TITLE
Add resend confirmation button on login

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#263]
Many users report not getting confirmation emails. When an unconfirmed user tries to log in, we should notify them that they need to confirm and give them a button to resend confirmation email button.

**Comment by kathy-phet** [comment]
Just curious what "many users" means? Are these coming to phethelp?

**Comment by aaronsamuel137** [comment]
Yes these are emails to phet-help. I actually don't know what the numbers are, you'll have to ask @oliver-phet - he is the one who reported this to me.

**Comment by oliver-phet** [comment]
Probably 5-10 users over the past 2 weeks. It would just make it easier for both us and the users if they could log in and easily resend the confirmation email.

**Comment by aaronsamuel137** [comment]
As part of this effort, we've also discussed adding a "Confirm email" box on the register page to help the user not type an invalid email, which apparently we have been getting a lot of.

**Comment by aaronsamuel137** [comment]
I've addressed this and created a testing task.

**Comment by aaronsamuel137** [comment]
Deployed and tested on phet-dev. Closing for now. Feel free to reopen if you notice any issues with it @oliver-phet.
