### ISSUE TITLE
Remove breadcrumbs from some pages 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#264]
After a discussion on 8/12, we are noticing that many sites don't use breadcrumbs anymore. On our site, they are redundant of the navigation highlights on the left-hand side. As an incremental improvement to the site, we would like to remove them. 

We are thinking of just starting with removing them from all pages under "About". A concern about removing them all at once is that there may be some pages where they are useful. 

@aaronsamuel137 is it easier to remove them from individual pages or all pages at once? What are your thoughts (in general) about breadcrumbs?

**Comment by aaronsamuel137** [comment]
It's much easier to remove them all at once. I don't see much use for them personally, I always use the side navigation, but I am not sure about our users.

Is there a way to see how often those links are clicked with our analytics (maybe @ariel-phet would know this). If they are not used much, I would recommend getting rid of all of them in one go.

**Comment by ariel-phet** [comment]
@aaronsamuel137 and @amanda-phet - a couple of places have been pointed out where these "might" be useful (such as on the teacher resources page). But I think I would be OK with removing them all. The small possible benefit does not seem to outweigh the clutter anywhere.

@amanda-phet can make the call, if she is comfortable with just removing them everywhere, I will be fine with that decision. Unfortunately, we are not going to be able to deduce their use from analytics, since the bread crumbs are links that are identical to ones that get used often, Google counts them all the same. For instance, see below, where *Simulations*, *New sims* and *HTML5* sims all get the same percentage, since all basically are the same link, including the breadcrumbs. Just seems like a judgement call. 

The downside is that some pages would then probably require a title instead of a breadcrumb. But perhaps that title could be automatically generated?

![untitled](https://cloud.githubusercontent.com/assets/4051174/9280259/585b47de-427a-11e5-8ae1-e114dc082f8f.png)

**Comment by amanda-phet** [comment]
I think it might be useful to comb the site for pages that will need a title if the breadcrumbs are removed. Can I make an undergrad task for this? 

The Teaching Resources pages do not have useful breadcrumbs and for them to be useful would require a reorganization of those pages. Since we've decided not to touch that part of the site yet, and the breadcrumbs are not currently useful, I don't see a reason to keep those right now.

**Comment by amanda-phet** [comment]
After discussing this with @oliver-phet I realized that the breadcrumbs are actually serving as page titles for 2nd-level pages. For example, a top-level page like For Translators has a title (which is a link...):
![screen shot 2015-08-19 at 1 39 03 pm](https://cloud.githubusercontent.com/assets/7852916/9366984/ceb4724c-4677-11e5-9e25-bd2e7bad7480.png)


The 2nd-level page adds on to that title/link:
![screen shot 2015-08-19 at 1 38 18 pm](https://cloud.githubusercontent.com/assets/7852916/9366985/d1a96aac-4677-11e5-83a6-cb3521391d63.png)

I think the best course here is to make titles for every page based on the "title" in the breadcrumb. It would align with the title shown in the left-hand navigation, so it should be really clear. 

In the above example, For Translators would have the title "For Translators". The 2nd-level page PhET Translation Utility page would have the title "PhET Translation Utility."

**Comment by aaronsamuel137** [comment]
I've made this change and deployed to phet-dev. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great to me. There are a few pages where we may need to customize... like the Translation Credits page.. it had a custom title so it now has two titles. Otherwise I think it looks great. 

Should I list the individual pages that need to be slightly modified?

**Comment by aaronsamuel137** [comment]
Yes, that would be very useful for me. Thanks!

**Comment by amanda-phet** [comment]
These pages have custom titles that are duplicates of the new orange title. 

Full Install (Remove "-Full Install") 
Translation Credits (Remove "Translation Credits") 
Activity Licensing (Remove "Activity Licensing Information") 
Source Code (Remove "Where can I get the source code for the PhET simulations?") 

Also, I think this change radially improves the Teaching Resources pages! The breadcrumbs never made sense on some of the deeper pages, but now those pages have real titles. However, some still have duplicate titles. Here are the ones I found.

Using PhET In Lecture (Remove "Using PhET in Lecture:") 
Using PhET with Clickers (Remove "Using PhET with Clickers and Peer Instruction:")
Designing Activities for K12 (Remove "Designing Effective Activities for Use in K12:") 
Facilitating Activities for K12 (Remove "Facilitating Activities for K12")

**Comment by aaronsamuel137** [comment]
I've made these changes, assigning to @amanda-phet for review. You might want to force refresh on the first page you look at to make sure your browser is using the updated css file.

**Comment by amanda-phet** [comment]
The only one that looks strange to me is the Activity Licensing page. It is missing the spacing after the title that every other page has. Otherwise, they look great to me!

**Comment by aaronsamuel137** [comment]
Fixed this last issue and deployed to figaro. Closing
