### ISSUE TITLE
possible issue with an activity's file name

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#265]
There is an issue with the installer builder where the version that includes activities is not building reliably.  After some extensive investigation (see https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3697), it seems like there may be a single activity file with a name that includes Latin and Greek characters, as well as spaces, that is causing issues for the InstallBuilder utility.  I'd like to work with the web developers to change the name of this file to something simpler and see if this allows the installer builder to run successfully.

Here's a link to the potentially problematic activity: http://phet-downloads.colorado.edu/files/activities/3516/P%20etropoulos%20Agisilaos_%CE%A0%CE%9B%CE%91%CE%99%CE%A3%CE%99%CE%9F%20%CE%A3%CE%A7%CE%95%CE%94%CE%99%CE%91%CE%A3%CE%9C%CE%9F%CE%A5%20%CE%9A%CE%91%CE%99%20%CE%91%CE%9D%CE%91%CE%A6%CE%9F%CE%A1%CE%91%CE%A3%20%CE%A3%CE%95%CE%9D%CE%91%CE%A1%CE%99%CE%9F%CE%A5%20%20%CE%B3%CE%B9%CE%B1%20%20%CE%97%CE%9B%CE%95%CE%9A%CE%A4%CE%A1%CE%99%CE%9A%CE%91%20%CE%9A%CE%A5%CE%9A%CE%9B%CE%A9%CE%9C%CE%91%CE%A4%CE%91%20%CE%A3%CE%A5%CE%9D%CE%95%CE%A7%CE%9F%CE%A5%CE%A3%20.pdf

**Comment by jbphet** [comment]
@aaronsamuel137 renamed the file, and I set up the auto-builder to run on Sat morn, Aug 15 2015.  From an analysis of the logs, it appears to have succeeded.

**Comment by aaronsamuel137** [comment]
Looks like this has been resolved. Closing
