### ISSUE TITLE
Remove "home" from left-hand navigation

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#266]
Discussed in 8/19 meeting. @oliver-phet pointed out that there is a Home link in the left-hand navigation. This is extremely outdated and unnecessary. Everyone knows to click on the logo in the banner! 

<img width="133" alt="screen shot 2015-08-20 at 12 26 30 pm" src="https://cloud.githubusercontent.com/assets/7852916/9391874/b5fc571e-4736-11e5-83ac-5413f38509f6.png">

**Comment by aaronsamuel137** [comment]
I've removed this in the code, it will disappear from the website on the next deploy.

**Comment by aaronsamuel137** [comment]
Deployed. Closing
