### ISSUE TITLE
Remove "principal sponsors" from left-hand side of every page 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#267]
The Principal Sponsors section on the left-hand side of every page is outdated. 
<img width="228" alt="screen shot 2015-08-24 at 10 48 28 am" src="https://cloud.githubusercontent.com/assets/7852916/9446230/ac3624f2-4a4d-11e5-8246-0d17a09cb335.png">

Instead, we would like the 4 main sponsors that are listed on the homepage to be listed at the *bottom* of every page. To make things simple, we would like you to take the homepage's "footer" and apply it to every page, so that the sponsors (and social media links- why not?) will be included on every page (in addition to the languages).
<img width="737" alt="screen shot 2015-08-24 at 10 51 28 am" src="https://cloud.githubusercontent.com/assets/7852916/9446315/2f8f39ec-4a4e-11e5-9c81-ab3441e14beb.png">

Kathy has already approved of this change. Assigning to @ariel-phet for prioritization. I believe we want this done with the roll out of the team page, but if you think it can be delayed I'll leave that up to you.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - if this is an easy change to make it would really clean up lots of the pages and would be nice to wrap up in the Team Page work. Thoughts? Basically remove the side bar principal sponsors completely, and show the basic home page footer gets shown on every page.

**Comment by aaronsamuel137** [comment]
My understanding is that the team page is first priority, and then the licensing stuff. If I get all of that done with time to spare, I'll do this. Not sure if it'll get done before the Kathy's conference or not. What was the exact date for that again?

**Comment by aaronsamuel137** [comment]
Deployed to phet-dev. It would be great to have someone take a quick glance through all of the pages, since this touches a lot of code.

Social media has been moved to the bottom, and only remains on the side in the sim pages.

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I think it looks really good. Not sure what I need to look for in terms of touching a lot of code- should we have an undergrad test for bugs? 

The only weirdness was on a few short pages it came really close to the navigation. Perhaps there should be a slightly larger buffer above the line.

![screen shot 2015-08-26 at 2 41 18 pm](https://cloud.githubusercontent.com/assets/7852916/9505652/dfe6b5c8-4c00-11e5-943f-bc47d3d11932.png)

**Comment by aaronsamuel137** [comment]
I'll extend the margin above the footer.

I was imagining just having an undergrad go through all of the pages and make sure the layout doesn't look weird anywhere, and make sure the social icons are on the right pages, and make sure the right to left views still look right everywhere. I'll make a task for this.

**Comment by aaronsamuel137** [comment]
I ended up testing this myself since I know what to look for and it seemed easier than making a task. I think it's all good to go. It will be deployed with the new team page. Closing
