### ISSUE TITLE
social icons should be removed from side of contribution pages

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#269]
In #267 I removed social icons from the side of all pages except sim pages, however, I didn't notice that they are still showing up on contribution pages.

**Comment by amanda-phet** [comment]
good catch! they look really funny on that page.

**Comment by aaronsamuel137** [comment]
I've made a fix for this. It will show up on the next deploy.

**Comment by amanda-phet** [comment]
Looks like this can be closed now.
