### ISSUE TITLE
Team page minor tweak

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#271]
@aaronsamuel137 Dave Underwood pointed out one minor tweak to the Team page. I asked @amanda-phet and she agreed. 

The spacing for the text to the right of Kathy's photo is a little tight. Here is more what it should look like:

![team page](https://cloud.githubusercontent.com/assets/4051174/9692141/48c9191e-5304-11e5-830e-d2cb391568e8.PNG)

Please adjust when time allows (should be a quick fix).

**Comment by aaronsamuel137** [comment]
I've made this tweak. Assigning to @ariel-phet for review.

**Comment by amanda-phet** [comment]
This is looking good to me.

**Comment by ariel-phet** [comment]
Looks good, closing!
