### ISSUE TITLE
Modify bold text in the "registration" and "profile update" donation asks

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#272]
Our individual giving consultant would like us to try an experiment to see how it impacts the amount of giving we get from our asks. View this as an experiment. 

Please make the following change to our ask splash screens: 

Keep the images and top text as is. 

Replace the bold text with the following. Keep the spacing from the top text, but make the text regular (not bold) text and space the bullets in a little bit. Like shown below.

Suggested donation amounts: 
* $15 (if you use 1-4 sims) 
* $25 (if you use 5-14 sims)
* $50+ (if you use 15 or more sims)

**Comment by aaronsamuel137** [comment]
This will be deployed tonight.

**Comment by kathy-phet** [comment]
Hi Aaron, Can you deploy it to phet-dev first so that we can review what it looks like before going to the main site? Thx

**Comment by aaronsamuel137** [comment]
I've deployed to phet-dev. I've also put a screenshot here incase you don't want to go through the trouble of getting the register page to validate.

<img width="726" alt="screen shot 2015-09-15 at 2 39 27 pm" src="https://cloud.githubusercontent.com/assets/3193912/9889440/adf4d894-5bb7-11e5-9d19-7626444be86c.png">

**Comment by kdessau-PhET** [comment]
Also, we need to do it on the Power User version?

KD


On Sep 15, 2015, at 2:40 PM, Aaron Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


I've deployed to phet-dev. I've also put a screenshot here incase you don't want to go through the trouble of getting the register page to validate.

[screen shot 2015-09-15 at 2 39 27 pm]<https://cloud.githubusercontent.com/assets/3193912/9889440/adf4d894-5bb7-11e5-9d19-7626444be86c.png>

**Comment by aaronsamuel137** [comment]
Right now, I've set it to be the same message for both versions, power and new users. Is that correct?

**Comment by kdessau-PhET** [comment]
Yes. Thanks!

On Sep 15, 2015, at 2:51 PM, Aaron Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now, I've set it to be the same message for both versions, power and new users. Is that correct?

**Comment by kathy-phet** [comment]
Looks good. Thanks! We'll see how this first experiment goes!

**Comment by aaronsamuel137** [comment]
Alright, this is live! Hope this experiment goes great! Feel free to close @kathy-phet unless there is anything else to do here.
