### ISSUE TITLE
Statistics on number of profile/registration asks so far

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#273]
Aaron, 
Can you please pull some data on the total number for profile and registration pop-up "asks" seen so far since deployment to the website? Please include the start and end dates, so Kathy can cross check with the donations and see what the "conversion rate" is from viewing the ask to donating. 

Also, would we have google analytics on the number of clicks on the "Donate Now!" button in the pop-up? This would help us know the loss rate at each stage. 

Thanks, 
Kathy

**Comment by aaronsamuel137** [comment]
We have 14289 asks since we have added this to the site on June 1st (June 1 - Sep 14).

I don't have access to the google analytics account, so I am not sure if these clicks are being tracked there. Perhaps we can ask @ariel-phet?

**Comment by aaronsamuel137** [comment]
I'll add a page at /services/asks that gives some of these stats so you guys can look whenever you want. I'll let you know when it's deployed.

**Comment by kathy-phet** [comment]
Aaron, we deployed the ask on July 24 --- so do you mean between July 24 - Sept 14?

**Comment by aaronsamuel137** [comment]
Sorry about that, you're correct. Somehow there is a few wrong dates that got in there... not sure exactly how or why. I'll look into it.

**Comment by kathy-phet** [comment]
@kdessau-PhET -- Can you take Aaron's number of 14289 asks between July 24 - Sept 14, and record here the number of donations, and the conversion rate.... so we have that recorded and then we can compare with this change in wording we just added. Thanks!

**Comment by kdessau-PhET** [comment]
I’ve added a Google Spreadsheet but here’s the data:

Type of Campaign        Dates   # of Opportunities      Closed Opportunities    Closure Rate (in %)     Total Donation  Avg. Donation
PhET Girl Teacher Registration Ask      July 24-Sept. 14, 2015  14289   123     0.8608020155    $2,965  $24

On Sep 15, 2015, at 3:13 PM, kathy-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


@kdessau-PhET<https://github.com/kdessau-PhET> -- Can you take Aaron's number of 14289 asks between July 24 - Sept 14, and record here the number of donations, and the conversion rate.... so we have that recorded and then we can compare with this change in wording we just added. Thanks!

**Comment by amanda-phet** [comment]
@kathy-phet wrote: 
>Also, would we have google analytics on the number of clicks on the "Donate Now!" button in the pop-up? 

Google analytics tracks number of visits to a page, not number of clicks on specific links. The "donate now" button takes you to the donate page, but so does the "donate today" button in our permanent banner. It is unlikely that many of the visits to the donate page came from a source other than the new popup, but I just wanted to remind you of this!

**Comment by kathy-phet** [comment]
@jonathanolson - Do you know if Google Analytics will tell us how many times users exited PhET by clicking our button that leads to https://donatenow.networkforgood.org/1437859? 

Or would we need to add an event tracker to those buttons?

**Comment by jonathanolson** [comment]
I don't see anything that tracks that. If it opens in a new tab, it would be pretty feasible to add a Google Analytics event that records that they clicked.

**Comment by aaronsamuel137** [comment]
9/30 website meeting

@kathy-phet asked me to coordinate with @jonathanolson to get this happening.

**Comment by aaronsamuel137** [comment]
This is being tracked in Google Analytics now (as of 10/12). Since then we have had 88 clicks on the donate button.

To see this is GA, go under events and find "Event Category" Donation and "Event Action" Ask.

**Comment by aaronsamuel137** [comment]
Closing this issue, feel free to reopen if there is anything left to do here.
