### ISSUE TITLE
Activity file names should be ASCII

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#275]
Discussed during 9/17 dev meeting. Bitrock has issues with non-ascii file names. In the windows activities with activities, internal links to files don't work in non-english versions.

We discussed giving all activity files a unique ascii name, but maintaining the original name for the link text.

**Comment by aaronsamuel137** [comment]
@jonathanolson mentioned he had some thoughts about this issue. Want to comment here?

**Comment by jonathanolson** [comment]
It's probably possible to have the upload edit an .htaccess file that sends HTTP headers noting what filename will be used for the "Save As" dialog to save the file. In combination with showing that filename for the link, it could hide most of the negative effects of having the actual filename be something like 'activity-3660-1.pdf'

**Comment by ariel-phet** [comment]
Seems like discussing at dev meeting to figure out priority and such for installer

**Comment by samreid** [comment]
@jbphet found the filenames that were the problem.  The installer has been working OK since then.

@jbphet is wondering: can we just close this issue and fix non-ascii filenames if/when we see them again?

@samreid that would be OK with me as long as you completely document (a) how you detect this problem (b) how you solve this problem (c) how you verify the problem has been solved.

**Comment by samreid** [comment]
@jbphet An alternative would be to reject filenames that are non-ascii in the website UI.  If we did that, we would also want to revisit old filenames.  Possibly with redirects?

**Comment by samreid** [comment]
@aaronsamuel137 said: what we discussed last time was automatically renaming the filenames but keeping the full non-ascii filename in the database.  That would take some significant effort.

**Comment by samreid** [comment]
@jbphet said: it would be better to allow customers to use non-ascii.

@samreid can you detect whether a file has a problem before getting to the full build?

@jbphet said it may be possible.

**Comment by samreid** [comment]
@samreid suggests: add into the installer builder script to check the size.  If it is below the threshold, then don't publish it.

**Comment by jbphet** [comment]
For reference, this is the Unfuddle issue that documents the original problem and the current solution.  Look at the original issue description for information about how to recognize the problem. https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3697

**Comment by jbphet** [comment]
The installer-builder has been stable for a while now, and the installers are being tested on a weekly basis by @phet-steele.  Since we've decided not to take any immediate action on this, I'm going to close the issue and will reopen if we start having problems again.
