### ISSUE TITLE
Internal Error when editing strings in the Edit Content Page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#278]
When we try to edit a string and click submit, we get an internal error: 

https://phet.colorado.edu/?wicket:interface=:14:stringsForm::IFormSubmitListener::

**Comment by aaronsamuel137** [comment]
Can you tell me which page you were trying to submit? The one's I have tested seem to work, it's probably something peculiar with the particular page.

**Comment by amanda-phet** [comment]
It was the For Translators page.

**Comment by aaronsamuel137** [comment]
OK should be fixed now

**Comment by aaronsamuel137** [comment]
Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It works! Thanks for fixing that! 

@oliver-phet note that you can make some changes now... I already changed some to test that it's working but not everything that you wanted.
