### ISSUE TITLE
Update wording on translation page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#279]
http://phet.colorado.edu/en/for-translators
*Translating HTML5 Simulations*

*The translation process for HTML5 sims is currently being tested. To request access to the HTML5 translation utilty, please email phethelp@colorado.edu*

Translating *Java and Flash* Simulations

PhET *Java and Flash* simulations have been written so that they are easily translated to languages other than English. The process uses a simple tool called the *Java and Flash Translation Utility*, and requires no programming skills.

http://phet.colorado.edu/en/for-translators/translation-utility
*Java and Flash* Translation Utility
Check if your sim is already translated.

PLEASE READ THIS PAGE COMPLETELY BEFORE USING *THE* TRANSLATION UTILITY.

**Comment by amanda-phet** [comment]
Looks like you can change more than one string at a time. You should double-check the changes I made and make sure it is exactly how you want it above!

**Comment by aaronsamuel137** [comment]
Can this be closed @oliver-phet?

**Comment by oliver-phet** [comment]
Can you or @mattpen add the following text to the top of this page: http://phet.colorado.edu/en/for-translators
*Translating HTML5 Simulations

The translation process for HTML5 sims is currently being tested. To request access to the HTML5 translation utilty, please email phethelp@colorado.edu*

**Comment by mattpen** [comment]
@oliver-phet I can try to get this done on Monday.

**Comment by mattpen** [comment]
@oliver-phet The changes have been deployed to the dev site.  Can you check and make sure it looks ok now? http://phet-dev.colorado.edu/en/for-translators

**Comment by oliver-phet** [comment]
@ariel-phet With the new HTML5 utility, this could read:

>PhET HTML5 sims can now be translated through the browser. To request access to the HTML5 translation utilty, please email phethelp@colorado.edu

Thoughts?

**Comment by ariel-phet** [comment]
@oliver-phet I think that sounds good. Obviously we will need to come up with a policy if multiple people in some locale email you (such as putting them in touch and letting them know that things can be overwritten and such). But for now, that seems like a good simple clear statement.

**Comment by oliver-phet** [comment]
@mattpen Can you update the wording as follows:

>PhET HTML5 sims can now be [translated through the browser](http://phet.colorado.edu/translate/). To request access to the HTML5 translation utilty, please email phethelp@colorado.edu

**Comment by mattpen** [comment]
@oliver-phet This change is now showing up on the Dev site.  Can you take a look?

**Comment by oliver-phet** [comment]
Looks good @mattpen!

**Comment by aaronsamuel137** [comment]
This has been deployed to figaro. Closing
