### ISSUE TITLE
restrict teacher tips to signed in users

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#284]
When a user (who has also checked anything except "student" or "other" when they registered) tries to view a teacher tips document, they should be prompted to sign in, and after they have signed in they will be able to view the PDF.

**Comment by kathy-phet** [comment]
I think "other" could also be allowed to view. Did you have a sense of who other is?
Kathy

Sent from my iPhone

On Oct 5, 2015, at 3:18 PM, Amanda McGarry <notifications@github.com<mailto:notifications@github.com>> wrote:


When a user (who has also checked anything except "student" or "other" when they registered) tries to view a teacher tips document, they should be prompted to sign in, and after they have signed in they will be able to view the PDF.

-

**Comment by ariel-phet** [comment]
I am a bit confused by the first comment...how will you know what the user has checked if they are not signed in? I assume you mean all users will be prompted to sign in if not already, and those who are not student or other will be allowed to view the teacher tips once signed in?

**Comment by aaronsamuel137** [comment]
What should be the behavior for student and other when they click this link?

The easiest thing to do here would be to just mimic the behavior of the activity downloads.

**Comment by amanda-phet** [comment]
@aaronsamuel137 that's correct that it should basically mimic the behavior of the activity downloads or viewing the primer video. I just wanted to clarify that any of the non-student users (and not just teachers) should be able to view the tips after logging in, and assumed we wanted to exclude users like students and other (but I'm fine allowing other... I'm not sure who that includes!). 

What happens currently if a user tries to view a primer video or activity, signs in, and is not a teacher? Just curious.

**Comment by aaronsamuel137** [comment]
There is no check for student or teacher, anyone who is singed in can view any of these. It would add a bit of complication to add the check, but I can do it if we think it is necessary.

**Comment by amanda-phet** [comment]
I see. I was definitely under the impression that only teachers were able to view primer videos. 

If everyone is fine with that then let's just move forward with the same interaction for teacher tips, and later revisit the check.

**Comment by kathy-phet** [comment]
I was also under the impression that students should not be able to view the primers - even if they were logged in.

**Comment by aaronsamuel137** [comment]
It is possible to add that check, I'm just not sure what the behavior should be when a student tries to click the link... should it just do nothing? display a message? something else?

**Comment by aaronsamuel137** [comment]
I've deployed this on phet-dev. Assigning to @amanda-phet for review to make sure the behavior looks right.

**Comment by amanda-phet** [comment]
Seems to work fine. The first time I tried the "for teachers" section was collapsed after signing in, but it must've been a fluke because every time after that it stayed expanded. Looks good to me.

**Comment by aaronsamuel137** [comment]
Actually, it wasn't a fluke, the first time it is changing from http to https, so browser thinks it's a different page and doesn't save the fact that the text was expanded.

I made a change where this should work on the first try now, but it requires using the url hash. It will look almost the same, except it will scroll down to for teachers header in addition to reopening it.

The fix is applied on phet-dev, assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It's working. However, we may want to wait on this because of #286.

**Comment by amanda-phet** [comment]
Looks like the pdf issue is addressed so we can go ahead with this change. We can address the users that are allowed to access it at a later time.

**Comment by aaronsamuel137** [comment]
This is live now. Closing
