### ISSUE TITLE
Use updated table layouts when browsing all translated sims or by language

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#285]
I noticed that we are still using the old style of table on the Translated Sims page as well as the sims by language pages. In the 9/23 website design meeting we decided that we'd like to use the newer tables that are currently being used on sim pages that list translated sims as well as translation credits. 

Here is what those tables could look like. If you have an idea for how the layout could be improved let me know. I'm not 100% sure about the Dutch table, but the Translated Sims table is pretty straightforward. 

![screen shot 2015-10-05 at 4 18 21 pm](https://cloud.githubusercontent.com/assets/7852916/10295258/bbd50360-6b7c-11e5-9242-38156e361107.png)
![screen shot 2015-10-05 at 4 18 26 pm](https://cloud.githubusercontent.com/assets/7852916/10295262/c07d5a20-6b7c-11e5-876b-126876ca95cd.png)
(The "simulatie naam" column is in the title page language, while the "simulation name" column is in the *language of the locale*)

**Comment by aaronsamuel137** [comment]
This looks like a good one for you to tackle, @mattpen. Let me know if you have questions.

**Comment by mattpen** [comment]
@amanda-phet The tables for the translated sims should be updated on phet-dev.  Can you take a look and let me know if its ok to publish them?

**Comment by ariel-phet** [comment]
@mattpen - just a note that @amanda-phet is currently on vacation, so it might be a little while before you hear back.

**Comment by mattpen** [comment]
Thanks @ariel-phet 

@amanda-phet You might notice that "Simulation Name" is missing for languages where it hasn't been translated yet.  Would you prefer it to remain this way, or is it better to show it in English in this case?

**Comment by amanda-phet** [comment]
Looking good! I'm not sure exactly how translations work, but I imagine that the string would show up in English until it is translated (probably by one of our sim translators, @ariel-phet ?).

**Comment by aaronsamuel137** [comment]
Typically the English string would show up if it is not translated. However, I thought it looked a little weird with two columns with the same name, so thought in this case we might want to just leave it off entirely until it gets translated. But I am okay with falling back to the English too. Do you have a preference @amanda-phet?

**Comment by amanda-phet** [comment]
I don't have a preference and I think it would be fine if the column is empty. I am just wondering when it will get translated, since it is in the language of the translated sims- would that happen when someone translates a sim?

**Comment by aaronsamuel137** [comment]
No it would happen when someone translates the website in the language of the sim. It is the same string key for both columns, simulations.translated.simulationName, but the right column takes the translation from the language of the current locale, and then left takes it from the locale of the sim.

This is the only case I know of on the website of wanting a translation for a string that is from a different locale that the site is being browsed in (except for sim titles which are handled as a special case), so there is not really a good way to do it the way things are currently designed.

**Comment by amanda-phet** [comment]
Sounds good. Let's leave the column empty then. 

The current page for sims in a local has an odd "subtitle" that states the language + the language in the site locale...
All sims in French while viewing the site in Spanish: 
<img width="581" alt="screen shot 2015-10-21 at 10 17 42 am" src="https://cloud.githubusercontent.com/assets/7852916/10642834/00ca2470-77dd-11e5-8665-a85bd86b7191.png">

I thought the column titles would clear that up a bit but if it's confusing we can re-think the design.

**Comment by aaronsamuel137** [comment]
I think the design is definitely a step up from the old one, so let's go with this for now. It will be live on the next deploy.

**Comment by amanda-phet** [comment]
Great! I'll let you close this when it's deployed.

**Comment by amanda-phet** [comment]
Great! I'll let you close this when it's deployed.

**Comment by amanda-phet** [comment]
Great! I'll let you close this when it's deployed.

**Comment by amanda-phet** [comment]
Great! I'll let you close this when it's deployed.

**Comment by aaronsamuel137** [comment]
Deployed! Closing
