### ISSUE TITLE
Is there any way to allow .pdfs to open in the browser?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#286]
Before users were required to login to access teacher tips and activities, .pdf files would simply open in the browser. This allowed teachers to very conveniently access the tips/activities as they browsed the site. However, in addition to logging in, there is now the added barrier of downloading the .pdf before being able to view it. This could be an off-putting interaction for some users, which could ultimately affect the dissemination of these resources.

Is there a way to allow users to open the .pdf files in their browser <i>after</i> they have logged in to access tips/activities? I think this will greatly improve user interaction with our site.

**Comment by amanda-phet** [comment]
:+1:

**Comment by aaronsamuel137** [comment]
Looking into this. So far haven't found a good solution the still prevents these pdfs from being accessed through google, but I'll try a few more things.

**Comment by aaronsamuel137** [comment]
OK I've got this working now on phet-dev. @arouinfar or @amanda-phet, can you test?

For some reason, I can't get it to open in a new tab, but it does open in the browser instead of downloading.

**Comment by arouinfar** [comment]
It looks good @aaronsamuel137! I'd much rather have to hit the back button to return to the sim page than be forced to download .pdf's. Do you want to take a look @amanda-phet?

**Comment by amanda-phet** [comment]
Definitely better than downloading the file. I notice that pdf activities also open in the browser now! That's great! Thanks @aaronsamuel137 .

**Comment by arouinfar** [comment]
Thanks @aaronsamuel137! I'll go ahead and reassign this issue to you until the changes have been migrated to the main site.

**Comment by aaronsamuel137** [comment]
Changes have been migrated. Closing
