### ISSUE TITLE
Quick update to Accessibility page

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#287]
@aaronsamuel137 - I'd like provide a link to the accessibility page during some talks I'm giving over the next two days. It would be wonderful to have two things added:

- A new row in the top table that provides a link and information about a new version of Forces and Motion:Basics (the most recent version implemented w/ parallel DOM)
- A link to a video demonstration of accessibility features using Forces and Motion: Basics, located just below the Forces and Motion: Basics table. Here's a link to the video: https://drive.google.com/file/d/0BwSlILi92RatbC1NbXhBYV9uQVU/view?usp=sharing
Here's some text to go with it: Here is a brief (4 min.) demonstration of keyboard navigation and an introduction to auditory descriptions using our Forces and Motion: Basics simulation.

I'm going to ask @jessegreenberg to write the description for the table (following as similar a structure as possible to Sam's previous descriptions already in the table...but I wanted to check to see if you'd be able to do this before ~10am Wednesday the 14th.

**Comment by aaronsamuel137** [comment]
I can do this if I get the description from @jessegreenberg today. If I get it early enough I can put a dev version on phet-dev for you to review before this evening.

**Comment by jessegreenberg** [comment]
Sure, I will get this to you shortly @aaronsamuel137.

**Comment by aaronsamuel137** [comment]
@emily-phet, here is the new accessibility page on phet-dev: http://phet-dev.colorado.edu/en/about/accessibility

Let me know if you want to change anything. If I don't hear from you I will deploy this to the live site tonight.

**Comment by emily-phet** [comment]
@aaronsamuel137 and @jessegreenberg - everything looks great. Deploy away!
