### ISSUE TITLE
Use https for sim file links on website

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#289]
During 10/15 dev meeting @jonathanolson mentioned that Chrome may deprecate full-screen for non-https pages. To avoid any complications here, it might be better to use https for links to sim files on the website.

See https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins for more info.

Anything else to do here @jonathanolson? If not feel free to assign to me.

**Comment by jonathanolson** [comment]
I think for now, just changing the links is the plan, thanks.

**Comment by aaronsamuel137** [comment]
localizedSimulation.getRunUrl() now returns an https link. Is there anywhere else this should be done that you can think of @jonathanolson?

**Comment by jonathanolson** [comment]
I can't think of anything else off the top of my head. We can always fix anything we miss as we notice later.

Thanks!
