### ISSUE TITLE
Breakdown of users in the database

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#290]
Aaron, Can you please report on the following measures from the PhET database?  

- Number of registered users for who we do not have updated profile information - that people who only have the old fields and not the new fields. 
- Number of registered users for whom we have the new profile fields complete 
- Number of additional email contacts we have for "newletter only" - that are not really full registered users. 

Thanks, K

**Comment by aaronsamuel137** [comment]
The results below are for confirmed users only. It is likely most of the non-confirmed users are spam accounts that will be deleted a month after not confirming.

Number of users who have only the old fields: 57167 (out of 89700)
Number of users who have the new fields complete: 32535 (out of 89700)
Number of newsletter only accounts: 3439

Let me know if you need any additional info.

**Comment by kathy-phet** [comment]
Can you also look at each group of users and tell us how many are listed as "students"? for old field users and then for new field users?

**Comment by aaronsamuel137** [comment]
Old users who are students: 16151 (description is 'I am a student interested in using PhET in the future' or 'I am a student who uses PhET')

New users who are students: 6627

**Comment by aaronsamuel137** [comment]
Anything left to do here @kathy-phet, or is it okay to close this issue?

**Comment by aaronsamuel137** [comment]
Closing for now. We can always reopen if you need more metrics, but I am trying to get to the point of ```assigned issues = to do list```.
