### ISSUE TITLE
Website VM improvements

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#291]
There are a few things that could be improved with the website VM. This is not a high priority issue, but could be a nice thing to work on if you have time @mattpen. 

1. Currently the VM runs in "software rendering mode", which is really annoying. If you can figure out a way to get this to render using the GPU, that would be awesome.
2. The VM is out of date from the live site. We could write a script to automatically update it and sync the database and sim files.

I can take care of number 2 since I have most of this already working for syncing simian to figaro, I just need to adapt it to the VM. Feel free to look into number 1 if/when you have time @mattpen. Comment here about your findings.

**Comment by mattpen** [comment]
@aaronsamuel137 It looks like the VBox Guest Additions are not installed on the VM, which could be causing this issue.  I'll let you know if this fixes it.  https://forums.virtualbox.org/viewtopic.php?f=6&t=66834

**Comment by mattpen** [comment]
OK, this solution worked for me. I'm not getting the popup error about "software rendering mode" anymore.

1. Start VM
2. Devices > Insert Guest Additions CD Image
Run the following commands in the terminal
3. cd /media/phet/VBOXADDITIONS_4.3.30_101610
4. sudo rm -vf /var/lib/apt/lists/*
5. sudo apt-get update
6. sudo apt-get purge virtualbox*
7. sudo bash ./VBoxLinuxAdditions.run
8. Shut Down the guest machine
9. Open Settings>Display in the VBox manager
10. Change Video Memory to >= 128MB
11. Check box for Enable 3D acceleration
12. Start the VM and verify "Software Rendering Mode" error does not popup.

**Comment by aaronsamuel137** [comment]
Awesome! That seemed to fix it, thanks @mattpen!

**Comment by aaronsamuel137** [comment]
Assigning to myself to address number 2.

**Comment by aaronsamuel137** [comment]
I've made a script for syncing the VM to figaro and emailed to @mattpen.

**Comment by aaronsamuel137** [comment]
One more thing to look into here. It looks like apache in the VM is configured in such as way as to not serve files over https. If you try to load a file over https, it says not found.

Can you look into fixing this if you have spare time @mattpen? Low priority.

**Comment by mattpen** [comment]
I configured the VM today to deliver static content over https.  I've also synced the DB and part of the Doc Root with figaro. @jonathanolson should we update the saved copy of the VM image?  I'm not sure where its stored.

**Comment by jonathanolson** [comment]
Sounds great to update it. See /data2/phet-vm/ under simian (figaro-dev).

**Comment by mattpen** [comment]
I uploaded the VM image to that location and saved the previous one as .old.
