### ISSUE TITLE
Dialog box language

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#292]
In response to a teacher email to phethelp we would like to change the text on the sign in dialog from “sign in” to “please sign in to access”. This will ensure that users know why they are seeing a dialog to sign in. However, this should not be the text when a user clicks the sign in button directly.

**Comment by aaronsamuel137** [comment]
Got it, so in every case except clicking the login button directly the text should change?

**Comment by amanda-phet** [comment]
Yes. We tried to think of all the instances where the user gets the prompt to sign in and they all seem to be accessing something (video, document, upload a lesson, translate, etc.) except for clicking the sign in button directly.

**Comment by aaronsamuel137** [comment]
I've made this change. It will be live on the next deploy.

**Comment by aaronsamuel137** [comment]
This is live now. Closing.
