### ISSUE TITLE
Suggestion: Changing labeling ordering of search results when HTML5 sim version exists

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#293]
From @emily-phet 

>I’m making some screencasts for a chemistry PD video, and just noticed that if you search for a sim in the search box, you get a list… and if you click on the name of the sim you just searched for, you get the Java version, not the HTML version. 

>For example, I was searching for Balancing Chemical Equations, and automatically clicked the first option, and got the poo brown Java version. The html version is the second option, listed as “Balancing Chemical Equations (HTML5)”.

>It might make sense to switch the way these are listed now, so that if an HTML version exists, it is listed first and either all have a designation of what kind of sim they are, or the one without a designation is the HTML version.

>Just a thought.

**Comment by ariel-phet** [comment]
@amanda-phet -- this might be worth discussing at a website meeting

**Comment by amanda-phet** [comment]
I think it's pretty straightforward. We've had to request this for the one-at-a-time page (http://phet.colorado.edu/en/get-phet/one-at-a-time) and for the list of sims when submitting an activity. We just need to ask Aaron to do the same for search results.

**Comment by amanda-phet** [comment]
@aaronsamuel137 does this seem like an easy change to make?

**Comment by aaronsamuel137** [comment]
This is definitely easy. I've made the change and it will be live on the next deploy.

**Comment by amanda-phet** [comment]
Thank you!

**Comment by aaronsamuel137** [comment]
Deployed. Closing
