### ISSUE TITLE
Remove job title from edit profile page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#296]
The old version of the team page had the job title for team members come from the job_title field in the phet_user table of the database. The new team page doesn't use this.

The job title field is still marked as required for team members to edit their profile, or another users profile. We should get rid of this.

Assigning to @mattpen. Let me know if you have questions.

**Comment by kathy-phet** [comment]
I think this field may contain what we know about our users who have not updated their profiles yet?? E.g. if they are a student or what not? If that is the case, we will want to keep the field itself and just remove from the team member pages.

**Comment by aaronsamuel137** [comment]
That is correct @kathy-phet. I mean only to remove the field from the edit profile page, not to delete it from the database. Definitely a good thing to make clear for @mattpen.

**Comment by mattpen** [comment]
@aaronsamuel137 I removed the title field on simian.  Can you check and make sure it looks ok?

**Comment by aaronsamuel137** [comment]
Looks good, and seems to work when I test. The only thing I would say is just remove all of the code entirely, don't leave commented out code there.

**Comment by mattpen** [comment]
I removed the code that I had previously commented out.

**Comment by aaronsamuel137** [comment]
Great thanks! I'll test this and close on the next deploy.

**Comment by aaronsamuel137** [comment]
Deployed. Closing
