### ISSUE TITLE
JSON Metadata API

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#297]
For the phet-app and other internal sources (e.g. things that want lists of simulations, or details about simulations, potentially rosetta/build-server/installer/etc.), it would be helpful to have a way of downloading a more closer-to-the-database version of metadata for simulations, and preferably in one (or a few) requests. My current thought is supporting a request that can grab all relevant data in one request, would filter results based on locale, and would ideally be HEAVILY cached on the Varnish layer (since these requests may hit Tomcat fairly hard).

I was imagining something like http(s)://phet.colorado.edu/metadata/v1/simulations, potentially with query parameters:
- format=json: Required for future-proofing, allows for supporting other formats, without having to use HTTP headers to request certain formats.
- summary: If present, would skip most of the simulation record and some of the localized records, including no categories/alignments/keywords. This would mostly be a comprehensive list of sim names/titles with types and versions. If absent, all data is included
- locale=[locale]: Exclude localized simulations and translated strings that aren't of the specified locale (cuts down significantly on keyword/sim record size
- type=[type]: Only include records for 'html' / 'java' / 'flash', excluding projects of the other types
- (possibly) simulation=simName: Exclude simulations without this name (and projects that don't have simulations with that name). This would presumably show both hits for Java/HTML or Flash/HTML sims, like molarity or wave-on-a-string, but would increase the number of unique metadata URLs that would/should/could get cached.

e.g.:
http://phet.colorado.edu/metadata/v1/simulations?format=json&summary - List of projects/sims with info for all locales.
http://phet.colorado.edu/metadata/v1/simulations?format=json&type=html&locale=en - Metadata for all HTML sims, with details but just English strings/sim translations. This is presumably what the phet-app would use.

There are a few high-level options for providing a lot of data at once (in a small number of requests):

Option 1 (inline sims/localizedSims instead of with IDs, but leave categories/alignments/keywords out, e.g. things that would be duplicated):
```js
{
  projects: [
    {
      ... project data ...
      simulations: [ // OR indexed by name
        {
          ... simulation data ...
          localizedSimulations: [ // OR indexed by locale string
            {
              ... localizedSimulation data
            }
          ]
        },
        ...
      ]
    },
    ...
  ],
  categories: [ ... ],
  alignments: [ ... ],
  keywords: [ ... ]
}
```

Option 2 (top-level arrays included in filters):
```js
{
  projects: [ ... ], // Arrays OR indexed by IDs
  simulations: [ ... ],
  localizedSimulations: [ ... ],
  categories: [ ... ],
  alignments: [ ... ],
  keywords: [ ... ]
}
```

I currently prefer option 1 for client usage, but thought I'd mention option 2, as it makes lookup-by-ID easier.

Translated string record:
```
{
  en: {string} -- English string,
  <locale>: {string} -- string for locale,
  ...
}
```

Project record (presumably showing only visible projects?):
```
{
  id: {number} Project.id,
  name: {string} Project.name,
  type: {string} Project.type mapped to 'java', 'flash', 'html',
  version: {
    string: {string} -- pretty printed version, e.g. Project.getVersionString(),
    major: {number} Project.versionMajor,
    minor: {number} Project.versionMinor,
    dev: {number} Project.versionDev -- it's basically the HTML sim maintenance version, is 0 for Java/Flash,
    revision: [optional] {number} Project.versionRevision -- SVN rev for Java/Flash,
    timestamp: {string} Project.versionTimestamp -- ISO 8601 timestamp
  },
  simulationIds: {Array.<number>} Simulation IDs  -- OR inline Simulation records
}
```

Simulation record:
```
{
  id: {number} Simulation.id,
  name: {string} Simulation.name,

  projectId: {number} Project ID -- OR skip this if inlined under a Project record,

  // If 'summary' query parameter, exclude below here

  fileSize: {number} Simulation.kilobytes,
  credits: {
    designTeam: {string} Simulation.designTeam,
    libraries: {string} Simulation.libraries,
    thanksTo: {string} Simulation.thanksTo
  },
  videoUrl: {string} Simulation.videoUrl,

  lowGradeLevel: {string} Simulation.lowGradeLevel -- enumeration toString,
  highGradeLevel: {string} Simulation.highGradeLevel -- enumeration toString,

  createTime: {string} Simulation.getCreateTime() -- ISO 8601 timestamp,
  updateTime: {string} Simulation.getUpdateTime() -- ISO 8601 timestamp,

  simPageUrl: {string} See MetadataUtils.scala for <simPageLink>
  thumbnailUrl: {string} Simulation.getThumbnailUrl() -- absolute though,
  screenshotUrl: {string} Simulation.getImageUrl() -- absolute though,

  description: {Translated string},
  learningGoals: {Translated string},

  licenseUrls: {Array.<string>} Simulation.getLicenseURLs(),

  localizedSimulationIds: {Array.<number>} LocalizedSimulation IDs -- OR inline Localized simulation records,

  categoryIds: {Array.<number>} Category IDs -- NOTE that categories with 'auto' should be included,
  alignmentIds: {Array.<number>} Alignment IDs,
  secondaryAlignmentIds: {Array.<number>} Alignment IDs,
  scienceLiteracyMapKeys: {Array.<string>} Simulation.scienceLiteracyMapKeys,
  lreTerms: {Array.<{ id: {string}, englishCaption: {string} }>} - Simulation.getLRETerms(),

  keywordIds: {Array.<number>} Keyword IDs,
  topicIds: {Array.<number>} Keyword IDs,

  relatedSimulationIds: {Array.<number>} Simulation IDs. Note that if filters are applied, sims here may not be included in the request,

  // no contributions for now?
}
```

Localized Simulation record:
```
{
  id: {number} LocalizedSimulation.id,
  locale: {string} LocalizedSimulation.locale,
  title: {string} LocalizedSimulation.title,

  simulationId: {number} Simulation.id -- OR skip this if inlined under a Simulation record,

  // If 'summary' query parameter, exclude below here

  runUrl: {string} LocalizedSimulation.getHTTPSRunUrl(),
  downloadUrl: {string} LocalizedSimulation.getDownloadUrl(),
}
```

Category/Alignment/Keyword records would also be provided if not in "summary" mode:

Category record:
```
{
  id: {number} Category.id,
  name: {string} Category.name,
  parent: {number|null} Category.parent,
  childrenIds: {Array.<number>} Category.subcategories -- use category IDs,
  simulationIds: {Array.<number}> Category.simulations -- use simulation IDs. NOTE: categories with 'auto' should report sims like normal here
}
```

Alignment record:
```
{
  id: {number} Alignment.id,
  url: {string} Alignment.url,
  framework: {string} Alignment.framework -- enum toString()
}
```

Keyword record:
```
{
  id: {number} Keyword.id,
  key: {string} Keyword.key,
  strings: {Translated String}
}
```

MetadataUtils.scala may be a good reference (contains conversion of data to phet-master XML format) for some implementation details.

@aaronsamuel137, @jbphet, @samreid, @pixelzoom thoughts?

**Comment by aaronsamuel137** [comment]
I like approach 1 as well (inlining the simulations and localized simulations).

Some other things to think about:

1. Do we want to implement some kind of API key here, or is it okay to make this public? I personally think public is fine, especially if it is heavily cached to reduce the load on tomcat.
2. There are probably other third parties who would want to use this API. Should we get input from them first? (Notably, Go-Labs would want to use this API, see https://github.com/phetsims/tasks/issues/400)

**Comment by kathy-phet** [comment]
The metadata is part of our licensing discussions with some clients, so best not to make public. We can handle access via a password of some sort?

Sent from my iPhone

On Oct 27, 2015, at 10:25 AM, Aaron Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


I like approach 1 as well (inlining the simulations and localized simulations).

Some other things to think about:

  1.  Do we want to implement some kind of API key here, or is it okay to make this public? I personally think public is fine, especially if it is heavily cached to reduce the load on tomcat.
  2.  There are probably other third parties who would want to use this API. Should we get input from them first? (Notably, Go-Labs would want to use this API, see phetsims/tasks#400<https://github.com/phetsims/tasks/issues/400>)

-

**Comment by jonathanolson** [comment]
> The metadata is part of our licensing discussions with some clients, so best not to make public. We can handle access via a password of some sort?

Could you clarify? We've had public metadata in other formats for a while (which includes the data we would be making available here), and if the PhET App uses the API, it would be fairly trivial for someone to use the PhET App credentials for it. Would we want to remove our current metadata APIs/exports?

**Comment by aaronsamuel137** [comment]
Sounds like the phet-app team might need something to work with soon. Adding developer meeting label to get more feedback before doing any more work on this.

**Comment by pixelzoom** [comment]
I don't have experience with the use cases for this, so don't have an feedback. Hopefully this doesn't need to be private, since that sounds like a huge pain.

**Comment by arnopoulos** [comment]
@jonathanolson I think I know where you're getting at with the API proposal. However is there a time, next week, where we can meet up in person to talk about some of the intricacies of your proposal? Just so I can make sure that I'm on the same page that your on.

**Comment by arnopoulos** [comment]
@aaronsamuel137 @ariel-phet Could you also guys also join the meeting?

**Comment by aaronsamuel137** [comment]
Yep I can come to the meeting, or you can email or Skype me if you have questions.

I'll be the primary implementer of the API, so I can iterate with you if you need things to change as we go or unanticipated needs arise.

**Comment by aaronsamuel137** [comment]
Also, if you want something to work with ASAP, I can deploy the incomplete version of the API to our dev site at any time. It probably has most of what you will need already if you are just looking to get the sim names and links.

**Comment by ariel-phet** [comment]
@arnopoulos yes happy to attend, please email me when you know the time.

**Comment by jonathanolson** [comment]
I should be free Monday/Tuesday/Wednesday all before 1pm. What works for everyone else?

**Comment by ariel-phet** [comment]
I should be fairly flexible before 1 pm those days

**Comment by aaronsamuel137** [comment]
Any of those times works for me except after 11:30 on Wednesday.

**Comment by arnopoulos** [comment]
I can meet up on Tuesday at that time. Does that work for everyone?

**Comment by arnopoulos** [comment]
Sorry for this but something for work came up tomorrow and I can't get out of it. I might be able to meet up on Wednesday but I have to make sure first.

**Comment by jonathanolson** [comment]
I'm personally sick right now, and probably won't be able to meet in person through Wednesday. Will be available on Skype, so let me know what is convenient.

**Comment by arnopoulos** [comment]
@jonathanolson I'm sorry to here about that and I hope you get better soon. However some of the questions I had could be answered here.
1. What is the difference between Projects and Simulations?
2. Why are the categories, alignments and keywords outside of the projects scope?

**Comment by aaronsamuel137** [comment]
I can probably answer these questions, @jonathanolson feel free to clarify or add things to my answer.

1. Projects are basically wrappers around simulations that contain information about versioning and timestamps. In the Java sims, a single project could have more than one simulation associated with it, such as circuit construction kit, which has many variations. In the html5 simulations, there is always just one project per sim. The sims are stored at /sims/[project-name]/[simulation-name]_[locale] on the server, for instance: https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-ac_af.jnlp. For the purposes of the phet-app, you probably won't need to worry too much about projects, you can just iterate over them and get the simulation info you need.
2. I think these are outside the project scope to avoid lots of duplication. Many sims share keywords and categories, so just listing the ids will keep the size of responses from the API smaller, instead of duplicating each keyword entry across many sims.

**Comment by aaronsamuel137** [comment]
@arnopoulos, I have implemented this and deployed to phet-dev so you guys can test and we can iterate on the design if necessary.

You'll probably want this address for the app: http://phet-dev.colorado.edu/services/metadata-api?format=json&type=html

Let me know how it works for you and if you have questions or suggestions.

**Comment by aaronsamuel137** [comment]
Still left to do here:

1. Varnish configuration. We need to worry about timeouts for large requests and caching and cache invalidation.
2. Authentication. Still haven't heard from @kathy-phet as to whether or not this can be public.
3. Design improvement. Let's try this and see if we want to make any changes.

**Comment by aaronsamuel137** [comment]
The new API file has been merged into master (MetadataAPI.java), but it is commented out as a route in PhetWicketApplication because the three remaining items in the above comment are not yet taken care of.

Assigning to @jonathanolson since he will be taking this issue over after I leave.

**Comment by jonathanolson** [comment]
We should also use this API for build-server to determine what the currently published translations of an HTML5 sim are.

**Comment by erudat** [comment]
@jonathanolson the address Aaron provided for the API does not seem to be working.

**Comment by ariel-phet** [comment]
@mattpen since you have been doing lots on phet-dev is it possible for you to track down the address for the API?

**Comment by mattpen** [comment]
@ariel-phet The URL is correct but Aaron removed it from publication for the following issues (see above):

> 1. Varnish configuration. We need to worry about timeouts for large requests and caching and cache invalidation.
> 2. Authentication. Still haven't heard from @kathy-phet as to whether or not this can be public.
> 3. Design improvement. Let's try this and see if we want to make any changes.

(2) Is really the only concern for publication on phet-dev.  If its OK to publish it please confirm and reassign to me.

**Comment by ariel-phet** [comment]
@mattpen please go ahead and publish on phet-dev, we can figure out an alternative later if @kathy-phet decides for this not to be public in the long run, but I think there is low risk for the moment on phet-dev and the app teams needs access to make progress.

**Comment by arnopoulos** [comment]
@mattpen We can work on ways to decrease timeout too. If you want we can meet up sometime this week, or next week, to talk about how we can improve load times.

**Comment by kathy-phet** [comment]
We discussed it last week, and decided OK to have this API public. 
K

**Comment by jonathanolson** [comment]
Yes, publishing to phet-dev sounds good. It's also on my list to review, and try to figure out how to handle (1) nicely.

**Comment by mattpen** [comment]
This has been published on phet-dev.  The URL above may take a long time to load, this one has a much shorter load time if you want to verify that it is working.  http://phet-dev.colorado.edu/services/metadata-api?format=json&type=html&summary=true&locale=en

**Comment by arnopoulos** [comment]
@mattpen Is there a way to specify multiple locales? If not is there any particular reason why the value for "localizedSimulations" is an array rather than just an object? Also could you provide the route that will allow us to gather the metadata for a particular simulation?

**Comment by mattpen** [comment]
@arnopoulos As of today, you can only request one locale.  If you omit the argument you will receive all of them, which is why its stored in an array.

As of now, there is no parameter for requesting a particular sim.  The simulation=simName route has not been implemented yet.

**Comment by arnopoulos** [comment]
@mattpen That makes sense. I just wanted to make sure that there was a justification for it.

**Comment by jonathanolson** [comment]
I'll be reviewing the code soon, and I'll be able to flesh out the implementation (like that feature) and also work in improving performance (it seems quite slow).

**Comment by arnopoulos** [comment]
@jonathanolson In terms of the application, I don't believe that there will be a time where we will need access to more than one localization at a time.

**Comment by mattpen** [comment]
Discussed with the phet-app team on 2/1/2016.  It was requested to implement a method of requesting the full data for a single sim by id.  My suggestion was to add an additional query parameter, Andrew suggested to add a separate URI route.

@jonathanolson - Do you forsee any performance concerns implementing this in tomcat?  The reason they requested it is to improve performance of the app on the ipad itself.

**Comment by arnopoulos** [comment]
@mattpen @jonathanolson To add to that we are only planning on updating the simulations every 24 hours. I've never used varnish but you should be able to set the cache invalidation time to be 24 hours.

**Comment by mattpen** [comment]
Tagging developer meeting to discuss whether this can be deployed to figaro (possibly hidden with robots.txt?).  As this is currently deployed to phet-dev, it will be unavailable whenever I am using phet-dev to test the master branch.

The performance concerns mentioned above also warrant further discussion.

**Comment by jonathanolson** [comment]
> @jonathanolson In terms of the application, I don't believe that there will be a time where we will need access to more than one localization at a time.

Sounds good, presumably the locale query parameter has been implemented?

> It was requested to implement a method of requesting the full data for a single sim by id. My suggestion was to add an additional query parameter, Andrew suggested to add a separate URI route.

I suggested the query parameter for specifying a simulation in my original specification (below). What of these query parameters are implemented?

> I was imagining something like http(s)://phet.colorado.edu/metadata/v1/simulations, potentially with query parameters:
> 
> format=json: Required for future-proofing, allows for supporting other formats, without having to use HTTP headers to request certain formats.
> summary: If present, would skip most of the simulation record and some of the localized records, including no categories/alignments/keywords. This would mostly be a comprehensive list of sim names/titles with types and versions. If absent, all data is included
> locale=[locale]: Exclude localized simulations and translated strings that aren't of the specified locale (cuts down significantly on keyword/sim record size
> type=[type]: Only include records for 'html' / 'java' / 'flash', excluding projects of the other types
> (possibly) simulation=simName: Exclude simulations without this name (and projects that don't have simulations with that name). This would presumably show both hits for Java/HTML or Flash/HTML sims, like molarity or wave-on-a-string, but would increase the number of unique metadata URLs that would/should/could get cached.

> Do you forsee any performance concerns implementing this in tomcat?

It seems fine, but we'll probably want to investigate how many DB queries the process is making. Ideally it should just have a few, so performance wouldn't be a concern either way. I suspect it's making tons of DB queries. 

This can be debugged by running on a VM with the following commented out tag in log4j.properties:
```
#log4j.logger.org.hibernate.SQL=debug
```

**Comment by pixelzoom** [comment]
2/4/16 dev meeting: @mattpen and @jonathanolson will discuss this.

**Comment by mattpen** [comment]
@jonathanolson 

> presumably the locale query parameter has been implemented?

Yes, Aaron implemented this.

> I suggested the query parameter for specifying a simulation in my original specification (below). What of these query parameters are implemented?

This was the only query parameter that had not been implemented by Aaron.  I implemented a query parameter by project id, as in the current structure the project is basically a wrapper for the simulation and contains information which is probably useful, type for example.

> we'll probably want to investigate how many DB queries the process is making.

It was making upwards of 27,000 queries and was taking 38 minutes to complete in the worst case situation (locale, type, and summary not specified in the parameters, 2nd level cache not initialized).  I batched the keyword queries which eliminated 20,000 queries and reduced the response time to 12 seconds in the worst case and 5 seconds on average.  I'll keep investigating improvements as there are still several thousand possibly duplicated queries.

I also found a bug where the response was showing all simulations, not just the visible projects/sims, and fixed it.

**Comment by jonathanolson** [comment]
> I implemented a query parameter by project id

Lots of our code only knows "it's an HTML sim called molarity", and doesn't know about its project ID. How would that code query the API to get data for that sim?

> reduced the response time

Sounds great! Let me know if there are things I can help with.

**Comment by mattpen** [comment]
@jonathanolson 

> Lots of our code only knows "it's an HTML sim called molarity"

As the project is wrapping the simulation, this seems difficult with the current structure.  Does the project name always contain what the sim thinks it's name is, or are there exceptions?

If so, I could change the query from `project.id = :id` to ```project.name like '%:name%' ```

**Comment by mattpen** [comment]
If a request is received for a specific sim, should we limit the contents of category, keyword, and alignment to only the objects relevant to the sim?

**Comment by jonathanolson** [comment]
> Does the project name always contain what the sim thinks its name is, or are there exceptions?

Project and sim names can look totally different, and I wouldn't try substring comparisons. We would want to filter simulations by their name, e.g.:

- http://phet.colorado.edu/metadata/v1/simulations?format=json&type=html&simulation=molarity would just show the entry for HTML Molarity. The category/keyword/alignment entries shouldn't include extras not used by the simulation data returned.
http://phet.colorado.edu/metadata/v1/simulations?format=json&simulation=molarity would include both the Java and HTML entries for Molarity.
http://phet.colorado.edu/metadata/v1/simulations?format=json&simulation=density would include just the Flash Density simulation, and NOT the Buoyancy sim (which is in the same project).

**Comment by mattpen** [comment]
I implemented the query by simulation name, as well as cleaned up some of the other queries.  The full request is now down to ~1500 queries served by tomcat in about 4 seconds.  I removed the "pretty printing" from the response which reduced the size from 6.2MB to 4.7MB.  The original view is still available with the query parameter `debug`, but I assume we'll want to disable this if/when it is deployed to figaro.  I also restricted the Alignment, Category, and Keyword objects when a specific sim is requested.

I've published the updates to phet-dev to test.

@jonathanolson - If you have time to do a code-review I'd appreciate it.

**Comment by jonathanolson** [comment]
Assigned for code review.

**Comment by mattpen** [comment]
<h4>Summary of differences from initial specification</h4>

Not Implemented Yet:
- Varnish caching
- Simulation.relatedSimulationIds

Changed:
- URL: changed from /metadata/v1/simulations to /services/metadata-api
- Query parameter: "simulation=simName", changed to "name=simName"
- Option 1 was used ( nested projects > simulations > localizedSimulations rather than parallel )
- Project.simulationIds changed to Project.simulations with inline records
- Simulation.videoUrl is optional ( missing if it doesn't exist )
- Translated string record was implemented as 
```
[ 
  {locale: 'en', string: 'english string value' },
   ...
]
```

**Comment by mattpen** [comment]
@arnopoulos @jonathanolson - The metadata API is now available on the main site, so it should be up with near-100% reliability.  There were a few breaking changes made tonight that may affect the code for the phet-app.

1. The URL will now be: https://phet.colorado.edu/services/metadata/1.0/simulations?
2. The `name` parameter has been changed to the `simulation` parameter.
3. The structure of the keywords has changed to match the specification for Translated strings in the first comment in this thread, i.e.:

```
{
  en: {string} -- English string,
  <locale>: {string} -- string for locale,
  ...
}
```

**Comment by mattpen** [comment]
Requested changes from phet-app team:

Within the simulation object, categories and grade levels should be embedded directly in the simulation   as arrays.  Categories are currently stored as an array of reference ids.  Grade level is currently stored as a lowest/highest values and within the category ID .

Ostensibly the simulation object would be changed as follows:

```
{
    ...
    gradeLevels: [
        "ELEMENTARY",
        ....
    ],
    categories: [
        "physics",
        "html",
        ....
    ],
    ...
}
```
@jonathanolson - Do you see any issues with implementing this change?  I'm worried that it will require a significant number of extra database calls.

**Comment by mattpen** [comment]
Discussed at dev meeting on 4/21.

I can make the categories object more easily accessible by changing it from an array to an object accessed by id, as follows:

```
categories: {
  '3': {
    id: 3,
    name: 'new',
    ...
  },
  ...
}
```

The grade level changes can be put off for now as its not a high priority.

I'll contact the phet-app team to follow up.

**Comment by mattpen** [comment]
The changes in categories object were implemented and published on figaro.

Here is the new structure:
```
{
  ...,
  categories: {
    'categoryId': {
      id: {number} Category.id,
      name: {string} Category.name,
      parent: {number|null} Category.parent,
      childrenIds: {Array.<number>} Category.subcategories
      simulationIds: {Array.<number}> Category.simulations
    },
    ...
  },
  ...
}
```

This is to enable faster lookup for categories by id, i.e. `categories['categoryId']`

**Comment by mattpen** [comment]
Metadata API is in a stable state.  Further improvements will require versioning to maintain compatability with the phet-app.

**Comment by kathy-phet** [comment]
@mattpen - Please do make a markdown file with documentation for API use. Thanks! 
Medium priority.

**Comment by mattpen** [comment]
New issue was created for documentation, closing.
