### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#298]
At the 10/28 website meeting we decided to move forward with a new design for the sponsors page (http://phet.colorado.edu/en/about/sponsors). This may be something that @mattpen could tackle, but it is not a top priority. 

The design will be based off of Dave's design in https://github.com/phetsims/tasks/issues/345. We also will have @elisemorgan working to find updated logos and links for sponsors. 

The specifications for logos should be similar to what we have on sim pages: all logos should fit within a maximum height (I don't recall exactly what that height is on sim pages) and possibly a maximum width (if there is an oddly short but wide logo we can go from there). 

Here is a mockup that shows how we will incorporate the current elements of the website with the changed layout proposed by Dave. 
<img width="566" alt="screen shot 2015-10-28 at 5 49 04 pm" src="https://cloud.githubusercontent.com/assets/7852916/10806603/4f601422-7d9c-11e5-985b-1aaed9db839f.png">

**Comment by aaronsamuel137** [comment]
Looks great! Between @mattpen and I, we should be able to get to this fairly soon. We'll just need to get the updated logos after https://github.com/phetsims/tasks/issues/347 is completed. Perhaps we should store these in a drive folder?

**Comment by amanda-phet** [comment]
Awesome! Elise should be putting them in a drive folder as well as making a spreadsheet with links. I'll update you when we have the logos and correct links.

**Comment by kdessau-PhET** [comment]
And we should update the list as some have not sponsored recently. Maybe we can have a list of "honor roll" sponsors or something like "Past Donors." If you need updated links, let me know and I can help.

**Comment by aaronsamuel137** [comment]
Feel free to start on this any time @mattpen. I would work on a branch instead of master in case there are things with the sponsors that delay us in getting this deployed.

**Comment by mattpen** [comment]
I updated the table format to match the screenshot from above.  I can push it to phet-dev if anyone wants to see the changes.

**Comment by amanda-phet** [comment]
Yes please!

**Comment by mattpen** [comment]
@amanda-phet The new sponsors page is up on phet-dev. Can you take a look and let me know if you have any feedback?

**Comment by amanda-phet** [comment]
It looks great! It came out really nicely. 

Just one question- the "platinum level" title seems larger than the usual 3rd-level heading. It's important to me that we use the site's standard css so that down the road when we make changes to it we do not need to go to individual pages to change it. 

Otherwise I think it looks very good.

**Comment by mattpen** [comment]
@amanda-phet - These headings were just tagged as bold text, not 3rd level headers.  I'll change them to h3 on the next deploy to phet-dev.  Thanks!

**Comment by amanda-phet** [comment]
Perfect!

**Comment by amanda-phet** [comment]
@arouinfar pointed out a mistake in the CU logo. I will upload the correct version to the folder now. Also, there is a typo in "William" in the first listed sponsor.

**Comment by kdessau-PhET** [comment]
One question...did Amplify donate? I don't have anything on my records. Also, do we want to update them. Some of the people haven't donated in a while. We could remove them or move them to an previous donors list?

**Comment by amanda-phet** [comment]
@kdessau-PhET There was a note from @elisemorgan : Wireless Generation **has been renamed Amplify** Does that seem accurate to you? 

We are not reviewing the list for current or past... It would be great if you and @kathy-phet reviewed the list and suggested changes. However, we will not be changing it for the purposes of redesigning this page, but the content can always be changed in the future!

**Comment by kdessau-PhET** [comment]
I hadn't heard that but Wireless Generation did give once. Kathy P., I know that we've revisited as to how deal with sponsors who have given in the past, but have stopped. Do we want to hold off on this until after we get some "partners"?

**Comment by mattpen** [comment]
@amanda-phet I updated the third level headers on phet-dev.  Do they look ok now?

**Comment by amanda-phet** [comment]
Thank you! 

I'm not as concerned about the look, just the consistency. One day I will ask you to change h1, h2, and h3, and am hoping every page will change together :)

**Comment by amanda-phet** [comment]
Three changes that still need to be made: 
- CU logo (in drive) needs updating
- W.W. Norton logo (in drive) needs updating 
- Amplify needs to go back to Wireless Generation (updated on drive spreadsheet)

**Comment by mattpen** [comment]
@amanda-phet These changes have been completed and pushed to phet-dev.

**Comment by amanda-phet** [comment]
Logos look good. Wireless Generation currently links to phet-dev, so we should remove that and just leave it with no link. 

Once that is done I think you can deploy it to figaro!

**Comment by amanda-phet** [comment]
Hey @mattpen . It seems like there is not much left to do on this page. Is there anything left to do other than change the Wireless Generation link?

**Comment by mattpen** [comment]
@amanda-phet That's the only thing left that I can think of.  I'll fix that today.  The changes to this page got intertwined with the new help-center, so I'm waiting to deploy to the main site until the help-center's initial roll out, but it should be ready to go soon.

**Comment by mattpen** [comment]
As there was some confusion, I'm clarifying which of the in-progress website changes are dependent on each other.  
This change is dependent on the help-center.  It will be deployed at the same time as the help-center.

**Comment by mattpen** [comment]
This was deployed to the main site tonight (finally!).

**Comment by kathy-phet** [comment]
Sponsor page looks much improved! But I noticed that some of the images took a very long time to load. 

Can we resize these images so that they are just a bit higher resolution than what we need at 100%, and so suit most zoomed in levels. This would ensure they load fast and do not use too much unnecessary bandwidth? The KSU one for instance is huge. 

Perhaps one of the undergrads, or Steel could take this on?

**Comment by mattpen** [comment]
@ariel-phet - who should this be reassigned to?  I can do the resizing if needed.

**Comment by kdessau-PhET** [comment]
@mattpen @ariel-phet the Spectroscopy Society of Pittsburgh (Pittcon conference people) have generously donated $2000. We need to add them to our sponsors list and also on the featured sponsor weighted as 1.
Let me know when this is done so that I can let John from Piton know it's up. 
![ssprainbowlogo](https://cloud.githubusercontent.com/assets/10424210/12159832/fc6564d2-b4a2-11e5-83f4-4803c66c1e83.jpg)
![ssprainbowlogo sm](https://cloud.githubusercontent.com/assets/10424210/12159834/fc7aeed8-b4a2-11e5-834c-7dd9da561298.jpg)
![ssprainbowlogolg](https://cloud.githubusercontent.com/assets/10424210/12159833/fc79cdd2-b4a2-11e5-8fe4-1949286ed1d4.jpg)

**Comment by ariel-phet** [comment]
@mattpen can you create an issue in "tasks" for the re-sizing and assign it to me for now.

Please include relevant info (where to find the logo files, or if you need to upload them to google drive or such), and the approximate resolution (pixel x pixel) to which they should be changed,

**Comment by mattpen** [comment]
@kdessau-PhET The SSP info is now up on the About Sponsors page and in the Featured Sponsor rotating banner on the main site.  Does it look ok to you?

**Comment by mattpen** [comment]
This has been deployed to figaro.  Closing.
