### ISSUE TITLE
Some changes to the front page/banner

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#300]
@aaronsamuel137 and @mattpen we would like to make some changes to the front page and sitewide banner to continue making the site more cleanly. Obviously this work should first be done on phet-dev and then migrated to the main site once all polishes are complete.

This work should be a fairly high priority as the main point of this change is to encourage more teachers to register for the site (so the action of hitting the "teachers register here" should be the same as hitting the register button in the banner)

[Teacher_registration_v3.pdf](https://github.com/phetsims/website/files/25637/Teacher_registration_v3.pdf)

**Comment by ariel-phet** [comment]
This checklist might prove useful in making the various changes:

- [ ] remove "mini banner" this may mean increasing the vertical size of the navy blue banner to give the correct padding
- [ ] move the "over 200 million simulations delivered" text out of the banner on under the "Interactive Simulations for Science and Math"
- [ ] Remove social media icons to the right of the video player
- [ ] Change the CU logo mark to the single line mark, match the size shown in the mockup, and move in line with the search bar
- [ ] Make new "play with simulations" and "Teachers Register Here" buttons (text should be internationalized of course) Buttons should be "flat style"
- [ ] in the table of links, make the top bar gray (match the mockup) and move the donate button over the last column
- [ ] also note the "tech awards" logo has been removed

**Comment by ariel-phet** [comment]
@amanda-phet and @amyh-phet should be able to provide any assets you needs (such as the play with sims and the Teacher icon)

**Comment by aaronsamuel137** [comment]
I can work on this today. @amanda-phet or @amyh-phet can you email me these new icons? Thanks!

**Comment by amyh-phet** [comment]
@aaronsamuel137    Emailing AI file to you now.

**Comment by amanda-phet** [comment]
I will be emailing you the official CU logo as well.

**Comment by aaronsamuel137** [comment]
Sorry I wasn't clear. Can you just send 2 svg files with the icons only (the play with sims button icon and the teachers register icon)? I don't need the ai mockup of the whole page. Thanks!

**Comment by amyh-phet** [comment]
Sorry - first time I got to send artwork to a developer.  Thanks for your patience.

**Comment by aaronsamuel137** [comment]
OK I've deployed iteration 1 to phet-dev. Some things that will probably need to be addressed:

1. We might need a new graphic for teachers register button. As you can see when you highlight over it, it is inconsistently white and transparent background.
2. We'll probably need new images for the right facing triangles since these look crappy and have a different background color.

Let me know about any other pixel polished or changes that should be made here.

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
1. @amyh-phet can update the graphic. We probably didn't realize there was a white stroke there! 
2. Can we get rid of the triangles?

**Comment by ariel-phet** [comment]
We may have to do something different than grey for the Play with simulations button, but overall this is look SO MUCH cleaner. @amanda-phet - maybe one of the other quilting bee colors for the background of that button?

@aaronsamuel137 on the "Donate Today" button the font looks a bit different than on the "Sign In" button...looks maybe larger and not bold to my eye?

**Comment by amanda-phet** [comment]
@ariel-phet I agree, I'm not a huge fan of the gray. There is also a lot of gray on the homepage now... @amyh-phet suggested we look at this in today's website meeting, so we will bring some different options to compare.

**Comment by amyh-phet** [comment]
@aaronsamuel137   With the arrows, it looks to me like the blue background color from the original table is showing on the top and bottom of the arrow, almost like the color is filling in a space around the arrow.   If we have to leave the arrow, is there a way to fix this?
![arrow_issue](https://cloud.githubusercontent.com/assets/13650180/10948559/65e5dbf6-82eb-11e5-9784-854023f5f8b9.png)

**Comment by amanda-phet** [comment]
We decided to go with raspberry colors... @amyh-phet or I can send you artwork for the icons. 

![screen shot 2015-11-04 at 1 43 07 pm](https://cloud.githubusercontent.com/assets/7852916/10951316/11bebb2e-82fa-11e5-8f7f-4c98bff089b4.png)

**Comment by aaronsamuel137** [comment]
Raspberry sounds good. Feel free to send the icons any time. Also, try to get make so there is not extra empty space around the icons if you can.

If you know the color hex value, and values for the highlight colors, that would be helpful too.

Thanks!

**Comment by amanda-phet** [comment]
![screen shot 2015-11-06 at 3 34 37 pm](https://cloud.githubusercontent.com/assets/7852916/11010447/1f124806-849c-11e5-933f-be587ed0298a.png)

When the cursor hovers: 
![screen shot 2015-11-06 at 3 35 29 pm](https://cloud.githubusercontent.com/assets/7852916/11010451/23c48666-849c-11e5-88a0-c6f04d91beb1.png)

Since this button is a little different, @amyh-phet and I decided the highlight color can be used but we should also underline the text. (Underlining text is probably something we will do more of in the future...) 
![screen shot 2015-11-06 at 3 35 59 pm](https://cloud.githubusercontent.com/assets/7852916/11010453/275d1374-849c-11e5-9098-10192456a202.png)

Hex colors for the buttons: 
Default: c1477a
Highlight: d66ea2

**Comment by aaronsamuel137** [comment]
The latest design changes are up on phet-dev now. Let me know what you think @amanda-phet.

**Comment by amanda-phet** [comment]
Looks good to me, and I think everything on the checklist was addressed. @ariel-phet ?

**Comment by aaronsamuel137** [comment]
One detail to consider is the tab focus color for the table headers. Previously, the browser defaults were overridden to use a white focus. Does this still look good to you guys? Should we consider going back to browser defaults?

**Comment by ariel-phet** [comment]
The white focus looks very clear to me...I say deploy.

**Comment by amanda-phet** [comment]
I like the white. I might keep white around the Donate Today button as well.

**Comment by aaronsamuel137** [comment]
Sounds good. I'll add it to the donate button and deploy tonight.

**Comment by aaronsamuel137** [comment]
This is live! Closing
