### ISSUE TITLE
Translated sims should indicate if HTML5

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#302]
I noticed that if you click on all sims in a language (such as brazillian portuguese), the translated HTML5 sim name does not say (HTML5) at the end. In the long-term it seems like it would be a good idea to have this extension on the title. 

![screen shot 2015-11-03 at 1 12 46 pm](https://cloud.githubusercontent.com/assets/7852916/10920428/32e512b2-822d-11e5-8935-fa25e32e101d.png)

**Comment by kathy-phet** [comment]
What about a small icon?

Sent from my iPhone

On Nov 3, 2015, at 1:18 PM, Amanda McGarry <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed that if you click on all sims in a language (such as brazillian portuguese), the translated HTML5 sim name does not say (HTML5) at the end. In the long-term it seems like it would be a good idea to have this extension on the title.

[screen shot 2015-11-03 at 1 12 46 pm]<https://cloud.githubusercontent.com/assets/7852916/10920428/32e512b2-822d-11e5-8935-fa25e32e101d.png>

-

**Comment by amanda-phet** [comment]
@kathy-phet I've been thinking about icons too... there are many places on the site where we could implement this.

**Comment by aaronsamuel137** [comment]
Should I go ahead with this or wait on the icons? Also, given that this is part of the translated title, should this string be translatable?

**Comment by amanda-phet** [comment]
Go ahead with (HTML5). Icons may come later but for now that is the paradigm we are using. 

@ariel-phet should the string be translatable? I don't know for sure where this would fall.

**Comment by ariel-phet** [comment]
Yes, I think the string should be translatable

**Comment by ariel-phet** [comment]
@aaronsamuel137 please comment on how involved this would be, seems like a pretty easy change?

**Comment by aaronsamuel137** [comment]
This is easy. I've implemented it and will deploy soon.

**Comment by aaronsamuel137** [comment]
This is live. Closing
