### ISSUE TITLE
Get a Hooke's Law video for scrolling video player

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#303]
@arouinfar I think it might be nice to record a short clip for Hooke's Law to put on the front page video player, that seems like a place where we should start having new sims highlighted when they come out.

Not a huge priority, but seems like something that could be done with ease in the nearish future

**Comment by arouinfar** [comment]
Great idea, @ariel-phet! Is there any particular file format or aspect ratio I need to use? I was planning on  doing a QuickTime recording (.mov) at the regular dev ratio.

**Comment by ariel-phet** [comment]
@aaronsamuel137 can you give @arouinfar specs?

**Comment by aaronsamuel137** [comment]
Ideally we want 326 × 214 .mp4 files.

**Comment by arouinfar** [comment]
@aaronsamuel137 Thanks! I can use Camtasia to make an .mp4 recording at that resolution.

**Comment by aaronsamuel137** [comment]
If you can export as a .ogv too at the same resolution that would be useful. Firefox needs ogv as a fallback. I have a script that can do this if you can't, but probably better to find a solution that doesn't rely on my script, so we should see if camtasia can do this.

We also need a .jpg of the same resolution for a fallback if video is not supported. Any frame of the video will do.

**Comment by arouinfar** [comment]
Thanks for this info @aaronsamuel137. Not sure if I can create an .ogv, but I'll look into it.

**Comment by arouinfar** [comment]
@aaronsamuel137 I was not able to resize my browser to 326 × 214. The minimum resolution I was able to use was 798 x 524, which has the same aspect ratio. 

I also couldn't find a way to export to .ogv, so I only have an .mp4 for you, which I'll send via email.

Here's a .gif so you can see what the video shows:
![hookes_law_scrolling_video](https://cloud.githubusercontent.com/assets/8419308/11043249/0c24ae70-86d9-11e5-96af-73e527b9f86b.gif)

**Comment by ariel-phet** [comment]
BTW @aaronsamuel137 it would be best if this video were first in the order. Part of the idea would be to highlight new sims.

**Comment by aaronsamuel137** [comment]
OK sounds good. I have this up on phet-dev. I'll plan on changing the order so it comes up first.

**Comment by arouinfar** [comment]
Looks good @aaronsamuel137!

**Comment by aaronsamuel137** [comment]
Moved hookes-law first. Will deploy this soon (probably tonight)

**Comment by aaronsamuel137** [comment]
These changes were reverted because the hookes-law video we had seemed to be causing issues. Unassigning for now.

**Comment by ariel-phet** [comment]
It seems with the "new sims" page redesign almost up, as well as the new front page design coming, we can revisit what screen casts to have when we redo the front page. Plenty of other higher priority issues, so closing this one.

**Comment by arouinfar** [comment]
@phet-steele here's the relevant issue.
