### ISSUE TITLE
Website VM needs a place to live

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#305]
Now that I am leaving PhET, we'll want to have a copy of the website VM stored somewhere.

Perhaps a hard drive in the office? Or online somewhere? Both?

Any thoughts @jonathanolson ?

**Comment by jonathanolson** [comment]
I'm curious how large the image is?

Maybe storing it on simian (master copy, for when there are server changes needed), and then on developer devices would work?

**Comment by mattpen** [comment]
The image is about 23GB on my machine

**Comment by aaronsamuel137** [comment]
The VM is on simian under /data2/phet-vm/.

Assigning to @jonathanolson to review. Feel free to test the VM if you'd like before I leave.

**Comment by kathy-phet** [comment]
@jonathanolson  - My 2 cents -- seems like definitely a priority to test this before Aaron leaves. Yes?

**Comment by jonathanolson** [comment]
@mattpen, it seems like the VM has been working well (and has been updated at least once) since this was raised.

Anything else we need to do here?

**Comment by mattpen** [comment]
Yes, the VM is working well for me.  It's in a stable state so I'll close this issue and open a new one if we need to make further updates.
