### ISSUE TITLE
Increase size of CU branding 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#308]
Overall I like the new front page design. I think it will work nicely. 

However, I have considered the upcoming requests and meetings with several University officials I have set up, and the new size of the CU branding is too small. I know it makes for a visually cleaner site, but it doesn't support the messages I hope to send to CU in terms of their backing our project, so I need that one part to revert to the old, larger logo/branding, design. What was there in the version just before this one was a fine size. 

Thanks, Kathy

**Comment by ariel-phet** [comment]
@aaronsamuel137, I imagine this should be an easy change

If you need a new asset or such, @amanda-phet should be able to provide or you can go to http://www.colorado.edu/brand/downloads

**Comment by aaronsamuel137** [comment]
I've made this change and deployed to phet-dev. @ariel-phet, @amanda-phet, or @kathy-phet, can you verify it looks good to you?

**Comment by amanda-phet** [comment]
It looks fine to me. 

Should we also move the search bar up so that it is more centered vertically?

**Comment by ariel-phet** [comment]
@amanda-phet I would mock that up before we make any further changes. I get the feeling it might look odd.

**Comment by aaronsamuel137** [comment]
This has been completed and deployed. Closing
