### ISSUE TITLE
Update Hewlett Google Analytics code

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#311]
We'll (I'll?) need to update the main Google Analytics code AND the blog.

See https://github.com/phetsims/yotta/issues/17

@aaronsamuel137, are you aware of any other places on the website (or other web services) we have GA code? Do I need to open up a rosetta issue?

**Comment by aaronsamuel137** [comment]
I have not added GA code anywhere expect the donate button in the ask dialog that pops up for new registrations.

The only place I know of where _gaq is defined is in PhetPage.html, so no need to open a rosetta issue unless we want to add GA code there.

**Comment by kathy-phet** [comment]
JO, Aaron - Given extent of changes required. Please hold off on making any changes here until we speak with Lunametrics. 
Kathy

**Comment by jonathanolson** [comment]
@mattpen, can we replace every occurrence of "UA-5033010-1" with "UA-5033010-35" in the website code? It looks like this will require bumping the version in the JS filename.

Also @kathy-phet, the blog is currently set up with a plugin that only supports using one tracker (currently ours), so I can't update that. Let me know if we should remove that plugin and manually add the Google Analytics code into our templates, or investigate a better way.

**Comment by mattpen** [comment]
@jonathanolson The change has been applied to the master branch.  The commit is posted above.  Does any testing need to be done, or can this be deployed to figaro?

**Comment by jonathanolson** [comment]
Was the JS filename version bumped? If it has, I can test once it's been deployed to production (low chance of breaking anything).

**Comment by kathy-phet** [comment]
I think we can forgo the Hewlett tracker for the blog. It is not a main resource and I don't think Hewlett will miss it.

K

Sent from my iPhone

On Feb 4, 2016, at 12:08 PM, Jonathan Olson <notifications@github.com<mailto:notifications@github.com>> wrote:


@mattpen<https://github.com/mattpen>, can we replace every occurrence of "UA-5033010-1" with "UA-5033010-35" in the website code? It looks like this will require bumping the version in the JS filename.

Also @kathy-phet<https://github.com/kathy-phet>, the blog is currently set up with a plugin that only supports using one tracker (currently ours), so I can't update that. Let me know if we should remove that plugin and manually add the Google Analytics code into our templates, or investigate a better way.

-

**Comment by mattpen** [comment]
@jonathanolson - I usually don't bump the css/js filenames until immediately before I deploy to figaro.  I'll bump the js version and deploy tonight.

**Comment by jonathanolson** [comment]
Sounds great, thanks!

**Comment by mattpen** [comment]
@jonathanolson - This was deployed to figaro on Friday night.
