### ISSUE TITLE
Different spacing between admin help center questions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#312]
@mattpen Can you fix the spacing between questions on the admin panel of the help center? The 'Edit'/'Delete' button should be adjacent to the q/a they control. It might be best if they were to the left of the q/a they control (rather than above). See the screenshot below (disregard these awesome, bogus test questions):

Here's what it is now:

![help center spacing](https://cloud.githubusercontent.com/assets/5863899/11191264/ade282d6-8c57-11e5-863d-15928d657da1.PNG)

Maybe something like this:

![help center mockup](https://cloud.githubusercontent.com/assets/5863899/11191438/7b0ae230-8c58-11e5-9e00-22ace5659e07.png)

**Comment by mattpen** [comment]
@phet-steele This should be up on phet-dev now

**Comment by phet-steele** [comment]
It has been looking good to me. @oliver-phet have you checked out the spacing?

**Comment by oliver-phet** [comment]
Yep, looks good. Closing.
