### ISSUE TITLE
Add HTML5 Translation Utility User Guide link to HTML5 translation page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#316]
We should add a link to the user guide to the HTML5 translation page: https://phet.colorado.edu/translate/

Basically, add a line for 'User Guide' and put a line break after. 
The guide is located at https://docs.google.com/document/d/11BLxC7eDct6eifH1-nR6tWaxlnGeNEn2SPquT-lIUgY/edit#heading=h.cthiox7kfgfc

Here is a mockup: [Translate_Screen.pdf](https://github.com/phetsims/website/files/38174/Translate_Screen.pdf)

**Comment by ariel-phet** [comment]
Going to move this to a rosetta issue since it really belongs there

**Comment by ariel-phet** [comment]
moved to https://github.com/phetsims/rosetta/issues/104 

Closing
