### ISSUE TITLE
'Translate Simulation' from homepage should go to For Translators page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#319]
This link on the home page: https://phet.colorado.edu/en/for-translators/translation-utility
Should direct to https://phet.colorado.edu/en/for-translators

Currently, it takes you to the Java/Flash utility.

**Comment by ariel-phet** [comment]
@mattpen has this change been pushed to the live site yet?

**Comment by aaronsamuel137** [comment]
We didn't end up deploying last night because I wasn't sure if all of the changes for #314 were tested and verified correct. I'll plan on deploying tonight if everything is good to go and all of these changes will go live at once.

**Comment by aaronsamuel137** [comment]
Deployed. Closing
