### ISSUE TITLE
Remove translation warning string at the top of HTML5 sim pages

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#320]
When viewing a HTML5 sim page in a non-en locale (e.g. es_PE) there is a warning at the top of the page that tells users that the sim is not available in that locale. This is problematic, as some sims are now translatable and are actually available in that locale (as in the example below). As discussed in today's website design meeting, we've decided to remove this string from the top of all HTML5 sim pages, regardless of the redeploy/translation status of the sim.

![image](https://cloud.githubusercontent.com/assets/8419308/11252959/2d5c3f8a-8df6-11e5-87c2-9a9711b60a2f.png)

**Comment by aaronsamuel137** [comment]
This will be covered as part of #314.

**Comment by aaronsamuel137** [comment]
Actually, what I have done is have it display only if there is no translation in that locale. See phet-dev for the current behavior.

Should I remove it in all cases?

**Comment by arouinfar** [comment]
Great! Thanks @aaronsamuel137. The behavior now on phet-dev is ideal. We had suggested killing the string altogether because we thought it would be quicker to implement. I'll go ahead and close this issue.
