### ISSUE TITLE
Remove auto button from Admin Translate page

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#321]
As noticed by @phet-steele, there is a link for automatic translation on the Admin Edit Translation page that does not work.  The button replaces the current text with an ellipsis.  The problem is due to a change in version of Google Translate API, which is now a paid service.  @jonathanolson suggested that this was simply used for testing, is not compatible with html, and can be removed.  

I'm assigning to myself.

**Comment by mattpen** [comment]
@phet-steele I removed these buttons on phet-dev.  Anything left to do?

**Comment by phet-steele** [comment]
Nope, thanks!

**Comment by mattpen** [comment]
Thanks, I'll deploy this to figaro tomorrow.
