### ISSUE TITLE
Change "Translation Credits" to "HTML5 Translation Credits"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#322]
@mattpen when you get a chance can you change the sidebar navigation under For Translator from "Translation Credits" to "HTML5 Translation Credits"  (this should also change the title of the page)

**Comment by aaronsamuel137** [comment]
I'll take care of this. It's just changing the string key nav.forTranslators.translationCredits in the admin interface.

**Comment by aaronsamuel137** [comment]
Done, assigning to @ariel-phet for review. If you review within the next 15 minutes you might need to login to bypass varnish.

**Comment by ariel-phet** [comment]
Looking good.

@aaronsamuel137 we figured we could change this in the admin interface, but @oliver-phet was a little unsure of exactly which string. thanks for handling it!
