### ISSUE TITLE
Donation page should be updated to match current banner and sidebar navigation

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#325]
@kdessau-PhET we would like to update the network for good pages

both the main donation page:
https://donatenow.networkforgood.org/1437859

And the one for the new CCK ask.

We would like to update both the banner and the sidebar navigation to match the current main website.

**Comment by kdessau-PhET** [comment]
I've made the request to Network for Good $99 fee but it may take awhile.

KD

**Comment by kdessau-PhET** [comment]
I think this is done now so I will close it.
