### ISSUE TITLE
Question and answer strings on the translation admin page updating simultaneously

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#327]
When editing a question in the Help Center admin page, even if only the question string is edited (the answer string is left untouched) both strings will appear on the translation admin page with a red box like they were both updated (side note, they should be yellow. see #326). @mattpen I think it would behave better in this case if only the question string's box changed outline color since the contents of the answer string never changed. Would this be easy to do? Thoughts?

**Comment by mattpen** [comment]
I'll have to add some additional logic, but this shouldn't be to hard to do.  I'll make this change within the next week.

**Comment by mattpen** [comment]
@phet-steele I separated this behavior.  Can you please test?

**Comment by phet-steele** [comment]
Good to go!
