### ISSUE TITLE
Update to "Work on PhET by Outside Researchers" Section of Research page

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#328]
Please add to the top of the "Work on PhET by Outside Researchers" section this reference: 

Effectiveness of an inquiry-based learning using interactive simulations for enhancing students’ conceptual understanding in physics, Fan, Xinxin (2015). PhD Thesis, School of Education, The University of Queensland.
Link: http://espace.library.uq.edu.au/view/UQ:372336

Also, please change the heading of this section to "Publications on PhET Simulations by Other Researchers"

Thanks!

**Comment by ariel-phet** [comment]
@mattpen - this is not currently a high priority change, but it is an easy one, so if you feel like knocking off something simple, it would be good to fit in.

**Comment by mattpen** [comment]
@emily-phet, I'm pushing this to phet-dev now.  If it looks ok I'll push to the main site later this week.

**Comment by mattpen** [comment]
This was deployed tonight. Closing.
