### ISSUE TITLE
Some users report not receiving account confirmation email

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#329]
@jonathanolson Some users have emailed phethelp in the past few weeks reporting that they are not receiving an account confirmation email. Most of the affected users have school accounts (eg: @k12.sd.us)

I suspect the emails are being flagged by the school email server and are not delivered. 

Is there a way to check that these emails were successfully sent from us (to ensure it is not a problem on our end)? Is there an easy way for users to "whitelist" the emails coming from us (phetnoreply@phet.colorado.edu)? Could they simply add <phetnoreply@phet.colorado.edu> to their address book?

**Comment by jonathanolson** [comment]
Sign ups and confirmations are logged in the main website log. I presume an actual email failure would show up there. We can also potentially check the email account to see if we got a "rejected" reply back.

I can send you the log, filtered to display that information for whatever period we need to check over, or I can filter it for individual email addresses.

**Comment by oliver-phet** [comment]
Can you send me the log for 11/18-11/25?

**Comment by jonathanolson** [comment]
Sent the log file information, let me know if I can help further.

**Comment by oliver-phet** [comment]
Just checked the account associated with the first account help email today... the following is the log info "Could not find email for resend confirmation attempt. Email: [EMAILREMOVED]@talbot.k12.ga.us client: 168"

Does this mean the user entered a different email for resending the confirmation than the email originally used for registering? Does capitalization factor in?

**Comment by jonathanolson** [comment]
Just refreshed myself with some changes to the login/confirmations. Looks like they went to the sign-in, hit "Resend email confirmation", and then typed an email that the system did not recognize.

If I'm reading things correctly, it looks like capitalization does not factor in.

**Comment by jonathanolson** [comment]
Just checked for the matching email across logs. Looks like I only see attempts of resending the confirmation, and for resetting password. Don't see any capitalization changes (I searched for relevant entries in the DB also).

Probably have them sign up as normal?

**Comment by oliver-phet** [comment]
This issue is now being worked on in https://github.com/phetsims/website/issues/361
