### ISSUE TITLE
Extra line by "ar_SA" and "ku" locale links

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#331]
On the live site, there is a second line that appears next to the "ar_SA" and "ku" locales along the bottom of the website when viewed in RTL:

![double line](https://cloud.githubusercontent.com/assets/5863899/11480125/ec729134-9752-11e5-998f-e2517b334763.PNG)

Seen on Win 8.1 browsers (personal device).

**Comment by mattpen** [comment]
Website translation links were replaced with a dropdown menu, closing
