### ISSUE TITLE
Question/answer order needs to be retained after editing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#333]
Currently if I have a certain order of questions, say:

-Question 1
-Question 2
-Question 3

and I go to edit Question 1 for some reason, maybe a typo, the website will place the most recently updated question and answer at the bottom of the list so now the order appears as such:

-Question 2
-Question 3
-Question 1

This is not desired behaviour, it would be better to maintain the order while editing.

**Comment by mattpen** [comment]
@oliver-phet wrote: "We would like the ability to easily reorder the questions in the help center. Once the help center is up and running we'll visit adding this."

I'll try to implement this behavior in the next week.

**Comment by mattpen** [comment]
@phet-steele - The questions are now ordered by id, which is roughly by creation date.  If you delete a question, the next new question will get its id, so its easy to break the ordering.  I'm going to make this more robust when I add the option to reorder them arbitrarily.

**Comment by mattpen** [comment]
Helpcenter questions are now able to be reordered in the admin page.  @phet-steele can you please test this out if you have a chance?

**Comment by phet-steele** [comment]
It works well, but I have two gripes about this:

The ordering gets slightly difficult when ordering the "Running Sims" questions. Currently the admin page lists all the subcategories in one list so the list could appear like this:

A Windows Question
A Mac Question
A Second Windows Question

Moving the second windows question up doesn't actually change the order of questions since it is still after the first question. A user would have to move the second windows question up twice in order to reorder anything. Would it be difficult to have the admin page separate the subcategories into different, reorder-able lists? It would be like:

**Windows**
A Windows Question
A Second Windows Question

**Mac**
A Mac Question

Furthermore, this is more of a question @mattpen but I'm curious how categories with only one question are handled when reordered. On the surface everything looks fine, but is everything handled well under the hood? Do you foresee any problems :wink: ?

**Comment by phet-steele** [comment]
@oliver-phet reordering has not been affecting translations. If something was translated, it did not become "not translated" or "out of date".

**Comment by oliver-phet** [comment]
Thanks @phet-steele. 

@mattpen Can you comment on the ability to have the admin page for Running Sims separate the subcategories into different, reorder-able lists? Once that is resolved, we are ready to publish to the site (hidden at first)

**Comment by mattpen** [comment]
@oliver-phet @phet-steele I should be able to separate the running sims sub categories today.  I'll try to get it up on phet-dev by tonight and if it looks good we can do the silent deploy to the main site tomorrow.

To clarify the question from @phet-steele, I added a new column to the helpcenter database to track the order.  When hitting move up or down, it looks for the next item in the list and swaps the order values.  If it doesn't find an item (for example if there is only one question or if its at the top or the bottom of the list) then the click does nothing.  There shouldn't be anything changing in the translation key or english string when you hit this button.

**Comment by oliver-phet** [comment]
Thanks @mattpen that all sounds good.

**Comment by mattpen** [comment]
@oliver-phet @phet-steele - I wasn't able to get this up on phet-dev today, the internet connection where I'm working is terrible.  I'll get it posted on phet-dev tonight and we can push it to the main site later this week.

**Comment by phet-steele** [comment]
Working great @mattpen.
