### ISSUE TITLE
Help Center and Website Translation Utility out of sync?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#334]
At the moment these two question/answer strings are available to translate in the website utility:

![linux 16](https://cloud.githubusercontent.com/assets/5863899/11537827/2d2cef3c-98dc-11e5-9aeb-84311325be62.PNG)

![chromebook 14](https://cloud.githubusercontent.com/assets/5863899/11537843/4a790544-98dc-11e5-81cc-bdadd34462a7.PNG)

However! These questions do not exist on the Help Center admin page so should not exist here. I'm assuming these questions were deleted at some point, whether by clicking "delete" in the help center admin page or by some other dev trickery, and wherever the website translation utility pulls its strings from still has these questions/answers. The above two pairs of strings are both in the "Running Sims" category, and the only string that appears in the help center admin page is this question/answer pair:

![general 4](https://cloud.githubusercontent.com/assets/5863899/11538017/19868df2-98dd-11e5-82bb-d3bd3149d172.PNG)

**Comment by mattpen** [comment]
I jumbled a few things up on the back end when removing the IO category.  This should be fixed now.  @phet-steele can you please test it again?

**Comment by phet-steele** [comment]
:+1: I'll keep a lookout for if I can manage to make this happen myself (probably can't).
