### ISSUE TITLE
"Offline" subject displays the System Name

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#337]
"Offline" subject displays the System Name box instead of the "Running Sims" subject displaying it:

It's here
![offline general](https://cloud.githubusercontent.com/assets/5863899/11596016/da737212-9a6f-11e5-83dc-f660ba477798.PNG)

Instead of here
![no system](https://cloud.githubusercontent.com/assets/5863899/11596030/ed119606-9a6f-11e5-82b8-0a79c4d98275.PNG)

**Comment by mattpen** [comment]
I'll deploy the fix to phet-dev later today.

**Comment by mattpen** [comment]
This has been fixed and is live on phet-dev. Closing
