### ISSUE TITLE
Add URL Redirect for CCK Donate Ask

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#338]

**Comment by kdessau-PhET** [comment]
Can we make a redirect page for the CCK Ask. Call it: http://phet.colorado.ed/CCKHTML5Donate
Thanks! We will want to do this fairly soon as we want to sent out an e-mail using this URL on Monday.

**Comment by kdessau-PhET** [comment]
This is for the current https://donatenow.networkforgood.org/html5donatenow
Thanks!

**Comment by kdessau-PhET** [comment]
Sorry make sure that it's (of course http://phet.colorado.edu/CCKHTML5Donate)

**Comment by mattpen** [comment]
This should be working now on phet-dev, I'm going to deploy to the main site tonight.

**Comment by kdessau-PhET** [comment]
Thanks Matt!

**Comment by mattpen** [comment]
Deployed to the main site.  Closing.
