### ISSUE TITLE
Change directions for comments on activity pages

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#339]
Currently, on any activity page, users can add a comment. The text next to the entry box says:

"What do you think about this activity? How did you use it or change it for your class? Professionally constructive comments welcome."

We would like to change it to say:

"How did you use this activity or change it for your class? Answer keys are often not available because the activities are inquiry based and lead to multiple answers. Professionally constructive comments welcome."

**Comment by mattpen** [comment]
@amanda-phet  This is up on phet-dev now.  I can deploy to the main site tonight if it looks ok.

**Comment by amanda-phet** [comment]
Something changed with the layout and I have already tried doing a hard refresh... 
<img width="598" alt="screen shot 2015-12-09 at 4 11 45 pm" src="https://cloud.githubusercontent.com/assets/7852916/11701881/8bbbedd8-9e8f-11e5-92d2-7eb4fed03fec.png">

However, maybe we should go ahead and make a change since the text is longer?  
Current
<img width="604" alt="screen shot 2015-12-09 at 4 12 36 pm" src="https://cloud.githubusercontent.com/assets/7852916/11701894/a6394c6e-9e8f-11e5-85a9-5de7c3f086b3.png">

New?
<img width="861" alt="screen shot 2015-12-09 at 4 15 29 pm" src="https://cloud.githubusercontent.com/assets/7852916/11701966/145b08cc-9e90-11e5-9003-8347cfd5a022.png">

**Comment by mattpen** [comment]
@amanda-phet - I didn't refresh the css on the server side.  Can you try another hard refresh in your browser?  It should look like the attached screen shot now (close to the same as the current), but I can easily change it to your new suggestion.
![image](https://cloud.githubusercontent.com/assets/11747676/11703121/9844a93c-9e99-11e5-9a3d-02fc03b2ba5d.png)

**Comment by amanda-phet** [comment]
It seemed to work that time! However the comment button is still too close to the box, but if this is an issue that will eventually disappear can we just not worry about it? 

<img width="464" alt="screen shot 2015-12-09 at 5 34 07 pm" src="https://cloud.githubusercontent.com/assets/7852916/11703283/0b712f38-9e9b-11e5-8251-0cbe9a581b24.png">

**Comment by mattpen** [comment]
I'll add a margin and push it to the site tonight.

**Comment by mattpen** [comment]
Deployed to the main site.  Closing.  Please reopen if the format needs to be altered.
