### ISSUE TITLE
Remove Aaron from newsletter testers email list

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#340]
In https://github.com/phetsims/website/blob/8332f4dda2c265f0eb5a61ee5fcaa6d809d140a4/src/java/edu/colorado/phet/website/admin/AdminMainPage.java, he should be removed from the list under the debug-newsletter-to-team.

**Comment by jonathanolson** [comment]
Also, Ariel (Ariel.Paul@colorado.edu) should be added to the list where Aaron is removed.

**Comment by mattpen** [comment]
I made this change and I'll deploy it to the main site tonight.

**Comment by mattpen** [comment]
Deployed to figaro.  Closing.
