### ISSUE TITLE
Improve Tomcat request logging

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#341]
To help debug the times when there are stability issues, I'd like to have a separate log of all requests that Tomcat receives. Collaborating with @mattpen on this would be great.

Things I'd like:

1. A log line should be added (with a timestamp) when a request is received. This should include the URL/path, and a request ID. Probably easiest to do in PreFilter.
2. Another log line should be added (with a timestamp) when request generation is complete (and it starts to be sent out). It should include the request ID and preferably the URL/path also (so it can be matched up with the start), AND should include the total time spent generating the request.

I'm hoping to:
1. Identify long-running requests. What is taking up time and causing Apache processes to remain open?
2. Identify requests that seem to hold some sort of global lock long enough that they delay other requests from completing.

It's my current hypothesis that some requests are both (1) slow to generate and (2) hold a global lock, so when requested a few times they can cause Tomcat to show the symptoms of (a) lowered CPU usage across the board and (b) requests queuing up.

**Comment by mattpen** [comment]
@jonathanolson I added a new logger to capture this information and deployed it to figaro tonight.  The new log resides at /usr/local/tomcat/logs/request.log

**Comment by jonathanolson** [comment]
Thanks! Assigning to myself to investigate once there's a stability event.

**Comment by jonathanolson** [comment]
@mattpen, do you see any current reason to keep this enabled, or has it been disabled already?

Probably want to ensure it's disabled due to disk space.

**Comment by mattpen** [comment]
@jonathonolson The request issues on Figaro seem to have cleared up so I'll disable this script as well as the other two we put into place for this issue.

**Comment by mattpen** [comment]
@jonathanolson - Is it OK to delete the logfiles for these scripts, or should they remain in place?  They are using up about 15GB of space.

I stopped the netstat and apache monitoring scripts, the tomcat script will be stopped on the next deploy.

**Comment by jonathanolson** [comment]
I'd say they can either be moved to figaro-dev (if you want) or deleted. No preference.

**Comment by mattpen** [comment]
I removed the logfiles but retained the scripts so we can gather similar data in the future if the problems arise again.

**Comment by mattpen** [comment]
The remaining tomcat log on figaro was stopped tonight.
