### ISSUE TITLE
Further tweaks to front page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#342]
After some feedback from team members we'd like to change the color of the Play with Simulations and Teachers Register Here buttons. Instead of the raspberry color, they should both be the same navy as the banner. The play icon will also change to "PhET blue" instead of white. (This is the same as the help center icon.) 

<img width="336" alt="screen shot 2015-12-16 at 1 53 51 pm" src="https://cloud.githubusercontent.com/assets/7852916/11853642/69648c00-a3fc-11e5-97c7-4c4931b0fb9e.png">

When the user hovers, the navy should become a brighter color along with showing the text underline. We are using #203599 below:

<img width="335" alt="screen shot 2015-12-16 at 1 53 59 pm" src="https://cloud.githubusercontent.com/assets/7852916/11853661/811d627c-a3fc-11e5-8571-3035cfb64dff.png">

**Comment by mattpen** [comment]
@amanda-phet What is the light blue color behind the "play" triangle?  Is it the same color as the register button?

**Comment by amanda-phet** [comment]
The play triangle is just the play icon that is used in the help center. Right now, this icon is white on a raspberry button but we'd like it to the "PhET blue" on a navy button. PhET blue is from the logo and is #6ACEF5; navy is from the banner and is #2A326A. I can email you a .svg image of the play icon needed.

**Comment by mattpen** [comment]
Thanks Amanda.  I'll put this up on phet-dev later today for review.

**Comment by mattpen** [comment]
@amanda-phet Can you check the buttons on phet-dev and let me know if they look ok?

**Comment by amanda-phet** [comment]
Just one minor issue: it seems like there is an extra space to the left of the text in the buttons. This is problematic when I hover and see an extended underline to the left of the text. 

Otherwise, the look great!

**Comment by mattpen** [comment]
Thanks,  I'll remove the extra space and push to the main site next week.

**Comment by amanda-phet** [comment]
Awesome, thank you.

**Comment by mattpen** [comment]
As there was some confusion, I'm clarifying which of the in-progress website changes are dependent on each other.  
This change is not dependent on any others.  It is currently staged for the next deploy to the main site (early next week - delayed due to newsletter).

**Comment by mattpen** [comment]
@amanda-phet - I deployed this change tonight on the main site.  There is currently an issue with the color of the teacher icon, but it should be fixed by the morning.

**Comment by mattpen** [comment]
The colors are fixed now.  Closing.
