### ISSUE TITLE
Check December 16th installer

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#343]
Lots of errors in sim pages, looks like a component wasn't added if the installer user-agent was present. Might be missing every sim page.

**Comment by jonathanolson** [comment]
Confirmed that the installer is buggy, showing no main content for every sim page:

![bad-installer](https://cloud.githubusercontent.com/assets/480878/11860434/1059d274-a432-11e5-868f-30ec6ac22087.PNG)

@jbphet, can we roll back the installer? @oliver-phet, any complaints about the installer during this period are probably related to this bug.

**Comment by jbphet** [comment]
When was this problem introduced (so that I can figure out what version to roll back to)?

**Comment by jonathanolson** [comment]
Looks like https://github.com/phetsims/website/commit/e285545d4c25562b340d14c99fe819cc8b608f9b?

**Comment by jbphet** [comment]
I tested and then put up the installers built on Dec 2 2015, since they don't have this issue.  @oliver-phet tested after downloading directly from the web site, and will inform the one user who contacted us about the issue.

**Comment by mattpen** [comment]
The fix for the website/installer was pushed to figaro tonight.  [Commit is here](https://github.com/phetsims/website/commit/0edf7b95492db9ff5b509cd4fdf94dea1fb701ca)

**Comment by jbphet** [comment]
I ran an installer over the weekend and it looks good, so it appears that the fix referenced in the previous comment worked.  I will leave the auto build in place, and the installers should be checked after that finished, which should be by 6 am MST on Wed Dec 23rd.

**Comment by jbphet** [comment]
I tested the Windows version of the installers built on Wed Dec 23rd, and it looked fine - no problems with the sim pages.  Looks like this is fixed, closing.

**Comment by oliver-phet** [comment]
I just tested this on my Mac and all worked fine.
