### ISSUE TITLE
Consider setting project visibility to true if a sim's visibility is changed to true

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#344]
Assigned to developer meeting for discussion/feedback.

**Comment by samreid** [comment]
**Consensus from meeting: go for it**

@mattpen will look into it.

**Comment by mattpen** [comment]
@jonathanolson I've published the change to simian.  If you have a moment, can you check the commit above?

**Comment by jonathanolson** [comment]
Looks great to me.

**Comment by mattpen** [comment]
Ok, I'll push this to figaro on the next deploy.

**Comment by mattpen** [comment]
Deployed to figaro. Closing.
