### ISSUE TITLE
Terminate the translation utility image on 'For Translators' page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#345]
<img width="1014" alt="screen shot 2015-12-23 at 2 33 09 pm" src="https://cloud.githubusercontent.com/assets/5090275/11985533/f32d3690-a982-11e5-82a2-c85c58659c0f.png">

**Comment by mattpen** [comment]
@oliver-phet I've already removed this, it was pretty trivial.  Do you want me to post it on phet-dev?

**Comment by oliver-phet** [comment]
Sure. Post to phew-dev
--
Oliver Nix
PhET Interactive Simulations
University of Colorado
oliver.nix@colorado.edu<mailto:oliver.nix@colorado.edu>

On Dec 23, 2015, at 2:58 PM, Matt Pennington <notifications@github.com<mailto:notifications@github.com>> wrote:


@oliver-phet<https://github.com/oliver-phet> I've already removed this, it was pretty trivial. Do you want me to post it on phet-dev?

**Comment by mattpen** [comment]
@oliver-phet This is up on phet-dev now.

**Comment by mattpen** [comment]
As there was some confusion, I'm clarifying which of the in-progress website changes are dependent on each other.  
This change is not dependent on any others.  It is currently staged for the next deploy to the main site (early next week).

**Comment by oliver-phet** [comment]
@mattpen Can you add an extra line break at the end of each section so that the 3 sections are more spaced out.

**Comment by mattpen** [comment]
Sure thing.  Was everything else ok?  I can deploy this to the main site tonight.

**Comment by oliver-phet** [comment]
Yep, all good.

**Comment by mattpen** [comment]
Deployed to the main site tonight.  Closing.
