### ISSUE TITLE
Changes to the New Sims page

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#346]
As discussed in a skype conversation with @amanda-phet, we are planning to change the New Sims page back to a "Category" style page.  It is currently an "HTML5" page not dependent on the category of the sims.  The HTML5 page in its current state will be separated and linked in the nav menu under Simulations.  

I'm assigning this to myself.  I'll start work on it as soon as the design changes in #301 have been stabilized.

**Comment by mattpen** [comment]
This was discussed in the developer meeting today.  The consensus was that the New Sims page should display the 30 most recently published version 1.0.0 sims, and the newest sims box will contain the 3 most recently published.

**Comment by amanda-phet** [comment]
That's great news that it can be automated!

**Comment by mattpen** [comment]
@ariel-phet, @amanda-phet, or @oliver-phet  - Where should the html sims video and the "Future of PhET" blurb go?  Should they both go on the HTML5 category page?  In a skype call over the break, Amanda suggested that it should go there as there will be a new video/blurb coming soon for the New Sims page and that the old video/blurb would still be relevant to the HTML5 sims (if I'm remembering correctly)

**Comment by mattpen** [comment]
Should the thumbnails view of the New Sims page be ordered by publication date or alphabetically?

**Comment by ariel-phet** [comment]
@mattpen Yes they should both go on the HTML5 category page and on the new sims page. We will eventually have a donation video that replaces this video.

I think we had discussed having the "newest" 3 sims be in order of publication, and the rest be in alphabetical order.

**Comment by mattpen** [comment]
This was published to phet-dev tonight.  There are still some issues to be fixed - see #301.

**Comment by mattpen** [comment]
Setting status:on-hold - pending completion of #301

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
