### ISSUE TITLE
Statistics on registered teachers

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#348]
Matt, Can you look at the number of registered users - both those with updated profiles, and those still with the older profiles - and identify the number of teachers from the total users? Right now total users seems to be 118913 from admin stats. 

Here is the query that Aaron used for this previously .. where the older profiles are the "description" query. 
select count(*) from phet_user where teacher = true or teachereducator = true or description = 'Teacher using PhET' or description = 'I am a teacher interested in using PhET in the future' or description = 'I am a teacher who uses PhET in my classes';

count = 45591

Thanks! 
Kathy

**Comment by mattpen** [comment]
@kathy-phet - as of this morning the count for this query is 76357.  Do you want to add this query to the Statistics page?

**Comment by mattpen** [comment]
Disregard the question, I just realized this is requested in a different issue - #351.  Is it ok to close this one?

**Comment by kathy-phet** [comment]
Thanks, closing!
