### ISSUE TITLE
Add flag to profiles with bad or unconfirmed emails

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#349]
JO, Matt, 

Can we add a flag to each user in our database that represents whether it is a good/active email or not? 

We need this flag in order to work on integration with Salesforce in mid-Jan, and only sending salesforce good emails/users. 

Two steps I see are: 
1) Flag anyone who never confirmed their email (after the confirmation was required) .... assuming they cannot actually login without confirming the email. Is this correct? 
2) Flag anyone whose email bounced on the last round of emails 12/29. Is there an easy / automated way to do this from the records in the phetmail account? 

Assigning to Matt first, but please consult with JO on this task to discuss approaches. 

Thanks, 
Kathy

**Comment by mattpen** [comment]
@kathy-phet - we are already flagging users who have not yet confirmed their email.  There are 4114 of these users.  Flagging users when their emails bounce will take a little more effort, as I don't think this is currently recorded in the log.  I'll check on it.

**Comment by mattpen** [comment]
@jonathanolson and I discussed this earlier today. We currently don't have a method for doing this automatically.  I am going to write a utility to parse through the undeliverable reports in the phetmail@colorado.edu inbox and flag the affected users in the database.

@kathy-phet Should we indicate to the user somehow that we are no longer able to send them email?  For instance on their Edit Profile page we could put a warning message that says something like     
> "We're having trouble sending email to your address.  Please check your email address below and update it if necessary.  If it appears to be correct, please contact phethelp@colorado.edu"

**Comment by mattpen** [comment]
@jonathanolson - I implemented most of the items we discussed yesterday.  The only one that I wasn't able to get was using an API key rather than OAuth.  It doesn't look like this is possible for the Gmail API do to the interaction with a user account.  That said, the script should only need user interaction the first time it is run.  The script ran as expected on my VM (it flagged ~7000 users from the last month). Do you have time to review the changes so I can test the script on figaro-dev?

**Comment by mattpen** [comment]
I ran this script tonight on figaro.  The database on figaro now has a column called "delivery_failures" which is equal to 1 if they had an email returned as undeliverable in the last 30 days (as of today).  This should include all emails returned from the last mailer up until today. 

Concerns: 
+ It's possible we could still receive more emails returned from the last mailer although this number should be small.  
+ There are probably about 300 addresses that the script missed (it found 7136).  However, this is a notoriously difficult problem and I'm getting diminishing returns on the amount of time spent improving the logic.

I'm going to go ahead and close this issue and start work on incorporating this data into the Admin statistics page - #351.
