### ISSUE TITLE
Number of activity comments 12/1/2014-11/30/2015

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#350]
Is it possible to determine the number of activity comments posted in this timeframe? I need it for a grant report. Thx

**Comment by ariel-phet** [comment]
@mattpen if this is a bit tricky to do, the website does automatically generate an email with all the activity comments. If we amalgamate those emails we could have someone like Steele manually go through them - it would be tedious, but not particularly difficult.

**Comment by mattpen** [comment]
By activity comments, I'm assuming you mean the comments posted on pages like this: http://phet-dev.colorado.edu/en/contributions/view/3320?

If so, there were 135 new comments posted during this period.
