### ISSUE TITLE
Post warning for downtime for Figaro 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#353]
@jonathanolson - Might you have time today (Sunday) to post a warning for scheduled downtime onto Figaro? 

Warning: PhET's server will be down for maintenance on Monday, January 4 from 11:00-11:45 pm (MST).

Assuming 45 min is certainly enough time for a reboot and spinning everything back up. 

Thanks!

**Comment by kdessau-PhET** [comment]
@ariel-phet do you want me to twitter this? Or will you? I will blog and FB today.

**Comment by kdessau-PhET** [comment]
I will also blog/FB about this.

On Jan 3, 2016, at 8:06 AM, kathy-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


@jonathanolson<https://github.com/jonathanolson> - Might you have time today (Sunday) to post a warning for scheduled downtime onto Figaro?

Warning: PhET's server will be down for maintenance on Monday, January 4 from 11:00-11:45 pm (MST).

Assuming 45 min is certainly enough time for a reboot and spinning everything back up.

Thanks!

**Comment by kathy-phet** [comment]
Done! I did not know I had the power, but I do. Under "English" in translation, just add the maintenance text and you are done.

**Comment by ariel-phet** [comment]
Tweeted
