### ISSUE TITLE
Remove "updated" column from activity tables

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#354]
The activity tables are currently very crowded, and with the addition of the sorting arrows we decided at a 12/23 design meeting to remove the Updated column. The information is still available on the activity page, and when we eventually tackle the teaching resources we will revisit the information in the tables with a more holistic vision. 

This change is independent of other website changes and can be deployed at any time.

**Comment by mattpen** [comment]
@amanda-phet This was deployed to phet-dev today.

**Comment by amanda-phet** [comment]
Looks great. I'll leave it for you to close this issue once this is deployed.

**Comment by mattpen** [comment]
Deployed to figaro - closing.
