### ISSUE TITLE
Add blurb to 'For Translators' page about translating Tips

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#357]
This blurb can go below the 'Translating the Website' section:

**Translating Teacher Tips**

*The Teacher Tips associated with every sim can be translated by editing the original .pdf document. Translated Teacher Tips can be emailed to phethelp@colorado.edu for publication on the website. Please send .pdf documents only.*

**Comment by mattpen** [comment]
@oliver-phet - should we wait until #324 is complete to implement this, or is it ok to go ahead and post it?

**Comment by oliver-phet** [comment]
Yes, please wait until #324 is complete.

**Comment by amanda-phet** [comment]
@arouinfar suggested that we modify the blurb to say that the tips will not be uploaded until the sim has been redeployed. I recommend that we edit the blurb to be: 

*The Teacher Tips associated with every sim can be translated by editing the original .pdf document and emailing a .pdf to phethelp@colorado.edu for publication on the website. Please send .pdf documents only. Note that for some simulations, translated tips will not be uploaded until the sim is translatable.*

**Comment by arouinfar** [comment]
Sounds great @amanda-phet.

**Comment by mattpen** [comment]
This is now up on phet-dev.  It is branched with the translated teacher guide code, so it will be deployed at the same time as #324

**Comment by mattpen** [comment]
Setting status:on-hold - pending completion of #324

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
