### ISSUE TITLE
Odd/unneccesary character preceding copyright in footer

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#359]
There is an unnecessary character preceding the copyright statement in the footer

![footer](https://cloud.githubusercontent.com/assets/4051174/12146556/7daf8f88-b451-11e5-80fe-183e34dca194.PNG)

**Comment by mattpen** [comment]
This should be fixed on phet-dev now.  I'll deploy the change to figaro this week.

**Comment by mattpen** [comment]
I pushed the fix to figaro, but the character is still there.  I'm going to check again tomorrow, as the panel could be cached by varnish.

**Comment by mattpen** [comment]
I just checked, the odd character is gone now on figaro.
