### ISSUE TITLE
Add a "confirm email" line to change email page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#360]
The current page that allows a user to change their email asks for the new email and password. https://phet.colorado.edu/en/change-email 

However, when making a new account, the email is entered a second time (which is typical on websites). We should change the current change email page to force users to confirm their new email address:

<img width="608" alt="screen shot 2016-01-06 at 3 37 55 pm" src="https://cloud.githubusercontent.com/assets/7852916/12156969/6e23c4d2-b48b-11e5-890b-3e4dff59fdae.png">

**Comment by mattpen** [comment]
@amanda-phet This has been posted to phet-dev.  If it looks ok I can deploy it to figaro.

**Comment by mattpen** [comment]
Deployed to figaro - closing.
