### ISSUE TITLE
Plate Tectonics - Windows Only

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#362]
@mattpen We'd like to add a new badge/button to on Plate Tectonics what says "WINDOWS ONLY". This badge/button could be clickable and it would scroll the user to the System Requirements, open the System Requirements which would say:

*This simulation is incompatible with Macs
due to an incompatibility between the graphics
hardware on those systems and the 3D graphics library (LWJGL) used in the simulation.*

Mockup: https://drive.google.com/file/d/0B5JSfRAuRHDzU19aRGR5bGJoYzQ/view?usp=sharing

**Comment by mattpen** [comment]
I've added the button, behavior and requirements text.  I'll deploy this to phet-dev soon.

**Comment by mattpen** [comment]
This was published on phet-dev tonight.

**Comment by oliver-phet** [comment]
@mattpen Can you remove the 'Macintosh' section of the system requirements (only show Windows and Linux)?

Everything else looks good!

**Comment by mattpen** [comment]
@oliver - I removed the Mac requirements list and tested it on a variety of browsers.  I'll push this to figaro tonight.

**Comment by mattpen** [comment]
Pushed to figaro, closing.
