### ISSUE TITLE
Modify translated sims table

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#363]
@kathy-phet has requested that we add a column to tables of translated sims that indicates whether a sim is HTML5, Java, or Flash. The website team discussed this 1/6 and decided on the following table: 
<img width="815" alt="screen shot 2016-01-07 at 10 27 24 am" src="https://cloud.githubusercontent.com/assets/7852916/12177391/1dc0e666-b529-11e5-927e-e45508f213a3.png">

The changes from the current table include: 
- sortable columns
- move the current right-hand column (sim name in viewing locale) to the left
- move the current left-hand column (translated sim name and download/play links) to the right
- add in a column for code-base using iconic representations (the icons on the sim badges without the enclosing square) 

The color of the table can be blue for now but the mockup reflects what will become the universal table format.

**Comment by mattpen** [comment]
@amanda-phet - should there be any link behavior for the code icons? Are they just static images?

**Comment by mattpen** [comment]
@amanda-phet - Can you clarify the sortable behavior for the code column? Alphabetic/numeric sorting doesn't seem to make sense here.  Should the sort function group the sims by code-baseand then cycle through which one appears first?

**Comment by ariel-phet** [comment]
@mattpen I think I can answer a few questions here:
- no link behavior for code icons, merely static images
- Yes the sort function on code base would group the sims by code base. So for instance, all HTML5 first, then Java, then Flash. I think we felt it did not need to cycle, but either group or not. So if sorting group by HTML5, then Java, then Flash, and order alphabetically within a code base group. But no need to cycle through code base, one grouped you can just look down the column for the appropriate group.

**Comment by mattpen** [comment]
@ariel-phet - Would subsequent clicks on the same column keep the grouping by code-base and reverse the alphabetic order?  Or just leave it as is?

**Comment by mattpen** [comment]
Discussed with Ariel via skype.  A second click on the CODE column will return the table to the default sort (alphabetical a-to-z by untranstlated sim name).

**Comment by mattpen** [comment]
@amanda-phet @ariel-phet This was deployed to phet-dev today.  Please let me know if anything needs to be improved.

**Comment by amanda-phet** [comment]
@ariel-phet thanks for responding to @mattpen 's questions. I would agree for both.

**Comment by mattpen** [comment]
Is there anything else to add here?  Is it ok to deploy to figaro?

**Comment by ariel-phet** [comment]
:+1:  @mattpen , OK to deploy

**Comment by mattpen** [comment]
Deployed to figaro - closing.
