### ISSUE TITLE
Page not found: Vector Addition Italian

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#364]
Via phethelp:

*I'm getting a "Page not found" error at the following link about vector math:
*https://phet.colorado.edu/sims/vector-addition/vector-addition_it.html

I was just able to reproduce.

**Comment by mattpen** [comment]
This sim is missing from `/data/web/htdocs/phet/sims/vector-addition`.  I'm not up to speed yet on how the translated sims are deployed, @jonathanolson would you be able to help on this one?

**Comment by jonathanolson** [comment]
Not sure what happened. Did a translation deployment for it and it's there now. If it happens again, I can look into it further.
