### ISSUE TITLE
Create zh_HK (Hong Kong Chinese) locale

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#365]
As requested by a translator.

I'll take care of the HTML and Java/Flash/Website side. @mattpen, you'll want to SVN update after I do this, so that future website deployments will include the new locale. Additionally, we may need to create an English translated string for the locale after we do a deployment.

**Comment by jonathanolson** [comment]
Also, before this can be done, we'll need the name of the locale translated into it. E.g.:

For Simplified Chinese, we have 中文 (中国)
For Traditional Chinese, we have 中文 (台灣)

@oliver-phet, what would the translator like for this new locale?

**Comment by oliver-phet** [comment]
@jonathanolson The user replied 
"For Chinese, Hong Kong, it should be 中文 (香港)."

**Comment by oliver-phet** [comment]
@jonathanolson Any update on this?

**Comment by jonathanolson** [comment]
@jbphet, it looks like Rosetta uses localeInfo.js from chipper, is that correct? If so, once the website has it in its locale list, we'll want to add:
```js
    zh_HK: {
      name: 'Hong Kong Chinese',
      localizedName: '中文 (香港)',
      direction: 'ltr'
    },
```

@mattpen, first we'll want to modify phetcommon-locales.properties. Can you add the equivalent entry there, and let us know when it's deployed to figaro?

**Comment by mattpen** [comment]
@jonathanolson - I've made the change and I'll deploy to figaro tonight.  However, I don't think I have credentials to push these changes to SVN.

**Comment by mattpen** [comment]
The changes to  phetcommon-locales.properties were deployed to figaro, the locale is now available for translation.

**Comment by jonathanolson** [comment]
Pushed chipper change to include this.

@jbphet, can you (at your convenience) test/update rosetta with this new locale?

**Comment by jbphet** [comment]
This required a restart of Rosetta, but the zh_HK locale is now appearing in the locale list.  Back to @jonathanolson in case there is anything more to do on this.

**Comment by jonathanolson** [comment]
I can't think of anything. @oliver-phet, is this resolved?

**Comment by oliver-phet** [comment]
Appears to be translatable on the site. Closing for now!
