### ISSUE TITLE
Energy Skate park Internal Error

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#366]
Multiple users are emailing about ESP (Java) sim page yielding 'Internal Error'
http://phet.colorado.edu/en/simulation/energy-skate-park

**Comment by mattpen** [comment]
It seems to be working correctly now.  End users can try again.  I'll keep an eye on it throughout the day.  I may need to do a redeploy to apply a fix this afternoon.

**Comment by ariel-phet** [comment]
This appears to be fixed. Closing
