### ISSUE TITLE
Change the link in the embed option

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#368]
The link to sims in the embed link should be https not http to improve compatibility with LMS systems.

HTML5 sims are the priority.

**Comment by mattpen** [comment]
@ariel-phet - These links have been updated to https on phet-dev.  Do we need to do any testing, or is it ok to push this to figaro on the next deploy?

**Comment by ariel-phet** [comment]
@mattpen - lets have @phet-steele do a little testing before we make that change. Did you change this for only HTML5 sims or did it get changed for Flash/Java?

Also...in general, best to just reassign issues to me for a quick response. Sometimes simply mentioning slips through the cracks.

**Comment by mattpen** [comment]
@ariel-phet @phet-steele - this has been changed for all sims regardless of technology.  Assigning to Steele for testing.

**Comment by ariel-phet** [comment]
Making a testing issue for this in tasks

**Comment by mattpen** [comment]
Testing is complete - I'll push this to figaro on the next deploy.

**Comment by mattpen** [comment]
Deployed to figaro - closing.
