### ISSUE TITLE
Test login functionality for #361

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#370]
In order to implement the change requested in #361, I needed to change some code that may potentially have other side effects.  If a user logs in and has not confirmed their email, instead of getting a password error they now get redirected to the Awaiting Email Confirmation page.  We should test to make sure this happens when it is supposed to and does not happen if they have indeed confirmed their email.

Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@mattpen I assume this behavior is currently available on phet-dev?

**Comment by mattpen** [comment]
@ariel-phet - yes, this functionality is up on phet-dev

**Comment by ariel-phet** [comment]
moved to a task: https://github.com/phetsims/tasks/issues/480

@mattpen generally good to put tasks in the tasks repo, and reference the relevant issue. This workflow has worked well for us.

closing this issue
