### ISSUE TITLE
Registration prematurely completed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#371]
While registering for an account:

1. Don't fill in a required field. For example, fill in everything except first name.
2. Click Register, but then be redirected to the registration page with errors (because you missed a field).
3. Fill in the field. Notice that now the site wants you to re-enter your password (but doesn't make it obvious as only the field you missed in step 1 is red, not the password field). Do NOT fill in your password again.
4. Click Register, and the "Thanks for registering!" pop up appears...but you still get redirected to make a password. This pop up shouldn't appear in this step since the account has not yet been successfully made.

**Comment by phet-steele** [comment]
Related to phetsims/tasks/issues/480

**Comment by mattpen** [comment]
This behavior is not related to the change in that task.  I could recreate this behavior on phet.  That said, it was an easy fix.  I'll deploy to phet-dev ASAP.

**Comment by mattpen** [comment]
@phet-steele - This should be fixed now on phet-dev.  Let me know if it looks ok and I'll deploy it to figaro.

**Comment by phet-steele** [comment]
@mattpen it certainly is fixed.

**Comment by mattpen** [comment]
This was pushed to figaro.  Closing.
