### ISSUE TITLE
Page refresh subscribes to the newsletter

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#372]
So this is really weird. After clicking on the link in your email to verify an email address, the user gets brought to a simple website page stating the email was successfully confirmed. Well, refreshing this page states I've subscribed to the newsletter. Sure enough an email is sent confirming a newsletter subscription. This is happening even when the check box for the newsletter in the user profile is not checked, and what's weirder is after this email is sent it still isn't checked. @mattpen if this is confusing and you want to see this, I'll screen share you with Skype (didn't want to put a video here). So far I've only tested this with changing an email of an already existing account, but it may be possible while creating an entirely new account.

**Comment by phet-steele** [comment]
Related to phetsims/tasks/issues/480

**Comment by mattpen** [comment]
@phet-steele I'll take a look at this behavior.  I confirmed that you have indeed NOT been registered for the newsletter, even though you got an email saying you had.

**Comment by phet-steele** [comment]
@mattpen this issue has an ugly twin! Clicking "Resend" on the Awaiting Email Confirmation page AFTER successfully registering shows this:

![websiteregistrationnews](https://cloud.githubusercontent.com/assets/5863899/13016678/700b33e8-d17d-11e5-8551-c6702126b873.PNG)

Notice it's talking about my newsletter subscription.

**Comment by mattpen** [comment]
Updated priority per request from @ariel-phet

**Comment by mattpen** [comment]
@phet-steele I changed the page so that if they click on a confirmation link a second time or refresh the page, it will send them to the sign on page instead.

This fix has been posted to phet-dev.  Please let me know if you find any way to recreate the same behavior.

**Comment by mattpen** [comment]
I just noticed similar behavior when hitting "Resend" on the Awaiting Email Confirmation page.  I'll try to fix this tomorrow.

**Comment by mattpen** [comment]
I fixed the behavior on the "Awaiting ..." page also - https://github.com/phetsims/website/commit/52468ce2f4c9d67218c00db5de350f960235ed56

This will be deployed to phet-dev soon.

**Comment by mattpen** [comment]
The fix was deployed to phet-dev. @phet-steele, can you check?

**Comment by phet-steele** [comment]
@mattpen in both cases I was directed to the home page. This correct?

**Comment by mattpen** [comment]
If you were already signed in and didn't have a destination in the URL parameters, then yes that's correct.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
