### ISSUE TITLE
DocumentRoot problems

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#373]
@jonathanolson no new activities have been appearing on phet-dev since 11/13, and the 12 activities on and before that date aren't working (only on phet-dev):

Guía de consejos para docentes: balanceando ecuaciones químicas 11/13/15
Guía de consejos para profesores: bajo presión 11/13/15
Wave Basics for Middle Schoolers 11/12/15
States of Matter - Lab Simulation - student procedures and questions 11/11/15
Forces and Free Body Diagram Lab 11/10/15
Densidade 11/9/15
Densidades 11/9/15
Hooke's Law inquiry lab 11/5/15
Resistencias en serie y en paralelo 11/3/15
A PhET-Based Laboratory Activity in Teaching Direct Current Circuits (Guided Inquiry with Formative Assessment)  11/3/15
Fluid Pressure and Flow Phet Simulation worksheet 11/2/15
Momento de uma força 10/27/15

**Comment by phet-steele** [comment]
@jonathanolson this was probably fixed by phetsims/website/issues/367. Wasn't this an automated procedure @mattpen?

**Comment by mattpen** [comment]
@phet-steele I think this was automated at one time but was causing problems with some testing on phet-dev due to the database being synced with figaro.  I'll have to check the script and see if those are automatically copied over.  It sounds like I'll need to add these in.

**Comment by jonathanolson** [comment]
@mattpen, could we then use the script manually (when you want) to copy over both the DB contents and the document root files?

**Comment by mattpen** [comment]
@jonathanolson I manually ran a script written by Aaron, apparently its not pulling over the teacher's guide.  Its pulling some of the document root as the new sims are all there.  By automated I meant run it as a cron job, apparently Aaron had it set up to run at regular intervals but stopped for some reason.  I'll take some time to look at the script and see if we can use it to copy the teacher's guides too.

**Comment by mattpen** [comment]
@phet-steele - the new activities should be working now.  Please confirm or let me know if you find anything else that is missing.

**Comment by phet-steele** [comment]
@mattpen recent activities are working.

**Comment by mattpen** [comment]
I updated the script to automatically copy the activities and put it back on a crontab schedule.
