### ISSUE TITLE
On iPad why have sim open in "new tab"?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#374]
I think this is a good question to discuss with the dev team as a whole, but I noticed that currently, on the iPad when you open a sim from the website it opens up in a new tab. In my opinion this behavior diminishes the user experience since screen real estate is at a premium. If you only have the PhET site opened, and clicking the run button on the sim opened the sim without opening a new tab, you would have more room in the viewing window.

I think opening in a new tab is good behavior for laptops and such, but it seems to me suboptimal in the case of an iPad. Can we dictate the behavior based on browser (so for instance specify what happens in mobile safari?)

Curious what the rest of the dev squad thinks

@jonathanolson @jessegreenberg @samreid @pixelzoom @jbphet 

@mattpen - can you let me know if what I am suggesting is even an easy possibility?

**Comment by mattpen** [comment]
@ariel-phet Yes, we can detect the browser version in JavaScript.  We can also detect specifically if the device is an iPad from the user agent string. From there we can change the target tag in the link.

**Comment by pixelzoom** [comment]
It's a tradeoff. It gains more screen real estate (if the PhET site was the only tab open in the browser to begin with), but requires navigating back to the PhET site.  I have no strong opinion, sounds like a management decision to me.

**Comment by samreid** [comment]
No strong preference from me, here are my $0.04:

* keeping things consistent across platforms is nice (keeps code simple, etc)
* whatever reason we have for opening a separate tab on desktop probably also applies to iPad
* A future version of mobile safari could change how the tabs and vertical space works (I think a few versions ago it was different, always keeping the same vertical space for N=1 tabs compared to N>1 tabs).
* on the other hand the extra vertical pixels seem nice on iPad

**Comment by pixelzoom** [comment]
Thinking about this more... -1 for doing something different on iPad.  It complicated things (see @samreid comments above).  And if someone really needs the additional space, they can close the PhET website tab.

**Comment by ariel-phet** [comment]
Well I think there is a general question then maybe as well...usually links *internal* to a site do not open in separate tabs, general practice is to only open external links in a new tab. Sims seem to fall in a bit of a gray area...do we really consider these external links?

**Comment by pixelzoom** [comment]
I'm not sure what "usually" is referring to - PhET convention? general websites?  But the general wisdom is that you open a new tab/window when the user is leaving your site or beginning a task that is likely to occupy them for many minutes (eg, reviewing statements on a banking site.)

**Comment by pixelzoom** [comment]
I'm not sure what "usually" is referring to - PhET convention? general websites?  But the general wisdom is that you open a new tab/window when the user is leaving your site or beginning a task that is likely to occupy them for many minutes (eg, reviewing statements on a banking site.)  Sims clear fall into the latter category.

**Comment by pixelzoom** [comment]
Another thought... Opening sims in a new tab increases the likelihood that they will inadvertently have multiple sims open.  And on iPad, that has a good chance of crashing the browser.  If sims did *not* open in a new tab, then it's more likely that only 1 sim at a time would be open.

**Comment by pixelzoom** [comment]
So now I'm leaning towards not opening sims in a new tab on mobile devices, so that we're less likely to crash the browser by having multiple sims running.

**Comment by samreid** [comment]
> So now I'm leaning towards not opening sims in a new tab on mobile devices, so that we're less likely to crash the browser by having multiple sims running.

To me, that seems like the most important concern in this thread.  Perhaps before acting on it, we should do a modern test of how many sims can be open in different tabs before they start crashing?  @ariel-phet is this something @phet-steele can test, say on iPad2?

**Comment by jonathanolson** [comment]
Also, if crashing is a symptom, we can work at minimizing memory usage.

It also is fairly annoying for me every time we start a sim in a new tab, and it seems like people would use the back button to navigate back if they want to go back.

**Comment by pixelzoom** [comment]
2/2/16 dev meeting: Deferred to 2/4/16 when @jonathanolson and @ariel-phet are available.

@jbphet @jessegreenberg @mattpen please weigh in before the next meeting.

**Comment by jessegreenberg** [comment]
> and it seems like people would use the back button to navigate back if they want to go back.

This is especially true for accessibility.  Browsers are very bad at telling AT when a new tab opens.  Unless we tell the user that a new tab is opening in the markup, screen reader users will navigate to 'back' at first.

**Comment by mattpen** [comment]
I don't have a strong opinion either way.  Personally, I feel like the site flows better if we open the sim in the same tab on mobile devices.  This seems to align with the performance and accessibility concerns mentioned above.

**Comment by jbphet** [comment]
I think opening them in the same tab on mobile devices would be a good way to prevent excessive memory use.

**Comment by ariel-phet** [comment]
OK, seems like opening in the same tab is the way to go, especially given the accessibility concerns. Going to make the management call here...opening in the same tab it shall be.

@mattpen make it so (I assume this only applies to flash and HTML5 sims since they are the only ones that open in the browser)

Removing developer meeting label. Not a rush in terms of priority but I am guessing this is a fairly straightforward change.

**Comment by pixelzoom** [comment]
@ariel-phet please clarify whether this change is for iPad only, or for all mobile devices.  That was an unanswered question at 2/2/16 developer meeting.

**Comment by ariel-phet** [comment]
@pixelzoom @mattpen to clarify, when I say all platforms, I mean everything. If you open an HTML5 or Flash sim it should open in the same tab, regardless of device (not just mobile). As was mentioned, if possible best to have it consistent instead of specialized code per device. And the accessibility argument was the tipping point for me.

**Comment by mattpen** [comment]
@ariel-phet - I applied this change.  It's ready to deploy to figaro tonight.  Do we need to do any testing? I don't think it will break anything.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.  I tested launching Java, Flash and HTML sims on FF, Chrome, and IE on Win 7 and everything seems to be fine, @ariel-phet tested iPad.
