### ISSUE TITLE
Can't follow links that are close to the header

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#375]
@mattpen If a link in an answer is too close to the header and arrow, the link cannot be clicked. Instead the question is just collapsed.

Link that is too close:
![closelink](https://cloud.githubusercontent.com/assets/5863899/12860895/65e237fe-cc14-11e5-8481-a5567a16b706.PNG)

When hovering over "here", I'm being directed to the link for the header. Clicking just closes the question.

**Comment by mattpen** [comment]
@phet-steele - I deployed the fix to phet-dev this morning.  Please confirm and reassign if it's not working.

**Comment by phet-steele** [comment]
@mattpen it's good! :football:
