### ISSUE TITLE
Duplicate emails/accounts

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#377]
@oliver-phet @ariel-phet 

We currently have ~150 duplicated email addresses in the website database.  Apparently at some point in the history of site we allowed people to register with the same email twice if they used case differently.  When this happens, tomcat refuses to allow either address to logon with the correct password.  

The behavior is being fixed as part of #167, I opened this issue to track discussion of how to handle the  problematic accounts.

**Comment by ariel-phet** [comment]
Back to you @mattpen, please summarize the plan in this issue

**Comment by ariel-phet** [comment]
@mattpen said
> 
> Discussed with @ariel-phet via skype.
> 
> This will probably not be a task that can be done by @phet-steele because the admin utility gives an internal error for duplicated accounts. I'll write a script to delete the older account as long as there are no associated contributions. If there are contributions, I'll flag the user and process the resulting list manually.

**Comment by mattpen** [comment]
All duplicates were deleted from the database tonight.  In the case where one of the accounts was a teammember or trustedtranslator, I deleted the less privileged account.  In the case where both accounts had activity (contribution or translation), I copied all the activities to the more complete profile and deleted the other. There were 152 users removed overall.
