### ISSUE TITLE
Scrolling carousel on home page partially blanks out

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#38]
Not sure when I first noticed this, but it's been at least a few weeks.  The carousel that displays the scrolling sims is turning gray in places, is blocky, and changes as the animation changes.  Several screen shots below.

May be a known issue, but I didn't see anything obvious in the issue list.  If so, feel free to close.

I'm seeing it on Chrome 38, Win 7.  

![website-carousel-issue](https://cloud.githubusercontent.com/assets/3082831/5249004/f22793c0-793c-11e4-9fa8-bbe8d2a42c32.png)
![website-carousel-issue-2](https://cloud.githubusercontent.com/assets/3082831/5249011/fa1d8134-793c-11e4-89c5-3fe9587efc81.png)
![website-carousel-issue-3](https://cloud.githubusercontent.com/assets/3082831/5249014/01c47726-793d-11e4-8669-2d56e0c7779a.png)

**Comment by aaronsamuel137** [comment]
This has to do with the old front page. Closing
