### ISSUE TITLE
"I am a..." profile field is behaving strangely

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#382]
@mattpen this occurs after registering, and going to the edit profile page. If my profile has me checked as a "Parent" after registering, I can go to the edit profile page and see that the website has changed me from being a "Parent" to being a "Teacher educator / Coach". Clicking "Update", then going back a second time to the edit profile page will reveal that the website removed me from being a "Teacher educator / Coach" and changed me to having nothing checked in that category. This change happened after pressing "Update", effectively making my account have nothing selected in his category. Trying to update here causes an error since I now have an empty field.

**Comment by phet-steele** [comment]
Note that other check boxes in this category don't behave this way.

**Comment by mattpen** [comment]
@phet-steele - Can you recreate this behavior for any value other than "Parent"?  It appears the parent column is missing from the database!

**Comment by phet-steele** [comment]
> Can you recreate this behavior for any value other than "Parent"?

No, except in the original comment my profile went from Parent --> Coach --> null, but I get the same result if I exclude Parent and start from Coach --> null.

**Comment by mattpen** [comment]
```
user.setTeacherEducator( checkboxMap.get( TEACHER_EDUCATOR ).getModelObject() );
user.setTeacherEducator( checkboxMap.get( PARENT ).getModelObject() );
```

This might be the problem!

**Comment by mattpen** [comment]
Tagged the wrong issue - ignore https://github.com/phetsims/website/commit/52468ce2f4c9d67218c00db5de350f960235ed56

**Comment by mattpen** [comment]
@phet-steele - The fix has been deployed to phet-dev.  Does it look ok now?

**Comment by phet-steele** [comment]
@mattpen fixed, sir!

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
