### ISSUE TITLE
Error message can't be found on email change page

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#383]
@mattpen I hope this screenshot makes this issue self-explanatory. I simply came to this page and clicked "Change Email" without entering anything. Also there is no error for leaving the email fields empty:

![websiteregistrationlost](https://cloud.githubusercontent.com/assets/5863899/13017650/7db5f91a-d182-11e5-9551-9b8e2165bf8c.PNG)

**Comment by mattpen** [comment]
@phet-steele - I published a fix to phet-dev.  Please test and reassign to me for changes or deployment.

**Comment by phet-steele** [comment]
@mattpen looks fixed.

**Comment by mattpen** [comment]
Thanks @phet-steele I'll post this on the next deploy.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
