### ISSUE TITLE
NewsletterEntity not available

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#384]
As described in an email to phethelp, when translators attempt to open the NewsletterEntity they are receiving an Internal Error.  The root cause is that we are passing a generic user to ConfirmEmailPanel but failing to initialize the phetUser.id.

@oliver-phet - This should be fixed the next time I deploy the website, probably by the end of the week.

**Comment by mattpen** [comment]
The fix was deployed to figaro.  The newsletter page is now accessible for translation.

**Comment by oliver-phet** [comment]
This was also verified by the translator.
