### ISSUE TITLE
A bit more negative space before help center items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#386]
I took a quick look at the help center, great work getting this up!

However, it could use a slight design tweak. The items with blue triangles are all very tight to the selection icons. There needs to be a bit more breathing room as shown in the mockup below:

![help center](https://cloud.githubusercontent.com/assets/4051174/13136428/a91a82bc-d5d6-11e5-9484-de101636f781.PNG)

**Comment by ariel-phet** [comment]
@mattpen this seems like an easy adjustment on the help center pages, would be nice to make the adjustment soon

**Comment by mattpen** [comment]
I added some additional padding to the navigation icons and published it to figaro tonight.  I'm closing the issue as the pages appear to match the mockup above.

**Comment by ariel-phet** [comment]
Looks good, thanks!
