### ISSUE TITLE
Swahili translation to be removed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#387]
@mattpen rutherford-scattering_sw.jnlp does not exist, nor has ever existed, and should be deleted.

**Comment by mattpen** [comment]
The rutherford-scattering_sw.jnlp and rutherford-scattering_sw.jar files did not exist on figaro or phet-dev.  The translated name also  appeared to be the same as the swedish translated name, so this translation appears to have been published in error.  I removed it from the database.
