### ISSUE TITLE
Remove green triangle in side bar navigation

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#388]
@mattpen please remove the green triangle from the sidebar navigation, this should be a quick tweak.

![green](https://cloud.githubusercontent.com/assets/4051174/13236916/f9355f40-d984-11e5-8268-2d289955e6e9.png)

**Comment by mattpen** [comment]
@ariel-phet - This change was deployed to phet-dev. I'll go ahead and push it to figaro on the next deploy.

**Comment by ariel-phet** [comment]
excellent thanks!

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
