### ISSUE TITLE
New Footer 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#390]
The next piece of design work to be done on the website (after the new sims page and a few other minor tweaks are finished) will be to implement a new footer. The design is shown below:

![footer](https://cloud.githubusercontent.com/assets/4051174/13240423/b8dee662-d99f-11e5-97ed-f649c53a495f.PNG)

This project will involve several important tweaks:

- [x] Social media icons will be B&W using font awesome 
- [x] We will change the icons on sim pages to also be B&W to match the footer
- [x] The locale selection will now be a drop-down menu

Links in the footer should point to the following:
- [x] Contact should http://phet.colorado.edu/en/about/contact
- [x] Source code should point to http://phet.colorado.edu/en/about/source-code
- [x] Translate should point to http://phet.colorado.edu/en/for-translators

**Comment by ariel-phet** [comment]
Self-assigning to discuss these points with @amanda-phet to make sure I am clear on the details

- I assume we are removing the sidebar "About PhET" category with this change?
- Should the various pages (such as source code) still be under the "about" hierarchy?
- What intermediate tweaks will we make to the current front page "table"?
 - now many links will be covered in the footer?

**Comment by mattpen** [comment]
Will the sponsor logos and the PhET logo be links to their respective web pages or just static images?

**Comment by ariel-phet** [comment]
Discussion with Amanda:

- when we hover over icons get color (ie facebook blue, youtube red)
- yes sponsors should be links
- PhET logo should link to the homepage
- "about" category removed from sidebar navigation
- "for translators" category removed from sidebar navigation
- "about" category removed from sidebar navigation
- "for translators" category removed from sidebar navigation
- Need a way to access teaching resources, research, etc from homepage, but could rearrange table or do an alternative solution
- fine to keep "about" category urls under the about heirarchy (source code, licensing, contact, our team, sponsors etc) 
- News category will also be gone from sidebar, but linked with envelope icon
- Everything under the about sidebar will be accessed from a different place (not the sidebar)
- globe icon is a font awesome icon
- "some rights reserved" should link to licensing page

**Comment by ariel-phet** [comment]
Note - ultimately "Help Center" and "offline access" will also be removed from side bar navigation.

**Comment by ariel-phet** [comment]
@mattpen we should discuss priority of this project on Thursday, but for the moment no work needs to be done. Do however add any further questions/clarifications to this issue in the meantime.

**Comment by mattpen** [comment]
Thanks, I won't start coding yet.  Here are some additional questions:

- Does the speech bubble icon point to the blog?
- Will these colors work for the social media icons? The first four are ripped from their homepages. 
    - Facebook: #3b5998
    - Twitter: #1da1f2
    - YouTube: #cc181e
    - Pinterest: #BD081C
    - Blog: PhET-orange maybe (#d36a04)?
    - Newsletter: PhET-blue maybe (#2a326a)?
- Can you confirm that the links should be all upper-case?
- Should the blue banner wrap from edge to edge (like the header), or have a specific or maximum width?
- The horizontal rules might need artwork, but I'll try implementing in HTML first.  What color should they be? #727272? 
- We will probably need artwork for the blue drop-down arrow in the locale select box.  I can try to style it with css, but it will probably be quicker to design it in AI, especially if it uses a gradient.

**Comment by ariel-phet** [comment]
- Yes, speech bubble is for blog
- Links should be all upper case
- blue banner should wrap edge to edge like the header
- seems easy to try the rules in HTML first
- I think the arrows in the locale selection are mimicking what you see on safari (these look very different in different browsers) I think we can use a standard element.
- The colors you propose  are probably fine, for the PhET colors use and colors that work well from the [PhET Visual Identity Doc](https://docs.google.com/document/d/1WnthgL675uxozx29siRB30zDRWZOgRFxqKC-mW0_q1c/edit#heading=h.y1wn8jx7bgs8)

And reminder, please assign to me to assure responses.

**Comment by mattpen** [comment]
@ariel-phet - All of the text links appear to be black instead of the normal blue link color.  Should they change color on hover?  What about after being visited?

**Comment by mattpen** [comment]
Also, will there be a translation credits line for non-english locales? (As in phet.colorado.edu/de)
![image](https://cloud.githubusercontent.com/assets/11747676/13536553/c795faae-e1fd-11e5-95b4-b790d50844ff.png)

**Comment by ariel-phet** [comment]
Yes, we should have that translation credit line, plan to put it below the locale drop down.

**Comment by mattpen** [comment]
@ariel-phet - Two more questions.

1. All of the text links appear to be black instead of the normal blue link color. Should they change color on hover? What about after being visited?

2. How should the translation select box be translated?  Should all languages (a) always be translated into their own locale (e.g. in /en/  English, Espanol, Deutsch...) , or (b) be translated into the locale being viewed  (e.g. in /en/ English, Spanish, German ...).  I'm personally inclined towards (a).

Thanks.

**Comment by ariel-phet** [comment]
@mattpen 

1. Let's just do change color and get underlined on hover for the moment. No change after being visited (this follows the convention in footers on sites like Amazon)

2. (a) seems correct. That is in essence the way the site works now and it seems correct. If you visit the main site and are looking for say the "french" translation, it makes most sense to see the name of your language correctly, and even more so for locales like arabic or chinese

3. yes I mean those icons, that should help "tame" that page a bit.

**Comment by mattpen** [comment]
@ariel-phet - I think the majority of the requirements specified above have been implemented and published to phet-dev.  The only thing that I could find that is missing is the updated artwork for the sponsors.  Do you have any comments or additional requirements at this time?

**Comment by ariel-phet** [comment]
@mattpen a few minor tweaks at this point:

1. When I open on chrome at a wide aspect ratio the left side of the footer cuts off (see screenshot below)

2. I think the icons in the footer need to be increased in size (facebook, twitter etc) The "Youtube" one is a bit hard to read. Maybe lets try increasing those by about 20% (that might also require some more vertical negative space below them once you increase in size)

3. The icons on the sim page now feel a bit stark. There were definitely too many colors before, but now they are pretty harsh. Maybe lets try a colored circle behind each (like on the website now) but first lets just try black and invert the icon (so facebook is a white "f", twitter is a white bird etc). This might take some tweaking to find something that works well...

![capture](https://cloud.githubusercontent.com/assets/4051174/13628150/e7aa9c36-e58c-11e5-93a0-e5450b09116d.PNG)

**Comment by ariel-phet** [comment]
Perhaps try the icons on the sim page in grayscale so as not to be so stark

![capture](https://cloud.githubusercontent.com/assets/4051174/13628194/43a834e4-e58d-11e5-9e14-fb30eb887594.PNG)

**Comment by ariel-phet** [comment]
Actually now that I see that...

Here is what I am going to recommend for those icons:

1. Change the order so facebook and twitter are first and second respectively (keeping the circles)
2. Have facebook and twitter in their normal colors
3. do the other 4 icons in black and withe (but with the circles)

Lets see how that looks

**Comment by ariel-phet** [comment]
TED talks uses that style

![capture](https://cloud.githubusercontent.com/assets/4051174/13628286/294671a0-e58e-11e5-9004-e6330ef20f1f.PNG)

**Comment by mattpen** [comment]
@ariel-phet - I can use the existing artwork for Facebook and Twitter and use FA icons for Pinterest, StumbleUpon, and Reddit.  YouTube provides a black icon in 48px that I can use.

Its worth noting that Pinterest and StumbleUpon appear to be particular about the use of color of their icons.
+ https://business.pinterest.com/en/brand-guidelines
+ http://www.stumbleupon.com/press/stumbleupon-image-use-guidelines

Here's how it would look:

![image](https://cloud.githubusercontent.com/assets/11747676/13647189/29e8a972-e5f0-11e5-80d7-bcb897778baf.png)

**Comment by ariel-phet** [comment]
Yeah....true but a google image search of "pinterest black white icon" makes me think they are not crazy picky. 

Can you put Pinterest in color above youtube and lets see what that would look like.

**Comment by mattpen** [comment]
How does this look?  (Aside from some minor differences in size and horizontal alignment)

![image](https://cloud.githubusercontent.com/assets/11747676/13648080/329928e0-e5f4-11e5-9257-82571a61097c.png)

**Comment by ariel-phet** [comment]
I think that looks pretty good.

I think for consistency lets next try making the black white icons use the color of the download and embed buttons.

**Comment by amanda-phet** [comment]
Something you may want to consider with respect to different icons (order, color, etc.)... some of these share a link to the sim page and others just bring you to the respective phet page. Not sure if we care or not, though! In the future I imagine we'll want all of these icons to do some sort of sharing action that is specific to the sim.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Mar 9, 2016 at 11:44 AM -0800, "Ariel Paul" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that looks pretty good.

I think for consistency lets next try making the black white icons use the color of the download and embed buttons.

-

**Comment by mattpen** [comment]
@ariel-phet - Fixes for 1, 2, and 3 from your [previous comment](https://github.com/phetsims/website/issues/390#issuecomment-194149564) have been published to phet-dev.  Is there anything else to be improved for now?

**Comment by ariel-phet** [comment]
@mattpen -- apologies this may take a few iterations...a few more tweaks:

1. For the icons can we have a hover behavior (so youtube, stumble upon, reddit have their respective hover colors?)

2. The "donate" button on the sim pages now feels very clashy in that orange. Can we try making it the same color scheme as the download and embed buttons?

3. And then lets try the bottom three icons on the sim page (youtube, stumble upon, reddit) in black and white

4. Can the footer links also change color (in addition to underlining) on hover? It appears the front page "table" link turn a blue on hover (those should actually also underline from an accessibility point of view on hover) 

With this new footer we will need to make some adjustments to that front page table, but that is not mocked up yet

Also the blue of the footer does not seem to match the blue of the banner (it looks like you took the color from the mockup) but it looks odd for these to be different colors. Lets change it to the same blue for the moment, but I think it will need some more worker...

The rest of the footer is looking really good!

**Comment by mattpen** [comment]
Additional requirements discussed via skype with @ariel-phet:

- [x] Index panel table links should underline on hover.
- [x] The footer panel navigation links should highlight in link-blue on hover.
- [x] Use #f0f0f0 for the highlight background
- [x] The phetlogo and copyright should be in black
- [ ] The higlight background should be slightly shorter after the new images are added
- [ ] Replace odonnell image with new schools image
- [x] Vertically center the translation dropdown between links and highlight background
- [x] The Donate button should be blue
- [x] Use the youtube-play icon instead of youtube text icon in footer
- [x] Side panel selected items should be bold black font, unselected should be grey normal-weight
- [x] Remove "For Translators" from sidebar navigation

**Comment by mattpen** [comment]
@ariel-phet - a few questions:

- Should the Sidebar navigation links turn blue and highlight on hover?
- The horizontal rule on the sim pages is still orange, should this change to blue or grey?

**Comment by ariel-phet** [comment]
@mattpen 

- Yes, lets try blue and highlight on hover for now
- Lets try black and thinner for the rule (more like the footer rule)

**Comment by mattpen** [comment]
@ariel-phet - The changes should be live on phet-dev now.

**Comment by amyh-phet** [comment]
New table format and contents.

![table_front_page-01](https://cloud.githubusercontent.com/assets/13650180/13889629/389ded5a-ed0d-11e5-915f-7f835e1e2ae1.png)

Text for table:
Founded in 2002 by Nobel Laureate Carl Wieman, the PhET Interactive Simulations project at the University of Colorado Boulder provides over 130 free interactive math and science simulations.  PhET sims are based on extensive education research and engage students through an intuitive, game-like environment where students learn through exploration and discovery.

INTERACT, DISCOVER, LEARN!

**Comment by mattpen** [comment]
@ariel-phet - All changes that were discussed have been published on phet-dev.  Any more tweaks before I deploy to figaro?

**Comment by ariel-phet** [comment]
@mattpen I believe you and I just skyped amount my final polish suggestion. All is looking really good, and a very nice improvement. Go ahead and deploy after that one front page paragraph tweak is incoroprated

**Comment by mattpen** [comment]
The new footer was deployed to figaro tonight.  Closing.
