### ISSUE TITLE
Translate the Website link is being hidden in non-english locales

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#393]
Currently, if you view the website in any non-english locale, the link to "Translate the website" does not appear.  This doesn't seem intuitive to me, should we display this link in all locales?

Example - link is missing in bottom-left:

![image](https://cloud.githubusercontent.com/assets/11747676/13371153/273af3c8-dcdc-11e5-9666-8cb3d5fed8c3.png)
![image](https://cloud.githubusercontent.com/assets/11747676/13371155/339e26b2-dcdc-11e5-8993-141361c9334f.png)

**Comment by ariel-phet** [comment]
Yes, we should display in all locales.

The obvious use case is if someone uses the website in a non-english locale and thinks "hey I would like to help translate the site!"

**Comment by mattpen** [comment]
This was deployed to phet-dev.  I checked a handful of locales and it appears to be working normally.  I'll publish it on figaro with the next deploy.

**Comment by mattpen** [comment]
Published to figaro.
