### ISSUE TITLE
HTML5 translation credits "by locale" should be in alphabetical order

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#395]
@mattpen currently if you go to http://phet.colorado.edu/en/for-translators/translation-credits/by-locale the list of locales is not alphabetical. That seems odd (for instance Albanian is near the bottom).

Not a high priority, but I imagine this is an easy fix.

**Comment by mattpen** [comment]
It looks like the current sort is alphabetical by locale code (Albanian is "sq").  I should be able to get this done before we start working on ox as its an easy fix.

**Comment by mattpen** [comment]
The fix has been published to phet-dev.  The Albanian translation hasn't been synced yet, but Chinese(Traditional) and Spanish(Peru) are now in the alphabetically correct places.

@ariel-phet - If this looks ok I can publish to figaro in the next deploy.

**Comment by ariel-phet** [comment]
Looks good!

**Comment by mattpen** [comment]
This was published to figaro tonight.
