### ISSUE TITLE
New Videos and Video Labels for the Front Page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#399]
At status meeting 3/10/2016 it was discussed that perhaps our scrolling video player should label each video by category ie

Physics, Chemistry, Math, Biology, Earth Science

And clicking on the video brings you to that category

The idea would be to better highlight the range of subjects we cover.

**Comment by ariel-phet** [comment]
@phet-steele you and I should game plan this a bit

**Comment by ariel-phet** [comment]
Here is what I am thinking:

1. Physics: use ESPB after it is redeployed with energy representations opened (probably just the bar graph is fine)

2. Chemistry: Use concentration, shaking in some particles adjust faucet and evaporation slider

3. Math: Show finishing a cool challenge on the game of Area Builder

4. Biology: Use Neuron showing stimulating the neuron (options checked, but 

5. Earth Science: Use Under Pressure once redeployed, doing something cool/eye catching.

What say you @phet-steele?

**Comment by phet-steele** [comment]
> Biology: Use Neuron showing stimulating the neuron (options checked, but

@ariel-phet but what? And only five videos? We have 7 currently on the site. I think we could sneak in another Physics video (we have plenty) like WoaS or M&L. Unless there's some reason I'm not thinking of to not double up on a category?
I do like the choices you have, though.

**Comment by ariel-phet** [comment]
@phet-steele 

- edited Neuron above, thanks for reminding me to finish my thought!
- I think 5 is all we need, since the will now be representing categories, most people will probably not hang on the home page very long, so I think one representative sim for each category is fine.

**Comment by phet-steele** [comment]
Well then I guess I shall wait for ESPB and UP to be redeployed.

**Comment by ariel-phet** [comment]
@phet-steele - it might be good for you to make a few of the vids, so we can test them out on phet-dev. You might recall that we tried putting a new video up (hooke's law) and had some issues.

**Comment by phet-steele** [comment]
@ariel-phet certainly. I recall a few exchanged words with this where we said gifs are okay?

**Comment by ariel-phet** [comment]
gifs might be nice if we can make them nice high resolution

**Comment by phet-steele** [comment]
@ariel-phet I'll do this eventually...have to find a high resolution screen to record on.

**Comment by ariel-phet** [comment]
@phet-steele I think within the next month would be good (so by mid June).

I believe there is a retina macbook or two....inquire with @oliver-phet

**Comment by phet-steele** [comment]
@mattpen I've emailed you some videos to upload :smile:, .ogv files coming later, but I'd like to get @ariel-phet's opinion when they are on phet-dev.

**Comment by mattpen** [comment]
@phet-steele - Can you please send over the jpg's too please? We use these as a fallback as the videos are loading and for iphones/ipods.

**Comment by phet-steele** [comment]
@mattpen jpg's sent.

**Comment by mattpen** [comment]
@ariel-phet @phet-steele - The new videos are up on the home page at [phet-dev](http://phet-dev.colorado.edu).  Can you please check and let me know if anything needs to be changed?

Steele noticed the black bars on ESPB already and is working on re-recording

**Comment by ariel-phet** [comment]
Looking good except one minor tweak.

For most of the videos the phet logo is cutoff in the navbar slightly for example

![clip](https://cloud.githubusercontent.com/assets/4051174/15787103/a0e67c04-297d-11e6-9345-872890fc86a9.PNG)

it should look more like this (for some reason only ESPB is correct, and only on Chrome)

![clip 2](https://cloud.githubusercontent.com/assets/4051174/15787120/b4b80cc0-297d-11e6-9de1-c3001a6f6bc7.PNG)

**Comment by phet-steele** [comment]
@mattpen Videos remade and sent, along with jpg's.

**Comment by mattpen** [comment]
@phet-steele - the new jpgs/mp4s are up on phet-dev.

**Comment by phet-steele** [comment]
@mattpen I like it, your turn @ariel-phet

**Comment by ariel-phet** [comment]
I like it, looking good!

**Comment by mattpen** [comment]
Alright,  I'll push the videos over when I deploy the changes to the rotator script.

**Comment by mattpen** [comment]
The new videos and category links were deployed to figaro tonight.
