### ISSUE TITLE
Videos don't play automatically on iOS

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#40]
The carousel will appear to be just a carousel of images on iOS, unless the user actually clicks the buttons to scroll left or right, at which point the video will begin playback.

There is nothing we can do to fix this since it is a feature of iOS designed to save mobile data:

"In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

This plays the movie: 
```html
<input type="button" value="Play" onclick="document.myMovie.play()">
```
This does nothing on iOS:
```html
<body onload="document.myMovie.play()">
```
"
source: http://developer.apple.com/library/safari/#documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

**Comment by ariel-phet** [comment]
Team settled on static images, closing.

**Comment by aaronsamuel137** [comment]
@kathy-phet had a good thought to use animated gif images for iPhone. After looking into it a bit, I think it will work just fine. I'll work on this.

**Comment by ariel-phet** [comment]
Try getting @orejolaphet to send you gif's made from camtasia original files with highest quality possible.

**Comment by ariel-phet** [comment]
None of these solutions worked...closing
