### ISSUE TITLE
Have we registered phet.colorado.edu with the Google Search Console?

### ISSUE THREAD

**Issue by samreid** [phetsims/website#401]
While I was testing the robots.txt for phet-io.colorado.edu I was sent this email from Google:

![image](https://cloud.githubusercontent.com/assets/679486/13693362/b0158444-e707-11e5-8769-4ab47668ee99.png)

I'm wondering if we have done that for phet.colorado.edu, or if we should.

@ariel-phet and @mattpen can you take a look and make a recommendation?

**Comment by mattpen** [comment]
phet.colorado.edu is registered and setup in the search console.  You can access the dashboard by using the phetadmin@gmail account.  

I browsed through the various analytics.  The biggest issue appears to be a lack of mobile support.  

@samreid - Anything else to do here for now?

**Comment by samreid** [comment]
Sounds good, thanks!
