### ISSUE TITLE
Add in New Bronze Sponsor De Agostini Scuola

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#403]
Need to add a new sponsor ($3K) to the Bronze sponsorship
The URL is
http://deascuola.it/

![dea_logo](https://cloud.githubusercontent.com/assets/10424210/13705229/1bb0b00c-e75d-11e5-97c8-9133b95e8a43.png)

**Comment by ariel-phet** [comment]
@mattpen marking this medium priority since it should be quick and easy

**Comment by mattpen** [comment]
@kdessau-PhET Should this also be added to the rotating sponsors on the home page and sim pages?

**Comment by kdessau-PhET** [comment]
@mattpen Yes. Please also add this to the rotating Featured Sponsor slot weighted as a Bronze sponsorship. Thanks.

**Comment by mattpen** [comment]
@kdessau-PhET - This is now live on phet-dev.  I'll publish it on the main site on the next deploy.

**Comment by mattpen** [comment]
@kdessau-PhET - Dea Scuola has been added to the sponsor page and roating feature on the main site.
