### ISSUE TITLE
Problem with Social Media link alignment on Tech Award page

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#407]
The social media links on this page are aligned on top of the video.  They should probably be adjusted to the right a bit.  This could be fixed as part of #390.

@ariel-phet - please comment on the priority.

![image](https://cloud.githubusercontent.com/assets/11747676/13853189/4092e692-ec2b-11e5-96a2-7788699f24cd.png)

**Comment by ariel-phet** [comment]
Looks close on phet-dev, but appears like the video just needs to move down a tad.

seems easy to address with the other changes

![capture](https://cloud.githubusercontent.com/assets/4051174/13854835/0ab2b680-ec33-11e5-8c5c-9cd52ac9f4cd.PNG)

**Comment by mattpen** [comment]
@ariel-phet 

Does this look OK?

![image](https://cloud.githubusercontent.com/assets/11747676/13882445/09fcc376-eceb-11e5-97ac-fac654eab464.png)

**Comment by ariel-phet** [comment]
@mattpen yes, for now...the about and awards and such section could use a layout overhaul, but this certainly looks fine for now.

**Comment by mattpen** [comment]
Deployed to figaro tonight with the footer. Closing.
