### ISSUE TITLE
Chinese Simplified & Traditional headers share the same link

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#409]
Hey @mattpen, came across this with dumb luck. The locale headers on the HTML5 Translation Credit page for "Chinese (Simplified)" and "Chinese (Traditional)" both use the same href="#zh-header". Because of this, only the "Chinese (Simplified)" header can be expanded. Clicking "Chinese (Traditional)" only affects the expansion of "Chinese (Simplified)".
Auxiliary note: every header has a style attribute "height: 0px;" whose pixel value dynamically changes when expanding and collapsing....except the header for "Chinese (Traditional)".

**Comment by phet-steele** [comment]
Page I'm talking about: http://phet.colorado.edu/en/for-translators/translation-credits/by-locale

**Comment by mattpen** [comment]
@phet-steele - The headers now use the full locale instead of just the country code.  This may have potentially broken links to translation-credits#zh.  Can you check it out and let me know if there is anything else to fix here?

**Comment by mattpen** [comment]
The fix is up on phet-dev now

**Comment by phet-steele** [comment]
@mattpen where would I run into a potentially broken link? I can't think of a URL ending with "translation-credits#zh", do you mean "translation-credits/by-locale#zh-header"? What you've fixed looks great, thanks!

**Comment by mattpen** [comment]
Yes, that's correct. If someone linked directly to https://phet.colorado.edu/en/for-translators/translation-credits/by-locale#zh-header it wouldn't scroll to the correct spot on the page.  It doesn't seem like that big of a deal as you get to the credits page anyway, so I'll deploy as is.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
