### ISSUE TITLE
Add HTML5 sim translation credits on "For Translators" page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#410]
@mattpen, on the For Translators page we should probably have a link to the HTML5 Translation Credits.

Perhaps right under where it says
> PhET HTML5 sims can now be translated through the browser. To request access to the HTML5 translation utilty, please email phethelp@colorado.edu

Add a line break and then have a link that says "HTML5 simulation translation credits" that links to http://phet.colorado.edu/en/for-translators/translation-credits

Otherwise this link is only reachable from the sims themselves, and it seem like one should be able to navigate to it from the site if desired

**Comment by ariel-phet** [comment]
Marking medium priority, only because this should be a very minor and easy change.

**Comment by mattpen** [comment]
@ariel-phet - I've deployed the change to phet-dev.  If it looks ok I'll stage it for deployment to figaro.

**Comment by ariel-phet** [comment]
Yes, looks good!

**Comment by ariel-phet** [comment]
@mattpen ping on this issue?

**Comment by mattpen** [comment]
I was delaying the deploy because there weren't any high-priority fixes, but I can get this done before 5pm tomorrow.

**Comment by ariel-phet** [comment]
Hey @mattpen looks like this was not deployed yet?

**Comment by mattpen** [comment]
I had to delay this because of the server switch-over for the outage last weekend. I'll deploy it early next week.

**Comment by mattpen** [comment]
This was published to figaro today.
