### ISSUE TITLE
Add NewSchools logo to Platinum Level Contributors ($100k+) and rotation

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#411]
Matt - Can you add NewSchools logo to the platinum level contributors. 

Order for platinum should be: 
- Hewlett
- NSF
- Moore
- NewSchools
- O'Donnell
- CU
- JILA
- King Saud (2 logos)
- Kavli
- Carl and Sarah

Thanks!

**Comment by mattpen** [comment]
@kathy-phet - I've deployed the requested changes to phet-dev and I'll publish them to figaro on the next deploy.

**Comment by mattpen** [comment]
The new schools sponsor was deployed to figaro tonight,
