### ISSUE TITLE
Removing blog for server switchover

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#413]
Currently our blog requires wordpress and is going to complicate the server switch over. In addition, the blog is mainly a repeat of posts we have on facebook, and get negligible viewing or engagement. It seems the prudent course of action would be to remove the blog for now, and in the future come up with a plan to make the blog more robust and meaningful for our web presence.

**Comment by kathy-phet** [comment]
Sounds OK to me - but certainly retain copy of the blog entries and history so that we can leverage that going forward as needed. @kdessau-PhET, work for you?

**Comment by kdessau-PhET** [comment]
sure. will it be going back up or are we removing and just having FB, Twitter, etc..


On Apr 5, 2016, at 12:14 PM, kathy-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds OK to me - but certainly retain copy of the blog entries and history so that we can leverage that going forward as needed. @kdessau-PhET<https://github.com/kdessau-PhET>, work for you?

**Comment by ariel-phet** [comment]
I think the plan would be to just have FB, Twitter, etc for the moment

And then in the future when a few other things are settled revamping the blog and coming up with a communication plan to get more engagement (Kate has a bunch of ideas around this), and my guess is it might be a great place in the future to talk about PhET-iO/accessibility stuff in more depth.

**Comment by kdessau-PhET** [comment]
Sounds fine to me. I also have just downloaded the backup of the blog:

**Comment by kdessau-PhET** [comment]
Where do you want the backup?

**Comment by ariel-phet** [comment]
We will discuss at status meeting (I think your backup can just be on google drive or such for the moment @kdessau-PhET)

**Comment by mattpen** [comment]
I'm going to begin removing references in the branch for the new server

**Comment by mattpen** [comment]
@ariel-phet - What should we replace the blog with on the footer panel?

**Comment by ariel-phet** [comment]
Nothing for the moment....eventually (in a couple of months) we will put the "app store" icon there.

**Comment by mattpen** [comment]
@jonathanolson - I removed references to the blog from the wicket code.  Is there anything else to be done for this issue?

**Comment by jonathanolson** [comment]
Don't think so, closing.
