### ISSUE TITLE
support for multi-language installer seems to have gone away

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#415]
About four years ago, @jonathanolson and I worked together to make it possible to create versions of the installers that include translated versions of the web site.  Information about the implementation of the feature can be found here: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3331 (you'll need a PhET Unfuddle account).  The web site used information in the user agent field to decide which languages to allow in the rip.  The footer of the web site recently changed to be a combo box for selecting the language, and I'm guess that this broke the multi-language feature, but I'm not sure.  Assigning to @mattpen to look into, and @jonathanolson is free to chime in if he has any insights.

**Comment by jbphet** [comment]
When this feature was originally implemented, the intent was to be able to support installers with multiple languages, for example, English, Spanish, and Arabic.  We haven't had such a request for a while, so if it is easier to support ripping for a particular single locale, that would be acceptable.  For instance, it may work to build the installer using a starting point of, say, ```http://phet.colorado.edu/zh_TW/``` instead of ```http://phet.colorado.edu/```.  In other words **multi-**language support isn't as important as **other-**language support.

**Comment by mattpen** [comment]
Marking this as priority 3 for now, but I plan to work on it as soon as the phet-io and accessibility pages are complete.

**Comment by jbphet** [comment]
We discussed this in the 4/7/2016 developer meeting and decided to revisit in two weeks, since the web developers have a ton of other stuff on their plate right now, and we don't have any hard commitments on delivering alternate-language installers.  Unassigning for now, will reassign then.

**Comment by oliver-phet** [comment]
Our Chinese translator is now requesting having a zh_TW specific installer by "mid May" for the beta release of their Ezgo system. 
@jbphet Do we think we'll have a way to build locale-specific installers by then?

**Comment by jbphet** [comment]
@mattpen have started working on this, so yes, I think we will be able to deliver this by mid-May.  I'll bump the priority up a bit and make sure that we get it done.

**Comment by jbphet** [comment]
@mattpen and I looked at this yesterday and concluded that the main web page will need to have hidden links to the translations requested by the installer (via the user agent) in order to allow the installer builder to include the translations.  @mattpen says that he can have this change deployed by Thursday, April 28th.  Assigning this issue to him, he can assign back once the changes are deployed and at that point I'll test the installer build process end-to-end.

**Comment by mattpen** [comment]
I plan on deploying the hidden links to figaro tonight.

**Comment by mattpen** [comment]
@jbphet - The hidden links are now live on figaro.  Can you test the installer again and let me know if anything else needs to change on the website?

**Comment by jbphet** [comment]
I was recently able to build a set of installers that included Chinese and English versions of the web site.  The installers were tested here, then delivered to the user who requested them.  That user reports that the installers are working well.  I think our work here is done, closing.  Thanks @mattpen!
