### ISSUE TITLE
New Video for New Sims and HTML5 Sims pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#417]
URL:  https://www.youtube.com/watch?v=zsTFNkVnbOY&feature=youtu.be

New Text: 

>Be an HTML5 Hero!
>By converting our sims to HTML5, we make them seamlessly available across platforms and devices. Whether you have laptops, iPads, chromebooks, or BYOD, your favorite PhET sims are always right at your fingertips. 

>By donating to PhET, you can support the continued development of our awesome HTML5 simulations. Become part of our mission today, and transform the learning experiences of students everywhere!  

Also add the donate button from the sim page.

**Comment by mattpen** [comment]
@ariel-phet - This is up on phet-dev now.  Any comments?

**Comment by mattpen** [comment]
@ariel-phet - The pixel polishes from last night have been published on phet-dev.

**Comment by ariel-phet** [comment]
@mattpen this is looking good to me. However, do not push just yet. I want to try to get a few things fixed on our donation page before we deploy.

**Comment by mattpen** [comment]
Discussed with @ariel-phet in a Skype call.  This is now ok to publish.  It should be published on figaro tonight.

**Comment by mattpen** [comment]
@ariel-phet @kathy-phet This was deployed to figaro tonight.
