### ISSUE TITLE
balancing act should be updated in carousel

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#418]
The carousel that scrolls through animations of various sims on our home page includes the Balancing Act simulation.  The artwork for this sim has been updated, so the animation is now out of date.  It should probably be updated using a version of the sim that includes the new and improved artwork (v1.1.0 or later).

**Comment by jbphet** [comment]
Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
This issue is covered in #399 Closing
