### ISSUE TITLE
Buggy line in RegisterPanel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#419]
```java
user.setTeacherEducator( checkboxMap.get( PARENT ).getModelObject() );
```
should be
```java
user.setParent( checkboxMap.get( PARENT ).getModelObject() );
```

and has the following implications for our current data:
1. The teacher educator field (since this line was added) is filled with what the parent values should be, and I believe we've lost values about whether they are teacher educators.
2. We don't know whether people have updated their profiles before/after the "parent" field was added. Thus we can't distinguish whether they are (or aren't) a teacher educator or parent.

E.g. I just checked "parent" in my profile, and updated. The in-memory copy thinks I'm still a parent when I re-visit (due to line 825), but the DB says I am now a teacher educator (due to line 718).

**Comment by jonathanolson** [comment]
Looks like this was partially fixed (line 825) in https://github.com/phetsims/website/issues/382, but missed the fix for line 718.

**Comment by jonathanolson** [comment]
Timeline from my impression:

July 15th, 2015: Commit (buggy) to add parent field made, noted will deploy soon (https://github.com/phetsims/website/issues/249 and https://github.com/phetsims/website/commit/d19f05556e5bf6b8ff55d54e36d20236afeb7c50)
July 20th, 2015: Note about checking it live on Figaro, so has been deployed by now.
February 28th, 2016: Partial-fix commit applied to Figaro.

So we may be able to look at a DB snapshot from July 20th, 2015 and see who was actually a teacher educator then (and mark those users as such in our current DB). Then any users added after that who are marked as a "teacher educator" should have that set to false and "parent" set to true.

**Comment by kathy-phet** [comment]
JO - Would there have been more than one way to get "teacher educator" marked as t? e.g. by checking either teacher educator or parent ... and if so, wouldn't some of those teacher educators be truly teacher educators and not parents?

**Comment by jonathanolson** [comment]
Before July 20th, 2015: Register / edit profile will correctly mark teacher educator as true when it is selected.

After July 20th, 2015: Register / edit profile will write whatever the user marked as "parent" (true/false) into the "teacher educator" field in the DB. Whatever they mark as "teacher educator" in the UI is completely ignored.

This means if a user created their profile before the bug (and marked themselves as a teacher educator), it would be overwritten whenever they update their profile (by whatever is checked for the "parent" field).

So a "true" in the "teacher educator" field means either (or both):
1. They checked the "teacher educator" checkbox in the UI when registering/updating before July 20th, 2015 AND they haven't updated their profile after July 20th, 2015.
2. They checked the "parent" checkbox in the UI when registering/updating after July 20th, 2015.

**Comment by kathy-phet** [comment]
So if you changed all "teacher educator" to parent in the script for post 7/20 registration date. 

Shouldn't all the remaining blanks for post 7/20/15 registrations be teacher educators?

**Comment by jonathanolson** [comment]
Yes, seems the validation would make them enter at least one type. Thus if they have no other type, they SHOULD be a teacher educator.

Let me know if I should regenerate the spreadsheet with that assumption made (just for users with profileupdated = true).

**Comment by jonathanolson** [comment]
@mattpen, this looks to still be an issue. It would be good to fix this when we sanitize things.

Additionally, the partial fix went live between February 24th and 28th according to history. For sanitization, we won't need an end-date for when to apply this fix for now.

**Comment by mattpen** [comment]
@jonathanolson - Line 718 has been fixed in this [feature branch](https://github.com/phetsims/website/tree/profile-updated-date-master), which is currently deployed to phet-dev.

**Comment by mattpen** [comment]
@jonathanolson - The second line has been fixed and deployed to figaro as of today.
