### ISSUE TITLE
Edge users get no sign-in form

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#420]
While on our website in Edge, clicking "Sign-in" in the top right does nothing (on any page).

**Comment by phet-steele** [comment]
Have a console error I think:
```
SCRIPT87: Invalid argument.
phet-v25-min.js (61,56)
```

**Comment by ariel-phet** [comment]
@mattpen pinging on this issue, seems like something we should address

**Comment by mattpen** [comment]
The problem was caused by an incompatibility between edge and the version of jquery we are using.  I found a work around, but it would be nice to migrate to the latest version of jquery soon.

The work-around is ready for the next deploy.

**Comment by mattpen** [comment]
The fix was deployed to figaro tonight.  Due to caching, it will take some time for the functionality to start working over http, but it should be working over https now.
