### ISSUE TITLE
Deactivate the CCK ask pop-up

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#423]
@mattpen we want to re-purpose the donation page for CCK and so we need to remove all instances of the CCK ask pop-up.

**Comment by kathy-phet** [comment]
@mattpen - Please do not delete code, just comment out or otherwise deactivate the pop-up.

**Comment by mattpen** [comment]
@kdessau-PhET @kathy-phet I disabled this functionality on figaro tonight.  I didn't delete any code so we can re-enable the popup at any time.
