### ISSUE TITLE
Add in New Bronze Sponsor for MyTrendyPhone

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#424]
@mattpen We have another Bronze donor that needs to be added on the Sponsor page and in the Featured Sponsor spot with weighting of 1

![mtpdk_logo](https://cloud.githubusercontent.com/assets/10424210/14607151/4383ced4-0535-11e6-8b0c-83af0dcc5366.png)

 MyTrendyPhone

 http://www.mytrendyphone.dk/shop/frontpage.html

**Comment by mattpen** [comment]
@kdessau-PhET - This was deployed to figaro tonight.
