### ISSUE TITLE
New International Reference for Research Page

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#425]
Under the "Publications on PhET Simulations by Other Researchers" section:

Wickham, C. M., Girvan, C., & Tangney, B. Constructionism and microworlds as part of a 21st century learning activity to impact student engagement and confidence in physics. (2016, Feb.) Sipitakiat, A., & Tutiyaphuengprasert, N. (Eds.) _Proceedings of Constructionism 2016_. Paper presented at Constructionism 2016, Bangkok Thailand (34-41). http://e-school.kmutt.ac.th/constructionism2016/Constructionism%202016%20Proceedings.pdf.

**Comment by mattpen** [comment]
@emily-phet - This was added to the research page tonight.
