### ISSUE TITLE
Adding meta tags for "twitter cards" to mutiple site pages

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#426]
I am curious how difficult it would be to add "twitter cards" to several of our prominent pages 

https://dev.twitter.com/cards/types/summary-large-image

This would provide a much richer user experience as I continue to grow our twitter following (and would be nice for the "share this on twitter" button on sim pages for instance)

My thoughts were these cards would be especially nice on:
- all HTML5 sim pages
- the accessibility pages
- our homepage
- potentially our donation page
- possibly the "about" page at some point

With sim pages, accessibility, and homepage being the priority.

**Comment by ariel-phet** [comment]
Ideally I would also really like to have a "player card" for our donation video

https://dev.twitter.com/cards/types/player

**Comment by samreid** [comment]
@mattpen will work with @ariel-phet on this.

**Comment by mattpen** [comment]
High priority cards:

1. Accessibility page
2. Single sim page (BAA or ESP)
3. Donation Video (player card)

**Comment by mattpen** [comment]
@ariel-phet - Here is a preview of how the card will look.  This is taken from a copy of the site hosted at locally at my house, we can't test these on phet-dev or phet-new because of the robots.txt configuration.  The image appears pretty blurry, twitter for some reason is converting the 600x400 image I'm providing to be more like 280x150, then blowing it up again.  They don't make it clear why.  Hopefully its just because its in preview mode.

Are there any changes you'd like to see?  If not I can publish this on figaro for all the sim pages.  The sim pages are generated dynamically, so we can't just test one like we discussed in dev meeting.

![image](https://cloud.githubusercontent.com/assets/11747676/14987890/a91ed790-110e-11e6-8556-375f76a50327.png)

**Comment by ariel-phet** [comment]
@mattpen I think that looks good as a start. Pretty low risk I think to do for all sim pages, and then I can do some test tweets.

**Comment by mattpen** [comment]
OK, I can deploy it to figaro tonight.

**Comment by mattpen** [comment]
@ariel-phet - Twitter cards have been deployed to sim pages on figaro.  Should I aim for the donation video next?

**Comment by mattpen** [comment]
Discussed at dev meeting on 5/5.  

- The player cards are not necessary because the sharing function on YouTube automatically creates one.
- @ariel-phet said that the sim summary cards are showing up as intended when actually added to a tweet.

**Comment by mattpen** [comment]
@ariel-phet - The summary cards should be using the larger screenshot now.  Can you take a look and see if they are showing up as expected for you?  They might take a while to show up, if the cards are not showing up then try putting the url in the card validator first: https://cards-dev.twitter.com/validator.

I noticed an issue where if you share the URL using https the cards are not showing up.  I'll take a look at this over the weekend.

**Comment by ariel-phet** [comment]
Will check it out!

**Comment by ariel-phet** [comment]
@mattpen there was a little funkiness, but as long as I do a tweet using the share on twitter button on a sim page first, all twitter cards for that page work seamlessly thereafter with just the URL. Nice screenshots appearing 

See for example
https://twitter.com/PhETsims/status/728682565431746560

My next priorities (though not super high but would be nice) would be
- summary card for New Sims page
- summary card for HTML5 sims page
- summary card for Accessibility page
- Summary card for Home page

Let me know if there are descriptions or such I should write for any of these, or any other info you would need.

**Comment by mattpen** [comment]
@ariel-phet - I posted twitter cards for the home page, a11y pages , and new/HTML5 sims pages.  If you want to change the images or text, it should be fairly easy now.  Please let me know.

**Comment by ariel-phet** [comment]
@mattpen we should definitely tweak a few images, for instance, the homepage image looks like this:

![capture](https://cloud.githubusercontent.com/assets/4051174/16526345/03277688-3f6e-11e6-921f-26881d104a2d.PNG)

It would be good to use an image where the logo is fully visible (perhaps the image for the card just needs some negative space padding?) or needs to be resized?

I also think the following picture would be much better for the a11y card

![a11y](https://cloud.githubusercontent.com/assets/4051174/16526483/b2a55bb6-3f6e-11e6-834e-44ef24f85379.PNG)

**Comment by mattpen** [comment]
@ariel-phet - I've uploaded the new images, they'll be available to test on the next deploy.

**Comment by mattpen** [comment]
@ariel-phet - The new images are now available for the twitter cards.  The logo image now fits within the borders of the image, however it does look a little pixelated.  Is it acceptable now?  If not, do we have a higher resolution copy of this image?  There isn't one stored on the website anywhere.

**Comment by ariel-phet** [comment]
@mattpen the accessibility card looks great.

Agreed about the PhET logo, and we should probably use black text for the tagline.

I would suggest this image

![phet_registered_logo](https://cloud.githubusercontent.com/assets/4051174/16955697/dd330978-4d92-11e6-8cd9-65800ce05811.png)

**Comment by ariel-phet** [comment]
And one odd thing. On the a11y card the text "moreabout" is one word instead of "more about"

![capture](https://cloud.githubusercontent.com/assets/4051174/16955938/b383631a-4d93-11e6-83b0-68faf6d5ae94.PNG)

**Comment by mattpen** [comment]
@ariel-phet - The new image and the text for the A11Y pages should be fixed now.

**Comment by ariel-phet** [comment]
This is all looking good, and hitting all primary targets for twitter cards. Thanks @mattpen closing!
