### ISSUE TITLE
CSS minified file is in non-deterministic order

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#427]
In the WebsiteBuildCommand in the SVN repository, the minified css file is built by concatenating all the css files in the root/css directory.  The command to iterate over this directory does not return the files in deterministic order, which can cause conflicts with specificity between builds of the website on different platforms.  On the version currently checked out at mendeleev@phettest:~/website-source/svn, I added an alphabetical sort which solves this problem.

@jonathanolson - Is the repo checked out on phettest setup to push these changes to unfuddle?

**Comment by jonathanolson** [comment]
Not sure, we can work through it today when we're both around?

**Comment by mattpen** [comment]
@jonathanolson pushed the changes to Unfuddle.  Closing.
