### ISSUE TITLE
We should not be hosting videos on figaro or phet-server

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#430]
Remove any videos stored on our servers and remove "download video" links.  All videos should be hosted on YouTube or Vimeo.

**Comment by mattpen** [comment]
@ariel-phet - I've removed the download links for any videos that are hosted on YouTube in the code.  I plan on deploying this to phet-server soon.  I'm not planning on trying to fix this on figaro before the switch as its not currently causing problems with performance.

Should we remove the videos from disk?  Or do you want to keep them there for now?

**Comment by ariel-phet** [comment]
They are all up on youtube, I see no reason to keep them on disk

**Comment by mattpen** [comment]
@ariel-phet @jbphet - I'm not entirely sure, but I'm guessing if we remove this link that this will remove the videos from the installer as well.  If the installer is run with network access, it will be able to embed the youtube videos, but if its offline the videos won't be available.  Should these videos be available on the installer?  If not, should we remove the youtube videos as well (when the installer is detected)?

**Comment by ariel-phet** [comment]
@mattpen I believe the installer already rejects videos from being ripped and included. tagging for dev meeting to verify

**Comment by mattpen** [comment]
@phet-steele checked the installer this morning and it has both the youtube iframe and the "(download video)" link.

**Comment by ariel-phet** [comment]
@mattpen yes, but I think if you try to run the installed version without an internet connection, neither of these will work. @jbphet and I looked at some point and it appeared that those links in the installer were not pointing to a local location.

**Comment by phet-steele** [comment]
@mattpen running offline has no video and the link IS there (but doesn't link to anything).

![offlineteaching](https://cloud.githubusercontent.com/assets/5863899/15124668/69ac5470-15e6-11e6-82c8-088a1c75b550.PNG)

**Comment by mattpen** [comment]
Do we want to either (a) setup the videos so they work with the installer or (b) remove the video section entirely on the installer?

**Comment by ariel-phet** [comment]
The videos should most definitely NOT work on the installer when offline, they would bloat the installer, and these videos get very little viewership as is. As for removing entirely....it is nice to have the ability to have access if your run the installed site while online.

**Comment by mattpen** [comment]
OK, thanks for the clarification.  I'll leave the embedded videos as-is and continue with removing the videos from the new server.

**Comment by mattpen** [comment]
The videos and links have been removed from the new server.  [Example](https://phet-new.colorado.edu/en/teaching-resources)

@ariel-phet Do we need to apply these changes to figaro as well, or is it ok to close this issue?

**Comment by ariel-phet** [comment]
No need to apply to figaro as well. Closing
