### ISSUE TITLE
Legacy sims sorted into By Device

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#431]
@mattpen old legacy Java/Flash sims are sorted into **both** "By Device" categories. They are not visible on these web pages at first. If their corresponding HTML5 sim is removed from either category via the admin pages, then the legacy sims will appear in their stead. This causes old java sims to be listed as runnable on tablets and Chromebook.

Certainly no one would remove HTML5 sims from either By Device category, but the fact that the legacy versions are sorted in both as well is a problem (excluding Flash + Chromebook). It could be a logic error in the database, meaning that newly ported sims would cause their legacy sims to "inherit" incorrect categories and other metadata, but that's just a thought.

**Comment by phet-steele** [comment]
@mattpen the existing Java/Flash sims have been correctly sorted in phetsims/tasks/issues/642. If it doesn't take too long, can you see if what originally caused this might be repeated (bug) or if this was a one time occurrance? I'm mostly concerned about:
> newly ported sims would cause their legacy sims to "inherit" incorrect categories and other metadata

**Comment by mattpen** [comment]
@phet-steele - I couldn't find any code that automatically adds categories when sims are deployed to figaro.  I tested adding and removing categories in various order from related HTML/Legacy sims and could not find a way to recreate this problem.  It appears to me to be an error that is not likely to reoccur, although we should double check the next time a ported sim is deployed.

**Comment by ariel-phet** [comment]
@phet-steele since some ported sims (charges and fields notably) have been deployed, can you check and close?

**Comment by phet-steele** [comment]
Legacy sims are retaining their own categories!
