### ISSUE TITLE
phet-server is not providing alternate "_all" jar to installer

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#433]
There is an alternate version of the JAR files for the Java sims that should be supplied to the installer when it is performing the rip.  This doesn't appear to be happening.  Java files in the most recent installer built on phet-server have the 'sandbox' setting for permissions, which is incorrect.

**Comment by mattpen** [comment]
Reassigning to @zepumph to check if the problem exists with the new installer.

**Comment by zepumph** [comment]
Just in the past few days this has started happening. I'm going to try and crack down on it and make it more reproducible.

**Comment by zepumph** [comment]
Last night I successfully installed a without activities rip with installer jars.

**Comment by zepumph** [comment]
The js port is getting these, I'll reopen if this stops happening.

**Comment by jbphet** [comment]
This shouldn't be re-opened.  I had forgotten when I originally opened this issue that the installer-builder explicitly grabs the version of the JAR files with the "all permissions" setting.  The web site, to date, hasn't supplied them to the installer builder.  If we decide that the web site should start doing this, it should be a separate issue.
