### ISSUE TITLE
Content to omit from future installer builds

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#436]
@jbphet @mattpen Some things that may be a good idea to filter out of the installer at some point:

- The registration form (accessed via "Teachers Register Here" button, maybe also get rid of the entire button?)
- Offline Access page
- All the search result documents with the name searchXXXX.html (a few aren't html). You can't use the search bar anyway....

Not an exhaustive list for sure, but some beginning ideas. Not assigning until time is allotted to this.

**Comment by phet-steele** [comment]
@zepumph these three items might be good to work on for now.

**Comment by zepumph** [comment]
Closing, to be tracked in phetsims/installer-builder#34
