### ISSUE TITLE
Prepare for Chrome to block Flash by default

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#438]
According to this article, Chrome is going to block Flash by default starting somewhere around Q4 2016.  

http://www.zdnet.com/article/googles-chrome-to-block-flash-this-year-except-for-10-top-websites/

We should probably be prepared for this, and have some information on our site about it.

**Comment by ariel-phet** [comment]
Marking for developer meeting. Lets come up with a list of some actions. Some thoughts

- Make a clear note in the help center (probably the earliest action item)
- Make a note in the "by device" chromebook category
- include in a newsletter email at some point?

**Comment by mattpen** [comment]
We could also display a message on the sim pages for flash sims, like we do for plate tectonics now.

**Comment by pixelzoom** [comment]
Not surprising, since even Adobe has been telling people to stop using Flash:
http://www.theverge.com/2015/12/1/9827778/stop-using-flash

**Comment by pixelzoom** [comment]
5/17/16 moved to Thursday 5/19/16 dev meeting, when @ariel-phet and @oliver-phet are around.

**Comment by pixelzoom** [comment]
5/19/16 dev meeting notes:

Definitely add something to the Help Center.

There are 20 Flash sims that have not been ported.

Firefox currently blocks Flash by default (http://money.cnn.com/2015/07/14/technology/flash-firefox-facebook). Do we need similar Help Center support for Firefox?

**Comment by pixelzoom** [comment]
This article details how Google plans to disable Flash:
http://www.wired.co.uk/news/archive/2016-05/16/google-chrome-adobe-flash-html5

> A proposal document put online by LaForge outlines how the change will take place:

> • Flash would still be "bundled" with Chrome but it won't be advertised by default
• If HTML5 is offered by a website Chrome will automatically default to this 
• If Flash Player is needed a user will be prompted 
• When a user accepts the page will be refreshed and Flash will appear on any following visits to the domain

**Comment by oliver-phet** [comment]
Added the following entry to Running Sims:

**What if my browser blocks Flash?**

Several internet browsers, including Google Chrome, will begin blocking Flash by default by the end of 2016. Flash will still be bundled with Chrome, but users will be prompted to accept the page. Once a page has been accepted, all pages that display Flash content at that domain (phet.colorado.edu) will be allowed.

You can read more about changing [Chrome plugins here](https://support.google.com/chrome/answer/142064?hl=en).

We are continuing to reprogram our original Java and Flash sims into HTML5, which will allow them to run seamlessly across platforms and devices.

**Comment by oliver-phet** [comment]
To add information about Safari 10: http://www.macrumors.com/2016/06/14/safari-macos-sierra-plugins-disabled-default/

**Comment by zepumph** [comment]
@oliver-phet how would you like to update the running sims entry for safari 10, I think it may be possible to just add 'including Google Chrome and Safari 10' to the answer from above.

**Comment by oliver-phet** [comment]
Done. Thanks for the suggestion!

**Comment by zepumph** [comment]
We updated our help center to accommodate this issue. Closing
