### ISSUE TITLE
phet-server emails to phethelp during translation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#439]
I've tried in the context of a translator creating a new translation, submitting a new translation, and a translation being updated. None of these events resulted in an email to phethelp. Additionally, creating/updating a translation failed to send an email to the collaborator. 

For phetsims/tasks#584.

**Comment by phet-steele** [comment]
Emails I expected to see, by subject line:

- PhET Website Translation #### created
- PhET Website Translation #### created based on ####
- PhET Website Translation #### submitted
- PhET Website Translation #### deleted

**Comment by mattpen** [comment]
@phet-steele - This should be working now.  Can you please confirm and close/reassign?

**Comment by phet-steele** [comment]
@mattpen they have certainly been working for awhile now.
