### ISSUE TITLE
Additions to Virtual Workshop page

### ISSUE THREAD

**Issue by schasteen** [phetsims/website#44]
Some changes and additions Workshop pages.

A.   Virtual Workshop page; http://phet.colorado.edu/en/for-teachers/virtualWorkshop

1.  Add a subtitle:  K12 teacher workshop
Have all existing content appear below that.

2. Below that content, have a new subtitle:  College physics teacher workshop
Embed the YouTube video at https://www.youtube.com/watch?v=Aw1HT9hMqIw&index=2&list=PLx_woo78JX4myOgPUllIH8EfSrkVVWgAL
Below it, include the text, "Provided courtesy of PhysPort" and link that to http://physport.org/nfw

Below that, create a link (as for K12 video) for handouts.  You can use the same wording.  Link to this file:  https://dl.dropboxusercontent.com/u/783982/Dubson-handouts-NFW-2014.zip

B.  Workshop page, http://phet.colorado.edu/en/for-teachers/workshops

1.  I just realized that this video is the wrong one.  It should be https://www.youtube.com/watch?v=mEe3lD5l0dc&list=UUMRZ0-ci4ifGBF1bJvrcDRQ

2.  Let's move that video to the upper right, next to the short menu, and make it smaller.  Now that we have two virtual workshop videos, I just want to reframe this one, so it's more of a sample video for the header of the page, rather than "the" virtual workshop.

3.  On the bullet point, "take a virtual PHET workshop", link that text to http://phet.colorado.edu/en/for-teachers/virtualWorkshop.  Remove the text that says "Download slides and handouts for this video...".  After the linked "Take a virtual PhET workshop" put unlinked text, (Videos of K12 and college workshops).

**Comment by aaronsamuel137** [comment]
These changes have been made. Closing
