### ISSUE TITLE
request to collaborate email not being sent

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#440]
phet-server does not send an email to a collaborator when someone requests access to a website translation. The person trying to request access is stuck on this screen:
![request2](https://cloud.githubusercontent.com/assets/5863899/15300485/284d62d2-1b66-11e6-89d9-7a23649978c2.PNG)

and never reaches this screen:
![request](https://cloud.githubusercontent.com/assets/5863899/15300433/eabd8df2-1b65-11e6-8225-b10dda2da0ef.PNG)

The expected email is:
- PhET translator requests access to your **** website translation ####

For phetsims/tasks#584.

**Comment by mattpen** [comment]
@phet-steele - This should be working now.  Can you please confirm and close/reassign?

**Comment by phet-steele** [comment]
Works!
