### ISSUE TITLE
How do I translate the language name?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#441]
@mattpen I've translated two strings I would expect to be the native word for a locale:

The "Common" string: language.name
The "Languages" string: language.names.cu

But both of these do not change the name of the language in the combo box. Am I missing a string? Church Slavic should be translated, but those strings are not working.
![nogluub](https://cloud.githubusercontent.com/assets/5863899/15304427/7ee12e26-1b7a-11e6-9e73-3596f297940f.PNG)

For phetsims/tasks/issues/584.

**Comment by mattpen** [comment]
@phet-steele - The language names are translated automatically by Java itself.  It looks like Church Slavic is not supported by the Java locale class - see full list of locales [here](http://www.oracle.com/technetwork/java/javase/javase7locales-334809.html).  

As of now, there is no method or need to translate the language names, as all of the website supported locales are also supported by Java.  Did we get a request for a translation in Church Slavic, or is this a test case?

**Comment by phet-steele** [comment]
@mattpen so what you are telling me is that the long list of languages that can be chosen from on https://phet-new.colorado.edu/en/for-translators/website are not necessarily supported by Java? And yes, totally just a test case used for testing the new server.

**Comment by mattpen** [comment]
@phet-steele - That's how its currently setup. If we need to publish a translation in a locale that is not supported I can build a custom solution.
