### ISSUE TITLE
Broken links on Research page

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/website#442]
I've found a few broken links and one pair of duplicate links, from poking around on phet-new for phetsims/tasks#584. 

From the top of the page down:

- _Blending Implicit Scaffolding and Games in PhET Interactive simulations_, links to a 404 page. From what I can find, the article it refers to is on page 3 of this larger article: https://ccl.northwestern.edu/papers/2014/ICLS14_ScienceGames_published%20(1).pdf

- _Research-Based Design Features of Web-based Simulations_, also links to a 404. I believe it should link to http://phet.colorado.edu/publications/Simulation%20Design%20AAPT%2004.pdf

- _Sims for science: Powerful tools to support inquiry-based teaching_, links to a search bar on the correct website where the article can be found, but the actual page of the article is http://learningcenter.nsta.org/resource/?id=10.2505/4/tst10_077_07_46

- Duplicate links:
 _Making On-Line Science Course Materials Easily Translatable and Accessible WorldWide: Challenges and Solutions_, and
 _Making Science Simulations and Websites Easily Translatable and Available Worldwide: Challenges and Solutions_, have slightly different titles and could possibly be two separate articles, but they both link to the exact same page, and as far as I can tell, they are not two separate articles.

**Comment by alynne-phet** [comment]
@mattpen I found another broken link on the same page:
- Inservice science teachers' views of a professional development workshop and their learning of force and motion concepts, Ramlo, S., Teaching and Teacher Education, 28(7), pp 928-935, 2012.
http://dx.doi.org/10.1016/j.tate.2012.04.002.

There is an extra "." at the end of the link: "002.". It should just be "002".

**Comment by mattpen** [comment]
@zepumph - this would probably be an easy website issue to tackle if you have time.

**Comment by zepumph** [comment]
I fixed all of the links, they should be up on the next deployment.

**Comment by zepumph** [comment]
Deployed these changes this evening and all looks good. Closing
