### ISSUE TITLE
Add "profile updated" field to PhetUser

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#443]
Exclude "sanitization". As discussed during status meeting. Set when they hit "Save", presumably null for users who haven't updated since this was added.

**Comment by mattpen** [comment]
@jonathanolson - Do you have an opinion on how the field should be initialized?  Would this work?
```
if ( profileUpdated == true ) 
  set profileUpdatedDate = today
else
  set profileUpdatedDate = null
```
Or should everyone be null for now?

**Comment by jonathanolson** [comment]
Presumably everyone would be null at the start.

**Comment by mattpen** [comment]
OK, I'll add this field to phet-dev today

**Comment by mattpen** [comment]
@jonathanolson - This has been added in [this branch](https://github.com/phetsims/website/tree/profile-updated-date-master) and has been deployed to phet-dev.

**Comment by mattpen** [comment]
@jonathanolson - This was deployed to figaro today immediately before the sanitization script ran.
