### ISSUE TITLE
Send notification to Trusted Translators when new sim is published.

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#445]
```ON: would it be possible to send an automatic email to trusted translators when a new sim is published to notify them? This might be easier that notifying via Rosetta?```

We could modify the simulation notifications to check if the user is a trusted translator rather than using the outdated receive-simulation-notifications field.

**Comment by mattpen** [comment]
@ariel-phet - Can you please assign a priority?

**Comment by ariel-phet** [comment]
I am going with medium. This seems like a nice feature, and my impression was that it would not be too difficult to implement.

**Comment by mattpen** [comment]
@jonathanolson - I changed the query for sim notification recipients to search for trusted translators.  Is there any way to test this from simian without sending out mass emails?

**Comment by jonathanolson** [comment]
The only way I've tested equivalent things has been overriding the list of emails (usually just me) and running it from figaro (email tests ideally should be done from there).

**Comment by mattpen** [comment]
This appears to be complete. Closing.
