### ISSUE TITLE
Broken java licensing link

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#447]
This link for "Creative Commons....3.0 United State Licensing" and the link on the image below it should both be http://creativecommons.org/licenses/by/3.0/us/. Located here on the http://phet.colorado.edu/en/licensing/java page: 
<img width="615" alt="screen shot 2016-05-26 at 1 53 50 pm" src="https://cloud.githubusercontent.com/assets/5863899/15588050/50f2a66c-2349-11e6-839c-07aa0abcbaf3.png">

**Comment by mattpen** [comment]
The link has been fixed and is ready for the next deploy

**Comment by mattpen** [comment]
This was pushed to figaro today.  Closing.
