### ISSUE TITLE
Update website translation instructions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#448]
This paragraph found at https://phet.colorado.edu/en/for-translators/website that reads:
<img width="935" alt="screen shot 2016-06-01 at 10 19 05 am" src="https://cloud.githubusercontent.com/assets/5863899/15718881/a3fe57a2-27ea-11e6-9e08-3bf9828ca160.png">

Change this *entire* sentence: "If you wish to make further changes or improvements, please create a new....."

To this: "If you wish to make further changes or improvements, please continue to work in the version of the translation above, make your edits, and re-submit the same version. There is no need to make any further copies."

**Comment by mattpen** [comment]
This was deployed to figaro, closing.
