### ISSUE TITLE
Internationalization of "Over 200 million simulations delivered"

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#45]
I noticed that many of the translations include an older number since that depends on the translator updating it. Perhaps we should consider restructuring this string to include a variable for the "200" that we can update as we want? And then all the translations will stay in sync? 

@jonathanolson , @aaronsamuel137 - Would that make sense?

**Comment by aaronsamuel137** [comment]
OK this is implemented. The translators have the option to add a {0} where the number will get filled in automatically. The change won't take effect until this has been updated by translators.
