### ISSUE TITLE
Hide comments and 'Comment on this Activity'

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#450]
@mattpen Can you please "hide" all comments and the 'Comment on this Activity' section on all activity pages? We have been getting a lot of flagrant comments recently and since this isn't a particularly helpful portion of the site we would like to remove it.

I'm assuming we can do this by just "hiding" all of that content from the site, without permanently removing it.
<img width="902" alt="screen shot 2016-06-07 at 1 24 24 pm" src="https://cloud.githubusercontent.com/assets/5090275/15871718/49d23988-2cb3-11e6-961c-357f693e611a.png">

**Comment by mattpen** [comment]
@oliver-phet - I applied this change on phet-dev.  See https://phet-dev.colorado.edu/en/contributions/view/3660 for an example.  If all looks good I can push this to figaro on the next deploy..

**Comment by oliver-phet** [comment]
Thanks Matt, all looks good!

**Comment by mattpen** [comment]
@oliver-phet - This was deployed to figaro today.  Closing.
