### ISSUE TITLE
Registration email has invalid link to blog

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#453]
Hello, [name]!

Thank you for creating an account on PhET's website! Your account is now active.

You can now submit activities, comment on activities, and translate the website.

For updates on PhET activities:
[Read our blog,](http://blog/)
[Join us on Facebook,](http://www.facebook.com/pages/PhET-Interactive-Simulations/161503243888932?v=wall) or
[Follow us on Twitter](http://twitter.com/PhETSims)

Thanks,
The PhET Team
http://phet.colorado.edu

**Comment by mattpen** [comment]
Should the link to the blog just be removed since we are removing it from the new server?

**Comment by ariel-phet** [comment]
Yes

**Comment by mattpen** [comment]
Its been removed and is ready for the next deploy.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.
