### ISSUE TITLE
Setup rosetta on phet-server-dev

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#454]
Install rosetta for testing on phet-server-dev, should point to the babel test branch.

**Comment by mattpen** [comment]
Rosetta is installed and running, but access is blocked because the server does not have a domain name yet

**Comment by mattpen** [comment]
Rosetta is now running and accessible via http.  It appears to be configured for use with the babel tests branch. The "babelBranch" value in `/home/phet-admin/.phet/build-local.json` is "tests".  This should be ready for testing, but it would be good if @jbphet could confirm first.

**Comment by ariel-phet** [comment]
Also assigning myself to make sure this is on @jbphet radar

**Comment by jbphet** [comment]
@mattpen - I think I know why translations are not being successfully submitted to babel, and why trying to submit them results in Not Found (404) errors.  When the user submits strings, the strings are sent to Rosetta using an HTTP post method, not a get method.  It looks like get methods are being forwarded to the IP port associated with Rosetta (16372 I believe), which is why we can log in and get to the translation pages, but post methods are **not** being fowarded, so Rosetta is never seeing the string submissions.

Can you look at whatever has been set up for the forwarding and let me know if this is indeed the root cause of the issue?

**Comment by mattpen** [comment]
@jbphet - That looks correct.  The varnish rule for passing the `/translate` route to rosetta was preceded by a rule that sent any POST request to tomcat.

I tried to change a string in chains, and in the web interface it appears successful:
![image](https://cloud.githubusercontent.com/assets/11747676/16936551/bcecc988-4d24-11e6-9a83-1553bfffc7d7.png)


But I instantly received an email regarding a failure:
```
Build failed with error: error running command git pull: Error: Command failed: error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
. Sim = chains Version = 1.1.0 Locales = za Shas = {
  "comment": "# chains 1.1.0 Fri Apr 22 2016 14:52:35 GMT-0600 (MDT)",
  "assert": {
    "sha": "7d27130a4d27da15aa7f8a21bbfb9245288c1b44",
    "branch": "HEAD"
  },
  "axon": {
    "sha": "5e33541f53066f495d1b42efe7344a3c4cb3e3d2",
    "branch": "HEAD"
  },
  "brand": {
    "sha": "bb1cfcc63c3d007d800ede089994d8705db6d47b",
    "branch": "HEAD"
  },
  "chains": {
    "sha": "058f519571acedf4e2311b1bffdbe05048071186",
    "branch": "HEAD"
  },
  "chipper": {
    "sha": "558a1f4fb39110c5f8d979932b74294236a1eb52",
    "branch": "HEAD"
  },
  "dot": {
    "sha": "833eef12a0c06039634802ebb2b50acd347a0a09",
    "branch": "HEAD"
  },
  "joist": {
    "sha": "97fac8d0fb6a596f5fa1373bd5b774cb128f53a6",
    "branch": "HEAD"
  },
  "kite": {
    "sha": "24ad131a77aee78e266436ef6b618c8353953f28",
    "branch": "HEAD"
  },
  "phet-core": {
    "sha": "c48bf32035dc5a4ed092ad611012fcbdeb5c6351",
    "branch": "HEAD"
  },
  "phetcommon": {
    "sha": "eab7fb7f41ae9bd31935d2ee95f84e7546a9253f",
    "branch": "HEAD"
  },
  "scenery": {
    "sha": "917a2a39bf709b46df14442a9570e8b6fed0f147",
    "branch": "HEAD"
  },
  "scenery-phet": {
    "sha": "548ce98dfc17051fe37f7d269b9de80a201ad92b",
    "branch": "HEAD"
  },
  "sherpa": {
    "sha": "b74418c01f7b018cfc2ad130becdc0ad428b71c2",
    "branch": "HEAD"
  },
  "sun": {
    "sha": "3f17b4742775556436879dce53d08799fab8de44",
    "branch": "HEAD"
  },
  "tandem": {
    "sha": "0ad35fb75928d18ecc1a429587bed4c605878e89",
    "branch": "HEAD"
  }
}
```

**Comment by mattpen** [comment]
However, it appears the commit was successful: https://github.com/phetsims/babel/commit/00070672889a711484998d02aa84b5e6af3b19bf

**Comment by jbphet** [comment]
Definitely a step in the right direction.  Not that the POST issue is resolved, I'll see if I can figure out why the build fails.

**Comment by jbphet** [comment]
I fixed one of the reasons why the build was failing by doing a pull and restarting the build-server.

However, there is another issue related to permissions.  The problem is that if I do a pull from my account on phet-server, any new files are created with the ```facstaff``` group.  The build server runs under the phet-admin user, and phet-admin is not part of this group.  I looked on figaro to see why this wasn't a problem there, and found that files that I create on figaro are created as belonging to the ```phet``` group.  The phet-admin account **does** belong to that group.  So, I think the next step is to make it so that files that I (or any other PhET team member) create on phet-server belong to the ```phet``` group.  Back to @mattpen to make this change.

**Comment by mattpen** [comment]
@jbphet - You are a member of the phet group but it appears that facstaff is your default on phet-server for some reason.  You will need to change your default group by adding the following line to your .bash_profile or .bashrc:

`newgrp phet`

I don't think there is a way to automatically do this for all PhET team members.  Alternatively I can add a cronjob for the root user that rewrites file owners and groups in the phet-repos directory on a regular basis (say every 15 minutes). We have something similar running on figaro.

**Comment by jbphet** [comment]
I tried ```newgrp phet```, but it didn't work as I expected.  In the ```.bashrc``` file it seems to have no effect.  In ```.bash_profile``` it appears to start a new shell without my usual shell commands.  I'll do some more investigating.

**Comment by mattpen** [comment]
Excerpts from email chain with @markmorlino  and Dylan Canfield (OIT - Unix)

On Wed, Jul 20, 2016 at 12:57 PM, Matthew Pennington <Matthew.Pennington@colorado.edu> wrote:
Is it possible to change the primary group on phet-server to be phet if a user is a member of that group? 

On Wed, Jul 20, 2016 at 1:47 PM, Dylan Canfield <dylan.canfield@colorado.edu> wrote:
Your primary group ID is determined by your user AD object, of which I have no control. Additionally, since phet is not an AD group, but rather a local group, this will get very complicated very fast. A better approach is to use "group sticky bit" permissions so enforce that new files and directories inherit the group ownership of their parent directory.

To set group sticky run "chmod g+s" on the directory that you want to preserve group ownership on.

For example:
`chgrp -Rh phet /path/to/directory`
`find /path/to/directory -type d -exec chmod g+s {} +`

From: mark morlino <markmorlino@gmail.com>
Date: Wed, Jul 20, 2016 at 3:01 PM
The other part of it is to make sure the files get created correctly with read and write permissions for the group. So, everyone will want to set their umask to 0002 (or 002 should do the same thing) in order for the sticky gid bit strategy to work without requiring manual permission changes. If they are defaulting to 0022 then they can be changed in everyone's individual  .bashrc files, or system-wide in someplace like /etc/profile

**Comment by mattpen** [comment]
I applied the group sticky bit to `/data/share/phet/phet-repos` using the method Dylan provided above.  As long as everyone sets their umask in .bashrc, this should work now.

**Comment by jbphet** [comment]
I tested a submission of strings and a build with the updated permissions and it seems to have worked.  I think we are probably good on this for now, and then will do some final testing as soon as the cutover happens.

**Comment by mattpen** [comment]
@jbphet - Do we need to have more extensive testing done by the QA team before the switch?

**Comment by jbphet** [comment]
I would say no, since there isn't much more that they can test.

**Comment by mattpen** [comment]
Rosetta is working after the switch.

**Comment by jbphet** [comment]
Also, I've been keeping tabs on Rosetta after the switch to make sure that translations are being successfully submitted by translators and published to the web site.  I've seen at least 10 new translations submitted in the last several days, so it seems to be working well.
