### ISSUE TITLE
Special code for sponsors on installer version of home page is broken

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#46]
The main page has a bit of JavaScript that is used to select and display an image from one of PhET's sponsors.  This code is modified a bit for the installed version in order to make the images paths correctly specified on the local file system.  It appears that this little bit of specialized code is currently broken because it refers to an image id (green-arrow-image) that doesn't exist.  It probably used to exist, but got removed in some previous update, and the relationship with this piece of code was forgotten.

The code in question, from src/java/edu/colorado/phet/website/content/IndexPanel.html, looks like this:

```html
                                <script type="text/javascript">
                                    (function() {
                                        var greenArrowSrc = document.getElementById( "green-arrow-image" ).src;
                                        // 0x2F is a slash, to fool the httrack ripper
                                        var lastIndex = Math.max( greenArrowSrc.lastIndexOf( String.fromCharCode( 0x2F ) ), greenArrowSrc.lastIndexOf( "\\" ) );
                                        var newImagesDirectory = greenArrowSrc.substring( 0, lastIndex );
                                        document.getElementById( 'featured-sponsor-spot' ).innerHTML = document.getElementById( 'featured-sponsor-spot' ).innerHTML.replace( /\/images/g, newImagesDirectory );
                                    })();
                                </script>
```

I discussed this with @aaronsamuel137, and we tried manually changing 'green-arrow-image' to 'phet-logo-main-image' on my local copy and this fixed the problem.  @aaronsamuel137 has agreed to make this fix on the web site.

**Comment by aaronsamuel137** [comment]
This was fixed. Closing.
