### ISSUE TITLE
Check performance changes between figaro and phet-server before and after switch.

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#462]
Kathy recommended using NewRelic metrics.

**Comment by mattpen** [comment]
I'll take action this week.

**Comment by mattpen** [comment]
Performance metrics of figaro in April:  
![2016-08-25 10_39_17-tomcat figaro - new relic](https://cloud.githubusercontent.com/assets/11747676/18014384/f4af291e-6b7f-11e6-861c-3bfc1474d896.png)

**Comment by mattpen** [comment]
Performance metrics for phet-server from the last week:

![2016-08-25 10_38_57-my application - new relic](https://cloud.githubusercontent.com/assets/11747676/18014402/01c33d70-6b80-11e6-889a-b7b35b1ed2f1.png)

**Comment by mattpen** [comment]
As seen in the two previous charts, when looking at a weekly average phet-server is showing a 59% decrease in average transaction time over figaro, despite a 55% increase in requests per minute.  The additional requests are necessary due to using an ESI component for the logon button on every page.  

I checked average CPU consumption as well, which would indicate room for growth in terms of tomcat processing power, and average use has dropped from an average of of 20-25% to usage in June on figaro (oldest report available) to 8-9% for the last week on phet-server.

The only major problem encountered after the switch in terms of system resources was that the apache logs had filled their allotted volume and apache stopped recording log data for ~24 hours.  This was fixed as part of #476.

The cache servers are not currently tracked in new relic, but they have been running in a stable state since the switch and in general are responding quickly.  Overall, performance is much better over a weekly average than in May, even with ramped up traffic from the beginning of the school year.

@kathy-phet @ariel-phet Do you have any questions? Are there any other metrics you'd like me to investigate?

**Comment by kathy-phet** [comment]
Thanks. Seems good to me. Great work!

**Comment by ariel-phet** [comment]
@mattpen a few quick comments

1. Yes, great work!
2. You might ask @markmorlino if there are any performance metrics he recommends looking at
3. We should look at these number again at the end of September.

**Comment by ariel-phet** [comment]
Actually I might ask @markmorlino to chime in directly

**Comment by markmorlino** [comment]
Response time is probably my favorite metric as an indicator of overall health. At one point, @mattpen, I think you showed me something that hits the server externally (through the cache servers). While this would lack the jvm/postgres breakdown provided by newrelic, I think tracking trends on something like that would be useful.
System memory and JVM heap stats might be useful to have. As would postgres query stats, and io statistics for the disks but both of those (along with the cpu usage) are usually more useful in pinning down a problem when response time starts to lag rather than as something to watch when response times are good.
Is there anyway that varnish can cache the ESI part? (this may be a silly question, I'm not very familiar with ESI)

**Comment by mattpen** [comment]
@markmorlino - thanks for the detailed suggestions.

| At one point, @mattpen, I think you showed me something that hits the server externally (through the cache servers)

I think this might have been BlazeMeter?  We just cancelled our subscription to this, although it was essentially a distributed environment for running Apache JMeter scripts.  We could use JMeter or `ab` from a single host to compare response time on phet-server over time, but unfortunately I don't think we have data on response time for figaro while it was in production in order to compare the two servers together.

| Is there anyway that varnish can cache the ESI part?

We are using ESI to bypass the cache.  It is used primarily for the Sign In and Register buttons at the top right of the page, which get replaced by the username and edit profile links when the user is signed in. ESI allows us to cache the rest of the page, so we are only querying tomcat for the bare minimum content. The entire page was previously cached on HTTP only, and because we enforced HTTPS when people were signed in it did not cause a problem.   I don't think we want to cache this content, because the signed in version could be shown to the wrong user or to someone who is not logged in.  Do you know of any way we could cache content like this in varnish safely?

| both of those (along with the cpu usage) are usually more useful in pinning down a problem when response time starts to lag

I think it would be great to log this stuff if the storage requirements are not too high.  These are items I've checked in the past when problems have arisen.  However, we don't have this data logged on figaro when it was in production, so I don't think we can use it for comparison.

As far as a-b comparison for figaro and phet-server, I think we're limited to whatever was recorded in NewRelic (or perhaps Google Analytics?).  Do you know of any other metrics in these tools that might be of interest?  I could grant you access to NewRelic if you're interested.

**Comment by ariel-phet** [comment]
I think at this point that certainly compared to the old setup things are working well. So time to close this issue, and we will open performance specific issues as they arise
