### ISSUE TITLE
Activities using foreign alphabets not accessible.

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#464]
Activitiy files with filenames in alternative alphabets are not accessible.  For example, activity 4004, https://phet.colorado.edu/services/download-servlet?filename=%2Factivities%2F4004%2FSENARIO-orfanos-%CE%B5%CF%80%CE%B9%CF%84%CE%AC%CF%87%CF%85%CE%BD%CF%83%CE%B7.doc.

Website error:
An error occured. The requested file was not found or you were not logged in. Try logging in and see if that fixes the problem.

In the logs:
DownloadServlet - File: /data/web/static/phetsims/files/activities/4004/SENARIO-orfanos-ÎµÏ<U+0080>Î¹Ï<U+0084>Î¬Ï<U+0087>Ï<U+0085>Î½Ï<U+0083>Î·.doc does not exist

It appears to be a problem handling the unicode in the filename.  At some point it was discussed at dev meeting that we should replace the activity filenames with something standard and incremental rather than keeping the name of the file as submitted by the user. This should solve this problem.

**Comment by kathy-phet** [comment]
Hi Matt, It seems like this could cause problems for the user. Are you just changing how we store it or are you changing what file name looks like on the activity webpage?
Kathy

Sent from my iPhone

On Aug 9, 2016, at 8:47 PM, Matt Pennington <notifications@github.com<mailto:notifications@github.com>> wrote:


Activitiy files with filenames in alternative alphabets are not accessible. For example, activity 4004, https://phet.colorado.edu/services/download-servlet?filename=%2Factivities%2F4004%2FSENARIO-orfanos-%CE%B5%CF%80%CE%B9%CF%84%CE%AC%CF%87%CF%85%CE%BD%CF%83%CE%B7.doc.

Website error:
An error occured. The requested file was not found or you were not logged in. Try logging in and see if that fixes the problem.

In the logs:
DownloadServlet - File: /data/web/static/phetsims/files/activities/4004/SENARIO-orfanos-????^1??????(1/2)??*.doc does not exist

It appears to be a problem handling the unicode in the filename. At some point it was discussed at dev meeting that we should replace the activity filenames with something standard and incremental rather than keeping the name of the file as submitted by the user. This should solve this problem.

-

**Comment by mattpen** [comment]
@kathy-phet - I plan on only changing the name of the files as they are put in storage.  The database would still keep a record of the original name of the activity and would display that on the website.  

The main difference from the users perspective is that when they download the activity files, the files themselves would have the new name.  Will this be a problem? If so I can look into rewriting the name again as it is streamed to the user.  

The filenames would probably be in the format `phet-activity-1234-1.abc`, where the first number is the activity number and the second number is an index of the specific file within that activity.

**Comment by mattpen** [comment]
This is also affecting the installer-builder: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3705

**Comment by mattpen** [comment]
Regarding the encoding of the filename, `server.xml` on phet-server is missing `URIEncoding="UTF-8"` in the `connector`s.  This parameter is present on figaro, and appears to have been overlooked in the migration.  Adding this to the config on phet-server will require a reboot, and will solve the activity accessibility from the website itself, but not from the installer.

**Comment by mattpen** [comment]
I updated server.xml on phet-server and the activities in greek and korean are accessible now.  I am continuing work on changing the names of files in storage in order to get the installer working.

**Comment by mattpen** [comment]
This was deployed to phet-server tonight.  

@jbphet or @phet-steele - Can you check if [the installer issue](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3705) is resolved the next time the installer runs on phet-server?

**Comment by mattpen** [comment]
Discussed in dev meeting on 8/25.  This change will be reverted for the moment leaving the bug in the installer.

**Comment by mattpen** [comment]
I added a filename rewrite to the servlet that checks login-status for activity files.  It is only adding a minimal amount of processing work to tomcat, and delivers files in the original name to users over the internet and the standardized names to users on the installer version.

The one difference is that the filenames have spaces replaced with + signs, due to encoding issues.  However, they still retain the rest of the original text, so I think this should be sufficient to help teachers organize downloaded files. @ariel-phet - This is deployed to ox-dev. Can you check if the filenames are acceptable now?  If so I'll deploy to phet-server tonight and we can check the installer on monday.

**Comment by ariel-phet** [comment]
@mattpen that seems acceptable, and appears to be working for English submissions

However, when I try something like https://ox-dev.colorado.edu/en/contributions/view/3348 I get a title that looks like this:

%CE%93%CE%95%CE%9D%CE%99%CE%9A%CE%9F%CE%A3+%CE%9F%CE%94%CE%97%CE%93%CE%9F%CE%A3+%CE%BF%CF%81%CE%B3%CE%AC%CE%BD%CF%89%CF%83%CE%B7%CF%82+%CE%B4%CE%B9%CE%B4%CE%B1%CF%83%CE%BA%CE%B1%CE%BB%CE%AF%CE%B1%CF%82.pdf

Is that just my computer not having that character set or what? We might need QA to install some foreign character sets and make sure this is not an issue?

**Comment by phet-steele** [comment]
The activity above looks fine for me on Mac OSX 10.11.6 Chrome and Win 10 Chrome in all contexts (downloading, viewing, etc...).

**Comment by ariel-phet** [comment]
Ah, interesting, works in chrome for me as well

**Comment by ariel-phet** [comment]
@mattpen can you at least take a gander as to why this might be an issue in firefox?

**Comment by mattpen** [comment]
It is probably not decoding the URI correctly, I'll check tonight.

**Comment by mattpen** [comment]
Additionally in Safari, all files are saved as `download-servlet`.

**Comment by mattpen** [comment]
Apparently treatment of the Content-Disposition header, where I'm setting the filename, is pretty messy.  See http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http.  I'll see if I can find a solution that fits our needs.

**Comment by mattpen** [comment]
@ariel-phet - This should be working properly now, I even fixed the issue with the `+` signs.  It's deployed to ox-dev.

I've checked Chrome and Safari on OSX, and Chrome, FF, Edge, and IE 11 on Win10.  There may be some compatibility issues with old versions of IE (like 7 and earlier), do we need to support these?  The UTF-8 filenames may not be possible in the current configuration.

**Comment by ariel-phet** [comment]
@mattpen We don't support IE10 or earlier for our HTML5 sims so I think that is fine (and IE use is fairly small on our website these days - chrome has become the dominant browser).

**Comment by ariel-phet** [comment]
@mattpen feel free to close if all is good.

**Comment by mattpen** [comment]
This still needs to be deployed to phet-server, and the installer will need to be tested afterwards.

**Comment by mattpen** [comment]
This was deployed to the phet-server tonight.  The files are cached in varnish for some time, I'll test functionality tomorrow.

@phet-steele - Can you please check that the activities installer built this weekend is still downloading files using the standardized names?

**Comment by phet-steele** [comment]
@mattpen Win 10 Chrome, FF, and Edge are all correctly using the standardized names of some Greek files I tried (in the installer).

**Comment by mattpen** [comment]
Thanks Steele, this is working properly on the website too.
