### ISSUE TITLE
Vimeo primers are being cached as unavailable

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#465]
The vimeo primers are being cached and displayed as unavailable even if the user is signed in.  They should be converted to an ESI component built in varnish or enabled/disabled with client-side JS.

**Comment by mattpen** [comment]
Some of the primers are available to users who are not signed in also, BASE for example.

**Comment by mattpen** [comment]
I added some client-side JS code to check if the log-in-out ESI component is showing a username or not.  I've deployed the fix to ox-dev.colorado.edu and it appears to be working.

@phet-steele - Can you please confirm?

**Comment by phet-steele** [comment]
@mattpen looks to be working for me. I can successfully unlock the primer when signing in, and it locks back up when signing out.

**Comment by mattpen** [comment]
Thanks, I'll publish the fix tonight.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.  The primers are still cached from before the fix, so I'll check again tomorrow.

**Comment by mattpen** [comment]
This appears to be working now.  Closing.
