### ISSUE TITLE
Vietnamese translation credits are incorrect

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#467]
@mattpen, @samreid is credited for a Vietnamese translation of Bending Light. I'm willing to bet this incorrect, also since there is an actual translation credit for BL right above his in this screenshot:
<img width="651" alt="screen shot 2016-08-10 at 10 13 10 am" src="https://cloud.githubusercontent.com/assets/5863899/17561564/e5eada70-5ee3-11e6-9e00-8cbbd570d9a8.png">

For phetsims/tasks/issues/670.

**Comment by samreid** [comment]
I'm not too handy with Vietnamese at the moment, so this seems like an error.  I'm having a vague recollection that @jonathanolson and I used my account to test something for translations 10+ months ago and that something went wrong and @jonathanolson had to manually edit database entries.  That is about all I remember and I'm not sure if it is about this sim or not.

**Comment by samreid** [comment]
I wonder if this might resolve itself when we deploy a new Bending Light in https://github.com/phetsims/bending-light/issues/351

**Comment by samreid** [comment]
@mattpen or @jonathanolson can you report on this?  I'll be working on the Bending Light republishing shortly.

**Comment by jonathanolson** [comment]
Presumably there's still an entry (or something) marking that translation. We should get rid of it.

I don't know the details of how that information is stored in the DB, I'll wait for @mattpen to respond.

**Comment by mattpen** [comment]
There is an entry for a vietnamese localized sim by Sam Reid.  I can remove the DB entry, does anything need to be changed in rosetta/babel?

**Comment by mattpen** [comment]
Sam's entry has been removed from the database.

**Comment by samreid** [comment]
Thanks!

**Comment by mattpen** [comment]
The [Vietnamese Bending Light](https://phet.colorado.edu/sims/html/bending-light/latest/bending-light_vi.html) appears to still be working, so I'm going to close the issue.
