### ISSUE TITLE
Translation credits should check for visibility

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#468]
Hence this on the HTML5 translation credits page:
<img width="617" alt="screen shot 2016-08-10 at 10 22 16 am" src="https://cloud.githubusercontent.com/assets/5863899/17561951/ad59cb6a-5ee5-11e6-879d-f294c9c7a2df.png">

For phetsims/tasks/issues/670.

**Comment by mattpen** [comment]
@phet-steele - I've deployed a fix for this to ox-dev.  It appears to be working, I'll publish on phet-server on the next deploy.

**Comment by mattpen** [comment]
The fix was deployed to phet-server tonight.
