### ISSUE TITLE
New main web page, which is due to be released soon, has issues when used in conjunction with installer

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#47]
I tested a build of the installers using the prototype of the new main page as the root.  The rip process started with phet-dev.colorado.edu and proceeded from there.  For the most part, it all worked great, but if I click on the carousel on the locally installed version, the sim can't be found, and the URL looks funky.  Here is an example:

file:///C:/Program%20Files%20(x86)/PhET/index.htmlsimulation/balancing-act

@aaronsamuel137 and I looked at this together, and it appears to be due to some assumptions made about global variables in video-player-v2.js that are not correct when running from the locally installed version.  @aaronsamuel137 has agreed to investigate.

**Comment by aaronsamuel137** [comment]
I think this has been confirmed to be fixed on the latest installer versions. Closing.
