### ISSUE TITLE
get installer builder working on phet-server

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#470]
The cutover from figaro to phet-server has occurred, and I am now working to get the installer builder working on the new server.  I have run into an issue with this: The installer-builder relies on being able to see the page at https://phet.colorado.edu/sims/html/, but that page is currently returning a 403 (forbidden) error.  This will need to be fixed for the installer to work.

**Comment by mattpen** [comment]
I added `Options +Indexes` to `/sims/.htaccess`, it should be accessible now

**Comment by samreid** [comment]
@jbphet said:

> Sam - If you remember the other reason(s) that this page and related pages such as https://phet.colorado.edu/sims/ need to be visible, can you please put it in the issue?

I can't think of anything.

**Comment by samreid** [comment]
@jbphet can this issue be closed?

**Comment by jbphet** [comment]
I'm going to use this to track any issue that come up as I get the installer working, the one about the visibility of the links was just the first one I ran into.  So no, not ready to close this until the installer builder is fully tested and operational on the new server.

**Comment by jbphet** [comment]
There was an issue with the cron job that caused it to fail over the weekend.  I've fixed this and set it up to run overnight.

**Comment by jbphet** [comment]
The cron job last night succeeded, and @phet-steele downloaded and tested the OSX version and it worked fine and the date in the installer was correct.  However, the rebuild date on the web site itself wasn't updated.  Here is an annotated screenshot:

![installer-date](https://cloud.githubusercontent.com/assets/3082831/17707870/995df62c-639f-11e6-85dc-29e30c466f58.PNG)

In order to set this date, the installer builder hits the web site with a URL.  I'm not going to paste that URL here because this forum is publicly visible and we don't want anyone using the URL inappropriately, but I've conveyed it to @mattpen.  Assigning to him to investigate.

**Comment by mattpen** [comment]
@jbphet - The time update request now requires an authorization code.  Previously, it was required that the request operate locally, but due to the new server architecture we have no way of safely detecting if the request comes from localhost.  Let's discuss authentication methods offline.

**Comment by mattpen** [comment]
The installer-builder is working well enough for now and the new installer is in active development.  Closing.
