### ISSUE TITLE
Language selection sorts alphabetically by English name, but displays translated name

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#475]
On the website front page (drop down menu). I think the language selection would be more intuitive if it sorted alphabetically by the translated language name. So espanol was under "E" not "S". Thoughts?

**Comment by oliver-phet** [comment]
This would be consistent with the [Translation Credits page](https://phet.colorado.edu/en/for-translators/translation-credits/by-locale) and [Translated sims page](https://phet.colorado.edu/en/simulations/translated)

**Comment by mattpen** [comment]
I agree with sorting alphabetically.  This should be easy to implement and be ready to deploy by next week.

**Comment by mattpen** [comment]
I have a solution deployed to https://ox-dev.colorado.edu.  It looks like it is working, but the languages that use non-english alphabets but start with english-like letters are sorted at the bottom.  Is this OK?  For example, should čeština be sorted before Church Slavic, or is it ok as is?

![image](https://cloud.githubusercontent.com/assets/11747676/17744119/93b1c5f4-6463-11e6-991c-c06473005aa0.png)

**Comment by kathy-phet** [comment]
I would check out Khan Academy and try to match their order. They put cestina up with the regular alphabet because it basically uses a roman alphabet but with accents, then puts others below. 
https://www.khanacademy.org/

**Comment by mattpen** [comment]
I implemented a sorting algorithm that includes accents, this is ready for deploy.

**Comment by mattpen** [comment]
This was deployed to figaro tonight.  I tested it in several locales, it appears to be working.  Please reopen if needed.
