### ISSUE TITLE
Add Promethean to Sponsor and Featured Sponsor at Gold Level

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#477]
@mattpen We need to add Promethean to our Gold Sponsor and in our Featured Sponsor Group. I will believe that the URL should be http://www.prometheanplanet.com/ but I will confirm.
Thanks.
![promethean logo](https://cloud.githubusercontent.com/assets/10424210/17630334/1ccfd100-607c-11e6-80cb-836fd894a25e.png)

**Comment by mattpen** [comment]
@kdessau-PhET - Thanks.  I'll try to get this up by next week.

**Comment by mattpen** [comment]
| Featured Sponsor Group

@kdessau-PhET - Does this mean it should be in the sponsor rotator on the front page and sim pages with the highest weight?

**Comment by kdessau-PhET** [comment]
@mattpen - It should be the second highest weight. (Platinum sponsors are the highest.)

**Comment by mattpen** [comment]
@kdessau-PhET - Promethean has been added to the About page and the rotator at the Gold sponsor weight.

**Comment by kdessau-PhET** [comment]
Hi Matt, 
I tried the logo and it looks good on the sponsor page, but when I did the "reload" for the front page, I had a bad link to the image? 
<img width="822" alt="screen shot 2016-08-22 at 9 43 49 am" src="https://cloud.githubusercontent.com/assets/10424210/17861170/3c569bfc-684d-11e6-8b89-aab81a6378c0.png">

**Comment by mattpen** [comment]
@kdessau-PhET - This is caused by the varnish cache.  The images are cached for 30 days, so I'll have to rename the file tonight and then it will show up.

**Comment by mattpen** [comment]
@kdessau-PhET - The image for the rotator was updated tonight.

**Comment by kdessau-PhET** [comment]
Thanks Matt!

On Aug 22, 2016, at 11:18 PM, Matt Pennington <notifications@github.com<mailto:notifications@github.com>> wrote:


@kdessau-PhET<https://github.com/kdessau-PhET> - The image for the rotator was updated tonight.
