### ISSUE TITLE
No icon for .xls activity files

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#479]
But there is an icon for .xlsx and everything else (mostly)!

<img width="156" alt="screen shot 2016-08-17 at 8 59 21 am" src="https://cloud.githubusercontent.com/assets/5863899/17741309/f59ec97a-6458-11e6-9e92-dd00276cadbd.png">

**Comment by amanda-phet** [comment]
Strange. The .xls icons should be the same as the .xlsx icon (you probably knew that but it wasn't stated).

**Comment by mattpen** [comment]
@phet-steele @amanda-phet - there was a missing css rule for xls.  I added the rule, but it will take some time to appear on the website due to caching.
