### ISSUE TITLE
Possible UX issue with cached activity pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#481]
[10:53:35 AM] Steele Dalton: is having contribution pages being cached actually the best? It would be REALLY confusing for someone to edit their contribution, get the “Update Success…Continue to Activity”, then not see the activity be updated
[10:54:37 AM] Matt Pennington: They are only cached for 15 minutes.  In the edit success page we could put some very obvious message about having to wait to see results.
[10:54:53 AM] Steele Dalton: yea that sounds nice

The current success message looks like this:

![image](https://cloud.githubusercontent.com/assets/11747676/17782846/a4cc6176-6532-11e6-9a23-d497a1743ab0.png)

I propose that we change the text as follows:

Thank you! The contribution has successfully been updated.  The changes will not appear immediately, please check the activity page to confirm in 20 minutes.

@oliver-phet @amanda-phet - Does this sound ok?

**Comment by amanda-phet** [comment]
Hm, I don't want to give an exact number of minutes... What about something like this? 

Thank you! Your contribution has successfully been updated. The changes may not appear immediately due to browser caching but should be visible after refreshing or restarting your browser.

**Comment by mattpen** [comment]
@amanda-phet - This isn't due to browser caching, refreshing and restarting the browser won't have an effect.  The activity pages are cached on the varnish servers on our side, and the caches invalidate after 15 minutes, so 20 minutes should be a safe bet (although at that point there could be browser caching issues as well)

**Comment by amanda-phet** [comment]
I see. How about: 

Thank you! Your contribution has successfully been updated. The changes may take up to 20 minutes to appear.

**Comment by mattpen** [comment]
That works for me.

**Comment by mattpen** [comment]
The message was updated on phet-server tonight.
