### ISSUE TITLE
Encapsulate error messages within a red box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#483]
A suggestion from @oliver-phet, we should put the site's error messages within the red text box so users are more easily directed to read them:

Current:
<img width="375" alt="screen shot 2016-08-23 at 11 12 52 am" src="https://cloud.githubusercontent.com/assets/5863899/17902014/cafa31ea-6922-11e6-9872-84b2f166d848.png">

Suggested:
<img width="375" alt="screen shot 2016-08-23 at 11 12 52 am" src="https://cloud.githubusercontent.com/assets/5863899/17902232/bafc2ebe-6923-11e6-8956-4e1c8b64ecb8.png">

Disclaimer: editing with Preview is hard, the above does not reflect the final design 😄

**Comment by mattpen** [comment]
This is not trivial to implement.  These are separate components in wicket and it will be difficult to write css rules that would achieve this effect.  I'll try to take a look at this early in September.

**Comment by mattpen** [comment]
@phet-steele - I found a quick fix for this:

![image](https://cloud.githubusercontent.com/assets/11747676/17954307/4f2d63dc-6a37-11e6-8d7d-2708ad922991.png)


This is ready for the next deploy.

**Comment by mattpen** [comment]
This was deployed to phet-server tonight.  @phet-steele can you please confirm?

**Comment by phet-steele** [comment]
@mattpen It's working (yay!), @oliver-phet if you approve you may close.

**Comment by oliver-phet** [comment]
Looks good to me!
