### ISSUE TITLE
Known issue: activity file alignment is off for team members

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#484]
When team members sign in to the phet site and view an activity page, the admin control panel does something funny to the list of files. The first two will be aligned but any following activities are shifted over.

![screen shot 2016-08-23 at 1 02 48 pm](https://cloud.githubusercontent.com/assets/7852916/17906233/b534dd72-6933-11e6-99a6-87fc4ead259f.png)
![screen shot 2016-08-23 at 1 03 28 pm](https://cloud.githubusercontent.com/assets/7852916/17906236/b8d9c29e-6933-11e6-8c20-a34f40e19b23.png)

Since this does not affect non-team members, we will not address it, but wanted to make it a known issue here on github.

**Comment by mattpen** [comment]
I checked a this activity with a non-team member account and it is affected but only after 6 or more files are added.  I think it may be wrapping around the left side navigation menu.

![image](https://cloud.githubusercontent.com/assets/11747676/17906467/b13e38e8-6934-11e6-80c9-5dff352c51a9.png)

**Comment by mattpen** [comment]
This should be fixed, it will be deployed to phet-server with the rest of the contribution changes.

**Comment by mattpen** [comment]
@amanda-phet This should be fixed now on the live site.  https://phet.colorado.edu/en/contributions/view/3990

Please reopen if I missed anything.
