### ISSUE TITLE
Change Help Center to open on Getting Started

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#486]
Can we change the Help Center so that the default starting page is https://phet.colorado.edu/en/help-center/getting-started

(Effectively removing the page with the 5 larger icons)

I think all that needs to be updated is the footer link and removing the original page.

**Comment by mattpen** [comment]
@oliver-phet - Should `/locale/help-center` redirect to `/locale/help-center/getting-started` or vis versa, i.e. should the Getting Started page keep the same url or should it just use `/locale/help-center`?

**Comment by oliver-phet** [comment]
We can just use /locale/help-center/getting-started no need to have /locale/help-center for anything. So we'll have:
/locale/help-center/getting-started
/locale/help-center/running-sims
/locale/help-center/offline
etc.

**Comment by mattpen** [comment]
So no redirect needed?  It's ok for `/locale/help-center` to go to the 404 error page?

**Comment by oliver-phet** [comment]
As long as when a user clicks 'Help Center' in the footer they are given /l`ocale/help-center/getting-started`, I don't see a reason to have `/locale/help-center`. Do you?

**Comment by amanda-phet** [comment]
Please make sure `/locale/help-center` redirects to `/locale/help-center/getting-started`. 

I think it's even fine to keep the `/locale/help-center` page, we just wouldn't have a link to it from the footer (or anywhere on the site). It's not uncommon for this page to exist in case a user decided to delete the "getting-started" part of the link. But a redirect would be fine.

**Comment by mattpen** [comment]
I added a redirect for /locale/help-center to /locale/help-center/getting-started and changed the links in the footer panel.  This should be ready for the next deploy.

**Comment by mattpen** [comment]
This was deployed to phet-server tonight.  The Footer link is now directing to Getting Started and `/locale/help-center` is redirecting to Getting Started.  However, `/locale/help-center/` is not being redirected and goes to a 404 page instead. See https://phet.colorado.edu/en/help-center/   Does this need to be corrected @oliver-phet or @amanda-phet?  Thanks.

**Comment by amanda-phet** [comment]
>/locale/help-center is redirecting to Getting Started. However, /locale/help-center/ is not being redirected and goes to a 404 page instead.

The difference is the additional `/`? I'm not sure what the usual protocol is for links like that. When I play with a few different pages, the addition of a `/` at the end always seems to go to a 404 page, so this page doesn't seem to behave any differently.

**Comment by mattpen** [comment]
@amanda-phet - Yes, that was the difference I noticed.  I didn't realize it was a general pattern on the website.  I thought that trailing `/`'s were usually ignored, but I checked a few popular websites and this only applies to home pages. 

If that doesn't need to be fixed I think this can be closed.  Please reopen if needed.
