### ISSUE TITLE
Filter Teacher Primers from the installer

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#487]
Por favor, @mattpen. Installers currently display the primers, but are eternally locked. There is no way to sign in from the installer. Allowing users to view the primers from local host would be a nightmare with Vimeo permissions. It's best to just filter these out of the installer.

**Comment by mattpen** [comment]
This is ready for deploy, it *might* be ready to test on monday.

**Comment by mattpen** [comment]
@phet-steele - this should be blocked now, please confirm in the installer built over the weekend.

**Comment by phet-steele** [comment]
I do not see any primers in the Win w/activities installer. Thanks @mattpen!!!!
