### ISSUE TITLE
there are what looks like some old and unneeded backup directories for two sims

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#488]
While looking through the installer builder logs in the process of working on another issue, I came across a couple of errors where it was trying to pull something out of what looks like some backup directories.  The errors in the log look like this:
```
Error: Modded installer JAR not found: /data/web/static/phetsims/sims/energy-forms-and-changes-bak/energy-forms-and-changes-bak_all_installer.jar
Error: Modded installer JAR not found: /data/web/static/phetsims/sims/optical-tweezers-bak/optical-tweezers-bak_all_installer.jar
```

If I go to the URL that the installer uses to obtain a list of sims, these two directories indeed show up, see https://phet.colorado.edu/sims/energy-forms-and-changes-bak/ and https://phet.colorado.edu/sims/optical-tweezers-bak/.  

The dates on these directories are fairly old.  Can they be deleted?  It's not a huge problem for the installer builder, but it would clean up some noise in the log and would reduce the size of the rip a little bit.

**Comment by mattpen** [comment]
I'm not aware of any uses for these folders, tagging for developer meeting to see if anyone else knows if they are still used.

**Comment by jessegreenberg** [comment]
Asked at dev meeting 9/1/16 - determined that it was safe to remove.  @mattpen will remove these.

**Comment by mattpen** [comment]
I moved these directories to `/tmp` so they can be recovered if needed.
