### ISSUE TITLE
Remove changes section from about news page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#49]
Git rid of "Website and Simulation Updates" section under about news, as discussed in 12/11/14 dev meeting, as part of phasing out the changes.txt file.

**Comment by ariel-phet** [comment]
Also file size of sim download can be removed

**Comment by aaronsamuel137** [comment]
OK I've removed the changelog link and the file size. Assigning to @ariel-phet for review.

**Comment by aaronsamuel137** [comment]
This was done awhile ago, I'm closing the issue.
