### ISSUE TITLE
multi-language installer being messed up by redirects

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#490]
I am trying to get the multi-language installer working on phet-server due to a request for a zh_CN version.  The main index page of the resulting installed version looks like this:

![web-site-redirect](https://cloud.githubusercontent.com/assets/3082831/18023472/b27b2084-6bb6-11e6-878e-198d84320aed.PNG)

This made me think that perhaps it was having issues with redirects to https from http, since we've seen some other issues like this (see #472).  I looked at the source code for the main page, and it does indeed look like the main pages for the website translations are linked as http, see the screenshot below.  I think switching these to https may solve the issue with the multi-language installer.

![website-http-for-languages](https://cloud.githubusercontent.com/assets/3082831/18023502/17a9b1d2-6bb7-11e6-9512-9e933908135f.PNG)

**Comment by jbphet** [comment]
We made a commitment to deliver a zh_CN installer by September 1, so I'm marking this as high priority and assigning to @mattpen.

**Comment by mattpen** [comment]
@jbphet - I thought we left the links underneath this dropdown in for use with the installer.  It's not actually clicking the dropdown box right?  These links should be relative, so there shouldn't be any 301 redirect that the installer needs to follow. 

![image](https://cloud.githubusercontent.com/assets/11747676/18024959/6b7d1cf8-6bd6-11e6-9eb7-8417c52541bc.png)

 If I make one of these links visible and click it, the network tab reports only 200 OK and 304 Not Modified, there are no redirects.

![image](https://cloud.githubusercontent.com/assets/11747676/18024982/6d298dec-6bd7-11e6-9583-9e8730634677.png)

That said, those dropdown values *should* be https and I'll fix them tonight anyway.

**Comment by mattpen** [comment]
@jbphet - what is the content of the "Click here" link?

**Comment by jbphet** [comment]
The content of the link is: 
```html
<A HREF="index.html"><h3>Click here...</h3></A>
```
...which makes it a circular link.

**Comment by mattpen** [comment]
@jbphet - Is the initial link for httrack pointing to https?  It might be getting blocked by the initial 301 redirect.  

I tested a rip with httrack today, pointing to the initial location `https://ox-dev.colorado.edu/zh_CN` and using the user-agent `httrack-web-offline-activities`.  It built a local copy of the website with a working locale dropdown menu.  

I think this might be an issue with the httrack settings rather than with the website, can you point me to where those are stored on phet-server and I can check?

**Comment by jbphet** [comment]
I've done some investigation on this, and the details can be seen in https://github.com/phetsims/installer-builder/issues/22#issuecomment-243584145 and subsequent comments.  To summarize, HTTrack is trying to follow the links inside the language selector as http, not https.  I don't know why it would do this, and am open to suggestions if anyone has any.  For now, I'm trying a rip with an additional HTTrack filter set to disallow http links.

**Comment by mattpen** [comment]
@jbphet - I deployed the change for the dropdown menu at ~11PM.  I'll check again at 12PM and make sure that the cached entries have https links.

**Comment by mattpen** [comment]
The dropdown links are now in https on phet.colorado.edu.  This part should be g2g at least.

**Comment by mattpen** [comment]
@jbphet @phet-steele - Can you confirm if these links are working now?

**Comment by jbphet** [comment]
We were able to create a multi-language installer and provide it to the requester.  We've only done one, so I wouldn't call it an exhaustive test, but I think we can safely close this for now.
