### ISSUE TITLE
Update JetBrains logo

### ISSUE THREAD

**Issue by samreid** [phetsims/website#491]
On 8/30/16 1:58 AM, JetBrains asked us to update the logo on our page:

> We've switched to new design recently. Please, could you update JetBrains logo? The new one can be downloaded from https://www.jetbrains.com/company/press/

Tagging @mattpen to put it on his radar and assigning to @ariel-phet to prioritize.  Also, @ariel-phet the rest of the context is in the email I forwarded with the subject line `[JetBrains] Re: Open Source License Questions`

**Comment by mattpen** [comment]
I can upload the new image with the next deploy.

**Comment by ariel-phet** [comment]
Sounds good @mattpen, next deploy would work well for priority

**Comment by mattpen** [comment]
![image](https://cloud.githubusercontent.com/assets/11747676/18114561/3ab6bd50-6ef5-11e6-9178-be35c8ef182f.png)

![image](https://cloud.githubusercontent.com/assets/11747676/18114650/047f2afa-6ef6-11e6-8446-2769f6ead40d.png)

Do these look ok @ariel-phet @samreid ?  If so, they are ready for deploy.

**Comment by ariel-phet** [comment]
That looks good to me

**Comment by samreid** [comment]
Looks great, thanks!

**Comment by mattpen** [comment]
The new images were deployed to phet-server tonight.  @samreid Is this ok to close, or do we need to keep it open for:

> the rest of the context is in the email I forwarded with the subject line [JetBrains] Re: Open Source License Questions

**Comment by samreid** [comment]
Looks great, we will discuss the rest in dev meeting, closing.
