### ISSUE TITLE
Sim page title structure

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#492]
Currently, the page title structure for a sim page appears to be 

SimName - Keyword1, keyword2, keyword3 - PhET 

Many sims have keyword1 = SimName, so this seems redundant. Instead, we propose that the page title structure be in the form 

SimName - Topic1 | Topic2 | Topic3 - PhET Interactive Simulations 

unless there was a specific reason for using keywords instead of topics. If we stick with keywords, the keywords need to be ordered so that the top 3 are the best 3 to have listed on the page title. Since topics are already user-facing, they are likely to be vetted. 

@oliver-phet @ariel-phet @amyh-phet @arouinfar

**Comment by ariel-phet** [comment]
@zepumph we will have you make this change but first I am going to double check with @jonathanolson if there is anything this change will unintentionally mess up (some kind of meta data or such)

**Comment by jonathanolson** [comment]
I'm fine with this change, particularly if it makes better titles for Google search pages.

**Comment by zepumph** [comment]
@ariel-phet I fixed this issue, although it isn't pushed or deployed yet, and in working on it I realized that sometimes the Topics include the sim name as well. Correct me if I'm wrong, I don't really understand the keyword/topic differentiation or what they are used for separately. 

For example look at [faraday's law](https://phet.colorado.edu/en/simulation/faradays-law)
It has Faraday's law in the bulleted  list on the right of the Image, which I thought was the topic, but in the title it isn't there. Assigning to provide guidance. I can easily get rid of the sim name in either keywords or topics.

**Comment by zepumph** [comment]
On closer look perhaps Faraday's Law's keywords and topics may just be the same? Anyways I changed the look of title page and it references topics not keywords. @mattpen and I are deploying to production tonight if we want this to be added.

**Comment by zepumph** [comment]
@ariel-phet changes are deployed, see what you think

**Comment by ariel-phet** [comment]
@zepumph where this has taken effect, it looks good. However, I seem to be seeing places where the new format is not showing:

Example:
https://phet.colorado.edu/en/simulation/legacy/balloons-and-buoyancy
https://phet.colorado.edu/en/simulation/isotopes-and-atomic-mass
https://phet.colorado.edu/en/simulation/legacy/calculus-grapher

I did not look extensively but these seem to all be sims that have only 2 topics listed, so perhaps the logic needs to be adjusted so it still captures these case and lists 1-3 topics in the title depending how many are available (the ones with 3 appear to be working in quick random sampling).

**Comment by ariel-phet** [comment]
@zepumph did you see my comment above?

**Comment by zepumph** [comment]
Yeah I did, I'm still working on a change that incorporates less topics. I haven't had time to do much with it yet. I'll keep you posted.

**Comment by zepumph** [comment]
So the two topic title is now fixed:
![image](https://cloud.githubusercontent.com/assets/6856943/19813814/8cc6ecc4-9cf8-11e6-9f50-be325aafc203.png)


and so is the problem with sims' first topic being the name of the sim in the title:

![image](https://cloud.githubusercontent.com/assets/6856943/19813856/cab27454-9cf8-11e6-8030-ec23cab6578c.png)


How does that look @ariel-phet?

**Comment by ariel-phet** [comment]
@zepumph looks good, can you deploy to dev so I can test it out?

**Comment by zepumph** [comment]
Have a look on phet-dev now @ariel-phet.

**Comment by ariel-phet** [comment]
Looking great! I would say ready for the next website deploy

**Comment by zepumph** [comment]
Changes have been deployed. Closing
