### ISSUE TITLE
Help center pages using Hewlett logo in Open Graph Protocol

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#500]
@mattpen when answering a question on our facebook account I noticed that all help center pages are using the Hewlett logo in the open graph protocol. 

We should change that to be consistent. It seems the rule should be that unless otherwise specified (such as for sim pages) the default image is always the PhET logo as for the homepage and such.

**Comment by ariel-phet** [comment]
@zepumph this might be something nice for you to tackle once you have things set up on your computer

**Comment by ariel-phet** [comment]
@zepumph why don't you tackle this one

**Comment by mattpen** [comment]
Merged changes with master

**Comment by zepumph** [comment]
Deployed changes last night, closing
