### ISSUE TITLE
make translations open in same tab

### ISSUE THREAD

**Issue by jbphet** [phetsims/website#504]
Back in https://github.com/phetsims/website/issues/374 we decided to change the web site so that translations didn't open in a new tab.  I was doing some testing related to translations today, and noticed that the translations still open in a new tab.  I discussed this with @ariel-phet, and we think that this was just omitted when #374 was done, not a conscious choice, so the behavior should be changed such that translations also open in the same tab.

**Comment by ariel-phet** [comment]
@zepumph kicking this one to you

**Comment by zepumph** [comment]
Hey could I get a little more info on what exactly is meant by a 'Translation' . Perhaps a link where I can see the problem. Thanks!

**Comment by mattpen** [comment]
@zepumph If you go to a sim page, such as https://phet.colorado.edu/en/simulation/plinko-probability, then expand the Translations section, and click on one of the links in the "Download or run" column, these should open in the same tab, not a new tab.

**Comment by zepumph** [comment]
Deployed on the main website last night. Closing
