### ISSUE TITLE
Improper HTML sim version comparison

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/website#505]
It looks like in Project.java, getLatestHTMLDirectory sorts alphabetically, improperly saying "1.1.10" is a lower version number than "1.1.9" (see https://github.com/phetsims/rosetta/issues/137).

The correct way is to separate the version number into major/minor/maintenance and compare each in turn.

**Comment by mattpen** [comment]
The comparison was corrected in the previous commit.  This is ready for deploy.

**Comment by mattpen** [comment]
This was deployed to phet-server tonight.
