### ISSUE TITLE
User reported issue: United Kingdom registration country/state behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#509]
Hi, I've just signed up for an account at https://phet.colorado.edu/?wicket:interface=:0:2::: but I noticed that your (required) drop-down menu for State/Province seems to have only English council areas! It would be more normal for a box with those headings to just list England, Wales, Scotland and maybe Isle of Man and some of the smaller islands! In fact, what you've done - I only realised half-way through writing this email - is put 'United Kingdom' when you apparently mean 'England'; very unconventionally, Scotland and Wales have their own entries under 'country'. I look forward to Scotland becoming an independent country, but we're not there yet! And in the meantime, excluding everywhere except England from something marked 'UK' is widely considered to be pretty offensive. You should probably merge all these categories, along with Jersey, Guernsey, Man and any others you list separately, but you could also just rename the UK entry to 'England'.

I resorted to putting Islington (the London borough where I grew up) as my 'state' and Edinburgh (the capital of Scotland, which is much bigger than Islington) as my city, because I didn't notice you'd listed 'Scotland' as a separate country.

**Comment by oliver-phet** [comment]
Can @mattpen or @zepumph verify what lists/database we are currently using for the Country and State/Province lists?

**Comment by mattpen** [comment]
@oliver-phet - These are hard-coded into the dropdown panel and no source is given. See [this file](https://github.com/phetsims/website/blob/master/src/java/edu/colorado/phet/website/authentication/panels/CountryStateDropdownPanel.java) for the complete list.  I can edit as needed.  Using some open source resource would probably be better, but this is a difficult thing to handle as borders are frequently changing and always in dispute somewhere.  UK is a pretty clear case though and I think the person who wrote in is correct, how should we proceed?

**Comment by oliver-phet** [comment]
I searched around a bit for some country/city lists but there doesn't seem to be a solid, open source option.

Perhaps something like this: https://github.com/hiiamrohit/Countries-States-Cities-database

**Comment by zepumph** [comment]
I just found out that the un maintains some pretty detailed lists here:
http://www.unece.org/cefact/codesfortrade/codes_index.html

Download the .txt or .csv and look at the "2016-1 SubdivisionCodes" and it gives a list of every province/state:
"US","AL","Alabama","State"
"US","AR","Arkansas","State"
"US","AS","American Samoa (see also separate entry under AS)","Outlying area"
"US","AZ","Arizona","State"
"US","CA","California","State"
"US","CO","Colorado","State"
"US","CT","Connecticut","State"
"US","DC","District of Columbia","District"
"US","DE","Delaware","State"
"US","FL","Florida","State"
"US","GA","Georgia","State"
"US","GU","Guam (see also separate entry under GU)","Outlying area"
"US","HI","Hawaii","State"
"US","IA","Iowa","State"
"US","ID","Idaho","State"
"US","IL","Illinois","State"
"US","IN","Indiana","State"


This is only looking at two character country codes, if we need the actual country name we can use: 
https://datahub.io/dataset/iso-3166-1-alpha-2-country-codes/resource/9c3b30dd-f5f3-4bbe-a3cb-d7b2c21d66ce
to parse out two digit code and full name.

That wouldn't take too long to do, and it would not only be complete, but my guess is the unece likes to use the same formatting, so that if there was an updat away from iso-3166-1 then we could just replace the source file.

**Comment by oliver-phet** [comment]
This sounds like a great option - but how would we handle changes to user records?

**Comment by zepumph** [comment]
@oliver-phet can you be a little more specific on  what you mean by updating user records? Also there is also an index of cities if we want to go that far like these from the UAE:
,"AE",,".UNITED ARAB EMIRATES",,,,,,,,
,"AE","ABU","Abu al Bukhoosh","Abu al Bukhoosh",,"1-------","RL","0307",,"2529N 05308E",
,"AE","AUH","Abu Dhabi","Abu Dhabi","AZ","1-345---","AI","1101",,"2428N 05422E",""
,"AE","AMU","Abu Musa","Abu Musa",,"1-------","RL","0201",,"2552N 05501E",
,"AE","ARP","Ahmed Bin Rashid Port","Ahmed Bin Rashid Port","AZ","1-------","RL","1407",,"2532N 05533E",
,"AE","AJM","Ajman","Ajman",,"1-3-----","RL","0103","QAJ",,
,"AE","AAN","Al Ain","Al Ain",,"---4----","AI","9601",,,
,"AE","DHF","Al Dhafra","Al Dhafra",,"--34----","AI","0507","","2414N 05432E",""
,"AE","FJR","Al Fujayrah","Al Fujayrah","FU","1--4----","AI","0212",,"2507N 05620E",

(Notice the country name as the first for the column for the country)

**Comment by oliver-phet** [comment]
Wouldn't we want to update the existing user records to this new list? ie: A Scotland user would be converted to United Kingdom.

I'm also wondering about the salesforce integration - @mattpen may need to comment if this change will affect that.

**Comment by oliver-phet** [comment]
A report of this from a second user:

> Hello, I've just registered however you have absolutely no locations in Scotland (which is part of the UK) listed at all!  I've had to use a false province and city because of this.  Could you please consider updating this as I know many Scottish teachers which use pHet and it would be lovely if we were able to show our locations accurately.

**Comment by oliver-phet** [comment]
@ariel-phet Priority for this issue?

**Comment by ariel-phet** [comment]
@oliver-phet lets say medium and see if @zepumph can get to this next week

**Comment by zepumph** [comment]
I found this url: https://blueprints.launchpad.net/openobject-server/+spec/countries-states-and-provinces, that has states and provinces that I am going to use for the drop downs. It's in xml which will make it nice and easy. @mattpen where should the `countries.xml` and `provences.xml` go?

**Comment by zepumph** [comment]
Update, I think that https://github.com/hiiamrohit/Countries-States-Cities-database may be a really good option, after diving into an implementation myself, perhaps it would be easiest to export it. This github repo isn't tremendously popular, but it seems good enough option, and it's dynamically loaded, unsure how we would work wicket into that.

**Comment by zepumph** [comment]
The dropdowns for country and state have been updated. We did this by writing a script that polls the open source website geonames.org. See loadCountryStateDropdown.js for more information. That script finishes by manually overwriting the static arrays in CountryStateDropDownPanel.java. 

So the options are up to date now, and whenever we want to update it, we just have to run the script and then recommit the changed java file to github.

**Comment by zepumph** [comment]
@oliver-phet, after looking with @mattpen, all of the problems that you were being emailed about are now fixed. I'm going to unassign myself and add the waiting to be deployed flag. ( @mattpen thanks for all the help on this one).?

 @oliver-phet I will post it to ox-dev so you can take a look at it.

**Comment by zepumph** [comment]
Take a look here: https://ox-dev.colorado.edu/en/register?dest=%2F

**Comment by oliver-phet** [comment]
This is looking good to me! When do we expect this to be deployed?

**Comment by zepumph** [comment]
We were thinking sunday if that's good for you.

**Comment by mattpen** [comment]
@oliver-phet - This should be live on phet.colorado.edu now.
