### ISSUE TITLE
Should we get rid of the newletter page?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#510]
https://phet.colorado.edu/en/about/news 

The last posted newsletter is from spring 2015. We've definitely sent some since then. 

This page is also missing the "subscribe" entry box. (https://github.com/phetsims/website/issues/87#issuecomment-79353159) So there is currently no way to subscribe (other than through signing up, but that is not clear). 

I am wondering if we should get rid of this page entirely if it is not going to be monitored/updated and if users cannot subscribe.

**Comment by ariel-phet** [comment]
I would be fine with killing this page (it is currently not navigable from the site I believe). If we keep it, we should perhaps update the archive to only include our modern format newsletters and figure out a place to put a navigation link.

**Comment by amanda-phet** [comment]
It is navigable from the footer - the envelope icon.

**Comment by kdessau-PhET** [comment]
I'm fine with killing it especially since we use the new format. We'd have to make up a dummy newsletter to link it though. @oliver-phet What do you think? Or are the links from the footer active and not subscriber specific?

**Comment by ariel-phet** [comment]
@amanda-phet - oh right!

**Comment by oliver-phet** [comment]
@kdessau-PhET I'm not following. The latest newsletters could be rendered in a browser (since they are written in HTML) so it would be doable to convert a newsletter into a webpage. 

What did you mean by this comment?

> What do you think? Or are the links from the footer active and not subscriber specific?

**Comment by kdessau-PhET** [comment]
If you think it will work then we should be fine. But one question is is it worthwhile. I am not sure if it is necessary. The newsletters are so much shorter in the new format. Did anyone really use this page?

**Comment by amanda-phet** [comment]
Discussed further at 10/11/16 meeting and decided to get rid of this page (as well as the link from the footer). 

I assume reworking the footer is the nontrivial part of this request, so assigning to @mattpen to give an ballpark on the difficulty and @ariel-phet to assign priority.

**Comment by mattpen** [comment]
@amanda-phet -- I think removing the internal links to the newsletter pages should be relatively easy, even in the footer.  Removing the routes will be more difficult, and it's not clear what the new behavior should be.  If some requests one of the newsletter pages, should it show the 404 not found page or redirect to something else?

**Comment by ariel-phet** [comment]
@mattpen @amanda-phet I think if someone requests one the newsletter pages perhaps just redirect to the "about PhET" page. Eventually we will tidy that page up, and perhaps it will have a portion on it that is an archive of the latest news we have put up on the homepage (in the new design).

**Comment by amanda-phet** [comment]
>If some requests one of the newsletter pages, should it show the 404 not found page or redirect to something else?

I'm fine with @ariel-phet 's suggestion to redirect to the "about PhET" page. 

If there's nothing else to discuss, let's move forward with remove the newsletter page from the site and the footer.

**Comment by kdessau-PhET** [comment]
I agree.

**Comment by mattpen** [comment]
This should be ready for deploy, I'll publish the changes to [ox-dev](https://ox-dev.colorado.edu) shortly to check.

**Comment by mattpen** [comment]
This was deployed to phet-server tonight.
