### ISSUE TITLE
Write API for updating translate time of a sim

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#515]
We should add an API to the website code that takes a date, sim-name, and locale from a POST request and changes the translateTime for that localized sim with that date.  This is needed for https://github.com/phetsims/phet-app/issues/234, and after it is complete changes will need to be made to the build-server/rosetta.

**Comment by mattpen** [comment]
This data should also be added to v1.1 (new) of the Metadata API.

**Comment by mattpen** [comment]
Perhaps instead of implementing an API, `Project.synchronizeProject` should be changed so that it updates the translateTime rather than updateTime, if it detects that it was called because of a translation publication.  In this case, the build-server would need to know if it has been called by rosetta, and it should pass that information to the website.

@jonathanolson - Do you foresee any issues with this approach? Is there any reason a translation should change the updateTime in addition to the translateTime?

**Comment by mattpen** [comment]
@jonathanolson @jbphet -- I have made changes to build-server, rosetta, and the synchronizeProject call on the website, so that the website is notified if a synchronize project call was originated from a rosetta translation and what locale was translated.  I think this is ready to test on ox-dev, but I would like to get your input on if you think this is a good approach or not.  I made the changes for perennial and rosetta in a feature branch called `ios-i18n`.

**Comment by jbphet** [comment]
I'm not too keen on this approach.  It seems like it forces some tight coupling and some implicit assumptions that could easily get broken in the future.  Assuming I understand this correctly, the code has been changed such that Rosetta identifies itself to the build server when a build request is made, and the build-server assumes that this means that a translation is being requested, so the build-server changes how it calls ```synchronizeProject```.  If, in the future, we ever forget about this and modify Rosetta such that it doesn't identify itself, or we kick off translations from somewhere else, the meta data wouldn't get updated correctly.  I'd advocate for something simpler, something where it doesn't matter to the build-server where the build request came from - if it rebuilds a live version of a simulation, or updates the _all version for a given locale, the meta data for that live version is updated accordingly.

**Comment by mattpen** [comment]
@jbphet and I discussed this issue today.  We are going to remove the changes from rosetta, and change build-server so that it passes on the list of locales that it has built.  The Synchronize project will update the translate time of all locales in the list, and change update time for the simulation to return the translate time of the English locale.

**Comment by mattpen** [comment]
I committed the changes in above and in this perennial commit: https://github.com/phetsims/perennial/commit/311d2cb0675a96a0452344027cedb831a027f9d6.  This is ready for deploy/testing on ox-dev.

**Comment by mattpen** [comment]
@jonathanolson - The synchronizeProject command does not appear to be changing the update time on new releases of html simulations, only when new simulations or new translations are published.  Should updateTime change when we publish a new version of a sim?

**Comment by mattpen** [comment]
The translateTime logic appears to be working.  All sims were initialized to translateTime of `2016-11-09 20:28:01.31058` (the current date/time when I ran the initialization).  Here are the sims sorted by date descending today:
```
  id  | locale |                                                title                                                | simulation |       translatetime       
------+--------+-----------------------------------------------------------------------------------------------------+------------+---------------------------
 7337 | kn     | ಕಣಗಳು ಮತ್ತು ಬೆಳಕು                                                                                     |        169 | 2016-11-14 02:15:54.864
 7336 | kn     | ಟ್ರಿಗ್ ಪ್ರವಾಸ                                                                                           |        181 | 2016-11-14 02:13:53.218
 7335 | kn     | ಅಣು ಆಕಾರಗಳು                                                                                         |        170 | 2016-11-14 02:11:31.254
 7334 | hi     | रुदरफोर्ड विकिरण                                                                                      |        187 | 2016-11-13 08:22:26.757
 7333 | ko     | 러더포드 산란                                                                                       |        187 | 2016-11-11 23:57:55.454
 7332 | ko     | 플린코 확률                                                                                         |        190 | 2016-11-11 23:53:08.234
 7331 | ko     | 하전과 전기장                                                                                       |        188 | 2016-11-11 23:37:36.314
 7330 | ko     | 원자간 상호작용                                                                                     |        189 | 2016-11-11 23:30:59.516
 7329 | ko     | 면적 생성기                                                                                         |        149 | 2016-11-11 23:10:43.536
 7328 | hi     | फैराडे का नियम                                                                                        |        161 | 2016-11-10 22:15:47.356
 7327 | hi     | समस्थानिक और परमाणु भार                                                                               |        183 | 2016-11-10 22:07:31.103
 6240 | fr     | pH Scale                                                                                            |        173 | 2016-11-09 20:28:01.31058
 6472 | sk     | Farebné videnie                                                                                     |        158 | 2016-11-09 20:28:01.31058
 6592 | sk     | Roztok cukru a soli: Mikro                                                                          |        121 | 2016-11-09 20:28:01.31058
...
```

The simulation updatetime appears to still be working as well:
```
 id  |                   name                    |       updatetime        
-----+-------------------------------------------+-------------------------
 169 | molecules-and-light                       | 2016-11-14 02:15:54.864
 179 | arithmetic                                | 2016-11-08 08:26:19.399
 175 | resistance-in-a-wire                      | 2016-11-08 07:47:34.952
 172 | ohms-law                                  | 2016-11-08 07:27:54.808
...
```
