### ISSUE TITLE
Make Chemistry PD video featured video on Teacher Resources page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#516]
@amyh-phet please work with @zepumph to get the main video on the teacher resources page changed to the one featuring Tim. You might need to get @oliver-phet to put it up on youtube for you first.

With this change lets go ahead and remove the "happy speak" of "Welcome. in these pages..."

Might be good to give the video a brief title and description, something that conveys "college example but with ideas relevant to any teaching level"

**Comment by ariel-phet** [comment]
Labeling high priority since this should be a relatively speedy change and would be good to do in the near future, so at least the main video on the page is more relevant/useful

**Comment by ariel-phet** [comment]
After this issue is tackle it would be good to consider how to deal with https://github.com/phetsims/website/issues/456

**Comment by zepumph** [comment]
@amyh-phet what is the status of this video? Is it on youtube or do we still need to do something more?

**Comment by amyh-phet** [comment]
@zepumph   Working on this this afternoon.  I didn't see it on our youtube channel.  We will also need to make small changes to the text on the page that goes with the video.

**Comment by zepumph** [comment]
@amyh-phet should @oliver-phet put it on youtube, or is there another way to get that done? I can change the text simply, just let me know what you think we do instead of the "happy speak".

**Comment by oliver-phet** [comment]
I believe this is the video: https://www.youtube.com/watch?v=UypdZe2Wv9A&feature=youtu.be

It is currently "unlisted".

**Comment by amyh-phet** [comment]
@zepumph   Here's a mockup for the new video and text on the Teaching Resources page.  In addition to replacing the 'Teachers and Students Speak about PhET' video, the text above the video should be replaced with the text shown on the mockup.

![herzog_video](https://cloud.githubusercontent.com/assets/13650180/19742945/765c507a-9b84-11e6-9941-6f5effaccf70.png)

Let me know if you need anything else to make this change.

**Comment by zepumph** [comment]
In updating this page, I'm noticing that it isn't translatable. @ariel-phet is this purposeful or an oversight?

**Comment by ariel-phet** [comment]
I would say an oversight

**Comment by zepumph** [comment]
Alright ill use this issue to also make the Teaching Resources page translatable.

**Comment by zepumph** [comment]
@amyh-phet Would I have a draft on my local machine right now and I make the 'Teacher Feature' a bit bigger on accident, and I kinda like it. Also this is the thumbnail for the video that youtube is giving me. Would you rather this:

![image](https://cloud.githubusercontent.com/assets/6856943/19778272/36bcb30a-9c39-11e6-8bff-f0da4990dfb9.png)


Or your original small and black 'Teacher Feature'.

**Comment by amyh-phet** [comment]
@zepumph  I like the version above.

**Comment by zepumph** [comment]
> the version above.

To be explicit, @amyh-phet the one I just showed you?

**Comment by amyh-phet** [comment]
@zepumph   Yes, the version you just showed me.  Sorry to be so vague!

**Comment by zepumph** [comment]
Changes are now on maser

**Comment by amyh-phet** [comment]
@zepumph   Any chance I can take a look at this on ox-dev before it goes live in the website?

**Comment by zepumph** [comment]
Definitely, I'll tell you when it is on oxdev

**Comment by zepumph** [comment]
@amyh-phet it's on ox-dev now: https://ox-dev.colorado.edu/en/teaching-resources

**Comment by ariel-phet** [comment]
I see two typos @zepumph "howhe uses" should be "how he uses" and "that arerelevant" should be "that are relevant"

**Comment by zepumph** [comment]
Thanks for that! The line wraps in the code took away spaces. All fixed now in the code base.

**Comment by ariel-phet** [comment]
@zepumph pleases also change the text to say "relevant across grade levels and disciplines."

**Comment by amyh-phet** [comment]
@zepumph looks good with the changes requested above by @ariel-phet

**Comment by zepumph** [comment]
Thanks guys!

**Comment by ariel-phet** [comment]
@zepumph let me know when you have pushed changes to ox-dev

In the lower sections there are also a few typos where line breaks appear not to have given spaces (inmany ways) (writtenresources) (otherteachers) (asimulations) (scrolldown) etc.

**Comment by amyh-phet** [comment]
@zepumph   Can we make a few more changes to the Teaching Resources page before pushing to the live site.  We'd like to eliminate the orange buttons and make the three headings below the videos function as links to the three pages.  The descriptions below the page titles should also be removed.   
![teaching_resources_content_changes_11_01_16](https://cloud.githubusercontent.com/assets/13650180/19908445/03c0b870-a049-11e6-8b75-2775736219d8.png)

**Comment by zepumph** [comment]
You will have to pardon me as I just got camtasia today!!!!! So I'm sending you unnecessary gifs! How does this look @amyh-phet?

![teacherresources](https://cloud.githubusercontent.com/assets/6856943/19982063/1f622276-a1ca-11e6-9c23-0426aceb3ad6.gif)

**Comment by amyh-phet** [comment]
@zepumph   Looks great, but I think we still have issues with missing spaces between words in the description above the video.  Can we also end the sentence with  "relevant across grade levels and disciplines."

**Comment by zepumph** [comment]
Yes sorry that is only happening on my local machine, sorry that isn't clear at all.

**Comment by zepumph** [comment]
This is how it actually looks:

![image](https://cloud.githubusercontent.com/assets/6856943/19983046/fb7eb7b2-a1cd-11e6-8c2b-81bb0d33271a.png)

**Comment by amyh-phet** [comment]
@zepumph    Awesome!  Looks great.

**Comment by zepumph** [comment]
Changes have been deployed. Thanks for your patience on this issue. Closing
