### ISSUE TITLE
Edits to Help Center 'Running Sims' sub categories

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#517]
@zepumph Could you make the following edits? You may need to consult @mattpen since he was the original dev of the Help Center.
1. Change 'Tablet' to 'iOS'
2. Change 'Mac' to 'macOS'
3. Create 'Android' and position 6th (between 'Chromebook' and 'Linux')

Once these are done, I'll fix up the individual questions!

**Comment by zepumph** [comment]
We are close on this one, I have everything working, but the background blue svg isn't dynamic, it's a picture that is loaded as a background. Should be an easy fix, someone will just need to upload a new copy of it, slightly extended to the same url:
`https://phet.colorado.edu/images/icons/help-center/Running_sims_box.svg`

Here is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/6856943/19813337/80eb9140-9cf6-11e6-8554-1523a378b261.png)

**Comment by zepumph** [comment]
Assigning to ON to assign the right person for the job

**Comment by oliver-phet** [comment]
I think this should do the job! https://drive.google.com/open?id=0B3aB5oT9c4e0WkJCMVVNZjhVYzQ

**Comment by zepumph** [comment]
Also, just a note, because of how the admin panel is instrumented in indexing in a list, as soon as we push this change, the single linux question will be under android, which will need to be manually moved if that isn't too much of a problem.

**Comment by oliver-phet** [comment]
Yep, not a problem.

**Comment by zepumph** [comment]
Thanks for that! it is looking good!!

![image](https://cloud.githubusercontent.com/assets/6856943/19814430/643a6af8-9cfb-11e6-9826-9536be21cba6.png)


 I'll let you know when it is deployed

**Comment by oliver-phet** [comment]
Can you recenter the icons in the rectangle? It looks like they are shifted slightly to the right?

**Comment by zepumph** [comment]
Hows that?

![image](https://cloud.githubusercontent.com/assets/6856943/19814652/55eaeb5c-9cfc-11e6-9645-4cca37acaba3.png)

**Comment by oliver-phet** [comment]
Yep, that looks great!

**Comment by zepumph** [comment]
Have a look here: https://ox-dev.colorado.edu/en/help-center/running-sims

And you'll find that the pointing to 'running sims' is off because we made the svg bigger, I'm not sure how to debug on my end. . .

**Comment by oliver-phet** [comment]
Yeah and it looks like the image got scaled a little too: 
https://ox-dev.colorado.edu/en/help-center/running-sims
vs
https://phet.colorado.edu/en/help-center/running-sims

When I edited the image I kept the "pointer" in the same absolute location and just added width (hoping to avoid this problem).

**Comment by oliver-phet** [comment]
Can you try fixing the scaling to see if it aligns the "pointer" properly?

**Comment by zepumph** [comment]
Yeah I'll be able to make it pretty in my end, for some reason I was stuck
in the 'editing the svg directly'  mode, it will be simple css

**Comment by zepumph** [comment]
@oliver-phet can you comment on the look of this up on ox-dev https://ox-dev.colorado.edu/en/help-center/running-sims

**Comment by oliver-phet** [comment]
Looks Great. Some of the text on my phone is a little odd... Windows and Mac questions are a larger font size than the rest of the categories.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 2, 2016 at 5:17 PM -0600, "Michael Kauzmann" <notifications@github.com<mailto:notifications@github.com>> wrote:


@oliver-phet<https://github.com/oliver-phet> can you comment on the look of this up on ox-dev https://ox-dev.colorado.edu/en/help-center/running-sims

-

**Comment by zepumph** [comment]
I see that, I'll get that fixed, in the mean time the change is up on the real site, so you should add your questions to them.

**Comment by zepumph** [comment]
After poking around it didn't seem obvious why those two tabs were rendering larger. I'm going to close this issue and create a new one for the text size.
