### ISSUE TITLE
Licensing form link change

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#519]
Moved to @colorado.edu drive. Please modify the link on the page https://phet.colorado.edu/en/licensing

New link:
If your use includes redistribution of the simulations, please let us know with [this form](https://docs.google.com/forms/d/e/1FAIpQLScJLU-T_z-0BnIEH3TekDdxBdMZ8cKboKNeZ-ftF1vqyn6zcA/viewform).

**Comment by oliver-phet** [comment]
Fixing something just a sec.

**Comment by zepumph** [comment]
I updated the href, but it is not on any server yet.

**Comment by zepumph** [comment]
This is on phet-dev now if you want to make sure all is good

**Comment by oliver-phet** [comment]
Looks good! Please publish.

**Comment by zepumph** [comment]
Changes have been published. Closing
