### ISSUE TITLE
Suggestion: Decrease number of sims under "New Sims"

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#520]
I was just looking for Build an Atom, and it took me a minute to remember there's a "New Sims" list and an "HTML" list. The "New Sims" list contains so many sims that it seems like the complete list. There's enough on the "New Sims" list that I think people could just interpret it as "a lot" and perhaps not recognize that there's actually another list of HTML sims. 
A small tweak that might help the "New Sims" list pique interest without looking too comprehensive (and potentially stopping browsing teachers from looking further) would be to limit the number of sims in the "New Sims" list to maybe the newest 3 or 6. 
Just a suggestion.

**Comment by ariel-phet** [comment]
@emily-phet thanks for the suggestion. I think it is easy to tweak these days. 

One obvious way to go might be to on a normal size page not go beyond "scrolling" for new sims.

Adding to the agenda for website meeting

**Comment by arouinfar** [comment]
Discussed in the 11/1/16 website meeting. We've decided that 12 sims seems like a reasonable number of new sims to display.

@mattpen can you reduce the number of sims that is shown on the "New Sims" page to 12 sims?

**Comment by mattpen** [comment]
@arouinfar - This is ready for the next deploy.  We should probably do a quick check to make sure the list of 12 most recent sims is still correct:

```
website_production=# select id, name, createtime from simulation order by createtime desc;
 id  |                   name                    |       createtime        
-----+-------------------------------------------+-------------------------
 190 | plinko-probability                        | 2016-09-30 10:38:45.713
 189 | atomic-interactions                       | 2016-09-26 17:28:41.513
 188 | charges-and-fields                        | 2016-09-06 19:08:14.832
 187 | rutherford-scattering                     | 2016-08-17 17:10:01.686
 184 | function-builder                          | 2016-07-13 14:47:05.951
 183 | isotopes-and-atomic-mass                  | 2016-05-24 12:38:27.448
 182 | neuron                                    | 2016-02-29 17:38:13.145
 181 | trig-tour                                 | 2016-02-08 10:31:22.009
 180 | bending-light                             | 2015-12-23 12:48:36.955
 179 | arithmetic                                | 2015-12-17 14:40:34.859
 178 | hookes-law                                | 2015-10-21 10:35:16.908
 169 | molecules-and-light                       | 2015-04-07 00:00:00
```

**Comment by phet-steele** [comment]
👍

**Comment by mattpen** [comment]
We should be showing the 12 most recent sims on the New sims page now.
