### ISSUE TITLE
Add translateTime to Metadata API

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#523]
We need to specify which locales have been changed to add internationalization to the app phetsims/phet-app/#234.

**Comment by mattpen** [comment]
This has been added but the value is omitted if the column is null.  

@jonathanolson - Should we initialize translateTime to some value?  Say today, or perhaps `localizedSimulation.getSimulation().updateTime`?

**Comment by jonathanolson** [comment]
Initializing makes sense, since we mainly care about when it gets updated in the future.

**Comment by mattpen** [comment]
I initialized all values of the column to today.  The new API appears to be working as planned, and will be deployed soon.
