### ISSUE TITLE
Change Development overview link

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#524]
Migrating to @colorado.edu

Please update the link here https://phet.colorado.edu/en/about/source-code
 
to: https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit

**Comment by zepumph** [comment]
Will you have a link in the future for the 'legacy source code' document at the bottom as well?

**Comment by oliver-phet** [comment]
Thanks for the reminder. New link for 'legacy source code': https://docs.google.com/document/d/1O0ykIapy866yVIkgezgXD0lFf5Gb-WsKskym3GDhWQY/edit?usp=sharing

**Comment by zepumph** [comment]
Those are all staged in master for the next deploy. Do you think there will be many of these link changes, because if so we could just make 1 issue for it, kinda like how we do #123, and whenever you have a new link I'll just commit it there. Just a thought, you do it however you think is best.

**Comment by zepumph** [comment]
@oliver-phet I would love your opinion on the previous comment, and then we can close this issue, the links were deployed last night.

**Comment by oliver-phet** [comment]
Let's close this one. Other links that come up will be lumped into 1 issue!
