### ISSUE TITLE
Create HelpCenter string with User-Agent

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#528]
@oliver-phet - If you add a string into the helpcenter with the token {{USER_AGENT}}, I can replace it dynamically with the actual user-agent string.

**Comment by oliver-phet** [comment]
I added that to this question, but formatting seems odd?
https://phet.colorado.edu/en/help-center/running-sims#q39-header

**Comment by mattpen** [comment]
Oh, I need to do a deploy before this will work, sorry!  I should be able to get something working by this weekend.

**Comment by mattpen** [comment]
@oliver-phet - I see there were some other problems with formatting, it looks like a bunch of extra <br> tags were added, and some of the <p> and <li> tags were not properly closed.  Can you check https://phet.colorado.edu/en/help-center/running-sims?someRandomQueryParameter#q39 and see if it looks better?

**Comment by oliver-phet** [comment]
I wonder if I am seeing different code in my admin panel than you? The entry you cleaned up looks really similar to what I had in before. I'll keep an eye on it next time I do an edit.
`<p>Submitting a detailed system report by opening a working HTML5 sim, copy/paste the 'report a problem', and send the information in an email to phethelp@colorado.edu: </p><ol><li>Click the PhET Menu (3 horizontal lines)</li><li>Click "Report a Problem..."</li><li>Copy/paste the output in an email to phethelp@colorado.edu (be sure not to edit the 'Troubleshooting information' section)</li></ol><p>If you cannot open an HTML5 sim, please copy/paste the following text in an email to phethelp@colorado.edu: <b>User-agent: &quot;{{USER_AGENT}}&quot;</b></p>`

**Comment by mattpen** [comment]
@oliver-phet - When I checked it, there were `<br>` tags where the `</p>` and `</li>` tags should have been.

**Comment by mattpen** [comment]
@oliver-phet - This should be working now on phet.colorado.edu.
