### ISSUE TITLE
Add Facilitating Activities overview video

### ISSUE THREAD

**Issue by schasteen** [phetsims/website#53]
Let me know if I should be posting things like this somewhere other than "issues" (is this a "task"?)

We have a new YouTube video ready, and need to make a new page to hold it.

At http://phet.colorado.edu/en/for-teachers/tipsForUsingPhet, we need a new subpage:
Facilitating PhET Activities for the K12 Classroom

Details:
- This should appear underneath the "Designing" video
- Add to the sidebar, and the front Tips page
- Use the text "How to productively guide students' exploration of the simulations during in-class activities. Focused on K12 (Download Video)."
- The video is at http://youtu.be/biBwtj0Gf-U.

For Teacher Tips on the page, under the video, *move* the following items from the Designing Activities tips page to this one:

Effective Facilitation of Activities in Elementary and Middle School. A detailed overview of facilitation strategies to help students work effectively on activities using PhET simulations.

PhET's Reflection Rubric. A rubric for teachers to reflect on the success of an activity using PhET simulations in K12. Also available as an editable Word Doc.

**Comment by aaronsamuel137** [comment]
@schasteen, I've added the page to phet-dev for you to review: http://phet-dev.colorado.edu/en/for-teachers/facilitatingActivities

The only things I need are an image for the right hand menu and the video for the download link.

Assigning to @schasteen for review.

**Comment by aaronsamuel137** [comment]
@schasteen, the page is up on phet-dev now for your review.

**Comment by schasteen** [comment]
Looks good to me, but would like @emily-phet to review before it goes live since this is her area.  Emily, check out the new http://phet-dev.colorado.edu/en/for-teachers/facilitatingActivities, and make sure it looks good to you.  You might want to look at what is on this page, versus the Designing Activities page, and see that their titles in the sidebars look good to you.  They are a bit long, I'm not sure how you would feel about shortening to "Designing Activities for K12" and "Facilitating Activities for K12".  That might be easier to parse in the sidebar.

**Comment by emily-phet** [comment]
Looks good. I'm fine with shorting to "X for K12" as Stephanie suggested.

**Comment by aaronsamuel137** [comment]
I've updated titles and deployed to the main website. @schasteen, let me know if there are any other adjustments needed or close the issue.

**Comment by schasteen** [comment]
Thanks Aaron!
