### ISSUE TITLE
Updates to Accessibility "Research and Design" Page

### ISSUE THREAD

**Issue by emily-phet** [phetsims/website#532]
Please update the accessibility reseach and design page with the following:

**Upcoming Presentations:**
February 27-March 4, 2017 - Taliesin L. Smith, Clayton Lewis, and Emily B. Moore. Description strategies to make an interactive science simulation accessible. 32nd CSUN Assistive Technology Conference. San Diego, CA.

**Past Presentations:**

"Upcoming Presentation" from October down into "Past Presentations"

Change:
Emily Randall. Developing accessible physics simulations for students with vision impairments. (2016) Physics Education and Computer Science Undergraduate Honors Thesis. University of Colorado Boulder, Boulder, CO. In Press.

To:
Emily Randall. Developing accessible physics simulations for students with vision impairments. (2016) Physics Education and Computer Science Undergraduate Honors Thesis. University of Colorado Boulder, Boulder, CO. (Thesis) [link:http://scholar.colorado.edu/honr_theses/1128/]

@terracoda - can you add:
- a reference/link for your presentation this week (following format of existing refs on accessibility and research page), and 
- a link to your thesis presentation?  
 
**Publications**

Emily B. Moore and Taliesin Smith. The PhET Interactive Simulations Project: Working to Increase Access to Interactive STEM Simulations [Part 2 of 2]. _SNOW, Education, Access and You!_ (Paper) [link: http://www.snow.idrc.ocad.ca/node/264]

Emily B. Moore. The PhET Interactive Simulations Project: Working to Increase Access to Interactive STEM Simulations [Part 1 of 2]. _SNOW, Education, Access and You!_ (Paper) [link: http://www.snow.idrc.ocad.ca/node/263]

@terracoda - can you add:
- a link to your thesis in the OCAD repository (I'm assuming it's in a repository) for the existing reference on the accessibility and research page?

**Comment by terracoda** [comment]
Recent presentation in St. John's at the Teaching with Technology Community Conference:
- November 14 & 15, 2016, Taliesin L. Smith, Clayton Lewis, and Emily Moore. Inclusive Interaction: Description Strategies for a Complex Interactive Science Simulation. [Teaching with Technology Community Conference](http://www.teachwithtechcommunitynl.ca). St. John's, Canada. [Show 'n Tell Presentation](http://terracoda.ca/research/description-presentation/).

- April 15, 2016 - Taliesin L. Smith. Access, action, agency: Inclusive design for the non-visual use of a highly interactive simulation. OCAD University. [Final Presentation](http://terracoda.ca/research/mrp-final-presentation/).

- Master's Research Project Link
 Access, action, agency: Inclusive design for the non-visual use of a highly interactive simulation. [Master Research Project](http://openresearch.ocadu.ca/id/eprint/713).

**Comment by ariel-phet** [comment]
@zepumph could you make these updates?

Also, in the long run, how difficult would it be to make this page editable through the admin interface much like the FAQ page? It seems inefficient to make an issue every time we want a change if there were instead a pretty bare bones interface for editing.

**Comment by ariel-phet** [comment]
Marking as medium priority mainly because this should be a relatively quick task (the update itself)

If and admin interface seems like a good idea, please make a separate issue @zepumph and we can discuss, but lets make these updates regardless if there is a longer term solution.

**Comment by zepumph** [comment]
I updated the links, I think that the admin panel update may be a really nice upgrade. Let's ask @mattpen what he thinks because he wrote the help center one I think. Is this a reasonably easy task to add (see above two comments)?

**Comment by mattpen** [comment]
@zepumph @ariel-phet - These pages are totally static so it should be relatively easy as long as Taliesin and/or Emily are comfortable editing simple html tags.  It sounds like Taliesin has prior experience with web development so I'm thinking that is fine.  It may be slighty time consuming adding each of the strings as key/value pairs in the DB, but I think that would ultimately save time in the long run.

@zepumph - If you go ahead with this I would look at the pattern used on the "Content" admin pages rather than the Help Center.  The Help Center admin page is designed to be able to add and remove questions ad hoc, which we don't need for the Research Page (as far as I know).

NOTE: It would be very easy to make these pages translatable as part of this process as well.  We'll need to add these to the translatable strings in order to be able to edit them live, to make them translatable we just make a new Entity that holds all of the strings.  

I'm happy to help with anything you need.

**Comment by ariel-phet** [comment]
@zepumph please make a separate issue, something like "Admin interface for editing accessibility page?" and assign it to @emily-phet and @terracoda to see if they are OK with that idea and then if so track progress.

**Comment by mattpen** [comment]
@emily-phet @terracoda - The changes to the research page should be up now on phet.colorado.edu.  Can you please check that it is appearing correctly?

**Comment by terracoda** [comment]
@mattpen, there are a few adjustments to make. It's a little confusing as some items are both presentations and publications.

__Under past presentations__
Please add the link to the presentation slides for my HCII presentation. It's the third item under the past presentations heading:

Just add the following link to the end
```<a href="http://terracoda.ca/research/hcii-presentation/"><abbr>HTML</abbr> Slides</a>```

So it looks like this:
> July 19-22, 2016 – Taliesin L. Smith, Clayton Lewis, and Emily B. Moore. A balloon, a sweater, and a wall: Developing design strategies for accessible user experiences with a science simulation. _International Conference on Universal Access in Human-Computer Interaction._ Toronto, Canada. [HTML Slides](http://terracoda.ca/research/hcii-presentation/)

__Under Publications__
We have some duplication, and a couple of missing links. Please combine items 3 and 4 (my Master Research Project) into one item like this:
>Taliesin L. Smith. Access, action, & agency: Inclusive design for the non-visual use of a highly interactive science simulation. Masters in Inclusive Design, Major Research Project. OCAD University, Toronto, Canada. In Press. [ Master Research Project](http://openresearch.ocadu.ca/713/).

Please replace "In press" with links for the actual papers, and also, please add my middle initial, so the citations look like this:
>Emily B. Moore, Taliesin L. Smith, & Emily Randall. Exploring the Relationship Between Implicit Scaffolding and Inclusive Design in Interactive Science Simulations. _Universal Access in Human-Computer Interaction._ Access to Interaction. Springer International Publishing. [Paper](http://link.springer.com/chapter/10.1007/978-3-319-40238-3_12).

>Taliesin L. Smith, Clayton Lewis, & Emily B. Moore. A Balloon, a Sweater, and a Wall: Developing Design Strategies for Accessible User Experiences with a Science Simulation. _Universal Access in Human-Computer Interaction._ Access to Interaction. Springer International Publishing. [Paper](http://link.springer.com/chapter/10.1007/978-3-319-40238-3_15).

**Comment by terracoda** [comment]
@emily-phet, is there a reason you listed yourself as first author on the joint SNOW article - maybe for contact purposes? Please post correction if you want it corrected.

**Comment by terracoda** [comment]
@mattpen, @emily-phet, @zepumph, @ariel-phet, I am very capable at writing HTML and CSS. 

In the process of an upgrade we could improve the accessibility of these pages, too. There are some low hanging fruit that would be easy to improve:

1. Using titles of works to create unique links, instead on non-unique words like "paper, presentation, etc."
2. Adding ARIA attributes to make the collapsible areas more accessible to keyboard users and screen reader users. 
3. A more prominent focus style would really improve keyboard accessible on the entire site, as well.

**Comment by terracoda** [comment]
@mattpen, @emily-phet, @zepumph, @ariel-phet, I think my previous comment, should be part of the new issue about creating the admin interface, sorry.

**Comment by emily-phet** [comment]
@mattpen - please change author order for the publication:
Emily B. Moore and Taliesin Smith. The PhET Interactive Simulations Project: Working to Increase Access to Interactive STEM Simulations [Part 2 of 2]. SNOW, Education, Access and You! Paper.

It should be: Taliesin L. Smith and Emily B. Moore.

@terracoda - sorry about that, you're correct that this was just a mistake. I probably copied from Part 1 and wasn't paying close enough attention.

**Comment by zepumph** [comment]
@terracoda I only saw this,
>Emily B. Moore, Taliesin L. Smith, & Emily Randall. Exploring the Relationship Between Implicit Scaffolding and Inclusive Design in Interactive Science Simulations. Universal Access in Human-Computer Interaction. Access to Interaction. Springer International Publishing. Paper.

in the presentations category so I also added it to the publications page, as you can see in the above commit. Is this what you wanted?

**Comment by emily-phet** [comment]
For the first listing under "Past Presentations", please change the title from "Inclusive Interaction: Description Strategies for a Complex Interactive Science Simulation" to "Inclusive interaction: Description strategies for a complex interactive science simulation".

**Comment by zepumph** [comment]
@terracoda said in a comment above:
>@zepumph, looks great. If there are any more capitalization issues, maybe Emily and I can fix those once we have access through the upgraded admin interface.

And I agree. This issue looks good enough to close. Work will be carried on in #533. @emily-phet @terracoda  let me know if there is anything else that I can do before we get the admin page up. You can just reopen this issue, or send a carrier pigeon, or anything else you feel up to.
