### ISSUE TITLE
Visibility of Directories?

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#535]
@mattpen , @zepumph , @jonathanolson - While I was working on a presentation tonight, I discovered that the directory structure of the PhET website is viewable. I don't think you used to be able to see anything if you navigated to directories like this: 
https://phet.colorado.edu/sims/html/
or this: 
https://phet.colorado.edu/sims/html/build-an-atom/

That is I think the file names were hidden. 

Can you review this behavior and share your thoughts here? I'm not sure if I am mis-remembering, if this expected, or if this is an unintentional change? Thx

**Comment by jonathanolson** [comment]
I believe it has always been like this, and poses no security issues (all of those files are public).

**Comment by mattpen** [comment]
@kathy-phet - I agree with @jonathanolson.  I believe this is by design.  The sims directory is the only one that is visible publicly, Apache hides everything else.  For example, if you hit the "Parent Directory" link on https://phet.colorado.edu/sims/ it redirects you to the home page.

**Comment by ariel-phet** [comment]
Since no security issues are posed by this issue, and there has never been navigation confusion for users (you would have to manually type in one of these URLs to get to the directory structure), this seems like a clear non-issue. Closing.
