### ISSUE TITLE
Gravity and Orbits page not found

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#537]
https://phet.colorado.edu/en/simulation/legacy/gravity-and-orbits is throwing a page not found. @mattpen can you look into?

**Comment by ariel-phet** [comment]
@oliver-phet this is probably because we just published GAO, but the new HTML5 sim is not live yet. 

However, it does seem odd that publishing the sim, messes this up until the sim is live.

**Comment by ariel-phet** [comment]
will be investigated in #539. Making the HTML5 sim visible fixed this issue.
