### ISSUE TITLE
Investigate why legacy sims are not available when HTML is not visible

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#539]
Follow up issue for https://github.com/phetsims/website/issues/537

Gravity and Orbits legacy version was returning 404 pages after publishing the HTML version and before making the sim visible.

We should investigate the root cause and fix it before publishing the next new sim.

**Comment by ariel-phet** [comment]
@mattpen is it also possible some kind of cache invalidation rule is causing this issue?

**Comment by mattpen** [comment]
I don't think its related to the varnish cache, possibly the Wicket panel cache had some bug?

**Comment by arouinfar** [comment]
Making the HTML5 sim visible has fixed the 404 on the legacy page. However, it now appears that the legacy page is a duplicate of the HTML5 page.

**Comment by mattpen** [comment]
I'm still working on determining root cause, only GAO seems to be affected so far.  On ox-dev I tried making the HTML version of IAAM invisible, and the legacy version is still working normally.  

I noticed that the localized versions of legacy GAO seem to still be working normally, i.e. https://phet.colorado.edu/es/simulation/legacy/gravity-and-orbits

Also, the legacy sim itself is still available at https://phet.colorado.edu/sims/gravity-and-orbits/gravity-and-orbits_en.jnlp or https://phet.colorado.edu/sims/gravity-and-orbits/gravity-and-orbits_en.jar

**Comment by mattpen** [comment]
@arouinfar @ariel-phet - The legacy sim page should be available again now.  It looks like the website was missing a sort by sim type for the legacy pages and we've just happened to get lucky that this problem didn't pop up sooner.

I wrote an exhaustive test that checks for these errors for any other sim in any locale and it looks like everything should be working.
