### ISSUE TITLE
Add OpenStax to Sponsor Page and Featured Sponsor Slot

### ISSUE THREAD

**Issue by kdessau-PhET** [phetsims/website#541]
Hi @mattpen 
OpenStax signed a CC-BY agreement for $10K and so they need to be added to the Sponsor page at the Gold Level. Here's the logo and url. Thanks!
![osx-stacked-tm-rgb-300dpi-2016](https://cloud.githubusercontent.com/assets/10424210/20890617/bda1177c-bac4-11e6-8af4-751683669f2a.png)

openstax.org

**Comment by kdessau-PhET** [comment]
@mattpen Let me know if you need another size. They can sen a new one.

**Comment by mattpen** [comment]
@kdessau-PhET - Said via email that these should be added to the rotating sponsor as well.

**Comment by kdessau-PhET** [comment]
@mattpen yes...add to rotating sponsor too.

**Comment by mattpen** [comment]
This sponsor has been deployed to the website tonight.
