### ISSUE TITLE
Twitter and Facebook OG data are failing

### ISSUE THREAD

**Issue by mattpen** [phetsims/website#542]
Twitter is failing due to a missing "twitter:title" meta tag. This was present as of August, possibly later, and needs to be readded.

Facebook is failing due to an empty tag for app_id. We need to find out if we should omit the tag or create an app id.

(Migrated from phetsims/phet-io#902)

**Comment by mattpen** [comment]
Twitter and FB OG data appears to be working again.  The [FB OG debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fphet.colorado.edu) reports several warnings, but the tag appears to be rendering correctly:

![image](https://cloud.githubusercontent.com/assets/11747676/20932395/bc588d8c-bb91-11e6-866a-2a83070c285d.png)

**Comment by mattpen** [comment]
@ariel-phet - Is there anything else that needs to be fixed here?

**Comment by ariel-phet** [comment]
@mattpen while we are there we might want to change the default image used for OG to be the one in #529 if that is easy

**Comment by mattpen** [comment]
I'll follow up on adding the new image in #529.
