### ISSUE TITLE
Stay Connected page needs some work

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#55]
We should redesign this page:
![screen shot 2014-12-31 at 2 52 55 pm](https://cloud.githubusercontent.com/assets/7852916/5590774/b9c11f38-90fc-11e4-88f6-74d60519cf48.png)

**Comment by ariel-phet** [comment]
Current thought is to remove this page and category altogether now with the prominence of our social media icons. We also plan to implement a more modern global footer for the website which should also eliminate the need for this category.

**Comment by aaronsamuel137** [comment]
@ariel-phet, just want to confirm, should I go ahead and remove this page from the website now?

**Comment by ariel-phet** [comment]
@aaronsamuel137, not yet, let's plan to discuss with @kathy-phet during status meeting on Thursday. Please put this issue as one of your agenda items.

**Comment by ariel-phet** [comment]
@alexklinger said

I would recommend using font awesome social icons in the footer of the entire site, rather than having a stay connected page. http://fontawesome.io/icons/

**Comment by aaronsamuel137** [comment]
During status meeting on 2/5/15 we decided to get rid of this page.

**Comment by aaronsamuel137** [comment]
This page is gone now. Closing.
