### ISSUE TITLE
Jump to top link broken?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#56]
I was just looking at the FAQs page on our website (http://phet.colorado.edu/en/faqs) and noticed that when you scroll down there is a jump back to the top. I tried the first few and none of them worked (http://phet.colorado.edu/en/faqs#faq_top). 

Firefox 33.1.1
Mac 10.9.5

**Comment by amanda-phet** [comment]
They don't seem to work in Chrome, either.

**Comment by aaronsamuel137** [comment]
This has been fixed. Closing
