### ISSUE TITLE
implement "HTML5 licensing" page

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/website#60]
For quite awhile, the HTML5 sims have had a "Terms, Privacy & Licensing" link in the About dialog. Clicking that link currently takes you to a page on the PhET website that says "Information coming soon, please contact phethelp@colorado.edu."  The page is http://phet.colorado.edu/en/html-terms-privacy-and-licensing

**Comment by ariel-phet** [comment]
I have been nagging @kathy-phet about this issue, and will continue to push the priority

**Comment by jonathanolson** [comment]
I've uploaded a word document that contains what we'll want as HTML in the page: http://www.colorado.edu/physics/phet/dev/olsonjb/PhET_SoftwareAgreement_ForHTML5Sims_v1_KP_02112015.docx

This should be HTML-ified and put into the page.

**Comment by aaronsamuel137** [comment]
I've given this task to @thejakey. I am expecting it will be done very soon, but if not I may end up doing it.

**Comment by thejakey** [comment]
Heya, the html is done but I'm having a hard time fitting it into the src. I know we went over it but I unfortunately had to reinstall my OS since then and lost the skype call transcript.

**Comment by aaronsamuel137** [comment]
No problem. The file you want to modify is: /website/src/java/edu/colorado/phet/website/content/about/HTMLLicensingPanel.html. Let me know if you have any questions. Thanks for doing this!

**Comment by ariel-phet** [comment]
@aaronsamuel137 let me know if you want to look over this page on phet-dev together at some point (for cleaning up alignment and fonts and such)

**Comment by aaronsamuel137** [comment]
@BrianNewsom is going to work on making this translatable.

**Comment by ariel-phet** [comment]
We discussed at status meeting yesterday and we will also want to add in some sort of disclaimer when the license is being viewed in another language. We will need to figure out the exact verbiage, but something clear and up at the top when viewing in different locale (much like our temp html5 sims page) to the effect of 

Disclaimer: The text of the license information is only legally valid for the English version. Any translations of the licensing information are not legally binding, but instead are provided for convenience of non-English users.

**Comment by aaronsamuel137** [comment]
OK good to know. The licensing page is finished aside from this, and can be viewed on phet-dev. I'll wait to deploy until I hear back about this.

**Comment by ariel-phet** [comment]
OK, lets put in the following text:

Disclaimer: The text of the licensing information below is only legally valid for the English version. Any translations of the licensing information are not legally binding, but instead are provided for the convenience of non-English users.

Follow the same paradigm used on the temp HTML5 page, where this disclaimer only appears when viewing the site in a non English locale. Also use the same styling (grey box, black text)

![example](https://cloud.githubusercontent.com/assets/4051174/6535604/56ceb1c6-c403-11e4-975b-3e5b2194ebc3.PNG)

**Comment by ariel-phet** [comment]
@aaronsamuel137 when you have outfitted the disclaimer, send me an email so I can check things out carefully on phet-dev.

**Comment by ariel-phet** [comment]
All looking good. Just one more tweak. The cc by image is low quality and sort of pixelated. Perhaps replace with this one (but scaled down as needed):

http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png

After that you can make it live. Please send an email to @kathy-phet and I to say you have made it live on the website (that will be the surest way to have her review it :) )

**Comment by ariel-phet** [comment]
Up, working, and approved by @kathy-phet - closing!
