### ISSUE TITLE
Change default settings so users are subscribed to the newsletter when creating an account

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#61]
@kathy-phet requested that when the users create accounts on the PhET website the default check box state for the newsletter is "checked"

**Comment by ariel-phet** [comment]
@jonathanolson please comment on the complexity of this change, and if easy please go ahead and make the change, if not, please reassign to @aaronsamuel137

**Comment by jonathanolson** [comment]
It should be fairly easy, I'll take care of it.

**Comment by jonathanolson** [comment]
Tested and should be complete.
