### ISSUE TITLE
Change Old PhET Logo to New PhET Logo for Activities on Sim Pages

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#63]
On any given sim page with activities that have the "from PhET" stamp the old PhET logo is being used, we want to change it to the new PhET logo. On blue background matched to banner (and no "Interactive Simulations" text).

Work with @amanda-phet if you need a specific version of the logo

High priority since it should be a pretty easy

**Comment by aaronsamuel137** [comment]
This is done. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good to me!
