### ISSUE TITLE
Footer on pages has 2013 as copyright date

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#64]
Now that we have the copyright as 2015 on the front page, its seems that should be consistent across all website pages. Pretty minor, but probably worth fixing if it is a quick adjustment.

**Comment by aaronsamuel137** [comment]
This has been updated. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Not showing up on HTML5 temp page, but otherwise looks good

**Comment by aaronsamuel137** [comment]
Good catch. I've updated it on the HTML5 page too. Assigning to @ariel-phet for review

**Comment by ariel-phet** [comment]
Looks good, closing!
