### ISSUE TITLE
Typo on home page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#65]
Just a minor typo, but the sim identified in this video should be labelled "park" and not "part".

![screen shot 2015-02-09 at 9 52 18 am](https://cloud.githubusercontent.com/assets/7852916/6110789/71ceb42e-b041-11e4-8aa7-1a989136a761.png)

**Comment by ariel-phet** [comment]
We definitely don't want that typo...lets fix soon

**Comment by aaronsamuel137** [comment]
I've updated the string in the database, it'll appear as soon as tomcat's cache is refreshed.

**Comment by aaronsamuel137** [comment]
This has been fixed. Closing.
