### ISSUE TITLE
Nav locations don't appear when being redirected through login page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#67]
The nav locations for the page you are heading for used to appear on the login page when you needed to login before getting to the destination page. This feature was removed when addressing security issue #66, but could be added back if we think it's worth spending some time on. It's not as straightforward to implement as it was previously, but could be done.

Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - when you say the "nav locations" - do you mean in the side bar?

Our of curiosity, one possibility would be to have a login dialog that overlays the current window, so that you never really "leave" the page you are on. This seems to be done on many modern websites such as:

https://www.pinterest.com/

Thoughts?

**Comment by aaronsamuel137** [comment]
Yeah I mean the side bar. It used to have the little arrows and highlights for the page you were heading too. Now it doesn't anymore, but it still redirects you there after signing in.

![screen shot 2015-02-27 at 12 31 26 pm](https://cloud.githubusercontent.com/assets/3193912/6419694/96171418-be7c-11e4-8143-ba9885678432.png)

I think the idea of a popup instead is nice, but it could take a bit of work... I'd guess at least 5 hours, plus probably a lot more design work and pixel polishing if the team is going to review it.

**Comment by ariel-phet** [comment]
OK, lets close this issue for the moment. I will open for creating a dialog, and when we design it we can implement it. No big rush for the moment.
