### ISSUE TITLE
Update requirements page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#68]

**Comment by oliver-phet** [comment]
Aaron, I just sent you a Gdoc that has some updated FAQ's (that include the system requirements). Can these be merged into the existing? (and maintain the URL #qXX behavior).

**Comment by oliver-phet** [comment]
related to #74

**Comment by aaronsamuel137** [comment]
Yep they can be merged no problem. And I can add that behavior to the troubleshooting pages. Right now on the faq page the urls are little random, the number skip around and sometimes it is a description instead of a number, such as "#sourceCode". Is this a problem, or it doesn't matter if you have the link?

Would you prefer numbers or descriptions on the troubleshooting pages?

**Comment by oliver-phet** [comment]
I don't think it matters much as long as the links are unique so that I can send a URL to a specific issue.

**Comment by aaronsamuel137** [comment]
Do we want to change the FAQ page to use expandable text too? Also, what do you think about replacing the troubleshooting expandable text with the style used in the new sim pages, such as the ones used here: http://phet-dev.colorado.edu/en/simulation/area-builder?

We could probably also set it up so that when you visit a url with "#q2" or something it will automatically expand that portion of the text.

**Comment by oliver-phet** [comment]
Yes, if possible, it would be great to have the FAQ in expandable text. I like the style used on new sim pages. Let's go with that.

**Comment by aaronsamuel137** [comment]
Sounds great. If it's not too urgent, I may wait until the new web-dev intern is here (@ariel-phet mentioned staring the paperwork today), since this would be a good project to either pair with him on or just assign to him.

**Comment by oliver-phet** [comment]
Sounds good. Brian should be starting Monday.

**Comment by aaronsamuel137** [comment]
Assigning to @BrianNewsom.

We want the troubleshooting and FAQ pages to behave like the new sim pages drop down menus. Each link should be accessible by a url with a hash. See http://phet-dev.colorado.edu/en/simulation/area-builder for an example. Code is in SimulationMainPanel.html and expandable-text-v1.js on html5-sim-pages branch.

Let me know if you have questions.

**Comment by BrianNewsom** [comment]
Fixed with https://github.com/phetsims/website/pull/89.  Let me know what you think!

**Comment by oliver-phet** [comment]
I'm not seeing a change on the live website or phet-dev?

**Comment by aaronsamuel137** [comment]
The change isn't live yet - I am reviewing it and making some changes. I'll let you know when it's live. I'll probably put it on phet-dev first so you can review.

**Comment by aaronsamuel137** [comment]
Assigning to @BrianNewsom  - see my comments in #74

**Comment by aaronsamuel137** [comment]
Nice work on the expandable text updates Brian, thanks!

I've sent you a link to a google doc that has some updates for this page and the troubleshooting page. Can you make these updates (including updating the strings in the database). Thanks!

Also there are a few hrefs that need '#' before them, for instance ```href="mobileDevices-header"``` should be ```href="#mobileDevices-header"```

Assigning to @BrianNewsom.

**Comment by aaronsamuel137** [comment]
@BrianNewsom - I have started updating this from the document I sent you and fixed the hrefs, but there is still more to do.

**Comment by BrianNewsom** [comment]
Updated in #116, assigning to Aaron for review.

**Comment by aaronsamuel137** [comment]
These changes have been deployed to figaro. Assigning to @oliver-phet for review.

**Comment by oliver-phet** [comment]
It looks like the system requirements (faq#q2), but the google doc had updates for others as well (screen resolution, iPad/tablet) Can these be updated too?

**Comment by aaronsamuel137** [comment]
They look like the document to me. Are you looking at phet-dev or the main site? I have updated this only on the main site for now.

When I address #118 I will make a way for you to edit these FAQ and troubleshooting entries directly. This will make future changes like this much easier.

**Comment by oliver-phet** [comment]
Yep looks good. I was looking at dev.

**Comment by aaronsamuel137** [comment]
OK great. I am closing this issue.
