### ISSUE TITLE
Purge "Under Construction" Symbol from Website

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#76]
@aaronsamuel137 on several places on the website you will see sims with an "under construction" symbol, I am not sure why this symbol was ever used, but it seems outdated and odd.

If you click on the symbol it will take you to this page:
http://phet.colorado.edu/en/for-teachers/legend

I will make a separate issue for the "legend" page since it is outdated as well. Might make a quick little project for Brian.

See the example of the construction symbol below for capacitor lab

![construction](https://cloud.githubusercontent.com/assets/4051174/6428338/f1a79c96-bf5b-11e4-8b13-cf2dbb3a0877.png)

**Comment by aaronsamuel137** [comment]
I haven't looked into this at all yet, but I am assigning to @BrianNewsom just so there are some things in the your queue if you finish up your other tasks. Feel free to ask if you have questions, I am not totally sure how complicated this will be.

**Comment by aaronsamuel137** [comment]
At status meeting on 3/12/15 we agreed to have a student worker manually remove these from the database, since there are not that many of them. We are purging all of the symbols from the legend page, not just the under-construction.

Assigning to @oliver-phet to coordinate with the student workers.

**Comment by oliver-phet** [comment]
@kathy-phet Can you provide the metadata sheet that identifies the sims with legend symbols (called "Ratings" on the website administration)?

**Comment by ariel-phet** [comment]
@aaronsamuel137 I went through and unchecked everything. Can you do a query and make sure I didn't miss anything?

Can we also now remove the "ratings" category from the admin page so that the 3 items (classroom tested, guidance, and under construction) cannot be inadvertently checked again?

**Comment by aaronsamuel137** [comment]
Everything looks good on the database end. Thanks!

We should probably also disable these icons from appearing on the new sim pages. I will take care of this we deploying the new sim pages.

**Comment by aaronsamuel137** [comment]
All of these symbols have been removed. They are still in the database, but there is no way to see them on the site now. Closing
