### ISSUE TITLE
For Teachers "Legend" page needs updating/fixing

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#77]
@amanda-phet - this page seems very out of date:

http://phet.colorado.edu/en/for-teachers/legend

You can get to this page by clicking on one of these symbols, for instance the "under construction" symbol that can be found on the capacitor lab page:

http://phet.colorado.edu/en/simulation/capacitor-lab

I am going to get the "under construction" symbol purged from the website, see #76 

I am not sure we have ever used the "guidance" symbol, and I don't think we should if it exists.

Also currently the gold star does not seem to link to this legend.

We should decide to either update this page to include things like what the PhET logo means on an activity or kill it altogether.

**Comment by amanda-phet** [comment]
I agree that this a very odd page. 

If we want a legend for the star and the PhET logo, both of which apply to activities, we should include after the list of activities on a sim page. Another option would be to simply have some mouseover text for those two symbols.

**Comment by amanda-phet** [comment]
The plan is to discuss this on Thursday's status meeting.

**Comment by amanda-phet** [comment]
Also, it seems that there is already a mouseover description for gold-star activities and PhET-created activities.

**Comment by aaronsamuel137** [comment]
We've agreed to take down the legend page at status meeting on 3/12/15.

Assigning to @BrianNewsom. Let me know if you have questions about this. Don't worry about touching the database, but make sure there are no links anywhere to the legend page.

**Comment by aaronsamuel137** [comment]
Removed this page when taking care of #76. Closing
