### ISSUE TITLE
Disambiguate Java/Flash and HTML5 Licensing

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#80]
Now that we have a live page for our HTML5 licensing, we need to disambiguate between licensing our Java/Flash sims and our HTML5 licensing.

Currently, the only way to navigate to the HTML5 licensing page is via the about dialog in one of the sims.

However, we have licensing information under our "About" sidebar navigation

http://phet.colorado.edu/en/about/licensing

We need decide if there are two different links, everything on one page, subcategories under licensing or...? I will plan on making this a status meeting agenda item.

**Comment by aaronsamuel137** [comment]
We decided at status meeting on 3/12/15 that we are going to change the page at: http://phet.colorado.edu/en/about/licensing, to basically have three links: one to the java license page, one the html5 license page, and one to the phet trademark license page (a new page that requires some input from @kathy-phet).

We could model the look of this page after the source code page at: http://phet.colorado.edu/en/about/source-code, which also has three sections with links.

We need to move the html licensing page to: http://phet.colorado.edu/en/about/licensing/html-terms-privacy-and-licensing, and move the java licensing to http://phet.colorado.edu/en/about/licensing/java-flash-licensing or something like that, and create a new page for phet-trademark.

Assigning to @BrianNewsom

**Comment by aaronsamuel137** [comment]
Also, we'll need to make the url phet.colorado.edu/en/html-terms-privacy-and-licensing redirect to phet.colorado.edu/en/about/licensing/html-terms-privacy-and-licensing and update the link in joist to point to phet.colorado.edu/en/about/licensing/html-terms-privacy-and-licensing.

**Comment by aaronsamuel137** [comment]
We decided on 6/11/15 status meeting to make licensing a top level navigation, with three links for "java", "html" and "activities" - and also a short blurb about the licensing. about/licensing should redirect to the java licensing page.

Assigning to @amanda-phet for a mockup.

**Comment by aaronsamuel137** [comment]
Feel free to start on this @zepumph. Even without a mockup we can get a simple page up with the three links. Work on a branch for this one, and let me know if you run into difficulties. The nav links can sometimes cause unexpected errors.

You'll want to make this a static page following the same pattern as other StaticPages added with StaticPage.addPanel() in PhetWicketApplication.java. Note the warning about strings in the doc in StaticPage.java

**Comment by zepumph** [comment]
I just pushed the licensing branch to github if you want to take a look at it. There are probably some bugs, but for a rough outline it's pretty good. It includes a main licensing page, with sidebar navigation to it, and then 4 links from there: HTML5, Java, Activities, and Faq. The java page is the old 'software-agreement_v7' revamped in the HTML5 style, and the previous licensing page located at en/about/licensing/ is now located at /licensing/java/old. My understanding is that it will be replaced by content to be added to the main licensing page that @amanda-phet  is currently working on. All of this was discussed in the status meeting on 6/18/15.

**Comment by amanda-phet** [comment]
@zepumph How do I look at this page? I tried phet-dev.../en/licensing and that didn't work.

**Comment by aaronsamuel137** [comment]
I think he was commenting to me that I can look at it locally. I don't see any need for you to see it yet @amanda-phet until we get your mockup and implement that. Unless you think that would be useful.

**Comment by amanda-phet** [comment]
Sorry, that sounds good to me!

**Comment by zepumph** [comment]
Yeah sorry for the confusion, I'll tag better next time @amanda-phet. @aaronsamuel137 did you get a chance to look at it?

**Comment by aaronsamuel137** [comment]
Looks good so far. Let's just leave it as is for now until we get the mockup from @amanda-phet.

**Comment by amanda-phet** [comment]
We have the licensing page text! I am sending you an email now.

**Comment by aaronsamuel137** [comment]
New licensing page is up on phet-dev. Assigning to @amanda-phet for review.

The main final question I have is around the activities licensing. It is a different form than the others. Do we want a different header here?

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I think the format for the Activity licensing looks fine. It is a short license. I don't think we need the header, though- when the breadcrumbs eventually get removed, the page will have the title "Activity Licensing" so it would be redundant.

**Comment by amanda-phet** [comment]
This has been deployed. Closing.
