### ISSUE TITLE
Navigation from mini banner to all HTML5 sims

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#82]
@aaronsamuel137, now that we are setting up the HTML5 sim pages, if you click on HTML5 sims in the mini banner, we should change the behavior on the page a bit.

The page with all HTML5 sims should now still have the Mini banner, and I think we still want to keep the youtube video.

However, now when you click one of the sims, it should take you to the inidividual sim page, so that the action is consistent across the site.

**Comment by ariel-phet** [comment]
Obviously, I mean for this action take place of phet-dev first, until everything is settled.

**Comment by arouinfar** [comment]
As decided in today's website design meeting, the "Play with Simulations" button on the home page and the "HTML5 Sims" link in the banner will have the same target -- New Sims. This page will be populated with the HTML5 sims and contain the "Next Generation PhET Sims" YouTube video like the current HTML5 sims page.  

We may want to move the YouTube video to the top of the page to reduce the page width. Assigning to @amanda-phet to mock this up.

**Comment by aaronsamuel137** [comment]
In #97, there is a suggestion to make a category "HTML5 Sims" under "New Sims".

> In the sidebar navigation a category called "HTML5 Sims" - I suggest placing this category directly under "New Sims"

Should this new category not be created, and instead just make "New Sims" contain only the html5 sims?

**Comment by arouinfar** [comment]
Good catch, @aaronsamuel137. Having a "HTML5 Sims" category separate from the "New Sims" category would be redundant, as we have decided that the only sims listed under "New Sims" would be our HTML5 sims.

**Comment by ariel-phet** [comment]
@aaronsamuel137 yes, we discussed this today, see @arouinfar comment above

**Comment by ariel-phet** [comment]
To keep the page layout not too wide, we had also considered a possible layout as below, which would highlight the "Future of PhET" video if people wish to watch it

![new sims](https://cloud.githubusercontent.com/assets/4051174/6714913/96c64b5c-cd60-11e4-8f69-7816c2dbe0cb.PNG)

**Comment by ariel-phet** [comment]
Thoughts on the mockup above @oliver-phet, @amanda-phet, @aaronsamuel137, @arouinfar ?

**Comment by aaronsamuel137** [comment]
I like it, though it really highlights the video, which I doubt will be watched on most hits that this page gets.

Take a look at the current phet-dev to see how it currently looks for a comparison. I added the banner and nav locations.

**Comment by amanda-phet** [comment]
I hesitate to make the page really wide (like Teacher Resources) because it makes our site look so inconsistent. I would like to see the mockup above where the video is above the list of sims.

**Comment by ariel-phet** [comment]
Hey @aaronsamuel137, we also discussed with @arouinfar - lets try the centered video version, seems a bit cleaner.

**Comment by aaronsamuel137** [comment]
Centered version is deployed, assigning to @ariel-phet for review

**Comment by ariel-phet** [comment]
Looking good, lets close this issue for the moment (we will want @kathy-phet to take a look) but we will have her look over the whole flow of things with the new sim pages, and that review may or may not generate some polishing issues.
