### ISSUE TITLE
expanding categories tweak

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#83]
Right now, when you click on a category like "For Teachers", the section expands and jumps to the top of the webpage. This jump happens very quickly and is a little jarring. It is not obvious what happened. When you close the section, though, it has a very natural scrolling feel. 

Can these categories expand with some of that same natural feel? Maybe we should just animate the expansion and not scroll up at all (Google drive FAQs example: https://support.google.com/a/answer/2490100?hl=en). 

@oliver-phet if you have other examples of this action please add links.

**Comment by oliver-phet** [comment]
Here is an example of the "expandable animation": http://www.labor.ny.gov/ux/code-expandable-content.html

**Comment by aaronsamuel137** [comment]
I initially had it like this, but then there was a request that the page scroll down to right above the section header. I am happy to bring it back to how it was if that is better.

What are your thoughts @ariel-phet? I think you mentioned wanting it to jump down to the section that is clicked on.

**Comment by ariel-phet** [comment]
@aaronsamuel137 

Yeah, we thought the auto-scrolling might be good, but once we saw it in action, it seemed a bit disorienting. So yes, it seems like the way you had it was better.

**Comment by aaronsamuel137** [comment]
This has been updated on phet-dev. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks really good. @ariel-phet can you confirm that you like it as well and close the issue?

**Comment by ariel-phet** [comment]
Looks good, closing.
