### ISSUE TITLE
initial pixel polishing list

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#84]
- [x] The blue section titles like "Description" and "Sample learning goals" should be #00A6D3 and right now they look closer to #3298A6
- [x] The first section under About should be "Topics" not "Content"
- [x] The badges we are using vary a lot in size and color, and in particular the flash logo is really distracting. We have a new set of badges we'd like to use instead: 

![flash-sim](https://cloud.githubusercontent.com/assets/7852916/6607359/c1da31f8-c803-11e4-83f6-8ed5fb24ced6.png)
![html5-sim](https://cloud.githubusercontent.com/assets/7852916/6607360/c1dc11da-c803-11e4-817e-473077179090.png)
![java-sim](https://cloud.githubusercontent.com/assets/7852916/6607361/c1e069ba-c803-11e4-8d36-bb5b1944ac52.png)

- [x] We'd like to try changing the appearance of the buttons- right now there is a mishmash of button styles. Can you match the flat buttons below for Download, Embed, Donate (The Donate button is also moved slightly closer to the sponsor information), and Original sim. 
![screen shot 2015-03-11 at 6 40 30 pm](https://cloud.githubusercontent.com/assets/7852916/6609924/46932728-c81e-11e4-82d7-6eae81ce9eeb.png)

@aaronsamuel137 I will send you an email with the artwork above: the three badges, the new download icon, and the new embed icon.

**Comment by aaronsamuel137** [comment]
OK I've taken a stab at this. Assigning to @amanda-phet for review. Let me know what you think about the hover behavior for the buttons.

**Comment by ariel-phet** [comment]
Nice first stab. A couple of quick comments:

1. Hover behavior looks really good for the download and embed button (to my eye). Not really digging it for the donate button, since it gets darker not "brighter"

2. Seeing the hover behavior also makes me want to have a hover behavior for the big play button. 

3. Font in the Donate, Embed and Download buttons should all be bold

4. The Donate button should have a bit more padding

**Comment by amanda-phet** [comment]
It's looking great! The new badges look nice and uniform and the new buttons look really great. @ariel-phet some of my comments below are in response to yours, but I mostly agree with what you said. 

Button highlight: I agree that the donate button should have a brighter highlight. Is this something that is a designated color? Should I find the right color for the highlight? Also, I noticed that the text gets an underline- is this intentional? I would prefer if it did not have that behavior. The highlight should be enough. 

Button font: The font should be bold, and also slightly smaller so that there is more white space around the text. 

Play button: We don't want sims to be perceived as something that is played, like a video, so I don't think this is necessary. If you look at netflix, the big play icon does not have a hover behavior- I think this is because it opens a new page to play it, rather than playing it right there. 

Drop shadow: It looks like the download/embed buttons are behind the shadow that the sim screenshot is casting, making them appear darker. Can they be brought forward at all? The text should look white.

**Comment by ariel-phet** [comment]
@amanda-phet fair point about the play button. Let's leave it as is in that case.

**Comment by aaronsamuel137** [comment]
Sounds good, I'll work on these changes. @amanda-phet, if you have particular highlight colors in mind feel free to send them my way. Currently, I have just left the old highlight colors.

**Comment by amanda-phet** [comment]
@ariel-phet How about this for highlights? (I also changed the orange in the donate button.) 

![screen shot 2015-03-17 at 9 36 12 am](https://cloud.githubusercontent.com/assets/7852916/6690955/1df45408-cc89-11e4-8cf0-c3f3253698fb.png)

**Comment by aaronsamuel137** [comment]
That looks good to me. If you know the exact color codes, it would save me a step to just post them here - otherwise I have to download the image and go into photoshop to figure it out. But feel free to wait until we get the go-ahead from @ariel-phet

**Comment by ariel-phet** [comment]
Works for me

**Comment by aaronsamuel137** [comment]
@amanda-phet or @ariel-phet, also let me know if you have preferences about the "active" color or style of the button (how it looks when it is being clicked - you can click and hold to see this behavior)

**Comment by amanda-phet** [comment]
Here are the colors:
![screen shot 2015-03-17 at 12 51 09 pm](https://cloud.githubusercontent.com/assets/7852916/6695106/4f998e5e-cca4-11e4-91a5-8c6d75011d4f.png)

**Comment by aaronsamuel137** [comment]
I've made these changes, assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
It looks really good to me. However, before I close the issue... some really minute pixel issues I see:
![screen shot 2015-03-18 at 12 01 59 pm](https://cloud.githubusercontent.com/assets/7852916/6715800/9ec1c11e-cd66-11e4-8bbb-20f5eaf47763.png)

1. The height of the buttons appears to be different. The download/embed seem about 26 px tall and donate 28 px tall. Are these based on the contents or are they a fixed size? Either way, I think they should be the same- especially when we start to use these in other places in the site. 

2. The download/embed icons don't look vertically centered to my eye. Actually, neither does the text. 

So, adjusting the button height and centering will probably fix my issues. The buttons look in front of the shadow now so that's great, and I love the button highlights and behavior when clicked! 

I think @ariel-phet had wanted the badges to be smaller but he should specify with you what that looks like.

**Comment by aaronsamuel137** [comment]
I've adjusted the text height and made all  of the new buttons have the same padding. @ariel-phet or @amanda-phet, feel free to comment or close the issue.

**Comment by ariel-phet** [comment]
@aaronsamuel137 I think it will be easiest to adjust badge sizes and such in person on Thursday, but overall everything is looking really nice.

@amanda-phet I think we had also considered a couple of tweaks to the "Original Sim and Translations" navigation.

**Comment by amanda-phet** [comment]
The buttons all look consistent now. Before I close this issue, can we make another tweak to the buttons? There seems to be more padding on the left/right sides than on the top/bottom. I'd like to define our button style to have the same padding all around. 

![screen shot 2015-03-25 at 11 06 10 am](https://cloud.githubusercontent.com/assets/7852916/6830497/a7b95e34-d2df-11e4-873d-9ae9ded950e0.png)

**Comment by amanda-phet** [comment]
Everything looks good now. Closing this issue!
