### ISSUE TITLE
Search functionality when in a non-English locale

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#86]
Until we get the translation utility up and running we had planned for when viewing the website in a non-English local that searching would only show java sims in the search bar (unless only an HTML5 version exists, such as for Area Builder).

I know this is probably a bit tricky and an intermediate change that will go away, but it seems like something we will need to do.

**Comment by ariel-phet** [comment]
In addition, screenshot and sim should be the java version when looking a specific category. For instance, if looking at physics sims when viewing the website in French, only the Java sims should appear for all sims that have both a Java and HTML5 version.

**Comment by aaronsamuel137** [comment]
A question about this: when on the sim page in a non-english locale, should the "Back to HTML version" be present? Should they be able to access the HTML5 sim page at all when browsing in non english versions?

**Comment by ariel-phet** [comment]
Good question. We definitely want them to be able to access the HTML version. So I think the "back to HTML5 version" should be present, and obviously if they click the HTML5 sims in the mini banner they will see all the sims.

**Comment by aaronsamuel137** [comment]
OK this is deployed to phet-dev. Assigning to @ariel-phet for review. You may need to force refresh before this will work.

**Comment by ariel-phet** [comment]
Search functionality is working properly.

However, if I am in a locale and go to for instance "new sims" I will see for instance Graphing Lines appear as the Java screenshot, with the Java badge, if I click the screenshot, it takes me to the HTML5 version.

**Comment by aaronsamuel137** [comment]
I think this is working properly now. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
This is all working well. However it does raise a concern we should address. There is now a message that we should adjust on the "new sims" page if you are in a different locale. I will create a new issue and discuss with the team.
