### ISSUE TITLE
Subscribe to newsletter while on the newsletter page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#87]
Based on discussions with @schasteen and @ycarpenterphet, we would like to suggest the following change: 

Currently, the only place we can find a link to sign up for the newsletter is in two different places on the home page and no where else on the website. I am sure this will change when we implement a new universal footer on the website, but for now, we think it would make sense to have a link to subscribe (http://phet.colorado.edu/en/subscribe) to the newsletter somewhere on the newsletter page (http://phet.colorado.edu/en/about/news), as well as a link to the newsletter page on the subscribe page. 

Another option: Can the actual email entry box just exist on the newsletter page? Then it is a one-stop shop! 
![screen shot 2015-03-11 at 6 24 35 pm](https://cloud.githubusercontent.com/assets/7852916/6609794/efda9062-c81b-11e4-976b-767243abb716.png)

**Comment by amanda-phet** [comment]
Is it also possible to include the newsletter in the keyword search? (For example- I search for newsletter and it auto-completes with the newsletter page and takes me there.) 

Or is that something we will get to when searching as a whole is tackled?

**Comment by patricialoeblein** [comment]
I am very glad some consideration is being spend on the newsletter. I realize that the goal is to emphasize more things like facebook etc, but many teachers still appreciate newsletters. I know I subscribe to several.

Trish

**Comment by patricialoeblein** [comment]
Great idea

Trish

**Comment by ariel-phet** [comment]
:+1:  to @amanda-phet suggestion

**Comment by amanda-phet** [comment]
Here is the mockup for adding a subscribe link right on the newsletter page. Once this is added, we can purge the subscribe page.

![screen shot 2015-03-13 at 2 27 28 pm](https://cloud.githubusercontent.com/assets/7852916/6646718/6820530a-c98d-11e4-9e75-c0f0dfd4a319.png)

**Comment by ariel-phet** [comment]
@aaronsamuel137 if you feel this is a task @BrianNewsom could handle, feel free to assign it to him.

**Comment by aaronsamuel137** [comment]
Assigning to @BrianNewsom. Let me know if you want to discuss this further before you get started on it.

**Comment by amanda-phet** [comment]
Also, once this is done, any links that take you to the subscribe page should be changed to take you to the newsletter page (or redirected). 

I know that on the home page, there are two links: the social media icons on the right and the link in the footer.

**Comment by amanda-phet** [comment]
@aaronsamuel137 Since @BrianNewsom will not be working with us this summer, can you tackle this at some point this summer?

**Comment by aaronsamuel137** [comment]
Implemented on phet-dev. It doesn't quite match the mockup - but it uses the same css as is used for the new buttons, and I thought it would be good to stay consistent.

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks good, and it's good that it matches the rest of the site.
