### ISSUE TITLE
Create a redirect link to newsletter page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#88]
Can we make the URL phet.colorado.edu/en/newsletter exist and just redirect to the current phet.colorado.edu/en/about/news page?

**Comment by ariel-phet** [comment]
@amanda-phet and I discussed this possibility and she is working on a mockup.

**Comment by amanda-phet** [comment]
This is just requesting a redirect link so that we can have a cleaner URL to share. 

The mockup for this page is available in issue #87.

**Comment by amanda-phet** [comment]
Hey @aaronsamuel137 do you know what the status is here? Can this possibly be done within the next couple weeks?

**Comment by aaronsamuel137** [comment]
Yep, I'll look at this next week, or possibly this week if I get to it.

**Comment by aaronsamuel137** [comment]
This is implemented on phet-dev. I think we might as well deploy this with the sim pages since some of the css used in #87 is added in the new sim pages checklist

**Comment by aaronsamuel137** [comment]
Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great! Closing.
