### ISSUE TITLE
New universal footer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#90]
We need a universal footer for the website that has languages as well as social media. I propose that this footer also include links to other pages that are commonly found in footers such as About and Support. 

The motivation is also to remove this table from the front page: 
![screen shot 2015-03-12 at 12 15 32 pm](https://cloud.githubusercontent.com/assets/7852916/6624838/85c9b842-c8b1-11e4-9f73-536cbddabcf5.png)

**Comment by ariel-phet** [comment]
@amanda-phet - assigning this issue back to you. Since you have discussed it with Kathy, feel free to close this issue and perhaps wrap it into the larger front page project.

**Comment by amanda-phet** [comment]
It makes sense to wrap it into the front page project now that we have an idea of what will go in the footer.
