### ISSUE TITLE
Update download page?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#91]
We currently have a page that describes the three ways to run simulations: https://phet.colorado.edu/en/get-phet 

The third method of downloading one sim at a time takes you to a page that lists every sim:
https://phet.colorado.edu/en/get-phet/one-at-a-time. I noticed that all of the links seem to be .jar files, even flash sims. The only exception seemed to be Area Builder. 

Should we update these links so that the HTML5 versions are the default? Or should the instructions change when the new sim pages roll out with download buttons?

**Comment by ariel-phet** [comment]
I agree these links should default to HTML5 sims when available and we should adjust the instructions a bit.

@amanda-phet, why don't you and I take a look a the wording, and @aaronsamuel137 will handle the implementation

**Comment by aaronsamuel137** [comment]
These links are now defaulting to html5 sims when available. Do we want to have an option to download the legacy version too?

**Comment by amanda-phet** [comment]
That probably makes sense, and since we're using Sim Name (HTML5) to distinguish from the legacy sim, we'll probably want to do the same here. 

We/I should still spend some more time thinking about this page in general and if we want to make updates after the current HTML5 sim page rollout.

**Comment by aaronsamuel137** [comment]
I've updated this page to display both sim version and have a (HTML5) suffix for the html ones: https://phet-dev.colorado.edu/en/get-phet/one-at-a-time

Assigning to @amanda-phet for review and next steps.

**Comment by amanda-phet** [comment]
That looks good to me. I am wondering if we can make flash download files as well, or if those also need to be .jar when downloaded? 

While I want to make major changes to these pages, I think just a few small ones will make me happy for now. 

1. Is this accurate to say (in the first column) that flash sims can not be saved to the computer when using the website while connected to the web? and that java sims can not be moved from the cache? 
![screen shot 2015-04-06 at 1 06 46 pm](https://cloud.githubusercontent.com/assets/7852916/7010504/102d6b62-dc5f-11e4-9fc7-b93f4cba78a4.png)
2. I think this prompt would be clearer if the second sentence said "... double-click the *saved file.*" rather than "...double-click *it*." 
![screen shot 2015-04-06 at 1 06 56 pm](https://cloud.githubusercontent.com/assets/7852916/7010583/922f265a-dc5f-11e4-8421-638ffb28ab8e.png)

**Comment by amanda-phet** [comment]
@aaronsamuel137 Would you please respond to questions 1 and 3 above, and let me know if we can address 2 as well.

**Comment by aaronsamuel137** [comment]
1. I don't really understand this cell of the chart. If you are running the sims from the website the question of where to save the files seems irrelevant.

2. Changing the wording as you suggest sounds good to me.

3. It should be possible to fix the sorting issue. I will deploy a fix to this soon.

**Comment by amanda-phet** [comment]
Once 2 and 3 have been addressed I think we can close this issue. Thanks!

**Comment by aaronsamuel137** [comment]
Addressed. Closing
