### ISSUE TITLE
Change YouTube video on Interactive Lecture Demos

### ISSUE THREAD

**Issue by schasteen** [phetsims/website#92]
We needed to make a small change to one of our YouTube videos, and so we need to update the page with the new link.

It is the first video at http://phet.colorado.edu/en/for-teachers/lectureDemo

The new link is https://www.youtube.com/watch?v=933XYfUZGUo

**Comment by aaronsamuel137** [comment]
I'll plan on making this change the next time I deploy the website, which should be sometime this week. If it's urgent for some reason and needs an immediate deploy, let me know, but it will be easier for me if it can wait a few days.

**Comment by aaronsamuel137** [comment]
OK I've deployed this to figaro. Assigning to @schasteen for review.

**Comment by schasteen** [comment]
Looks great, thanks!
