### ISSUE TITLE
Tweaks to mini-banner

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#93]
Mockups will be emailed to Aaron to work on implementing before pixel-polishing.

**Comment by aaronsamuel137** [comment]
Do you have a mockup for how you'd like the banner to look when a user is logged in? Right now when a user is logged in it has a link to log out, edit profile, and their email address. For phet team members there is a admin link too.

**Comment by aaronsamuel137** [comment]
Also, could you send me the new CU logo image that you want to use if you have it. I can't find it with the white text anywhere. Thanks

**Comment by amanda-phet** [comment]
I sent an email with responses to your questions.

**Comment by aaronsamuel137** [comment]
I've taken a first shot at this. Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
I feel good about the changes. The only strange thing (which I'm not sure I had considered) is if the browser is really narrow and the sign in button goes behind the CU logo. We could make the logo smaller, or perhaps go with the shorter&wider logo. 

@ariel-phet what do you think?

**Comment by arouinfar** [comment]
The banner is looking nice! I've noticed that the text within the search button is not vertically centered. The search button is also not the same height as the text box, nor are the aligned properly.

![image](https://cloud.githubusercontent.com/assets/8419308/6832101/e55e83cc-d2e9-11e4-85dc-f5dc5a20b5b4.png)

**Comment by aaronsamuel137** [comment]
@arouinfar, try refreshing your browser cache (on Mac you can do this with cmd-shift-r). This won't be necessary when we deploy the page to figaro, but whenever you are testing a dev version it is good practice to force refresh just to be sure you are seeing the latest changes.

**Comment by arouinfar** [comment]
Thanks, @aaronsamuel137 that fixed the issue.

**Comment by amanda-phet** [comment]
Actually, now that it's looking better, I think a magnifying glass might work even better, as well as using the more CU horizontal logo. @aaronsamuel137 I'll email you the files.

**Comment by amanda-phet** [comment]
#132 addresses tweaks to the CU logo. Closing this issue.
