### ISSUE TITLE
Changes to registration page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#94]
In conjunction with the rollout of HTML5 pages, and the ability to view sim primer videos, we will want to update the registration page to include more information. The exact list will need to be discussed with @kathy-phet but some ideas include:

grade level taught
institution
if the person is also a translator

Also we may want to add a field that suggests we might verify their teacher status

@amanda-phet will discuss with Kathy in more depth.

**Comment by amanda-phet** [comment]
@kathy-phet and I met to discuss what information we would like to collect from users and will meet again to look at my mockup.

**Comment by ariel-phet** [comment]
@amanda-phet and @aaronsamuel137 - should we also perhaps have a CAPTCHA step for this page?

**Comment by kathy-phet** [comment]
Seems like good option to me too. Although I think this is partially what the email confirmation process does too for creating an account... So we know we have a good email? It's been so long I cannot quite remember all the steps that we currently require.

Kathy

Sent from my iPhone

On Apr 22, 2015, at 8:43 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


@amanda-phet<https://github.com/amanda-phet> and @aaronsamuel137<https://github.com/aaronsamuel137> - should we also perhaps have a CAPTCHA step for this page?

**Comment by ariel-phet** [comment]
I don't think we necessarily need to have this step immediately, but it seems like many websites that verify emails (such as facebook) also have CAPTCHA...I think there are some pretty sophisticated bots out there these days.

**Comment by aaronsamuel137** [comment]
I've noticed that there is no longer a checkbox for receiving the newsletter. Are we just having everyone receive the newsletter unless they unsubscribe?

**Comment by amanda-phet** [comment]
I'm so glad you noticed! There should definitely be a pre-checked box at the end, before clicking Register, that signs users up for the newsletter.

**Comment by aaronsamuel137** [comment]
Sounds good, I'll add it.

What kind of validation do we want on this form? Which fields should be required? Do they need to check at least one checkbox under each category, or can they leave them all empty?

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I believe we want *all* fields required

**Comment by aaronsamuel137** [comment]
What about teaching experience? Should we force them to enter 0 here if they have no experience or just default to 0 if they enter nothing?

**Comment by ariel-phet** [comment]
Good question, and will need to be answered by @amanda-phet - I personally think teaching experience should be a a set of ranges (and radio buttons). Something like Preservice Teacher, 1-5 years, 5-10 years, 10+ years

**Comment by amanda-phet** [comment]
A few tweaks to make based on discussion with Kathy. 

- [ ] Under **Grades**, add a checkbox for “Adult Education” and a textbook next to “Other”. 
- [ ] Under **I am a…**, add a checkbox for “Teacher educator / Coach”
- [ ] Make **Teaching Experience** a selection of radio buttons: 
* None / Not applicable
* 1-2 years
* 3-5 years
* 6-10 years
* 11-20 years
* 21+ years

**Comment by amanda-phet** [comment]
![registration-01](https://cloud.githubusercontent.com/assets/7852916/7398477/83251358-ee6c-11e4-8471-6f8dbd5b00ca.png)

**Comment by amanda-phet** [comment]
![registration-01](https://cloud.githubusercontent.com/assets/7852916/7402129/c136654c-ee86-11e4-8555-4c12646dbcb4.png)

**Comment by aaronsamuel137** [comment]
This is done I think. Assigning to @amanda-phet for review. Let me know if you think it is ready for testing.

**Comment by amanda-phet** [comment]
It looks great to me! I think we just need to resolve the First/Last name issue. I'll try to catch Kathy as soon as possible to ask about it.

**Comment by ariel-phet** [comment]
Two things:

1. Lets add the Terms of use link to this page (don't we have that link now to the general university website terms of use?)

2. If I view in a non-english local, we decided that if you click on a grade level (say elementary) that the dialog to check various grades should not appear. I am not sure if we ever communicated that or not. The idea was that in countries in Europe, our grade system is not really translatable.

**Comment by amanda-phet** [comment]
1. The link is: http://www.cu.edu/privacy-policy. How about this? 
![screen shot 2015-05-04 at 3 01 21 pm](https://cloud.githubusercontent.com/assets/7852916/7462407/7a18a3c8-f26e-11e4-9389-4050c96fe55d.png)
2. I think we said this would happen if you select a non-USA country (because the UK is not a different locale, for example), but have this vary by locale makes sense too.

**Comment by ariel-phet** [comment]
Sorry, yes, the correct approach is if you select a non-USA country

**Comment by aaronsamuel137** [comment]
I've made these changes. Assigning to @amanda-phet for review.

**Comment by aaronsamuel137** [comment]
Typo fixed. Closing. Feel free to reopen if something else comes up.
