### ISSUE TITLE
When submitting an activity using the link from sim page, autofill sim selection

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#95]
@aaronsamuel137 we will want a functionality on the new sim pages where if you choose to share an activity using the "submit an activity" link on the sim page, we will want the sim selection to be autofilled. This should help avoid errors of choosing between the Java sim and the HTML5 sim.

Also if you go to the share an activity section of the website from the link under "For Teachers" you will need to have sims "double listed" in the drop down menu when choosing a sim, so you can specifically choose either the Java or the the HTML5 sim.

**Comment by aaronsamuel137** [comment]
OK I've addressed this on phet-dev. Currently sims are double listed, and HTML5 sims have a " (HTML5)" suffix.

Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
The double listing looks good, however a couple of tweaks:

1. We should make sure the drop down menu is wide enough to accommodate sim names with the (HTML5) suffix

2. If you are on the HTML5 sim it should autofill just the HTML5 version right now I see this behavior:

![capture](https://cloud.githubusercontent.com/assets/4051174/6679115/2c449250-cc09-11e4-94d9-eb8f3f6049c8.PNG)

When I get there from the HTML5 version or from the Java version.

It would be good to only autofill the correct version. So that way if the submission is made from the sim page it has already made an unambiguous choice for you.

**Comment by aaronsamuel137** [comment]
Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looking good, closing.
