### ISSUE TITLE
Add "Toubleshooting Issues with Linux Installer" in troubleshooting section

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#96]
@oliver-phet has been getting requests for troubleshooting for linux users

We should add to our troubleshooting steps something under the heading of "Troubleshooting Issues with the Linux Installer" - we should also probably in that section add some disclaimer about HTML5 sims and that although Linux is not an officially supported platform, these sims should run well in Chrome/Firefox on Linux (if we believe that is true...)

**Comment by oliver-phet** [comment]
We might add more, but for now the first entry should be:
"I'm trying to install the Linux installation of the PhET Offline Website Installer, but running into trouble."

Open the console/terminal.
Navigate to the folder where the download is.
Run the following two commands:
chmod 777 PhET-Installer_linux.bin
This will give your system permissions to execute the file.
./PhET-Installer_linux.bin.
This does the install.
Some systems may require sudo but first try without.
Choose the install directory.
Choose carefully because after the install you cannot move the folder as many of the links will break as they use absolute and not relative referencing.

**Comment by oliver-phet** [comment]
Also, please just add a "Linux" link/navigation to the Troubleshooting page (not "Troubleshooting Issues with the Linux Installer") so that we can add other Linux fixes, if necessary.

**Comment by zepumph** [comment]
I can do this if there are no objections, @jbphet is a busy guy.

**Comment by zepumph** [comment]
@oliver-phet how does that look on phet-dev.  Also during this I saw a vast difference between the style of tablets/mobiledevices and all the other troubleshooting pages. Do we perhaps want to fix that? see: https://phet.colorado.edu/en/troubleshooting/mobile 
vs
https://phet.colorado.edu/en/troubleshooting/windows which is more of a FAQ style. Thoughts?

**Comment by arnabp** [comment]
1 - Download package.
2 - Open the console/terminal.
3 - Navigate to the folder where the download is.
4 - Give your system permissions to execute the file:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> chmod 777 PhET-Installer_linux.bin
5 - Run the installer:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> ./PhET-Installer_linux.bin 
5.1 - If you still do not have permissions use:
<a>&#160;&#160;&#160;&#160;&#160;</a>>> sudo ./PhET-Installer_linux.bin
5.2 - If you get the error of a "segmentation fault":
<a>&#160;&#160;&#160;&#160;&#160;</a>>> ./PhET-Installer_linux.bin --mode text 
<a>&#160;&#160;&#160;&#160;&#160;</a>You will need to navigate the installer UI within terminal, pressing "enter" and "y" when prompted for a <a>&#160;&#160;&#160;&#160;&#160;</a>default install

**Comment by arnabp** [comment]
This is an updated list of instructions that's been tested. The formatting and indentation might use some work, but otherwise everything else should be fine.

**Comment by oliver-phet** [comment]
@zepumph Can you change the instructions on http://phet-dev.colorado.edu/en/troubleshooting/linux#q1-header to use the list above?

**Comment by zepumph** [comment]
have a look on the live site, I can change minor formatting really easily, but the content is what @arnabp posted. http://phet.colorado.edu/en/troubleshooting/linux#q1-header

**Comment by zepumph** [comment]
Assigning to @oliver-phet for changes/closing

**Comment by oliver-phet** [comment]
This has been completed for a while. Closing.
