### ISSUE TITLE
Tweaks to HTML5 category page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#97]
@aaronsamuel137 a few more tweaks to the HTML5 sims category page:

http://phet-dev.colorado.edu/en/simulations/category/html

I think we want this page to be consistent with the rest of the site. So we should have:

1. The mini banner
2. The sidebar navigation (this will make the page wide, but not really wider than the teacher resources page -- so be it for the moment)
3. In the sidebar navigation a category called "HTML5 Sims" - I suggest placing this category directly under "New Sims"

**Comment by arouinfar** [comment]
The 3rd point is no longer necessary because website design team has decided to populate the "New Sims" category with the HTML5 sims (see #82)

**Comment by aaronsamuel137** [comment]
I've made these changes. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Hey @aaronsamuel137 - nice prompt changes! 

One thing I see that is missing is the "switch to index" link that is on other category pages.

Let's fix that.

**Comment by aaronsamuel137** [comment]
Added switch to index. Assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Looks good, I like the placement of the "Switch to Index". Thanks!
