### ISSUE TITLE
"Share your activity" page: HTML5 version listed first

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#99]
@aaronsamuel137 Would it be possible to change the ordering of the 'Simulation(s)' field to keep the sims alphabetized, but order the HTML5 version before the legacy version? Currently, if you start typing the name of a sim that has both versions it will highlight the legacy because it is first in the list.

**Comment by aaronsamuel137** [comment]
I've made this change on phet-dev. Assigning to @oliver-phet for review.

**Comment by oliver-phet** [comment]
@aaronsamuel137 It looks like if you open the drop down and start typing the name of a sim, the Java/Flash version still gets selected first, even though the HTML5 version is listed first. Is there a way to change this so that the HTML5 version is selected first?

**Comment by ariel-phet** [comment]
@oliver-phet and @aaronsamuel137 the behavior oliver describes is currently working for me?

**Comment by amanda-phet** [comment]
When I tried to jump to Under Pressure and typed "U", the first one listed (the HTML5 version) was selected, so it seems to be working for me.

**Comment by oliver-phet** [comment]
It looks like the behavior is inconsistent on different machines/browsers. @aaronsamuel137 's and my machine both select the non-html5 version first, even though it is first in the list.
@aaronsamuel137 is going to investigate if it is possible to make the list behavior more consistent.

**Comment by aaronsamuel137** [comment]
At a first glance, this issue is not going to be easy to address - most of the dropdown behavior seems to be handled by wicket and/or the browser.

**Comment by oliver-phet** [comment]
Let's revisit this once we have a mockup of the new "+" icon to add a sim. To me, the current behavior is acceptable since the HTML5 version is listed first.

**Comment by oliver-phet** [comment]
This is acceptable in the current version.
